#INCLUDE "loca072.ch"  
/*/{PROTHEUS.DOC} LOCA072.PRW
ITUP BUSINESS - TOTVS RENTAL
GRÁFICO DE STATUS DOS PROJETOS
@TYPE FUNCTION
@AUTHOR FRANK ZWARG FUGA
@SINCE 03/12/2020
@VERSION P12
@HISTORY 03/12/2020, FRANK ZWARG FUGA, FONTE PRODUTIZADO.
/*/
#INCLUDE "TOTVS.CH"
#INCLUDE "MSGRAPHI.CH"

FUNCTION LOCA072()

LOCAL   AAREA     := GETAREA()
LOCAL   ASIZE     := MSADVSIZE(.F.)
LOCAL   AINFO     := { ASIZE[1], ASIZE[2], ASIZE[3], ASIZE[4], 3, 3 }
LOCAL   AOBJECTS  := {}
LOCAL   APOSOBJ   := {}
LOCAL   ACOORDJAN := {}
LOCAL   CTIPOGRAF := "4"
LOCAL   ACBX      := {STR0001,STR0002,STR0003} //"1=LINHA"###"4=BARRAS"###"10=PIZZA"

PRIVATE DINI      := STOD( LEFT(DTOS(DDATABASE),6) + "01" )
PRIVATE DFIM      := STOD( LEFT(DTOS(DDATABASE),6) + IIF( STRZERO(MONTH(DDATABASE),2) $ "01;03;05;07;08;10;12", "31", IIF( STRZERO(MONTH(DDATABASE),2) $ "04;06;09;11", "30", "28") ) )
PRIVATE OGRAFICO
PRIVATE ACOORDGRA := {}

CTITJAN   := STR0004 //"STATUS DOS PROJETOS"

AADD( AOBJECTS, { 100, 015, .T., .F., .F. } )
AADD( AOBJECTS, { 100, 100, .T., .T., .T. } )
AADD( AOBJECTS, { 100, 015, .T., .F., .F. } )
APOSOBJ := MSOBJSIZE( AINFO, AOBJECTS)

AADD(ACOORDJAN,ASIZE[7])
AADD(ACOORDJAN,0       )
AADD(ACOORDJAN,ASIZE[6])
AADD(ACOORDJAN,ASIZE[5])

AADD(ACOORDGRA,APOSOBJ[2,1]-10)
AADD(ACOORDGRA,APOSOBJ[2,2]   )
AADD(ACOORDGRA,APOSOBJ[2,3]   )
AADD(ACOORDGRA,APOSOBJ[2,4]+10)

DEFINE MSDIALOG ODLG TITLE OEMTOANSI(CTITJAN) OF OMAINWND PIXEL FROM ACOORDJAN[1],ACOORDJAN[2] TO ACOORDJAN[3],ACOORDJAN[4]
	ATUGRF(ODLG, VAL(CTIPOGRAF))

	DEFINE SBUTTON FROM ACOORDGRA[4]+15,ACOORDGRA[3]-140 ACTION ODLG:END() ENABLE OF ODLG PIXEL
	//DEFINE SBUTTON FROM ACOORDGRA[4]+15,ACOORDGRA[3]-090 BMPBUTTON TYPE 13 ACTION FSALVABMP(OGRAFICO) ENABLE OF ODLG PIXEL

	@ ACOORDGRA[4]+15,ACOORDGRA[3]-190 BUTTON O3D  PROMPT "&2D"	SIZE 25,11 OF ODLG PIXEL ACTION(OGRAFICO:L3D := !OGRAFICO:L3D, O3D:CCAPTION := IIF(OGRAFICO:L3D, "&2D", "&3D"))
    @ ACOORDGRA[4]+15,ACOORDGRA[3]-270 COMBOBOX CTIPOGRAF ITEMS ACBX SIZE 050,008 OF ODLG PIXEL ON CHANGE ATUGRF(ODLG, VAL(CTIPOGRAF))

    @ ACOORDGRA[4]+16,ACOORDGRA[3]-470 SAY "DE:"  OF ODLG PIXEL
    @ ACOORDGRA[4]+15,ACOORDGRA[3]-455 MSGET DINI OF ODLG PIXEL ON CHANGE ATUGRF(ODLG, VAL(CTIPOGRAF))

    @ ACOORDGRA[4]+16,ACOORDGRA[3]-400 SAY "ATÉ:" OF ODLG PIXEL
    @ ACOORDGRA[4]+15,ACOORDGRA[3]-385 MSGET DFIM OF ODLG PIXEL ON CHANGE ATUGRF(ODLG, VAL(CTIPOGRAF))
ACTIVATE MSDIALOG ODLG

RESTAREA( AAREA )

RETURN NIL 



// ======================================================================= \\
STATIC FUNCTION ATUGRF(ODLG, NTIPOGRAF)
// ======================================================================= \\

LOCAL ATABCORES := {}
LOCAL OFONT	    := TFONT():NEW("ARIAL",9,10,.T.,.F.,5,.T.,5,.T.,.F.,.F.)
LOCAL NCLRFORE  := CLR_BLACK
LOCAL NCLRBACK  := CLR_WHITE
LOCAL L3D       := IIF(TYPE("OGRAFICO")=="U", .T., OGRAFICO:L3D)
LOCAL NI        := 0 
LOCAL NPOS      := 0 

CURSORWAIT()

ATABELA := FDADOS()

AADD(ATABCORES , CLR_HBLUE     )
AADD(ATABCORES , CLR_HRED      )
AADD(ATABCORES , CLR_HGREEN    )
AADD(ATABCORES , CLR_WHITE     )
AADD(ATABCORES , CLR_YELLOW    )
AADD(ATABCORES , CLR_GRAY      )
AADD(ATABCORES , CLR_BLUE      )
AADD(ATABCORES , CLR_RED       )
AADD(ATABCORES , CLR_GREEN     )
AADD(ATABCORES , CLR_CYAN      )
AADD(ATABCORES , CLR_MAGENTA   )
AADD(ATABCORES , CLR_BROWN     )
AADD(ATABCORES , CLR_HGRAY     )
AADD(ATABCORES , CLR_LIGHTGRAY )
AADD(ATABCORES , CLR_HCYAN     )
AADD(ATABCORES , CLR_HMAGENTA  )

FOR NI := LEN(ATABCORES) TO LEN(ATABELA)
	AADD(ATABCORES, ATABCORES[ LEN(ATABCORES) - NI ]   )
NEXT NI 

OGRAFICO := TMSGRAPHIC():NEW(ACOORDGRA[1],ACOORDGRA[2],ODLG,OFONT,NCLRFORE,NCLRBACK,ACOORDGRA[3],ACOORDGRA[4])
OGRAFICO:SETLEGENPROP(GRP_SERIES, CLR_WHITE, GRP_SCRTOP, .T.)
OGRAFICO:SETMARGINS(5,5,5,5)

IF NTIPOGRAF == 10			// PIZZA
	NHANDLE := OGRAFICO:CREATESERIE(NTIPOGRAF)
	FOR NPOS := 1 TO LEN(ATABELA)
		OGRAFICO:ADD(NHANDLE,ATABELA[NPOS,3],ATABELA[NPOS,2],ATABCORES[NPOS])
	NEXT NPOS 
ELSEIF NTIPOGRAF == 4		// BARRAS
	FOR NPOS := 1 TO LEN(ATABELA)
		NHANDLE := OGRAFICO:CREATESERIE(NTIPOGRAF, ATABELA[NPOS,2], 0, .T.)
		OGRAFICO:ADD(NHANDLE, ATABELA[NPOS,3], "", ATABCORES[NPOS])
	NEXT
ELSE 						// LINHA
	OGRAFICO:SETLEGENPROP( GRP_SCRTOP, CLR_YELLOW, GRP_SERIES, .F.)
	NHANDLE := OGRAFICO:CREATESERIE(NTIPOGRAF)
	FOR NPOS := 1 TO LEN(ATABELA)
		OGRAFICO:ADD( NHANDLE, ATABELA[NPOS,3], ATABELA[NPOS,2], CLR_BLUE )
	NEXT
ENDIF

OGRAFICO:SETTITLE(STR0004, "DE "+DTOC(DINI)+" A "+DTOC(DFIM), CLR_BLACK, A_CENTER, .F. ) //"STATUS DOS PROJETOS"
OGRAFICO:SETGRADIENT( 2, CLR_WHITE, CLR_WHITE)                //ORIENTAÇÃO E CORES DE FUNDO
OGRAFICO:L3D := L3D                                           //3D

CURSORARROW()				// DEVOLVE POSIÇÃO NORMAL DO CURSOR DO MOUSE

RETURN NIL



// ======================================================================= \\
STATIC FUNCTION FDADOS()
// ======================================================================= \\

LOCAL ATABELA   := {}
/*
LOCAL NPOS , NI
LOCAL ASTATUS
ASTATUS := MONTACOMBO("ZA0_STATUS")
FOR NI := 1 TO LEN(ASTATUS)
	IF ! EMPTY( ASTATUS[NI,4] )
		AADD(ATABELA, {ASTATUS[NI,3], ASTATUS[NI,4], 0 } )
	ENDIF
NEXT
*/
AADD(ATABELA,{"'1'==FP0->FP0_STATUS.AND.!EMPTY(FP0->FP0_NUMPED)",STR0005, 0}) //"DIGITADO C/ CONTRATO"
AADD(ATABELA,{"'1'==FP0->FP0_STATUS",STR0006    , 0}) //"DIGITADO"
AADD(ATABELA,{"'2'==FP0->FP0_STATUS",STR0007, 0}) //"EM APROVAÇÃO"
AADD(ATABELA,{"'3'==FP0->FP0_STATUS",STR0008    , 0}) //"APROVADO"
AADD(ATABELA,{"'4'==FP0->FP0_STATUS",STR0009, 0}) //"NÃO APROVADO"
AADD(ATABELA,{"'5'==FP0->FP0_STATUS",STR0010     , 0}) //"FECHADO"
AADD(ATABELA,{"'6'==FP0->FP0_STATUS",STR0011, 0}) //"INDISPONÍVEL"
AADD(ATABELA,{"'7'==FP0->FP0_STATUS",STR0012   , 0}) //"REJEITADO"
AADD(ATABELA,{"'8'==FP0->FP0_STATUS",STR0013    , 0}) //"FATURADO"
AADD(ATABELA,{"'A'==FP0->FP0_STATUS",STR0014    , 0}) //"REVISADO"
AADD(ATABELA,{"'B'==FP0->FP0_STATUS",STR0015    , 0}) //"EXCLUIDO"
AADD(ATABELA,{"'C'==FP0->FP0_STATUS",STR0016   , 0}) //"CANCELADO"

FP0->(DBSEEK( XFILIAL("FP0"), .T. ))
WHILE FP0->( !EOF() .AND. FP0_FILIAL == XFILIAL("FP0") )
	IF DINI <= FP0->FP0_DATINC .AND. DFIM >= FP0->FP0_DATINC
		ASCAN(ATABELA, {|X| IIF( &( X[1] ), X[3]++, NIL) } )
	/*
		NPOS := ASCAN(ATABELA, {|X| &( X[1] ) } )
		IF NPOS > 0
			ATABELA[NPOS][3] ++
		ENDIF
	*/
	ENDIF
	FP0->(DBSKIP())
ENDDO 

RETURN ACLONE(ATABELA) 



// ======================================================================= \\
STATIC FUNCTION FSALVABMP(OGRAFICO)
// ======================================================================= \\
/*
LOCAL CARQUIVO ,CDRIVE , CDIR , CNOME , CEXTENSAO
LOCAL CTIPOS , CTIPO , LGRAVA , CRAIZ := "\" 

WHILE .T.
	CTIPOS := "*.BMP|*.BMP"
	CTIPOS += "|*.JPEG|*.JPEG"
//                                                              .T.=ABRIR,.F.=SALVAR                                 ))
	CARQUIVO := UPPER(CGETFILE(CTIPOS,STR0017,0,"C:\",.F.,GETF_LOCALHARD+GETF_LOCALFLOPPY+GETF_NETWORKDRIVE)) //"SELECIONE ARQUIVO"
	IF !EMPTY(CARQUIVO)
		IF FILE(CARQUIVO)
			LGRAVA := MSGYESNO(STR0018+CARQUIVO+STR0019) //"ATENÇÃO: ARQUIVO "###" JÁ EXISTE. DESEJA SUBSTITUIR O ARQUIVO EXISTENTE ??"
		ELSE
			LGRAVA := .T.
		ENDIF

		IF LGRAVA
			SPLITPATH(CARQUIVO,@CDRIVE,@CDIR,@CNOME,@CEXTENSAO)
   			IF UPPER(CEXTENSAO) $ ".JPEG;.JPG"
				CTIPO := "JPG"
			ELSE
				CTIPO := "BMP"
			ENDIF

			CARQUIVO := LEFT(CARQUIVO, LEN(CARQUIVO)-LEN(CEXTENSAO)) + "." + CTIPO
			IF OGRAFICO:SAVETOIMAGE(CNOME,CRAIZ,CTIPO)
				COPY FILE &(CRAIZ+CNOME) TO &(CARQUIVO)
				DELETE FILE &(CRAIZ+CNOME)
				IF FILE(CARQUIVO)
					MSGINFO(STR0020 + CARQUIVO + STR0021 , STR0022) //"ARQUIVO: "###" ==> GERADO COM SUCESSO !!"###"GPO - ZA0GRAF.PRW"
					EXIT
				ELSE
					MSGSTOP(STR0023 + CARQUIVO , STR0022) //"ERRO: NÃO FOI POSSÍVEL GERAR O ARQUIVO ==> "###"GPO - ZA0GRAF.PRW"
				ENDIF
			ELSE
				MSGSTOP(STR0024 + CRAIZ + CNOME , STR0022) //"ERRO: NÃO FOI POSSÍVEL GERAR O ARQUIVO TEMPORÁRIO ==> "###"GPO - ZA0GRAF.PRW"
			ENDIF 
		ENDIF 
	ENDIF 
ENDDO 
*/
RETURN NIL 
