/*/{PROTHEUS.DOC} LOCA063.PRW  
ITUP BUSINESS - TOTVS RENTAL
ENVIA E-MAIL DE AVISO DE VISTORIA, COM A PESQUISA DE SATISFAÇÃO EM ANEXO
@TYPE FUNCTION
@AUTHOR FRANK ZWARG FUGA
@SINCE 03/12/2020
@VERSION P12
@HISTORY 03/12/2020, FRANK ZWARG FUGA, FONTE PRODUTIZADO.
/*/
#INCLUDE "PROTHEUS.CH"
#INCLUDE "TBICONN.CH"

FUNCTION LOCA063(AVISTORIA , NOPC , CCAMINHO) 
/*
LOCAL OHTML
LOCAL OPROCESS
LOCAL CMAILTO    :=  GETMV("MV_LOCX161",,"")
LOCAL CPATH	     := "C:\PESQUISA\"+CCAMINHO//GETMV("MV_LOCX260",,"\WORKFLOW\HTML\TEMP\VISTORIAS\") // *** CUIDADO *** ===> PATH *SEMPRE* A PARTIR DO ROOTPATH
LOCAL CREPORT    := ""
LOCAL NPOS       := 0
LOCAL CARQUIVO   := ""
LOCAL CTIPO      := ""
LOCAL CPROJETO   := ""
LOCAL COBRA      := ""
LOCAL CENDERECO  := ""
LOCAL CMUNICIPIO := ""
LOCAL CCONTATO   := ""
LOCAL CBAIRRO    := ""
LOCAL CRATLOG    := GETMV("MV_LOCX021",,"")  // parametro removido no produto padrão
//LOCAL APATH    := STRTOKARR(CPATH,"\") 
//LOCAL AEQUIPA  := {}
//LOCAL CDIRMAKE := ""
//LOCAL CSUBJECT := ""

PRIVATE CLOCAL  := "\WORKFLOW\HTML\" 
*/

// Funcao não ativa na virada do 94 - Frank Z Fuga em 05/04/2022

/*
IF EMPTY( CRATLOG ) 
	CRATLOG := "HTTP://WWW.ITUP.COM.BR/IMG/LOGO/ITUP-BUSINESS.PNG" 
ENDIF

IF NOPC == 1 .OR. NOPC == 2 
	CARQUIVO  := "VISTORIA.HTM"
	CTIPO     := "SOLICITAÇÃO DE R.A.T"
ELSE
	CARQUIVO  := "VREALIZADA.HTM"
	CTIPO     := "CONFIRMAÇÃO DE R.A.T"
ENDIF

IF ! EMPTY(CCAMINHO)
 //	CPATH := DIRECTORY(CPATH,"",,.F.)
	// --> COPIA DA PASTA LOCAL PARA SERVIDOR
	//CPYT2S(CPATH,"\WORKFLOW\",.F.)   removido pelos débito tecnicos - Frank em 05/04/2022
	CPATH:="\WORKFLOW\"+CCAMINHO
ENDIF

FOR NPOS := 1 TO LEN(AVISTORIA)

	// --> CRIO O OBJETO OPROCESS, QUE RECEBE A INICIALIZAÇÃO DA CLASSE TWFPROCESS 
	//     REPARE QUE O PRIMEIRO PARÂMETRO É O CÓDIGO DO PROCESSO QUE CADASTRAMOS 
	//     ACIMA E O SEGUNDO UMA DESCRIÇÃO QUALQUER. 
	OPROCESS:= TWFPROCESS():NEW("VISTORIA", "NOTIFICACAO - "+CTIPO)

	// --> CRIO UMA TASK. UM PROCESSO PODE TER VÁRIAS TASKS(TAREFAS). PARA CADA 
	//     TASK INFORMO UM NOME PARA ELA E O HTML ENVOLVIDO. REPARE QUE O PATH DO 
	//     HTML É SEMPRE ABAIXO DO ROOTPATH DO PROTHEUS. 
	OPROCESS:NEWTASK("VISTORIA", CLOCAL+CARQUIVO)

	// --> INFORMO O TÍTULO DO E-MAIL. 
	OPROCESS:CSUBJECT := CTIPO

	// --> INFORMO QUAL FUNÇÃO O WORKFLOW EXECUTARÁ AO LER A RESPOSTA DO USUÁRIO. //
 //	OPROCESS:BRETURN  := "LOCA06301()"

	// --> INFORMO QUAIS E-MAIL ESTARAO RECEBENDO A MENSAGEM.
	IF ! EMPTY(CCAMINHO)
		OPROCESS:CTO := CMAILTO + ";" + AVISTORIA[NPOS][2]
	ELSE
		OPROCESS:CTO := CMAILTO 
		CPROJET      := FP5->FP5_PROJET
		COBRA        := FP5->FP5_OBRA
	ENDIF

	// --> MODELO DE ATIVAÇÃO.
	OPROCESS:NEWVERSION(.T.)

	// --> INFORMO O CÓDIGO DO USUÁRIO NO PROTHEUS QUE RECEBERÁ O E-MAIL. 
	//     ISTO É ÚTIL PARA USAR A CONSULTA DE PROCESSOS POR USUÁRIO. 
	OPROCESS:USERSIGA := '000000' 

	// --> COLOCO AQUI UM PONTO DE RASTREABILIDADE. OS DOIS PRIMEIROS PARÂMETROS 
	//     SÃO SEMPRE OS ABAIXO PASSADOS E O TERCEIRO INDICA O CÓDIGO DO STATUS 
	//     ACIMA CADASTRADO. 
 //	RASTREIAWF(OPROCESS:FPROCESSID+'.'+OPROCESS:FTASKID,OPROCESS:FPROCCODE,'10001')   

	// --> SIMPLESMENTE PASSO O VALOR DA PROPRIEDADE OPROCESS:OHTML PARA UMA 
	//     VARIÁVEL LOCAL PARA FACILITAR.
	OHTML := OPROCESS:OHTML

	// --> CABECALHO DO HTML. 
	IF (FP0->FP0_TIPOSE <> "T" .OR. NOPC == 1 )

		DBSELECTAREA("FP1")
	 //	DBGOTO(AVISTORIA[NPOS,1])
		DBSETORDER(1)
		DBSEEK( FP0->FP0_FILIAL + CPROJET + COBRA )

		CNUMTEL   := STRTRAN(FP1->FP1_TELORI,'-','')
		CREPORT   := ALLTRIM(FP1->FP1_PROJET )+"_"+DTOS(DDATABASE)+"_"+CARQUIVO
		CPROJETO  := ALLTRIM(FP1->FP1_PROJET )
	    COBRA     := ALLTRIM(FP1->FP1_OBRA   )
	    CLOCAL    := ALLTRIM(FP1->FP1_NOMORI )
	    CENDERECO := ALLTRIM(FP1->FP1_ENDORI )
	    CMUNICIPIO:= ALLTRIM(FP1->FP1_MUNORI )
	    CCONTATO  := ALLTRIM(FP1->FP1_CONORI )
	    CBAIRRO   := ALLTRIM(FP1->FP1_BAIORI )
	    CTELEFONE := "( "+ALLTRIM(FP1->FP1_DDDORI)+" )" + " "+ ALLTRIM(TRANSFORM(CNUMTEL,"@R !!!!-!!!!") )
	    CPRZVISTO := DTOC(FP1->FP1_DTVIS)
	    CHORAVIST := ALLTRIM(TRANSFORM(FP1->FP1_HRVIS,"@R !!:!!") )
	    CESCOPO   := ALLTRIM(FP1->FP1_ESCOPO)

	 ELSE

		DBSELECTAREA("ZA6")
	 //	DBGOTO(AVISTORIA[NPOS]) 
		DBSETORDER(1)
		DBSEEK( FP0->FP0_FILIAL + CPROJET + COBRA )	

		CNUMTEL   := STRTRAN(ZA6->ZA6_TELORI,'-','')
		CREPORT   := ALLTRIM(ZA6->ZA6_PROJET )+"_"+DTOS(DDATABASE)+"_"+CARQUIVO
		CPROJETO  := ALLTRIM(ZA6->ZA6_PROJET )
	    COBRA     := ALLTRIM(ZA6->ZA6_OBRA   )
	    CLOCAL    := ALLTRIM(ZA6->ZA6_NOMORI )
	    CENDERECO := ALLTRIM(ZA6->ZA6_ENDORI )
	    CMUNICIPIO:= ALLTRIM(ZA6->ZA6_MUNORI )
	    CCONTATO  := ALLTRIM(ZA6->ZA6_CONORI )
	    CBAIRRO   := ALLTRIM(ZA6->ZA6_BAIORI )
	    CTELEFONE := "( "+ALLTRIM(ZA6->ZA6_DDDORI)+" )" + " "+ ALLTRIM(TRANSFORM(CNUMTEL,"@R !!!!-!!!!") )
	    CPRZVISTO := DTOC(ZA6->ZA6_DTVIS)
	    CHORAVIST := ALLTRIM(TRANSFORM(ZA6->ZA6_HRVIS,"@R !!:!!") )
	    CESCOPO   := ALLTRIM(ZA6->ZA6_OBSVIA)

	 ENDIF 

    OHTML:VALBYNAME( "RATLOG"      , CRATLOG  )    							// LOGO DO CLIENTE NA WEB - PARAMETRO MV_LOCX021

    OHTML:VALBYNAME( "FP1_PROJET"  , CPROJETO  )    						// PROJETO
	OHTML:VALBYNAME( "FP1_OBRA"    , COBRA     )    						// OBRA 
	OHTML:VALBYNAME( "FP1_NOMORI"  , CLOCAL    )    						// LOCAL                        
	OHTML:VALBYNAME( "FP1_ENDORI"  , CENDERECO )    						// ENDEREÇO
	OHTML:VALBYNAME( "FP1_MUNORI"  , CMUNICIPIO)    						// MUNICIPIO
	OHTML:VALBYNAME( "FP1_CONORI"  , CCONTATO  )    						// CONTATO
	OHTML:VALBYNAME( "FP1_BAIORI"  , CBAIRRO   )    						// BAIRRO
	OHTML:VALBYNAME( "FP1_TELORI"  , CTELEFONE )    						// TELEFONE
					
	AADD( (OHTML:VALBYNAME( "T.1"     )),  "ALTA"                   )     	// PRIORIDADE
	AADD( (OHTML:VALBYNAME( "T.2"     )),  ALLTRIM(SUBS(CUSUARIO,7,15)) ) 	// USUARIO
	AADD( (OHTML:VALBYNAME( "T.3"     )),  CPRZVISTO       )     			// PRAZO DA VISTORIA
	AADD( (OHTML:VALBYNAME( "T.4"     )),  CPRZVISTO       )     			// DATA DA VISTORIA
	AADD( (OHTML:VALBYNAME( "T.5"     )),  CHORAVIST       )     			// HORA DA VISTORIA
        
 //	AADD( (OHTML:VALBYNAME( "T.6"     )),  FP5->FP5_RESPON )     			// RESPONSAVEL
	IF FP0->FP0_TIPOSE <> "T" 
		AADD( (OHTML:VALBYNAME( "T.6"     )),  FP1->FP1_NOMRES         ) 	// RESPONSAVEL 
	ELSE
		AADD( (OHTML:VALBYNAME( "T.6"     )),  ZA6->ZA6_NOMRES         ) 	// RESPONSAVEL	
	ENDIF
	AADD( (OHTML:VALBYNAME( "T2.1"    )), CESCOPO  ) 						//OBSERVÇÕES
	    	    
 //	OHTML:SAVEFILE(CPATH)
		
	// --> ENVIA PARA OS DESTINATARIOS. 
 //	OPROCESS:ATTACHFILE(CPATH)
	OPROCESS:NENCODEMIME := 0
	OPROCESS:START()
 //	OPROCESS:FINISH() 
 //	SLEEP( 5000 )

 //	FERASE("C:\TOTVS 11\PROTHEUS_DATA_TESTE\"+CPATH) 

NEXT
*/
RETURN NIL 



/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±ÉÍÍÍÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍ»±±
±±ºPROGRAMA  ³ CHECKVIST º AUTOR ³ IT UP BUSINESS     º DATA ³ 01/01/2007 º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºDESCRICAO ³ VERIFICA RETORNO DO E-MAIL ENVIADO                         º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºUSO       ³ ESPECIFICO GPO                                 		      º±±
±±ÈÍÍÍÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß
*/
/*
FUNCTION LOCA06301(OPROCESS)
// --> CHAMADA: NÃO EXISTE - DESCONTINUADO - CHAMADA COMENTADA.
DBSELECTAREA("FP0")
DBSETORDER(1)

// PEGO O CÓDIGO DO PRODUTO, ATRAVÉS DO MÉTODO RETBYNAME, PARA ACHAR O PRODUTO CORRETO NO CADASTRO.
IF DBSEEK(XFILIAL("FP0")+OPROCESS:OHTML:RETBYNAME('TB.VISTORIA')[1])
	RECLOCK("FP0",.F.)
	FP0->FP0_VISTORIA := VAL(OPROCESS:OHTML:RETBYNAME('TB.VISTORIA')[1])		//GRAVO O CAMPO INFORMADO PELA PESSOA QUE RESPONDEU O E-MAIL
	MSUNLOCK()
ENDIF

// COLOCO MAIS UM PONTO DE RASTREABILIDADE, USANDO O STATUS 10002.
RASTREIAWF(OPROCESS:FPROCESSID+'.'+OPROCESS:FTASKID,OPROCESS:FPROCCODE,"10002")

RETURN NIL
*/
