#INCLUDE "loca047.ch" 
/*/{PROTHEUS.DOC} LOCA047.PRW
ITUP BUSINESS - TOTVS RENTAL
ORDEM DE CARREGAMENTO/ENTREGA
@TYPE FUNCTION
@AUTHOR FRANK ZWARG FUGA
@SINCE 03/12/2020
@VERSION P12
@HISTORY 03/12/2020, FRANK ZWARG FUGA, FONTE PRODUTIZADO.
/*/

#INCLUDE "RWMAKE.CH"
#INCLUDE "PROTHEUS.CH"
#INCLUDE "FONT.CH"                                                           
#INCLUDE "PRINT.CH"                               

FUNCTION LOCA047()
PRIVATE CCADASTRO := STR0001 //"SELECIONE A VIAGEM..."
PRIVATE AROTINA   := { {STR0002    , "AXPESQUI"    , 0 , 1} , ;  //"PESQUISAR"
					   {STR0003   , "AXVISUAL"    , 0 , 6} , ;  //"VISUALIZAR"
					   {STR0004 , "LOCA04711()" , 0 , 6} , ;  //"COMPLEMENTAR"
					   {STR0005   , "LOCA04701()" , 0 , 6}}  //"SELECIONAR"

PRIVATE BFILTRABRW := {|| NIL}
PRIVATE AINDICE    := {}
PRIVATE CCONDFIL   := ""

//IF !LOCA061() 								// --> VALIDAÇÃO DO LICENCIAMENTO (WS) DO GPO 
//	RETURN 
//ENDIF 

DBSELECTAREA("FQ5")                                                                                   
DBSETORDER(1)                                                                                               

CCONDFIL := "FQ5_FILIAL == '"+XFILIAL("FQ5")+"' .AND. "
CCONDFIL += "FQ5_TPAS == 'T' "
CCONDFIL += ".AND. FQ5_STATUS <> '9' "			// NÃO EXIBIR AS CANCELADAS
CCONDFIL += ".AND. !(EMPTY(FQ5->FQ5_DATFEC) .AND.  EMPTY(FQ5->FQ5_DATENC) .AND. FQ5->FQ5_STATUS == '1') "

BFILTRABRW := {|| FILBROWSE("FQ5",@AINDICE,@CCONDFIL) }
LJMSGRUN(STR0006,, {|| EVAL(BFILTRABRW) })					 //"POR FAVOR AGUARDE, FILTRANDO INFORMAÇÕES..."

MBROWSE(6,1,22,75,"FQ5")

DBCLEARFILTER()
   
RETURN



/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±ÉÍÍÍÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍ»±±
±±ºPROGRAMA  ³ SLOCF05   º AUTOR ³ IT UP BUSINESS     º DATA ³ 01/01/2007 º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºDESCRICAO ³ "SELECIONAR"                                               º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºUSO       ³ ESPECIFICO GPO                                             º±±
±±ÈÍÍÍÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß
*/
FUNCTION LOCA04701(NRECNO)

PRIVATE CCADASTRO := STR0007 //"MANUTENÇÃO DE ORDEM DE CARREGAMENTO (ZL8)"
PRIVATE AROTINA   := FMONTAROT() 	// MONTA O AROTINA
PRIVATE CDELFUNC  := ".T." 			// VALIDACAO PARA A EXCLUSAO. PODE-SE UTILIZAR EXECBLOCK
PRIVATE NOPC      := 0

PRIVATE COBRA     := FQ5->FQ5_OBRA 
PRIVATE CSEQVIA	  := FQ5->FQ5_SEQVIA
PRIVATE CSEQCAR   := FQ5->FQ5_SEQCAR
PRIVATE CSEQCAR2  := FQ5->FQ5_SEQCAR 
PRIVATE CPRJOBRA  := FQ5->FQ5_SOT+FQ5->FQ5_OBRA
PRIVATE CVIAGEM   := FQ5->FQ5_VIAGEM
PRIVATE AINDEX	  := {}
PRIVATE CSTRING   := "ZL8"
PRIVATE CFILTRA
PRIVATE BFILTRA

REGTOMEMORY("ZL8",.F.)

FP0->(DBSEEK(XFILIAL("FP0") + FQ5->FQ5_SOT ))               
FP1->(DBSEEK(XFILIAL("FP1") + CPRJOBRA ))               

DBSELECTAREA(CSTRING)
DBSETORDER(1)
CFILTRA := "ZL8_FILIAL+ZL8_PROJET+ZL8_OBRA+ZL8_VIAGEM=='"+XFILIAL("ZL8")+CPRJOBRA+CVIAGEM +"' .AND. ZL8_ITEM == '001' "
BFILTRA := {||FILBROWSE(CSTRING,@AINDEX,@CFILTRA)}

EVAL(BFILTRA)

MBROWSE(6 , 1 , 22 , 75 , CSTRING , , , , , , LOCA04702()) 
ENDFILBRW(CSTRING,AINDEX) 

RETURN 



/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±ÉÍÍÍÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍ»±±
±±ºPROGRAMA  ³ ZL8LEGE   º AUTOR ³ IT UP BUSINESS     º DATA ³ 01/01/2007 º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºDESCRICAO ³ TRATA A LEGENDA                                            º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºUSO       ³ ESPECIFICO GPO                                             º±±
±±ÈÍÍÍÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß
*/
FUNCTION LOCA04702(NRECNO) 

LOCAL ALEGENDA , ACORES 

ALEGENDA := {}

AADD(ALEGENDA,{"BR_AZUL"  , STR0008}) //"ORDEM DE CARREGAMENTO"
AADD(ALEGENDA,{"BR_VERDE" , STR0009       }) //"ORDEM DE COLETA"

IF NRECNO==NIL
	ACORES := {} 
	AADD(ACORES,{'!(ZL8_ESTADO=="SP" .AND. ZL8_ESTADD$"  ,SP")',ALEGENDA[1,1]})
	AADD(ACORES,{' (ZL8_ESTADO=="SP" .AND. ZL8_ESTADD$"  ,SP")',ALEGENDA[2,1]})
	RETURN(ACORES)
ELSE 
	BRWLEGENDA(CCADASTRO,OEMTOANSI(STR0010),ALEGENDA) //"TIPO DE DOCUMENTO"
	RETURN(.T.)
ENDIF

RETURN



// ======================================================================= \\
STATIC FUNCTION FMONTAROT() 					// MONTA O AROTINA
// ======================================================================= \\

LOCAL AROTINA := {} 

IF CNIVEL>=5
	AADD(AROTINA , {STR0002  , "AXPESQUI"     , 0 , 1}) //"PESQUISAR"
	AADD(AROTINA , {STR0003 , "LOCA04703(2)" , 0 , 6}) //"VISUALIZAR"
	AADD(AROTINA , {STR0011    , "LOCA04704(3)" , 0 , 3}) //"INCLUIR"
	AADD(AROTINA , {STR0012    , "LOCA04705(4)" , 0 , 6}) //"ALTERAR"
	AADD(AROTINA , {STR0013    , "LOCA04706(5)" , 0 , 6}) //"EXCLUIR"
	AADD(AROTINA , {STR0014   , "U_LOCI048"    , 0 , 6})	 //"IMPRIMIR"
	AADD(AROTINA , {STR0015    , "LOCA04702"    , 0 , 6}) //"LEGENDA"
ELSE
	AADD(AROTINA , {STR0002  , "AXPESQUI"     , 0 , 1}) //"PESQUISAR"
	AADD(AROTINA , {STR0003 , "LOCA04703"    , 0 , 2}) //"VISUALIZAR"
	AADD(AROTINA , {STR0015    , "LOCA04702"    , 0 , 6}) //"LEGENDA"
ENDIF 

RETURN(AROTINA)



// ======================================================================= \\
FUNCTION LOCA04703() 						// AXVISUAL
// ======================================================================= \\

FMANU(2)

RETURN

// ======================================================================= \\
FUNCTION LOCA04704()  						// AXINCLUI
// ======================================================================= \\

FMANU(3)

RETURN

// ======================================================================= \\
FUNCTION LOCA04705() 						// AXALTERA
// ======================================================================= \\

FMANU(4)

RETURN

// ======================================================================= \\
FUNCTION LOCA04706()  						// AXDELETA
// ======================================================================= \\

FMANU(5)

RETURN



// ======================================================================= \\
STATIC FUNCTION FMANU(NOPC)
// ======================================================================= \\

LOCAL CTITJAN    := STR0008 //"ORDEM DE CARREGAMENTO"
LOCAL NSTYLE 
LOCAL NPOS       := 0 
LOCAL CSTATSPROG := "4"

PRIVATE ODLG , OGETZA7
PRIVATE OARIAL12N1 := TFONT():NEW("ARIAL",12,16,,.T.,,,,.T.,.F.)
PRIVATE OARIAL12N2 := TFONT():NEW("ARIAL",12,16,,.T.,,,,.T.,.F.)
PRIVATE CALIASTMP  := GETNEXTALIAS()

NSTYLE := GD_INSERT + GD_UPDATE + GD_DELETE
OFONT1 := OARIAL12N1  	// SAY
OFONT2 := OARIAL12N2  	// GET

IF NOPC <> 3
	_FILTMP    := ZL8->ZL8_FILIAL
	_PROJTMP   := ZL8->ZL8_PROJET
	_OBRATMP   := ZL8->ZL8_OBRA
	_VIATMP    := ZL8->ZL8_VIAGEM
	_SEQTRATMP := ZL8->ZL8_SEQTRA
	BFILTRA    := {||FILBROWSE(CSTRING,@AINDEX,@CFILTRA)}
	EVAL(BFILTRA)
ENDIF   

IF FQ5->FQ5_FILORI <> CFILANT
	AAREASM0 := SM0->(GETAREA())
	SM0->(DBSEEK(CEMPANT+FQ5->FQ5_FILORI))
	MSGALERT(STR0016+ALLTRIM(SM0->M0_NOME)+"/"+ALLTRIM(SM0->M0_FILIAL)+STR0017 , STR0018)  //"ESTE PROJETO É DA FILIAL "###", ABRIR O SISTEMA NA FILIAL CORRETA!"###"GPO - LOCT005.PRW"
	RESTAREA(AAREASM0)
	RETURN
ENDIF      
   
DBSELECTAREA("ZA7")
DBSETORDER(1)
DBSEEK(XFILIAL("ZA7")+CPRJOBRA+FQ5->FQ5_SEQVIA + FQ5->FQ5_SEQCAR)

// --> MAXIMIZACAO DA AREA DE TRABALHO.
PRIVATE AOBJECTS  := {}
PRIVATE AINFO     := {}
PRIVATE APOSGET   := {}
PRIVATE APOSOBJ   := {}

ASIZEAUT 	 := MSADVSIZE()

IF OMAINWND:NCLIENTWIDTH > 800
	AADD( AOBJECTS, {  100, 008, .T., .T. } )  //ENCHOICE
	AADD( AOBJECTS, {  100, 092, .T., .T. } )  //MSGETDADOS
ELSE
	AADD( AOBJECTS, {  100, 010, .T., .T. } )  //ENCHOICE
	AADD( AOBJECTS, {  100, 090, .T., .T. } )  //MSGETDADOS
ENDIF

AINFO 	:= {ASIZEAUT[1],ASIZEAUT[2],ASIZEAUT[3],ASIZEAUT[4],3,3}
APOSOBJ := MSOBJSIZE( AINFO, AOBJECTS, .T. , .F. )
APOSGET := MSOBJGETPOS((ASIZEAUT[3]-ASIZEAUT[1]),315,{{004,024,240,270}} )

// --> MONTAGEM DA TELA QUE SERA APRESENTADA PARA USUARIO (LAY-OUT)
DEFINE MSDIALOG ODLG FROM ASIZEAUT[7],0           TO ASIZEAUT[6],ASIZEAUT[5] TITLE OEMTOANSI(CTITJAN) OF OMAINWND PIXEL
                                    
PRIVATE AHEADER:={}
PRIVATE ACOLS:={}
PRIVATE ODLGCLI,ODLGGER,ODLGORI,ODLGDES,ODLGFRO,ODLGEQU,ODLGOBS,ODLGMER
PRIVATE OFOLDERCLI,OFOLDERGER,OFOLDERORI,OFOLDERDES,OFOLDERFRO,OFOLDEREQU,OFOLDEROBS,OFOLDERMER
PRIVATE NFOLDERCLI,NFOLDERGER,NFOLDERORI,NFOLDERDES,NFOLDERFRO,NFOLDEREQU,NFOLDEROBS,NFOLDERMER
PRIVATE OPROJET,CPROJET
PRIVATE OLOCALO,OENDERO,ONUMERO,OCOMPLO,OBAIRRO,OESTADO,OCIDADO,OCGCO,OINSO
PRIVATE CLOCALO,CENDERO,CNUMERO,CCOMPLO,CBAIRRO,CESTADO,CCIDADO,CCGCO,CINSO
PRIVATE OLOCALD,OENDERD,ONUMERD,OCOMPLD,OBAIRRD,OESTADD,OCIDADD,OCGCD,OINSD
PRIVATE CLOCALD,CENDERD,CNUMERD,CCOMPLD,CBAIRRD,CESTADD,CCIDADD,CCGCD,CINSD
PRIVATE ODATAEMI,OHORAEMI,OPRAZOV,ODATACAR,OHORACAR,OQUANT,ODESCCAR,OCODICAR
PRIVATE DDATAEMI,CHORAEMI,NPRAZOV,DDATACAR,CHORACAR,NQUANT,CDESCCAR,CCODICAR
PRIVATE OCOMP,OLARG,OALTU,ODIAM,OPESOUNI,OPESOTOT
PRIVATE NCOMP,NLARG,NALTU,NDIAM,NPESOUNI,NPESOTOT
PRIVATE OOBS,COBS
PRIVATE OEMPREM, OENDREM, OESTREM, OMUNREM, OBAIREM, OTEL, OSOLIC, OREFER, OCNPJREM, OIEREM, ODEST, OESTDEST, OMUNDEST, OCODIGO, OLOJA 
PRIVATE CEMPREM, CENDREM, CESTREM, CMUNREM, CBAIREM, CTEL, CSOLIC, CREFER, CCNPJREM, CIEREM, CDEST, CESTDEST, CMUNDEST, CCODIGO, CLOJA   
PRIVATE LFIRST      := .T.

CCODIGO  := SPACE(06)
CLOJA    := SPACE(02)
CEMPREM  := SPACE(40)
CENDREM  := SPACE(40)
CESTREM  := SPACE(02)
CMUNREM  := SPACE(15)
CBAIREM  := SPACE(30)
CTEL	 := SPACE(15)
CSOLIC	 := SPACE(40)
CREFER	 := SPACE(40)
CCNPJREM := SPACE(14)
CIEREM	 := SPACE(18)
CDEST	 := SPACE(40)
CESTDEST := SPACE(02)
CMUNDEST := SPACE(20)

// FOLDERCLI (DADOS DO CLIENTE)
PRIVATE OPNLCLI
PRIVATE CCLI, CLOJ, CNOM, CEND, CCID, CBAI, CEST, CCEP, CDDD, CFAX, CCON, CDEP
AAM->(DBSETORDER(1))
AAM->(DBSEEK(XFILIAL("AAM")+FQ5->FQ5_CONTRA))
                                        
SA1->(DBSETORDER(1))
SA1->(DBSEEK(XFILIAL("SA1")+FP0->FP0_CLI+FP0->FP0_LOJA))

POSICIONE("SA1",1,XFILIAL("SA1")+FP0->FP0_CLI+FP0->FP0_LOJA ,"") 
CCLI := SA1->A1_COD
CLOJ := SA1->A1_LOJA            
CNOM := SA1->A1_NOME
CEND := SA1->A1_END
CCID := SA1->A1_MUN
CBAI := SA1->A1_BAIRRO
CEST := SA1->A1_EST
CCEP := SA1->A1_CEP 
CDDD := SA1->A1_DDD
CTEL := SA1->A1_TEL
CFAX := SA1->A1_FAX
CCON := SA1->A1_CONTATO
CDEP := SA1->A1_DEPTCON             
CCGC := SA1->A1_CGC
CINS := SA1->A1_INSCR                                  

/*BEGINDOC
//ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
//³QUERY INCLUSA PARA ATENDER NESSCIDADE DO ITEM TRANSP04 DO PROJETO AVATAR ³
//ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
ENDDOC*/
BEGINSQL ALIAS CALIASTMP   
	%NOPARSER%
	
	SELECT FPM_DTPROG,	FPM_FROTA, FPM_FROTA1, FPM_CODMOT, DA4_NOME
		FROM %TABLE:ZLE% ZLE, %TABLE:DTQ% DTQ, %TABLE:DA4% DA4
	WHERE 	FPM_VIAGEM 			=	DTQ.FQ5_VIAGEM
			AND FPM_AS     		=	DTQ.FQ5_AS
			AND FQ5_OBRA   		=	ZLE.FPM_OBRA
			AND	DA4.DA4_FILIAL	=	ZLE.FPM_FILIAL
			AND	DA4.DA4_COD		=	ZLE.FPM_CODMOT
			AND FPM_STATUS 		=	%EXP:CSTATSPROG%
			AND FPM_FILIAL 		=	%XFILIAL:ZA0%
			AND FPM_AS     		=	%EXP:FQ5->FQ5_AS%				
			AND ZLE.%NOTDEL%
			AND DTQ.%NOTDEL%
			AND DA4.%NOTDEL%
	ORDER BY 1,2			
ENDSQL

// --> CRIACAO DA INTERFACE 
NFOLDERCLI := 0
NFOLDERGER := 0
NFOLDERORI := 0
NFOLDERDES := 0
NFOLDERFRO := 0
NFOLDEROBS := 0
NFOLDERMER := 0

APAGES  := {}
ATITLES := {}
AADD(ATITLES,STR0019         ) ; NFOLDERCLI:=LEN(ATITLES) //"DADOS DO CLIENTE"
AADD(ATITLES,STR0020                    ) ; NFOLDERGER:=LEN(ATITLES) //"GERAL"
AADD(ATITLES,STR0021                   ) ; NFOLDERORI:=LEN(ATITLES) //"ORIGEM"
AADD(ATITLES,STR0022                  ) ; NFOLDERDES:=LEN(ATITLES) //"DESTINO"
AADD(ATITLES,STR0023                   ) ; NFOLDERFRO:=LEN(ATITLES) //"FROTAS"
AADD(ATITLES,STR0024              ) ; NFOLDEROBS:=LEN(ATITLES) //"OBSERVAÇÕES"

NLIN1 := APOSOBJ[2,1]
NCOL1 := APOSOBJ[2,2]
NLIN2 := APOSOBJ[2,4]-APOSOBJ[2,2]  //LARGURA
NCOL2 := APOSOBJ[2,3]-APOSOBJ[2,1]  //ALTURA

//       TFOLDER():NEW(<NROW>,<NCOL>,<CPROMPT>,<CDLGNAMEN>,<OWND> ,<NOPTION>,<NCLRFORE>,<NCLRBACK>,<.LPIXEL.>,<.LDESIGN.>,<NWIDTH>,<NHEIGHT>,<CMSG>)
OFOLDER:=TFOLDER():NEW(NLIN1 ,NCOL1 ,ATITLES  ,APAGES     ,ODLG   ,         ,          ,          ,.T.       ,.F.        ,NLIN2   ,NCOL2    ,      )

FOR NPOS:=1 TO LEN(ATITLES)
	OFOLDER:ADIALOGS[NPOS]:OFONT:=ODLG:OFONT
NEXT

// --> CONSISTENCIA A CADA MUDANCA DE PASTA DO OBJETO FOLDER
//OFOLDER:BSETOPTION:={|NINDO|LOCA04709(NINDO,OFOLDER:NOPTION,@ODLG,@OFOLDER)}
     
DBSELECTAREA("ZA6")                                                            
ZA6->(DBSETORDER(1))
ZA6->(DBSEEK(XFILIAL("ZA6") + CPRJOBRA + CSEQVIA))
IF NOPC==3  //3=INCLUI
	CPROJET := FQ5->FQ5_SOT   
	COBRA   := FQ5->FQ5_OBRA  
	CVIAGEM := FQ5->FQ5_VIAGEM
	CNUM    := LOCA04707()
	ZL8->(DBSEEK(XFILIAL("ZL8")+CPROJET+COBRA+CVIAGEM+CNUM))
	IF ZL8->(!EOF())
		MSGSTOP(STR0025) //"ATENÇÃO: PROBLEMAS NO NÚMERO DA ORDEM DE CARREGAMENTO !!"
		RETURN
	ENDIF
ELSE
	CPROJET:=FQ5->FQ5_SOT    
	COBRA  :=FQ5->FQ5_OBRA   
	CVIAGEM:=FQ5->FQ5_VIAGEM
	CNUM   :=ZL8->ZL8_NUM
ENDIF                                                                          
                                 
CLOCALO:= IIF(!EMPTY(ZL8->ZL8_LOCALO)	,ZL8->ZL8_LOCALO	,ZA6->ZA6_NOMORI)
CENDERO:= IIF(!EMPTY(ZL8->ZL8_ENDERO)	,ZL8->ZL8_ENDERO	,ZA6->ZA6_ENDORI)
CNUMERO:= ZL8->ZL8_NUMERO
CCOMPLO:= ZL8->ZL8_COMPLO
CBAIRRO:= IIF(!EMPTY(ZL8->ZL8_BAIRRO)	,ZL8->ZL8_BAIRRO	,ZA6->ZA6_BAIORI)
CESTADO:= IIF(!EMPTY(ZL8->ZL8_ESTADO)	,ZL8->ZL8_ESTADO	,ZA6->ZA6_ESTORI)         
CCIDADO:= IIF(!EMPTY(ZL8->ZL8_CIDADO)	,ZL8->ZL8_CIDADO	,ZA6->ZA6_MUNORI)
CCGCO  := IIF(!EMPTY(ZL8->ZL8_CGCO)	    ,ZL8->ZL8_CGCO		,ZA6->ZA6_CGCORI)
CINSO  := IIF(!EMPTY(ZL8->ZL8_IEO)		,ZL8->ZL8_IEO		,ZA6->ZA6_INSORI)

CLOCALD:= IIF(!EMPTY(ZL8->ZL8_LOCALD)	,ZL8->ZL8_LOCALD	,ZA6->ZA6_NOMDES)
CENDERD:= IIF(!EMPTY(ZL8->ZL8_ENDERD)	,ZL8->ZL8_ENDERD	,ZA6->ZA6_ENDDES)
CNUMERD:= ZL8->ZL8_NUMERD                            
CCOMPLD:= ZL8->ZL8_COMPLD
CBAIRRD:= IIF(!EMPTY(ZL8->ZL8_BAIRRD)	,ZL8->ZL8_BAIRRD	,ZA6->ZA6_BAIDES)
CESTADD:= IIF(!EMPTY(ZL8->ZL8_ESTADD)	,ZL8->ZL8_ESTADD	,ZA6->ZA6_ESTDES)
CCIDADD:= IIF(!EMPTY(ZL8->ZL8_CIDADD)	,ZL8->ZL8_CIDADD	,ZA6->ZA6_MUNDES)                                  
CCGCD  := IIF(!EMPTY(ZL8->ZL8_CGCD)	    ,ZL8->ZL8_CGCD		,ZA6->ZA6_CGCDES)
CINSD  := IIF(!EMPTY(ZL8->ZL8_IED)		,ZL8->ZL8_IED		,ZA6->ZA6_INSDES)
                                  
DDATAEMI := ZL8->ZL8_DTEMI
CHORAEMI := ZL8->ZL8_HREMI
NPRAZOV  := ZL8->ZL8_PRAZOV
DDATACAR := IIF(NOPC == 3, PESQZLE("D"), ZL8->ZL8_DTCARR) //TRANSP04
CHORACAR := ZL8->ZL8_HRCARR
NQUANT   := ZL8->ZL8_QUANT                               
CDESCCAR := ZL8->ZL8_CARGA

CCODICAR := SPACE(06)

NCOMP    := ZL8->ZL8_COMP
NLARG    := ZL8->ZL8_LARG
NALTU    := ZL8->ZL8_ALTU
NDIAM    := ZL8->ZL8_DIAM
NPESOUNI := ZL8->ZL8_PESOU
NPESOTOT := ZL8->ZL8_PESOT

COBS     := ZL8->ZL8_OBS

IF ZL8->(EOF())
	DDATAEMI := DDATABASE
	CHORAEMI := TIME()
ENDIF

CALIAS  := "ZL8"  //CALIAS:="SZ5"
ASAYZL2 := {}
AGETZL2 := {}

(LOCXCONV(1))->(DBSETORDER(1))
(LOCXCONV(1))->(DBSEEK(CALIAS))
WHILE (LOCXCONV(1))->(!EOF())  .AND.  GetSx3Cache(&(LOCXCONV(2)),"X3_ARQUIVO")==CALIAS     
	IF X3USO( &(LOCXCONV(3)) ) .AND. CNIVEL >= GetSx3Cache(&(LOCXCONV(2)),"X3_NIVEL")
		AADD(ASAYZL2,GetSx3Cache(&(LOCXCONV(2)),"X3_CAMPO"))    
		IF (LOCXCONV(1))->(!UPPER(ALLTRIM(GetSx3Cache(&(LOCXCONV(2)),"X3_CAMPO")))$UPPER("ZL8_PROJET")) .AND. (LOCXCONV(1))->(!UPPER(ALLTRIM(GetSx3Cache(&(LOCXCONV(2)),"X3_CAMPO")))$UPPER("ZL8_OBRA"))
			AADD(AGETZL2,GetSx3Cache(&(LOCXCONV(2)),"X3_CAMPO"))
		ENDIF
		IF GetSx3Cache(&(LOCXCONV(2)),"X3_CONTEXT") <> "V"   
			M->&(GetSx3Cache(&(LOCXCONV(2)),"X3_CAMPO")) := (CALIAS)->&(GetSx3Cache(&(LOCXCONV(2)),"X3_CAMPO"))   
		ELSE
			M->&(GetSx3Cache(&(LOCXCONV(2)),"X3_CAMPO")) := CRIAVAR(GetSx3Cache(&(LOCXCONV(2)),"X3_CAMPO"))
		ENDIF
	ENDIF
	(LOCXCONV(1))->(DBSKIP())
ENDDO 

// DADOS DA ORDEM DE CARREGAMENTO
NLIN1 := APOSOBJ[1,1]
NCOL1 := APOSOBJ[1,2]
NLIN2 := APOSOBJ[1,3]
NCOL2 := APOSOBJ[1,4]

@ NLIN1,NCOL1 TO NLIN2,NCOL2 OF ODLG PIXEL
@ NLIN1+06,NCOL1+005 SAY OEMTOANSI(STR0026)  SIZE 050,8 OF ODLG PIXEL COLOR CLR_BLUE FONT OFONT1 //"PROJETO:"
@ NLIN1+06,NCOL1+210 SAY OEMTOANSI(STR0027   )  SIZE 030,8 OF ODLG PIXEL COLOR CLR_BLUE FONT OFONT1 //"OBRA:"
@ NLIN1+06,NCOL1+298 SAY OEMTOANSI(STR0028 )  SIZE 045,8 OF ODLG PIXEL COLOR CLR_BLUE FONT OFONT1 //"VIAGEM:"
@ NLIN1+06,NCOL1+410 SAY OEMTOANSI("/"       )  SIZE 005,8 OF ODLG PIXEL COLOR CLR_BLUE FONT OFONT1
@ NLIN1+05,NCOL1+055 MSGET OPROJET VAR CPROJET  SIZE 150,8 OF ODLG PIXEL COLOR CLR_BLUE FONT OFONT2 WHEN .F. 
@ NLIN1+05,NCOL1+245 MSGET OBRA    VAR COBRA    SIZE 010,8 OF ODLG PIXEL COLOR CLR_BLUE FONT OFONT2 WHEN .F. 
@ NLIN1+05,NCOL1+345 MSGET OVIAGEM VAR CVIAGEM  SIZE 010,8 OF ODLG PIXEL COLOR CLR_BLUE FONT OFONT2 WHEN .F. 
@ NLIN1+05,NCOL1+420 MSGET ONUM    VAR CNUM     SIZE 050,8 OF ODLG PIXEL COLOR CLR_BLUE FONT OFONT2 WHEN .F. 
  
IF NFOLDERCLI>0 		// DADOS DO CLIENTE     
	NLIN1 := 002
	NCOL1 := 003
	NLIN2 := APOSOBJ[2,3]-55
	NCOL2 := APOSOBJ[2,4]-07
	FFOLDERCLI(NFOLDERCLI,NLIN1,NCOL1,NLIN2,NCOL2)
ENDIF                                                           

IF NFOLDERGER>0 		// GERAL
	NLIN1 := 002
	NCOL1 := 003
	NLIN2 := APOSOBJ[2,3]-55
	NCOL2 := APOSOBJ[2,4]-07
	FFOLDERGER(NFOLDERGER,NLIN1,NCOL1,NLIN2,NCOL2,NOPC)
ENDIF

IF NFOLDERORI>0 		// ORIGEM
	NLIN1 := 002
	NCOL1 := 003
	NLIN2 := APOSOBJ[2,3]-APOSOBJ[2,1]-15  //ALTURA
	NCOL2 := APOSOBJ[2,4]-07
	FFOLDERORI(NFOLDERORI,NLIN1,NCOL1,NLIN2,NCOL2)
ENDIF

IF NFOLDERDES>0 		// DESTINO
	NLIN1 := 002
	NCOL1 := 003
	NLIN2 := APOSOBJ[2,3]-APOSOBJ[2,1]-15  //ALTURA
	NCOL2 := APOSOBJ[2,4]-07
	FFOLDERDES(NFOLDERDES,NLIN1,NCOL1,NLIN2,NCOL2)
ENDIF

IF NFOLDERFRO>0 		// FROTAS          
	NLIN1 := 002
	NCOL1 := 003
	NLIN2 := APOSOBJ[2,3]-APOSOBJ[2,1]-15//////-35  //ALTURA
	NCOL2 := APOSOBJ[2,4]-07
	FFOLDERFRO(NFOLDERFRO,NLIN1,NCOL1,NLIN2,NCOL2,NOPC) 	//TRANSP04
ENDIF
                               
 IF NFOLDEROBS>0  		// OBSERVAÇÕES
	NLIN1 := 002
	NCOL1 := 003
	NLIN2 := APOSOBJ[2,3]-APOSOBJ[2,1]-15//////-35  //ALTURA
	NCOL2 := APOSOBJ[2,4]-07
	FFOLDEROBS(NFOLDEROBS,NLIN1,NCOL1,NLIN2,NCOL2)
ENDIF

ACTIVATE MSDIALOG ODLG CENTERED ON INIT ENCHOICEBAR(ODLG,{||FSALVAR(ODLG,NOPC),ODLG:END()},{||FSAIR(ODLG)},,)

(CALIASTMP)->(DBCLOSEAREA())

RETURN 



// ======================================================================= \\
STATIC FUNCTION FSALVAR(ODLG,NOPC)
// ======================================================================= \\

LOCAL LCHK     := .T.               
LOCAL AAREA    := GETAREA() 
LOCAL AAREAZL8 := GETAREA() 
LOCAL XOPC     := NOPC 

IF LOCA04708()
   FSALVARGER("ZL8",NOPC) 			// ORDEM DE CARREGAMENTO 

   IF NFOLDERFRO>0
		FSALVARFRO("ZL9",ODLGFRO:AHEADER,ODLGFRO:ACOLS,XOPC)
   ENDIF
	BFILTRA := {||FILBROWSE(CSTRING,@AINDEX,@CFILTRA)}
	EVAL(BFILTRA)
ELSE
   LCHK := .F.
ENDIF

RESTAREA(AAREA)
RESTAREA(AAREAZL8)  

RETURN LCHK



// ======================================================================= \\
STATIC FUNCTION FSAIR(ODLG)
// ======================================================================= \\

BFILTRA := {||FILBROWSE(CSTRING,@AINDEX,@CFILTRA)}
EVAL(BFILTRA)
ODLG:END()

RETURN



// ======================================================================= \\
STATIC FUNCTION FHEADER(ACAMPOSSIM)
// ======================================================================= \\

LOCAL NPOS , ATABAUX , AHEADER:={} 

DBSELECTAREA("SX3")
DBSETORDER(2)  //X3_CAMPO
FOR NPOS:=1 TO LEN(ACAMPOSSIM)
	IF (LOCXCONV(1))->(DBSEEK(ALLTRIM(ACAMPOSSIM[NPOS,1])))
		ATABAUX := {}
		AADD(ATABAUX,TRIM(X3TITULO()))
		AADD(ATABAUX,GetSx3Cache(&(LOCXCONV(2)),"X3_CAMPO")    )   
		AADD(ATABAUX,GetSx3Cache(&(LOCXCONV(2)),"X3_PICTURE")  )   
		AADD(ATABAUX,GetSx3Cache(&(LOCXCONV(2)),"X3_TAMANHO")  )   
		AADD(ATABAUX,GetSx3Cache(&(LOCXCONV(2)),"X3_DECIMAL")  )   
		AADD(ATABAUX,GetSx3Cache(&(LOCXCONV(2)),"X3_VALID")    )   
		AADD(ATABAUX,GetSx3Cache(&(LOCXCONV(2)),"X3_USADO")    )   
		AADD(ATABAUX,GetSx3Cache(&(LOCXCONV(2)),"X3_TIPO")     )   
		AADD(ATABAUX,GetSx3Cache(&(LOCXCONV(2)),"X3_F3")       )   
		AADD(ATABAUX,GetSx3Cache(&(LOCXCONV(2)),"X3_CONTEXT")  )   
		AADD(ATABAUX,GetSx3Cache(&(LOCXCONV(2)),"X3_CBOX")     )   
		AADD(ATABAUX,GetSx3Cache(&(LOCXCONV(2)),"X3_RELACAO")  )   
		AADD(ATABAUX,".T."            )
		AADD(ATABAUX,GetSx3Cache(&(LOCXCONV(2)),"X3_VISUAL")   )   
		AADD(ATABAUX,GetSx3Cache(&(LOCXCONV(2)),"X3_VLDUSER")  )   
		AADD(ATABAUX,GetSx3Cache(&(LOCXCONV(2)),"X3_PICTVAR")  )   
		AADD(ATABAUX,GetSx3Cache(&(LOCXCONV(2)),"X3_OBRIGAT")  )   
		AADD(AHEADER,ATABAUX          )
	ENDIF
NEXT

DBSETORDER(1)  //X3_ARQUIVO+X3_ORDEM

RETURN(ACLONE(AHEADER))



// ======================================================================= \\
STATIC FUNCTION FCOLS(AHEADER,CALIAS,NINDICE,CCHAVE,CCONDICAO,CFILTRO)
// ======================================================================= \\

LOCAL NPOS,ACOLS0,ACOLS:={}

(CALIAS)->(DBSETORDER(NINDICE))
(CALIAS)->(DBSEEK(CCHAVE,.T.))
WHILE (CALIAS)->(!EOF() .AND. &CCONDICAO)
	IF !(CALIAS)->(&CFILTRO)
		(CALIAS)->(DBSKIP())
        LOOP
	ENDIF
	ACOLS0:={}
	FOR NPOS:=1 TO LEN(AHEADER)
		IF !AHEADER[NPOS,10]=="V"  //X3_CONTEXT
			(CALIAS)->(AADD(ACOLS0,FIELDGET(FIELDPOS(AHEADER[NPOS,2]))))
		ELSE
			(CALIAS)->(AADD(ACOLS0,CRIAVAR(AHEADER[NPOS,2])))
		ENDIF
	NEXT
	AADD(ACOLS0,.F.  )  //DELETED 
	AADD(ACOLS,ACOLS0)    
	(CALIAS)->(DBSKIP())        
ENDDO 

IF EMPTY(ACOLS)
	ACOLS0:={}
	FOR NPOS:=1 TO LEN(AHEADER)
		(CALIAS)->(AADD(ACOLS0,CRIAVAR(AHEADER[NPOS,2])))
	NEXT
	AADD(ACOLS0,.F.  )  //DELETED
	AADD(ACOLS,ACOLS0)
ENDIF

RETURN(ACLONE(ACOLS))
                    


// ======================================================================= \\
STATIC FUNCTION FGRAVATUDO(CALIAS,AHEADER,ACOLS)  
// ======================================================================= \\
// GRAVA TODOS OS CAMPOS DO ACOLS

LOCAL NPOS,CCAMPO
FOR NPOS:=1 TO LEN(AHEADER)
	CCAMPO:=AHEADER[NPOS,2]
	(CALIAS)->(&CCAMPO):=ACOLS[NPOS]
NEXT

RETURN(.T.)



// ======================================================================= \\
FUNCTION LOCA04707()
// ======================================================================= \\

RETURN(FPROSEQ("ZL8","ZL8_NUM",1,XFILIAL("ZL8")+CPROJET+COBRA+CVIAGEM,"ZL8_FILIAL+ZL8_PROJET+ZL8_OBRA+ZL8_VIAGEM"))



// ======================================================================= \\
STATIC FUNCTION FPROSEQ(CALIAS , CCAMPO , NORDEM , CSEEK , CCHAVE) 
// ======================================================================= \\

LOCAL NRECANT := (CALIAS)->(RECNO()) 
LOCAL NORDANT := (CALIAS)->(INDEXORD()) 
LOCAL CRET

(CALIAS)->(DBSETORDER(NORDEM))
(CALIAS)->(DBGOBOTTOM())
CRET := (CALIAS)->(SPACE(LEN(&CCAMPO)))
(CALIAS)->(DBSEEK(CSEEK))
WHILE (CALIAS)->(!EOF() .AND. &CCHAVE==CSEEK)
	CRET := (CALIAS)->(&CCAMPO) 
	(CALIAS)->(DBSKIP())
ENDDO 

CRET := STRZERO(VAL(CRET)+1,LEN(CRET))

(CALIAS)->(DBSETORDER(NORDANT))
(CALIAS)->(DBGOTO(NRECANT))

RETURN(CRET)



// ======================================================================= \\
STATIC FUNCTION FSALVARGER(CALIAS,NOPC) 		// GERAL
// ======================================================================= \\

LOCAL NPOS  := 0 
LOCAL NITEM := 0
LOCAL NQUANTZA7 := 0

DBSELECTAREA(CALIAS)  							// FROTAS
DBSETORDER(1)         							// ZL8_FILIAL+ZL8_PROJETO+ZL8_OBRA+ZL8_VIAGEM+ZL8_NUM+ZL8_SEQTRA+ZL8_SEQCAR

IF NOPC==5 										// 5=EXCLUI

	DBSEEK(XFILIAL(CALIAS)+CPROJET+COBRA+CVIAGEM+CNUM )
	WHILE !EOF() .AND. ZL8->ZL8_FILIAL+ZL8->ZL8_PROJET+ZL8->ZL8_OBRA+ZL8->ZL8_VIAGEM+ZL8->ZL8_NUM == XFILIAL() + CPROJET+COBRA+CVIAGEM+CNUM
		RECLOCK(CALIAS,.F.)
		DBDELETE()
		MSUNLOCK()
	       
		DBSELECTAREA("ZA7")
		DBSETORDER(1)
		IF MSSEEK(XFILIAL("ZA7") + ZL8->ZL8_PROJET + ZL8->ZL8_OBRA + ZL8->ZL8_SEQTRA + ZL8->ZL8_SEQCAR )
			RECLOCK("ZA7",.F.)   	
			ZA7->ZA7_QJUE := ( ZA7->ZA7_QJUE - ZL8->ZL8_QUANT )
			MSUNLOCK()
		ENDIF
		DBSELECTAREA("ZL8")
		DBSKIP()
	ENDDO 

ELSE      

	FOR NPOS:=1 TO LEN(OGETZA7:ACOLS)
		IF NOPC == 3
			CSEQTRA := OGETZA7:ACOLS[NPOS][ASCAN(OGETZA7:AHEADER,{|X|ALLTRIM(X[2])=="ZA7_SEQTRA"})]
			CSEQCAR := OGETZA7:ACOLS[NPOS][ASCAN(OGETZA7:AHEADER,{|X|ALLTRIM(X[2])=="ZA7_SEQCAR"})]
		ELSE
			CSEQTRA := OGETZA7:ACOLS[NPOS][ASCAN(OGETZA7:AHEADER,{|X|ALLTRIM(X[2])=="ZL8_SEQTRA"})]
			CSEQCAR := OGETZA7:ACOLS[NPOS][ASCAN(OGETZA7:AHEADER,{|X|ALLTRIM(X[2])=="ZL8_SEQCAR"})]
			NQUANT  := OGETZA7:ACOLS[NPOS][ASCAN(OGETZA7:AHEADER,{|X|ALLTRIM(X[2])=="ZL8_QUANT"})]
		ENDIF
		
		IF !OGETZA7:ACOLS[NPOS,LEN(OGETZA7:AHEADER)+1]
			DBSEEK(XFILIAL(CALIAS) + CPROJET + COBRA + CVIAGEM + CNUM + CSEQTRA + CSEQCAR )
			IF EOF()
				RECLOCK(CALIAS,.T.)
			ELSE
				RECLOCK(CALIAS,.F.)
			ENDIF
			(CALIAS)->ZL8_FILIAL := XFILIAL(CALIAS)
			(CALIAS)->ZL8_PROJET := CPROJET    //NRO.PROJETO
			(CALIAS)->ZL8_OBRA   := COBRA      //NRO.OBRA  
			(CALIAS)->ZL8_VIAGEM := CVIAGEM    //VIAGEM
			(CALIAS)->ZL8_NUM    := CNUM       //NRO.CARREGAM.
            (CALIAS)->ZL8_LOCALO := CLOCALO
			(CALIAS)->ZL8_ENDERO := CENDERO
			(CALIAS)->ZL8_NUMERO := CNUMERO
			(CALIAS)->ZL8_COMPLO := CCOMPLO
			(CALIAS)->ZL8_BAIRRO := CBAIRRO
			(CALIAS)->ZL8_ESTADO := CESTADO
			(CALIAS)->ZL8_CIDADO := CCIDADO
			(CALIAS)->ZL8_CGCO   := CCGCO
			(CALIAS)->ZL8_IEO    := CINSO
			(CALIAS)->ZL8_LOCALD := CLOCALD
			(CALIAS)->ZL8_ENDERD := CENDERD
			(CALIAS)->ZL8_NUMERD := CNUMERD                
			(CALIAS)->ZL8_COMPLD := CCOMPLD         
			(CALIAS)->ZL8_BAIRRD := CBAIRRD
			(CALIAS)->ZL8_CIDADD := CCIDADD               
			(CALIAS)->ZL8_ESTADD := CESTADD
			(CALIAS)->ZL8_CGCD   := CCGCD
			(CALIAS)->ZL8_IED    := CINSD
			(CALIAS)->ZL8_DTEMI  := DDATAEMI
			(CALIAS)->ZL8_HREMI  := CHORAEMI
			(CALIAS)->ZL8_PRAZOV := NPRAZOV
			(CALIAS)->ZL8_DTCARR := DDATACAR
			(CALIAS)->ZL8_HRCARR := CHORACAR
			(CALIAS)->ZL8_QUANT  := NQUANT
			(CALIAS)->ZL8_CARGA  := CDESCCAR
            (CALIAS)->ZL8_OBS    := COBS			

            (CALIAS)->ZL8_ITEM   := STRZERO(++NITEM,3)
			(CALIAS)->ZL8_SEQTRA := CSEQTRA
			(CALIAS)->ZL8_SEQCAR := CSEQCAR
            (CALIAS)->ZL8_CARGA  := GDFIELDGET("ZA7_CARGA"  ,NPOS ,.F. ,OGETZA7:AHEADER ,OGETZA7:ACOLS )			
            (CALIAS)->ZL8_QUANT  := GDFIELDGET("ZA7_QTD"  ,NPOS ,.F. ,OGETZA7:AHEADER ,OGETZA7:ACOLS )			
			(CALIAS)->ZL8_COMP   := GDFIELDGET("ZA7_COMP"   ,NPOS ,.F. ,OGETZA7:AHEADER ,OGETZA7:ACOLS )
			(CALIAS)->ZL8_LARG   := GDFIELDGET("ZA7_LARG"   ,NPOS ,.F. ,OGETZA7:AHEADER ,OGETZA7:ACOLS )
			(CALIAS)->ZL8_ALTU   := GDFIELDGET("ZA7_ALTU"   ,NPOS ,.F. ,OGETZA7:AHEADER ,OGETZA7:ACOLS )
			(CALIAS)->ZL8_DIAM   := GDFIELDGET("ZA7_DIAM"   ,NPOS ,.F. ,OGETZA7:AHEADER ,OGETZA7:ACOLS )
			(CALIAS)->ZL8_PESOU  := GDFIELDGET("ZA7_PESO"   ,NPOS ,.F. ,OGETZA7:AHEADER ,OGETZA7:ACOLS )
			(CALIAS)->ZL8_PESOT  := GDFIELDGET("ZA7_PESO"   ,NPOS ,.F. ,OGETZA7:AHEADER ,OGETZA7:ACOLS )
			
			(CALIAS)->(MSUNLOCK())
        
			IF NOPC==3
				DBSELECTAREA("ZA7")
				DBSETORDER(1) //FILAL + PROJET  + OBRA  +  SEQTRA           + SEQCAR
				IF MSSEEK(XFILIAL("ZA7") + CPROJET + COBRA + ZL8->ZL8_SEQTRA  + ZL8->ZL8_SEQCAR )
					RECLOCK("ZA7" , .F.)
					ZA7->ZA7_QJUE := ZA7->ZA7_QJUE + ZL8->ZL8_QUANT
					MSUNLOCK()   
				ENDIF 
			ENDIF 
           
			DBSELECTAREA(CALIAS)
        
		ENDIF
	NEXT NPOS 

	IF NOPC==4
		AAREAZL8 := ZL8->(GETAREA())
		DBSELECTAREA("ZL8")
		DBSETORDER(1) 			// FILIAL+PROJETO+OBRA+VIAGEM+NUMERO+SEQTRA+SEQCAR
		MSSEEK(XFILIAL("ZL8") + CPROJET + COBRA + CVIAGEM  )	       
		WHILE !EOF() .AND. CPROJET + COBRA + CVIAGEM ==  ZL8->ZL8_PROJET + ZL8->ZL8_OBRA + ZL8->ZL8_VIAGEM
			NQUANTZA7 += ZL8->ZL8_QUANT
			DBSELECTAREA("ZL8")
			DBSKIP()
		ENDDO 
		RESTAREA(AAREAZL8)
	       
		AAREAZA7:=ZA7->(GETAREA())
		DBSELECTAREA("ZA7")
		DBSETORDER(2) 			// FILAL + PROJET  + OBRA  + VIAGEM  + SEQTRA + SEQCAR
		IF MSSEEK(XFILIAL("ZA7") + CPROJET + COBRA + CVIAGEM + ZL8->ZL8_SEQTRA  + ZL8->ZL8_SEQCAR )
			RECLOCK("ZA7" , .F.)
			ZA7->ZA7_QJUE := NQUANTZA7
			MSUNLOCK()   
		ENDIF
		RESTAREA(AAREAZA7)
	ENDIF

ENDIF

RETURN 



// ======================================================================= \\
STATIC FUNCTION FSALVARFRO(CALIAS,AHEADER,ACOLS,XOPC) 	// FROTAS
// ======================================================================= \\

LOCAL NPOS,AGRAVADOS:={} 								// GRAVADOS

IF XOPC == 3
	CCHAVE := XFILIAL(CALIAS)+CPROJET+COBRA+CVIAGEM+SPACE(6)
ELSE
	CCHAVE := XFILIAL(CALIAS)+CPROJET+COBRA+CVIAGEM+CNUM
ENDIF

DBSELECTAREA(CALIAS)  									// FROTAS
DBSETORDER(1)         									// ZL9_FILIAL+ZL9_PROJETO+ZL9_OBRA+ZL9_NUM+ZL9_SEQ

IF XOPC==5     											// 5=EXCLUI

ELSE
	FOR NPOS:=1 TO LEN(ACOLS)
		IF !ACOLS[NPOS,LEN(AHEADER)+1] 
			IF DBSEEK(CCHAVE+ACOLS[NPOS][ASCAN(AHEADER,{|X|ALLTRIM(X[2]) == "ZL9_SEQ" }) ])
				RECLOCK(CALIAS,.F.)
			ELSE
				RECLOCK(CALIAS,.T.)
			ENDIF
			FGRAVATUDO(CALIAS,AHEADER,ACOLS[NPOS]) 		// GRAVA TODOS OS CAMPOS DO ACOLS
			(CALIAS)->ZL9_FILIAL := XFILIAL(CALIAS)
			(CALIAS)->ZL9_PROJET := CPROJET
			(CALIAS)->ZL9_OBRA   := COBRA
			(CALIAS)->ZL9_VIAGEM := CVIAGEM
			(CALIAS)->ZL9_NUM    := CNUM
			(CALIAS)->ZL9_SEQ    := ACOLS[NPOS][ASCAN(AHEADER,{|X|ALLTRIM(X[2]) == "ZL9_SEQ" }) ]
			AADD(AGRAVADOS,RECNO()) 					// GRAVADOS
			(CALIAS)->(MSUNLOCK())
		ENDIF
	NEXT
ENDIF

// EXCLUI OS REGISTROS ALTERADOS
DBSEEK(XFILIAL(CALIAS)+CPROJET+COBRA+CVIAGEM)
WHILE !EOF() .AND. ZL9_FILIAL+ZL9_PROJET+ZL9_OBRA+ZL9_VIAGEM==XFILIAL(CALIAS)+CPROJET+COBRA+CVIAGEM
	IF ASCAN(AGRAVADOS,{|X|X==RECNO()})==0
		RECLOCK(CALIAS,.F.)
		DBDELETE()
		(CALIAS)->(MSUNLOCK())
	ENDIF
	DBSKIP()
ENDDO 

RETURN



// ======================================================================= \\
STATIC FUNCTION FFOLDERCLI(NFOLDER,NLIN1,NCOL1,NLIN2,NCOL2)
// ======================================================================= \\

@ NLIN1,NCOL1 SCROLLBOX OPNLCLI HORIZONTAL VERTICAL SIZE NLIN2-3,NCOL2-3 PIXEL BORDER OF OFOLDER:ADIALOGS[NFOLDER]

APOSCAMPO := {}
NPOSCAMPO := (NCOL2-60)/8
NTAMCAMPO := NPOSCAMPO

AADD(APOSCAMPO,(NPOSCAMPO*0))
AADD(APOSCAMPO,(NPOSCAMPO*1))
AADD(APOSCAMPO,(NPOSCAMPO*2))
AADD(APOSCAMPO,(NPOSCAMPO*3))
AADD(APOSCAMPO,(NPOSCAMPO*4))
AADD(APOSCAMPO,(NPOSCAMPO*5))
AADD(APOSCAMPO,(NPOSCAMPO*6))
AADD(APOSCAMPO,(NPOSCAMPO*7))

@ 007,APOSCAMPO[1]+(NTAMCAMPO/2) SAY OEMTOANSI(STR0029 )  SIZE (NTAMCAMPO/2),8 PIXEL OF OPNLCLI //OFOLDER:ADIALOGS[NFOLDER] //"CLIENTE"
@ 007,APOSCAMPO[3]+(NTAMCAMPO/2) SAY OEMTOANSI(STR0030    )  SIZE (NTAMCAMPO/2),8 PIXEL OF OPNLCLI //OFOLDER:ADIALOGS[NFOLDER] //"LOJA"
@ 007,APOSCAMPO[5]+(NTAMCAMPO/2) SAY OEMTOANSI(STR0031    )  SIZE (NTAMCAMPO/2),8 PIXEL OF OPNLCLI //OFOLDER:ADIALOGS[NFOLDER] //"NOME"

@ 020,APOSCAMPO[1]+(NTAMCAMPO/2) SAY OEMTOANSI(STR0032)  SIZE (NTAMCAMPO/2),8 PIXEL OF OPNLCLI //OFOLDER:ADIALOGS[NFOLDER] //"ENDEREÇO"
@ 020,APOSCAMPO[5]+(NTAMCAMPO/2) SAY OEMTOANSI(STR0033  )  SIZE (NTAMCAMPO/2),8 PIXEL OF OPNLCLI //OFOLDER:ADIALOGS[NFOLDER] //"BAIRRO"

@ 033,APOSCAMPO[1]+(NTAMCAMPO/2) SAY OEMTOANSI(STR0034  )  SIZE (NTAMCAMPO/2),8 PIXEL OF OPNLCLI //OFOLDER:ADIALOGS[NFOLDER] //"CIDADE"
@ 033,APOSCAMPO[5]+(NTAMCAMPO/2) SAY OEMTOANSI(STR0035      )  SIZE (NTAMCAMPO/2),8 PIXEL OF OPNLCLI //OFOLDER:ADIALOGS[NFOLDER] //"UF"

@ 046,APOSCAMPO[1]+(NTAMCAMPO/2) SAY OEMTOANSI(STR0036     )  SIZE (NTAMCAMPO/2),8 PIXEL OF OPNLCLI //OFOLDER:ADIALOGS[NFOLDER] //"CEP"
@ 046,APOSCAMPO[3]+(NTAMCAMPO/2) SAY OEMTOANSI(STR0037	 )  SIZE (NTAMCAMPO/2),8 PIXEL OF OPNLCLI //OFOLDER:ADIALOGS[NFOLDER] //"DDD"
@ 046,APOSCAMPO[5]+(NTAMCAMPO/2) SAY OEMTOANSI(STR0038)  SIZE (NTAMCAMPO/2),8 PIXEL OF OPNLCLI //OFOLDER:ADIALOGS[NFOLDER] //"TELEFONE"
@ 046,APOSCAMPO[7]+(NTAMCAMPO/2) SAY OEMTOANSI(STR0039     )  SIZE (NTAMCAMPO/2),8 PIXEL OF OPNLCLI //OFOLDER:ADIALOGS[NFOLDER] //"FAX"

@ 059,APOSCAMPO[1]+(NTAMCAMPO/2) SAY OEMTOANSI(STR0040 )  SIZE (NTAMCAMPO/2),8 PIXEL OF OPNLCLI //OFOLDER:ADIALOGS[NFOLDER] //"CONTATO"
@ 059,APOSCAMPO[5]+(NTAMCAMPO/2) SAY OEMTOANSI(STR0041   )  SIZE (NTAMCAMPO/2),8 PIXEL OF OPNLCLI //OFOLDER:ADIALOGS[NFOLDER] //"DEPTO"

@ 072,APOSCAMPO[1]+(NTAMCAMPO/2) SAY OEMTOANSI(STR0042     )  SIZE (NTAMCAMPO/2),8 PIXEL OF OPNLCLI //OFOLDER:ADIALOGS[NFOLDER] //"C.G.C"
@ 072,APOSCAMPO[3]+(NTAMCAMPO/2) SAY OEMTOANSI(STR0043	 )  SIZE (NTAMCAMPO/2),8 PIXEL OF OPNLCLI //OFOLDER:ADIALOGS[NFOLDER] //"I.E."

@ 006,APOSCAMPO[2] MSGET OCLI VAR CCLI SIZE NTAMCAMPO*1,08 PIXEL PICTURE "@!" WHEN .F.	OF OPNLCLI //OFOLDER:ADIALOGS[NFOLDER]
@ 006,APOSCAMPO[4] MSGET OLOJ VAR CLOJ SIZE NTAMCAMPO*1,08 PIXEL PICTURE "@!" WHEN .F.	OF OPNLCLI //OFOLDER:ADIALOGS[NFOLDER]
@ 006,APOSCAMPO[6] MSGET ONOM VAR CNOM SIZE NTAMCAMPO*3,08 PIXEL PICTURE "@!" WHEN .F.	OF OPNLCLI //OFOLDER:ADIALOGS[NFOLDER]

@ 019,APOSCAMPO[2] MSGET OEND VAR CEND SIZE NTAMCAMPO*3,08 PIXEL PICTURE "@!" WHEN .F.	OF OPNLCLI //OFOLDER:ADIALOGS[NFOLDER]
@ 019,APOSCAMPO[6] MSGET OBAI VAR CBAI SIZE NTAMCAMPO*2,08 PIXEL PICTURE "@!" WHEN .F.	OF OPNLCLI //OFOLDER:ADIALOGS[NFOLDER]

@ 032,APOSCAMPO[2] MSGET OCID VAR CCID SIZE NTAMCAMPO*2,08 PIXEL PICTURE "@!" WHEN .F.	OF OPNLCLI //OFOLDER:ADIALOGS[NFOLDER]
@ 032,APOSCAMPO[6] MSGET OEST VAR CEST SIZE NTAMCAMPO*1,08 PIXEL PICTURE "@!" WHEN .F.	OF OPNLCLI //OFOLDER:ADIALOGS[NFOLDER]

@ 045,APOSCAMPO[2] MSGET OCEP VAR CCEP SIZE NTAMCAMPO*1,08 PIXEL PICTURE "@R XXXXX-XXX"	 WHEN .F.	OF OPNLCLI //OFOLDER:ADIALOGS[NFOLDER]
@ 045,APOSCAMPO[4] MSGET ODDD VAR CDDD SIZE NTAMCAMPO*1,08 PIXEL 						 WHEN .F.	OF OPNLCLI //OFOLDER:ADIALOGS[NFOLDER]
@ 045,APOSCAMPO[6] MSGET OTEL VAR CTEL SIZE NTAMCAMPO*1,08 PIXEL						 WHEN .F.	OF OPNLCLI //OFOLDER:ADIALOGS[NFOLDER]
@ 045,APOSCAMPO[8] MSGET OFAX VAR CFAX SIZE NTAMCAMPO*1,08 PIXEL 						 WHEN .F.	OF OPNLCLI //OFOLDER:ADIALOGS[NFOLDER]

@ 058,APOSCAMPO[2] MSGET OCON VAR CCON SIZE NTAMCAMPO*3,08 PIXEL PICTURE "@!"			 WHEN .F.	OF OPNLCLI //OFOLDER:ADIALOGS[NFOLDER]
@ 058,APOSCAMPO[6] MSGET ODEP VAR CDEP SIZE NTAMCAMPO*3,08 PIXEL PICTURE "@!"			 WHEN .F.	OF OPNLCLI //OFOLDER:ADIALOGS[NFOLDER]

@ 071,APOSCAMPO[2] MSGET OCGC VAR CCGC SIZE NTAMCAMPO*1,08 PIXEL PICTURE "@R XX.XXX.XXX/XXXX-XX"	 WHEN .F.	OF OPNLCLI //OFOLDER:ADIALOGS[NFOLDER]
@ 071,APOSCAMPO[4] MSGET OINS VAR CINS SIZE NTAMCAMPO*1,08 PIXEL 						 WHEN .F.	OF OPNLCLI //OFOLDER:ADIALOGS[NFOLDER]

OCLI:SETFOCUS()                                                               

RETURN 
  


// ======================================================================= \\
STATIC FUNCTION FFOLDERGER(NFOLDER,NLIN1,NCOL1,NLIN2,NCOL2,NOPC) 
// ======================================================================= \\

LOCAL ACPOSZA7 := {"ZA7_PROJET","ZA7_VIAGEM","ZA7_VIAVEL","ZA7_INCADV","ZA7_JUNTO ",;
                   "ZA7_VALICM","ZA7_INCICM","ZA7_TPCARG","ZA7_VALADV","ZA7_OBRA  ",;
                   "ZA7_EHTERC","ZA7_RESPC ","ZA7_RESPD "}

LOCAL ACPOSZL8 := {"ZL8_FILIAL","ZL8_PROJET","ZL8_OBRA  ","ZL8_VIAGEM","ZL8_NUM   ","ZL8_DTEMI ",;
                   "ZL8_HREMI ","ZL8_DTCARR","ZL8_HRCARR","ZL8_PRAZOV","ZL8_LOCALO","ZL8_ENDERO",;
                   "ZL8_NUMERO","ZL8_COMPLO","ZL8_BAIRRO","ZL8_CIDADO","ZL8_ESTADO","ZL8_CIDADD",;
                   "ZL8_LOCALD","ZL8_ENDERD","ZL8_NUMERD","ZL9_COMPLD","ZL8_BAIRRD","ZL8_CGCD  ",;
                   "ZL8_ESTADD","ZL8_OBS   ","ZL8_CODCAR","ZL8_CGCO  ","ZL8_IEO   ","ZL8_IED   " }

LOCAL ACPOSNAO := {}
LOCAL AHEADZA7 := {}
LOCAL ACOLSZA7 := {}
LOCAL ATEMP    := {}
LOCAL CCHAVE   := ""
LOCAL NSTYLE   := GD_UPDATE + GD_DELETE
LOCAL CALIAS   := ""
LOCAL NORD     := 1
LOCAL BCOND
LOCAL I        := 0 

PRIVATE CNUMZL8 := ""

IF NOPC == 3
	ACPOSNAO := ACLONE(ACPOSZA7)
	CALIAS   := "ZA7"
	NORD     := 1
	BCOND    := {|| (ZA7->ZA7_FILIAL+ZA7->ZA7_PROJET+ZA7->ZA7_OBRA+ZA7->ZA7_SEQTRA == XFILIAL("ZA7") + CPROJET + COBRA + CSEQVIA) .AND. (ZA7->ZA7_QTD > ZA7->ZA7_QJUE)  }                          
   CCHAVE    :=  XFILIAL("ZA7") + CPROJET + COBRA + CSEQVIA //+ CSEQCAR
ELSE   
	ACPOSNAO := ACLONE(ACPOSZL8)
	CNUMZL8  := ZL8->ZL8_NUM
	CALIAS   := "ZL8"
	NORD     := 1
	BCOND    := {|| ZL8->ZL8_FILIAL+ZL8->ZL8_PROJET+ZL8->ZL8_OBRA+ZL8->ZL8_VIAGEM+ZL8->ZL8_NUM == XFILIAL("ZL8") + CPROJET + COBRA + CVIAGEM + CNUMZL8 }
    CCHAVE   := XFILIAL("ZL8") +  CPROJET + COBRA + CVIAGEM + CNUMZL8 //FILIAL + PROJETO + OBRA + VIAGEM
ENDIF
IF !EMPTY(FQ5->FQ5_DATFIM) .AND. !EMPTY(FQ5->FQ5_DATINI)     
	NPRAZOV  := FQ5->FQ5_DATFIM - FQ5->FQ5_DATINI
ELSE
	NPRAZOV  := 0
ENDIF   

OPANEL:= TPANEL():NEW(0, 0, "", OFOLDER:ADIALOGS[NFOLDER],, .F., .F.,,,0,80, .F., .F. )
OPANEL:ALIGN:= CONTROL_ALIGN_TOP

OPANEL2:= TPANEL():NEW(0, 0, "",OFOLDER:ADIALOGS[NFOLDER],, .F., .F.,,,0,160, .F., .F. )
OPANEL2:ALIGN:= CONTROL_ALIGN_TOP

@ 002+000+000,002+000 SAY OEMTOANSI(STR0044      ) SIZE 080,8 PIXEL OF OPANEL //"DATA EMISSÃO"
@ 002+000+000,002+120 SAY OEMTOANSI(STR0045              ) SIZE 080,8 PIXEL OF OPANEL //"HORA"
@ 002+011+000,002+000 SAY OEMTOANSI(STR0046   ) SIZE 080,8 PIXEL OF OPANEL //"PRAZO DE VIAGEM"
@ 002+022+000,002+000 SAY OEMTOANSI(STR0047 ) SIZE 080,8 PIXEL OF OPANEL //"DATA CARREGAMENTO"
@ 002+022+000,002+120 SAY OEMTOANSI(STR0045              ) SIZE 080,8 PIXEL OF OPANEL //"HORA"

@ 001+000+000,057+000 MSGET ODATAEMI   VAR DDATAEMI       SIZE 045,8 PIXEL OF OPANEL WHEN .F.
@ 001+000+000,057+090 MSGET OHORAEMI   VAR CHORAEMI       SIZE 025,8 PIXEL OF OPANEL PICTURE "@R 99:99:99" WHEN .F.
@ 001+011+000,057+000 MSGET OPRAZOV    VAR NPRAZOV        SIZE 020,8 PIXEL OF OPANEL PICTURE "@E 9999" WHEN .F.
@ 001+022+000,057+000 MSGET ODATACAR   VAR DDATACAR       SIZE 045,8 PIXEL OF OPANEL
@ 001+022+000,057+090 MSGET OHORACAR   VAR CHORACAR       SIZE 025,8 PIXEL OF OPANEL PICTURE "@R 99:99:99"

ATEMP    := LOCA036(CALIAS,ACPOSNAO)
AHEADZA7 := ACLONE(ATEMP[1]) 
	
ATEMP    := GETACOLSZA7(CALIAS,AHEADZA7,4,NORD,CCHAVE, BCOND, CSEQCAR2) //LOCA03601(CALIAS,AHEADZA7,4,NORD,CCHAVE, BCOND )
ACOLSZA7 := ACLONE(ATEMP[1]) 
  
IF LEN(ACOLSZA7) == 0
	AADD( ACOLSZA7, {} )
	FOR I:= 1 TO LEN(AHEADZA7)
		AADD( ACOLSZA7[ LEN(ACOLSZA7) ], CRIAVAR( AHEADZA7[I, 2] ) )
	NEXT I 
	AADD( ACOLSZA7[ LEN( ACOLSZA7) ], .F.)
	NSTYLE := 0
ENDIF    
//                           NTOP ,NLEFT,NBOTTOM,NRIGHT,NSTYLE,CLINHAOK      ,CTUDOOK       ,CINICPOS    ,AALTER,NFREEZE,NMAX          ,CFIELDOK,CSUPERDEL,CDELOK,OWND    ,AHEADER  ,ACOLS}
OGETZA7:=MSNEWGETDADOS():NEW(10   , 10  , 100   , 100  ,NSTYLE, "ALLWAYSTRUE", "ALLWAYSTRUE",            ,      ,       ,LEN(ACOLSZA7) ,        ,         ,.T.   ,OPANEL2 ,AHEADZA7 ,ACOLSZA7 )
OGETZA7:OBROWSE:ALIGN:= CONTROL_ALIGN_ALLCLIENT
    
RETURN



// ======================================================================= \\
STATIC FUNCTION FFOLDERORI(NFOLDER,NLIN1,NCOL1,NLIN2,NCOL2)
// ======================================================================= \\

@ 002+000+000,002 SAY OEMTOANSI(STR0048   )  SIZE 060,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER] //"LOCAL"
@ 002+011+000,002 SAY OEMTOANSI(STR0032)  SIZE 060,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER] //"ENDEREÇO"
@ 002+022+000,002 SAY OEMTOANSI(STR0033  )  SIZE 060,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER] //"BAIRRO"
@ 002+033+000,002 SAY OEMTOANSI(STR0049  )  SIZE 060,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER] //"ESTADO"
@ 002+044+000,002 SAY OEMTOANSI(STR0034  )  SIZE 060,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER] //"CIDADE"
@ 002+055+000,002 SAY OEMTOANSI(STR0042   )  SIZE 060,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER] //"C.G.C"
@ 002+066+000,002 SAY OEMTOANSI(STR0043    )  SIZE 060,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER] //"I.E."

@ 001+000+000,047 MSGET OLOCALO  VAR CLOCALO SIZE 120,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER]
@ 001+011+000,047 MSGET OENDERO  VAR CENDERO SIZE 120,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER]
@ 001+022+000,047 MSGET OBAIRRO  VAR CBAIRRO SIZE 080,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER]
@ 001+033+000,047 MSGET OESTADO  VAR CESTADO SIZE 015,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER] PICTURE "@!" F3 "12"
@ 001+044+000,047 MSGET OCIDADO  VAR CCIDADO SIZE 080,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER]
@ 001+055+000,047 MSGET OCGCO    VAR CCGCO   SIZE 080,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER]
@ 001+066+000,047 MSGET OINSO    VAR CINSO   SIZE 080,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER]

RETURN



// ======================================================================= \\
STATIC FUNCTION FFOLDERDES(NFOLDER,NLIN1,NCOL1,NLIN2,NCOL2)
// ======================================================================= \\

@ 002+000+000,002 SAY OEMTOANSI(STR0048   )  SIZE 060,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER] //"LOCAL"
@ 002+011+000,002 SAY OEMTOANSI(STR0032)  SIZE 060,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER] //"ENDEREÇO"
@ 002+022+000,002 SAY OEMTOANSI(STR0033  )  SIZE 060,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER] //"BAIRRO"
@ 002+033+000,002 SAY OEMTOANSI(STR0049  )  SIZE 060,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER] //"ESTADO"
@ 002+044+000,002 SAY OEMTOANSI(STR0034  )  SIZE 060,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER] //"CIDADE"
@ 002+055+000,002 SAY OEMTOANSI(STR0042   )  SIZE 060,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER] //"C.G.C"
@ 002+066+000,002 SAY OEMTOANSI(STR0043    )  SIZE 060,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER] //"I.E."

@ 001+000+000,047 MSGET OLOCALD  VAR CLOCALD SIZE 120,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER]
@ 001+011+000,047 MSGET OENDERD  VAR CENDERD SIZE 120,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER]
@ 001+022+000,047 MSGET OBAIRRD  VAR CBAIRRD SIZE 080,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER]
@ 001+033+000,047 MSGET OESTADD  VAR CESTADD SIZE 015,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER] F3 "12"
@ 001+044+000,047 MSGET OCIDADD  VAR CCIDADD SIZE 080,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER]
@ 001+055+000,047 MSGET OCGCD    VAR CCGCD   SIZE 080,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER]
@ 001+066+000,047 MSGET OINSD    VAR CINSD   SIZE 080,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER]

RETURN



// ======================================================================= \\
STATIC FUNCTION FFOLDERFRO(NFOLDER,NLIN1,NCOL1,NLIN2,NCOL2,NOPC)
// ======================================================================= \\

LOCAL ACAMPOSSIM := {}
LOCAL NSTYLE     := GD_INSERT + GD_UPDATE + GD_DELETE

LOCAL CALIAS,CCHAVE,CCONDICAO,NINDICE,CFILTRO

CALIAS    := "ZL9"
CCHAVE    := XFILIAL(CALIAS)+CPROJET+COBRA+CVIAGEM
CCONDICAO := 'ZL9_FILIAL+ZL9_PROJET+ZL9_OBRA+ZL9_VIAGEM=="'+CCHAVE+'"'
NINDICE   := 2 											// ZL9_FILIAL+ZL9_PROJET+ZL9_OBRA+ZL9_VIAGEM+ZL9_FROTA
CFILTRO   := CCONDICAO

AADD(ACAMPOSSIM,{"ZL9_SEQ"   ,""})
AADD(ACAMPOSSIM,{"ZL9_FROTA" ,""})
AADD(ACAMPOSSIM,{"ZL9_PLACA" ,""})
AADD(ACAMPOSSIM,{"ZL9_MOTORI",""})
AADD(ACAMPOSSIM,{"ZL9_NOME"  ,""})

AHEADER := FHEADER(ACAMPOSSIM)
ACOLS   := FCOLS(AHEADER,CALIAS,NINDICE,CCHAVE,CCONDICAO,CFILTRO) 

ACOLS:=IIF(NOPC == 3,PESQZLE("A"),ACOLS) 				// PREENCHIMENTO DO ACOLS CONFORME PROGRAMAÇÃO DIARIA TRANSP04

IF LEN(ACOLS)==1
	IF EMPTY(ACOLS[1][ASCAN(AHEADER,{|X|ALLTRIM(X[2])=="ZL9_SEQ"})])
		ACOLS[1][ASCAN(AHEADER,{|X|ALLTRIM(X[2])=="ZL9_SEQ"})]:="001"
	ENDIF
ENDIF

//                           NTOP ,NLEFT,NBOTTOM,NRIGHT,NSTYLE,CLINHAOK      ,CTUDOOK,CINICPOS  ,AALTER,NFREEZE,NMAX,CFIELDOK,CSUPERDEL,CDELOK,OWND                     ,AHEADER,ACOLS}
ODLGFRO:=MSNEWGETDADOS():NEW(NLIN1,NCOL1,NLIN2  ,NCOL2 ,NSTYLE,              ,       ,"+ZL9_SEQ",      ,       ,110 ,        ,         ,.T.   ,OFOLDER:ADIALOGS[NFOLDER],AHEADER,ACOLS)

RETURN



// ======================================================================= \\
STATIC FUNCTION FFOLDEROBS(NFOLDER,NLIN1,NCOL1,NLIN2,NCOL2)
// ======================================================================= \\

LOCAL NSTYLE 

NSTYLE := GD_INSERT + GD_UPDATE + GD_DELETE 

@ NLIN1+000,NCOL1 GET OOBS VAR COBS SIZE INT((NCOL2-NCOL1)),INT((NLIN2)) OF OFOLDER:ADIALOGS[NFOLDER] PIXEL MEMO
                                                                                
RETURN 



// ======================================================================= \\
FUNCTION LOCA04708()
// ======================================================================= \\

LOCAL LRET := .T.

IF NOPC <> 4
	IF EMPTY(OGETZA7:ACOLS[1][2])
		MSGALERT("NÃO EXISTEM CARGAS.VERIFIQUE!" , "GPO - LOCT005.PRW") 
		LRET := .F.
	ENDIF 
ENDIF

RETURN LRET


/*
// ======================================================================= \\
FUNCTION LOCA04709(NINDO,NESTOU,ODLG,OFOLDER)
// ======================================================================= \\
// --> CHAMADA: COMENTADA / DESCONTINUADO 
LOCAL NPOS,ADIR,ACOLS,ACOLS0,LRET:=.T.
LOCAL CNOMEMOT := ""
LOCAL CCODIMOT := ""
LOCAL NCAMPOMO := ASCAN(ODLGFRO:AHEADER,{|X| ALLTRIM(X[2]) == "ZL9_MOTORI"})
LOCAL CRG      := ""

IF LFIRST
	FOR NPOS := 1 TO LEN(ODLGFRO:ACOLS)
	    IF !EMPTY(ODLGFRO:ACOLS[NPOS][NCAMPOMO])
	        CCODIMOT := ODLGFRO:ACOLS[NPOS][ASCAN(ODLGFRO:AHEADER,{|X| ALLTRIM(X[2]) == "ZL9_MOTORI"}) ]
	        CNOMEMOT := ODLGFRO:ACOLS[NPOS][ASCAN(ODLGFRO:AHEADER,{|X| ALLTRIM(X[2]) == "ZL9_NOMEMO"}) ]
	        CRG      := POSICIONE("DA4",1,XFILIAL("DA4") + CCODIMOT , "DA4_RG")
		ENDIF
	NEXT
	
	DO CASE
	CASE NINDO==NFOLDEROBS
		COBS   := "MOTORISTA: "+CNOMEMOT+" - RG:. " +CRG +". "+COBS
	    OOBS:REFRESH()
	    LFIRST := .F.
	ENDCASE
	
	DO CASE
	CASE NESTOU==NFOLDEROBS
		COBS   := "MOTORISTA: "+CNOMEMOT+" - RG:. " +CRG +". "+COBS
        OOBS:REFRESH()
		LFIRST := .F.
	ENDCASE
ENDIF

ODLG:REFRESH()

RETURN(LRET)
*/


/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±ÉÍÍÍÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍ»±±
±±ºPROGRAMA  ³ PESQZLE   º AUTOR ³ IT UP BUSINESS     º DATA ³ 01/01/2007 º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºUSO       ³ ESPECIFICO GPO                                             º±±
±±ÈÍÍÍÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß
*/
STATIC FUNCTION PESQZLE(UPAR)

LOCAL URET

DO CASE 
CASE UPPER(UPAR) == "D"
	URET := STOD((CALIASTMP)->FPM_DTPROG)

CASE UPPER(UPAR) == "A"
	URET:= {}
	IF !EMPTY((CALIASTMP)->FPM_FROTA)
		AADD(URET, {"001",	(CALIASTMP)->FPM_FROTA, POSICIONE("ST9",1,XFILIAL("ST9")+(CALIASTMP)->FPM_FROTA,"T9_PLACA"),;
							(CALIASTMP)->FPM_CODMOT,(CALIASTMP)->DA4_NOME,.F.})
		IF !EMPTY((CALIASTMP)->FPM_FROTA1)
			AADD(URET, {"001",	(CALIASTMP)->FPM_FROTA1, POSICIONE("ST9",1,XFILIAL("ST9")+(CALIASTMP)->FPM_FROTA1,"T9_PLACA"),;
								(CALIASTMP)->FPM_CODMOT,(CALIASTMP)->DA4_NOME,.F.})
		ENDIF
	ENDIF

ENDCASE

RETURN(URET)



// ======================================================================= \\
STATIC FUNCTION GETACOLSZA7(CALIAS, AHEADER, NOPC, NORD, CCHAVE, BCOND, CSEQCAR)
// ======================================================================= \\

#DEFINE _X3CONTEXTO		10

LOCAL ACOLS   := {}
LOCAL ARECNOS := {}
LOCAL AAREAAUX:= {}
LOCAL AAREAATU:= GETAREA()
LOCAL NLOOP   := 0
LOCAL NHEAD   := LEN( AHEADER )
LOCAL CVARTMP

REGTOMEMORY(CALIAS,.F.)

CACAO := IIF(NOPC==1,STR0050,IIF(NOPC==3,STR0051,STR0052 )) //"- VISUALIZAR"###"- ALTERAR"###"- EXCLUIR"

//ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
//³ PARÂMETROS DA FUNÇÃO:                                                   ³
//³    CALIAS  -> ALIAS DA TABELA                                           ³
//³    AHEADER -> MATRIZ COM O CABEÇALHO DE CAMPOS (AHEADER)                ³
//³    NOPC    -> SEGUE A MESMA LÓGICA DAS OPÇÕES DA MATRIZ AROTINA         ³
//³    NORD    -> ORDEM DO ÍNDICE DE CALIAS                                 ³
//³    CCHAVE  -> CHAVE PARA O SEEK DE POSICIONAMENTO EM CALIAS             ³
//³    BCOND   -> CONDIÇÃO DO `DO WHILE`                                    ³
//³    BLINHA  -> CONDIÇÃO DE FILTRO (SELEÇÃO) DE REGISTROS                 ³
//³    LQUERY  -> VARIAVEL LOGICA QUE INDICA SE O ALIAS É UMA QUERY         ³
//³                                                                         ³
//³ RETORNO DA FUNCAO                                                       ³
//³    ARRAY COM:                                                           ³
//³    ELEMENTO [1] - ARRAY DO ACOLS                                        ³
//³    ELEMENTO [2] - ARRAY DOS RECNOS DA TABELA                            ³
//ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ

// AJUSTA OS PARAMETROS NECESSÁRIOS COM SUAS OPÇÕES DEFAULT
DEFAULT CALIAS 	:= ALIAS()
DEFAULT CCHAVE 	:= ""
DEFAULT NOPC	:= 3
DEFAULT NORD   	:= 1
DEFAULT BCOND  	:= {|| .T. }

// ARMAZENA AREA ORIGINAL DO ARQUIVO A SER UTILIZADO NA MONTAGEM DO ACOLS
AAREAAUX := (CALIAS)->(GETAREA())

IF ! NOPC == 3 // INCLUSÃO
	DBSELECTAREA(CALIAS)
	DBCLEARFILTER()
	IF LQUERY
		DBGOTOP()
	ELSE
		DBSETORDER(NORD)
		DBSEEK(CCHAVE)
	ENDIF
	// MONTA O ACOLS
	WHILE !EOF() //.AND. EVAL( BCOND )
		IF !EVAL( BCOND )
			(CALIAS)->( DBSKIP() )
			LOOP
		ENDIF
		IF FUNNAME(0)=="LOCA047"    	
			IF CALIAS == "ZA7"
				IF !EMPTY(ZA7->ZA7_JUNTO) .AND. ZA7->ZA7_QUANT == "0"
					NPOS := ASCAN(ACOLS,{|X| X[2] == ZA7->ZA7_JUNTO})
					IF NPOS <= 0
					 //	(CALIAS)->( DBSKIP() )
					 //	LOOP
					ENDIF
				ELSE
					IF ZA7->ZA7_SEQCAR != CSEQCAR
						(CALIAS)->( DBSKIP() )
						LOOP
					ENDIF
				ENDIF
			ENDIF
		ENDIF
		
		AADD( ACOLS, {} )
		FOR NLOOP := 1 TO NHEAD
			// VERIFICA SE O CAMPO É APENAS VIRTUAL
			IF AHEADER[ NLOOP, _X3CONTEXTO ] == "V"
				IF AHEADER[ NLOOP ][ 2 ] == "DTR_NOMMOT"
				   CVARTMP  := POSICIONE("DA4",1,XFILIAL("DA4")+FIELDGET( FIELDPOS("DTR_CODMOT")),"DA4_NOME" )
				ELSE
				    CVARTMP := CRIAVAR( AHEADER[NLOOP][2] )
				ENDIF
			ELSE 
		        IF FUNNAME(0)=="LOCA047" .AND. ALLTRIM(AHEADER[NLOOP][2]) == "ZA7_QTD"
					CVARTMP := FIELDGET( FIELDPOS( AHEADER[NLOOP][2] ) ) - FIELDGET( FIELDPOS( "ZA7_QJUE" ) )
		        ELSE 
					CVARTMP := FIELDGET( FIELDPOS( AHEADER[NLOOP][2] ) ) 
				ENDIF
			ENDIF
				
			// ACRESCENTA DADOS À MATRIZ
			AADD( ACOLS[ LEN(ACOLS) ], CVARTMP )
		NEXT NLOOP
		
		// ACRESCENTA A ACOLS A VARIÁVEL LÓGICA DE CONTROLE DE DELEÇÃO DA LINHA
		AADD( ACOLS[ LEN(ACOLS) ], .F. )
		
		// ACRESCENTA A ARECNOS O NÚMERO DO REGISTRO
		(CALIAS)->( DBSKIP() )
	ENDDO
ELSE 
	AADD( ACOLS, {} ) 
	FOR NLOOP := 1 TO NHEAD 
		AADD( ACOLS[LEN(ACOLS)], CRIAVAR( AHEADER[NLOOP,2] ) ) 
	NEXT NLOOP 
	AADD( ACOLS[LEN(ACOLS)] , .F.)
	AADD( ARECNOS, {} ) 
ENDIF

// RESTAURA AREA ORIGINAL DO ARQUIVO UTILIZADO NA MONTAGEM DO ACOLS
RESTAREA(AAREAAUX) 

// RESTAURA AREA ORIGNAL DA ENTRADA DA ROTINA
RESTAREA(AAREAATU) 

RETURN { ACOLS , ARECNOS } 
                        


// ======================================================================= \\
FUNCTION LOCA04710() 
// ======================================================================= \\
// --> CHAMADA: VALIDAÇÃO DO CAMPO: ZA7_QTD - QUANTIDADE DIGITADA NO ACOLS

LOCAL AAREA	   := GETAREA() 
LOCAL AAREAZA7 := ZA7->(GETAREA())
LOCAL CSEQTRA  := "" 	// OGETZA7:ACOLS[N, GDFIELDPOS("ZA7_SEQTRA")]
LOCAL CSEQCAR  := "" 	// OGETZA7:ACOLS[N, GDFIELDPOS("ZA7_SEQCAR")]
LOCAL LRET     := .T.
    
IF FUNNAME(0)=="LOCA047"
	CSEQTRA := OGETZA7:ACOLS[N, GDFIELDPOS("ZA7_SEQTRA")]
	CSEQCAR	:= OGETZA7:ACOLS[N, GDFIELDPOS("ZA7_SEQCAR")]
	DBSELECTAREA("ZA7")
	DBSETORDER(1)
	IF DBSEEK(XFILIAL("ZA7")+CPROJET+COBRA+CSEQTRA+CSEQCAR)
		IF M->ZA7_QTD > (ZA7->ZA7_QTD - ZA7->ZA7_QJUE)	
			MSGALERT(STR0053 , STR0018)  //"ATENÇÃO: QUANTIDADE INVÁLIDA!"###"GPO - LOCT005.PRW"
			LRET := .F.	
		ENDIF
	ENDIF
	IF M->ZA7_QTD <= 0
		MSGALERT(STR0053 , STR0018)  //"ATENÇÃO: QUANTIDADE INVÁLIDA!"###"GPO - LOCT005.PRW"
		LRET := .F.
	ENDIF
ENDIF

RESTAREA(AAREAZA7)
RESTAREA(AAREA)

RETURN(LRET)

     

// ======================================================================= \\
FUNCTION LOCA04711()  
// ======================================================================= \\
// --> "COMPLEMENTAR" - GERO UMA VIAGEM COMPLEMENTAR PARA EMITIR UM CTRC COMPLEMENTAR

LOCAL NAREADTQ := FQ5->(GETAREA())
LOCAL NRECDTQ  := FQ5->(RECNO())
LOCAL CCTRC1   := FQ5->FQ5_NUMCTR
LOCAL CVIAGEM1 := FQ5->FQ5_VIAGEM
LOCAL CSOT     := FQ5->FQ5_SOT
LOCAL COBRA    := FQ5->FQ5_OBRA
LOCAL CTIPCTRC := ""	
/*
IF EMPTY(FQ5->FQ5_NUMCTR) .OR. FQ5->FQ5_NUMCTR = "-"
	MSGALERT("SÓ É PERMITIDO A GERAÇÃO DE CTRC COMPLEMENTAR" + CHR(13) + ;
		     "PARA DOCUMENTOS (CTRC) JÁ GERADOS NO SISTEMA.")
	RESTAREA(NAREADTQ)
	RETURN(.F.)
ELSEIF !EMPTY(FQ5->FQ5_CTRDES)
/*	MSGALERT("CTRC JÁ POSSUI COMPLEMENTO GERADO NA VIAGEM " + FQ5->FQ5_CTRDES + "." + CHR(13) + ;
	         "VOCÊ SÓ PODE GERAR CTRC COMPLEMENTAR PARA A MESMA.")
	RESTAREA(NAREADTQ)
	RETURN(.F.) */
//ENDIF 
/*
IF !EMPTY(FQ5->FQ5_TPCTRC) //SE DIFERENTE, É CTRC COMPLEMENTAR,E NÃO PODE GERAR COMPLEMENTO DO COMPLEMENTO.
	MSGALERT("SÓ É PERMITIDO A GERAÇÃO DE CTRC COMPLEMENTAR" + CHR(13) + ;
		     "PARA DOCUMENTOS (CTRC) ORIGEM.")
	RESTAREA(NAREADTQ)
	RETURN(.F.)
ENDIF
*/
CTIPCTRC := CRIACOMBOBOX() 

IF !MSGYESNO(STR0054 + CVIAGEM1 + " ?") //"CONFIRMA A GERAÇÃO DE UM CTRC COMPLEMENTAR PARA A VIAGEM "
	RESTAREA(NAREADTQ)
	RETURN(.F.)
ENDIF

BEGIN TRANSACTION

CVIAGEM := GETSX8NUM("FQ5", "FQ5_VIAGEM" )

IF  LOCA00108("FQ5",1,"FQ5_FILIAL+FQ5_VIAGEM",XFILIAL("FQ5")+CVIAGEM1,{{"FQ5_VIAGEM",CVIAGEM},;
                                                                        {"FQ5_PERADV",0},;
                                                                        {"FQ5_VLRINF",0},;
                                                                        {"FQ5_VALADV",0},;
                                                                        {"FQ5_DATGER",DDATABASE},;
                                                                        {"FQ5_HORGER",SUBSTR(TIME(),1,2)+SUBSTR(TIME(),4,2)},;
                                                                        {"FQ5_NUMCTR",""},;
                     {"FQ5_SERCTR",""},;
                                                                        {"FQ5_ENCERR","1"},;
                                                                        {"FQ5_OBSCTR",STR0055 + CCTRC1 + ", VIAGEM " + CVIAGEM1},; //"COMPLEMENTAR AO CTRC NUMERO "
                                                                        {"FQ5_NUMPV" ,""},;
                                                                        {"FQ5_NUMCTC",""},;
                                                                        {"FQ5_FORCTC",""},;
                                                                        {"FQ5_LOJCTC",""},;
                                                                        {"FQ5_NOMCTC",""},;
                                                                        {"FQ5_NTCLI" ,""},;
                                                                        {"FQ5_VALCAR",0},;
                                                                        {"FQ5_CONHEC",""},;
                                                                        {"FQ5_OBSCTB",""},;
                                                                        {"FQ5_OBSCOM",""},;
                                                                        {"FQ5_NUMSLD",""},;
                                                                        {"FQ5_TPCTRC",CTIPCTRC},;
                                                                        {"FQ5_CTRDES",""},;
                                                                        {"FQ5_CTRORI",CVIAGEM1}})	// DUPLICA O REGISTRO DA TABELA INFORMADA
 /*	LOCA00108("DTC",9,"DTC_FILIAL+DTC_VIAGEM",XFILIAL("DTC")+CVIAGEM1,{{ADUPLDTC},;            	// NAO ESTAVA FUNCIONANDO POR CAUSA DO INDICE
    																	{"DTC_DOC"   ,""},;
    																	{"DTC_SERIE" ,""},;
    																	{"DTC_VIAGEM",CVIAGEM}})*/	// DUPLICA O REGISTRO DA TABELA INFORMADA  
    				 
    GETDTCDUPL(CSOT,COBRA,CVIAGEM1,CVIAGEM) 		// DUPLICA DTC

	_CCHAVE := "DTR_FILIAL+DTR_SOT+DTR_OBRA+DTR_VIAGEM"
    LOCA00108("DTR",7,_CCHAVE,XFILIAL("DTR")+CSOT+COBRA+CVIAGEM1,     {{"DTR_VIAGEM",CVIAGEM},;
                                                                        {"DTR_INSRET",0},;
                                                                        {"DTR_VALFRE",0},;
                                                                        {"DTR_VALPDG",0},;
                                                                        {"DTR_ADIFRE",0},;
                                                                        {"DTR_SLDREC",0},;
                                                                        {"DTR_DTVENC",CTOD("//")},;
                                                                        {"DTR_IRPF",0},;
                                                                        {"DTR_INSS",0},;
                                                                        {"DTR_DATA",CTOD("//")}})	//DUPLICA O REGISTRO DA TABELA INFORMADA
	CONFIRMSX8()
	RESTAREA(NAREADTQ)
	FQ5->(DBGOTO(NRECDTQ))
	RECLOCK("FQ5", .F. )
	FQ5->FQ5_CTRDES := CVIAGEM
	FQ5->(MSUNLOCK()) 
	MSGINFO(STR0056 + CVIAGEM + STR0057 , STR0018) //"CTRC COMPLEMENTAR GERADO COM SUCESSO ! VIAGEM "###" GERADA."###"GPO - LOCT005.PRW"
ELSE
	ROLLBACKSX8()
	RESTAREA(NAREADTQ)
	FQ5->(DBGOTO(NRECDTQ))
	MSGINFO(STR0058 , STR0018) //"CTRC COMPLEMENTAR NÃO FOI GERADO ! "###"GPO - LOCT005.PRW"
ENDIF

RESTAREA(NAREADTQ)
FQ5->(DBGOTO(NRECDTQ))

END TRANSACTION

RETURN   



// ======================================================================= \\
STATIC FUNCTION GETDTCDUPL(CSOT , COBRA , CVIAGEM1 , CVIAGEM) 
// ======================================================================= \\

LOCAL AAREA    := GETAREA()
LOCAL AAREADTC
LOCAL ADTC     := {}
LOCAL NX       := 0 

DBSELECTAREA("DTC")
DBORDERNICKNAME("DTCIND10")
DBSEEK(XFILIAL("DTC") + CSOT + COBRA + CVIAGEM1 )
WHILE !DTC->(EOF())  .AND.  DTC->DTC_FILIAL + DTC->DTC_SOT + DTC->DTC_OBRA + DTC->DTC_VIAGEM == XFILIAL("DTC") + CSOT + COBRA + CVIAGEM1 
	FOR NX := 1 TO DTC->(FCOUNT())		// ARMAZENO OS DADOS PARA DUPLICAR O REGISTRO
		AADD(ADTC, DTC->(FIELDGET(NX)))
	NEXT NX  
	
	AAREADTC := DTC->(GETAREA())																		
	RECLOCK("DTC",.T.)
	FOR NX := 1 TO DTC->(FCOUNT())
		DTC->(FIELDPUT(NX, ADTC[NX]))
	NEXT NX
	DTC->DTC_DOC 	:= ""
	DTC->DTC_SERIE	:= ""
	DTC->DTC_VIAGEM := CVIAGEM
	DTC->(MSUNLOCK()) 
	RESTAREA(AAREADTC)
		
	DTC->(DBSKIP())
ENDDO
	
RESTAREA(AAREA)

RETURN



// ======================================================================= \\
STATIC FUNCTION CRIACOMBOBOX()
// ======================================================================= \\
// CRIAR PERGUNTA COM O TIPO DE COMPLEMENTO(VALOR OU ICMS)

LOCAL ACOMBO  := {} 
LOCAL CCOMBO  := ""
LOCAL NRESULT := SPACE(01)

DBSELECTAREA("SX3")
DBSETORDER(2)
IF DBSEEK("FQ5_TPCTRC")
	CCOMBO := X3CBOX()	
ENDIF 

ACOMBO := STRTOKARR(CCOMBO,";")
    
DEFINE MSDIALOG ODLGUSER TITLE STR0004 FROM 000,000 TO 150,300 PIXEL OF OMAINWND //"COMPLEMENTAR"
	@ 025,020 SAY      STR0059                        PIXEL OF ODLGUSER  //"SELECIONE A OPÇÃO:"
	@ 035,020 COMBOBOX OCOMBO1 VAR NRESULT ITEMS ACOMBO SIZE 80,10 PIXEL OF ODLGUSER 
	@ 035,105 BUTTON   STR0060                      SIZE 35,14 PIXEL OF ODLGUSER ACTION (ODLGUSER:END()) //"CONFIRMAR"
ACTIVATE MSDIALOG ODLGUSER CENTERED
	 
RETURN(NRESULT)
