/*/{PROTHEUS.DOC} LOCA071.PRW  
ITUP BUSINESS - TOTVS RENTAL
VALIDAÇÃO DO NUMERO DO PIS NO CADASTRO DO FORNECEDOR (SA2)
E MOTORISTA (DA4)
@TYPE FUNCTION
@AUTHOR FRANK ZWARG FUGA
@SINCE 03/12/2020
@VERSION P12
@HISTORY 03/12/2020, FRANK ZWARG FUGA, FONTE PRODUTIZADO.
/*/

#INCLUDE "RWMAKE.CH"
#INCLUDE "PROTHEUS.CH"
#INCLUDE "TOPCONN.CH"

FUNCTION LOCA071()
return .T. // removido na 94
/*
PRIVATE _CCAMPO := READVAR()
PRIVATE _CPIS   := &(_CCAMPO)
PRIVATE _CMSG	:= ""
PRIVATE _CQUERY := IIF(_CCAMPO == "M->DA4_PIS" , "SELECT DA4_FILIAL,DA4_COD COD,DA4_NOME NOME,DA4_PIS PIS FROM "+RETSQLNAME("DA4")+" WHERE DA4_FILIAL = "+XFILIAL("DA4") + " AND DA4_PIS = '"+ALLTRIM(_CPIS)+"' AND D_E_L_E_T_ = ''" , "SELECT A2_COD COD,A2_NOME NOME,A2_PIS PIS FROM "+RETSQLNAME("SA2")+" WHERE A2_PIS = '"+ALLTRIM(_CPIS)+"' AND D_E_L_E_T_ = ''") 
PRIVATE _AAREA 	:= GETAREA() 
PRIVATE LRET    := NIL

TCQUERY _CQUERY NEW ALIAS QRY

DBSELECTAREA("QRY")
DBGOTOP()

IF !EMPTY(QRY->PIS)
	LRET := .F.
ELSE
	LRET := .T.
ENDIF

IF !LRET
	_CMSG := "O NUMERO DE PIS: "+_CPIS+" ESTÁ CADASTRADO PARA O(S) FORNECEDORE(S) ABAIXO:"+CHR(10)+CHR(15) 
	WHILE !EOF() 
		_CMSG += "CODIGO: "+ALLTRIM(QRY->COD)+" NOME: "+ALLTRIM(QRY->NOME)+" PIS:"+ALLTRIM(QRY->PIS)+"."+CHR(10)+CHR(15) 
		DBSKIP() 
	ENDDO 
	MSGALERT(_CMSG , "GPO - VLDPIS.PRW")  
ENDIF

QRY->(DBCLOSEAREA()) 

RESTAREA(_AAREA)

RETURN LRET
*/
