#INCLUDE "loca060.ch" 
/*/{PROTHEUS.DOC} LOCA060.PRW
ITUP BUSINESS - TOTVS RENTAL
CADASTRO DE CONCORRENTES - FATURAMENTO
@TYPE FUNCTION
@AUTHOR FRANK ZWARG FUGA
@SINCE 03/12/2020
@VERSION P12
@HISTORY 03/12/2020, FRANK ZWARG FUGA, FONTE PRODUTIZADO.
/*/

#INCLUDE "PROTHEUS.CH"   

FUNCTION LOCA060()
AXCADASTRO("ZAH",STR0001)  //"CONCORRENTES"

RETURN
