#INCLUDE "loca026.ch" 
/*/{PROTHEUS.DOC} LOCA026.PRW
ITUP BUSINESS - TOTVS RENTAL
PROTOCOLO DE ENTREGA DO ROMANEIO.
@TYPE FUNCTION
@AUTHOR FRANK ZWARG FUGA
@SINCE 03/12/2020
@VERSION P12
@HISTORY 03/12/2020, FRANK ZWARG FUGA, FONTE PRODUTIZADO.
/*/

#INCLUDE "TOTVS.CH"

FUNCTION LOCA026()
LOCAL   AAREASZ0	:= FQ2->(GETAREA())
LOCAL   AAREASZ1	:= FQ3->(GETAREA())

PRIVATE ODLG
PRIVATE LOK			:= .F.
PRIVATE DDTINI		:= FQ2->FQ2_DTFISC
PRIVATE CTITULO		:= STR0001 //"DATA DE ENTREGA FISCAL"

DEFINE MSDIALOG ODLG TITLE CTITULO FROM 1,0 TO 9.5,26.5 OF OMAINWND
	@   5.0,07 TO 55.0,100  LABEL STR0002 OF ODLG PIXEL //"DATA DA ENTREGA:"
	@  20.0,30 MSGET ODTINI VAR DDTINI OF ODLG PIXEL WHEN .T. SIZE 45 ,9
	@  40.0,30 BUTTON OOK PROMPT "OK" SIZE 40,12 OF ODLG PIXEL ACTION IIF( VALDT(), ( LOK := .T., ODLG:END() ), NIL )
ACTIVATE MSDIALOG ODLG CENTERED

IF LOK
	//BEGIN TRANSACTION
		IF RECLOCK("FQ2",.F.)
			FQ2->FQ2_DTFISC	:= DDTINI
			FQ2->(MSUNLOCK())
	
			FQ3->( DBSETORDER(1) )
			FQ3->( DBSEEK( FQ2->FQ2_FILIAL + FQ2->FQ2_NUM, .T. ) )
			WHILE ! FQ3->( EOF() ) .AND. FQ2->FQ2_FILIAL==FQ3->FQ3_FILIAL .AND. FQ2->FQ2_NUM==FQ3->FQ3_NUM
				IF RECLOCK("FQ3",.F.)
					FQ3->FQ3_DTFISC	:= dtoc(DDTINI)
					MSUNLOCK()
				ELSE
					MSGALERT(STR0003 , STR0004)  //"PROTOCOLO FISCAL: NÃO FOI POSSÍVEL ATUALIZAR O REGISTRO"###"GPO - LOC048D.PRW"
	
					//DISARMTRANSACTION()
	
					FQ3->( RESTAREA(AAREASZ1) )
					RESTAREA(AAREASZ0)
	
					RETURN NIL
				ENDIF
				FQ3->(DBSKIP())
			ENDDO 
			MSGINFO(STR0005 , STR0004)  //"DATA DE PROTOCOLO FISCAL ATUALIZADA COM SUCESSO!"###"GPO - LOC048D.PRW"
		ELSE
			MSGALERT(STR0003 , STR0004)  //"PROTOCOLO FISCAL: NÃO FOI POSSÍVEL ATUALIZAR O REGISTRO"###"GPO - LOC048D.PRW"
		ENDIF
	//END TRANSACTION
ENDIF

FQ3->( RESTAREA(AAREASZ1) )
RESTAREA(AAREASZ0)

RETURN NIL



// ======================================================================= \\
STATIC FUNCTION VALDT()
// ======================================================================= \\


IF EMPTY( DDTINI ) .AND. AVISO(CTITULO, STR0006, {STR0007,STR0008}) != 1 //"DATA EM BRANCO, CONFIRMA A GRAVAÇÃO?"###"SIM"###"NÃO"
	RETURN .F.
ENDIF

RETURN .T.
