/*/{PROTHEUS.DOC} LOCA066.PRW  
ITUP BUSINESS - TOTVS RENTAL
WS para controle da licença, mantido para compatibilidade com a versão antiga
@TYPE FUNCTION
@AUTHOR FRANK ZWARG FUGA
@SINCE 03/12/2020
@VERSION P12
@HISTORY 03/12/2020, FRANK ZWARG FUGA, FONTE PRODUTIZADO.
/*/
#INCLUDE "PROTHEUS.CH"
#INCLUDE "TOPCONN.CH"
#INCLUDE "APWEBSRV.CH"
#INCLUDE "TBICONN.CH"
#INCLUDE "APWEBEX.CH"
/* ===============================================================================
WSDL LOCATION    HTTP://192.168.0.14:2728/WS_GERA_LIC.APW?WSDL
GERADO EM        05/23/19 21:48:02
OBSERVAÇÕES      CÓDIGO-FONTE GERADO POR ADVPL WSDL CLIENT 1.120703
                 ALTERAÇÕES NESTE ARQUIVO PODEM CAUSAR FUNCIONAMENTO INCORRETO
                 E SERÃO PERDIDAS CASO O CÓDIGO-FONTE SEJA GERADO NOVAMENTE.
=============================================================================== */
FUNCTION LOCA066()
RETURN LOCA066()

FUNCTION _RGLQTKK ; RETURN  // "DUMMY" FUNCTION - INTERNAL USE 

/* -------------------------------------------------------------------------------
WSDL SERVICE WSWS_GERA_LIC
------------------------------------------------------------------------------- */
WSCLIENT WSWS_GERA_LIC
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD RESET
	WSMETHOD CLONE
	WSMETHOD PESQUISAR

	WSDATA   _URL               AS STRING
	WSDATA   _HEADOUT           AS ARRAY OF STRING
	WSDATA   _COOKIES           AS ARRAY OF STRING
	WSDATA   CCNUMCNPJ          AS STRING
	WSDATA   CQTDFONTE          AS STRING
	WSDATA   CIPSERVCL          AS STRING
	WSDATA   OWSPESQUISARRESULT AS WS_GERA_LIC_RETORC
ENDWSCLIENT


WSMETHOD NEW   WSCLIENT WSWS_GERA_LIC
::INIT()
IF !FINDFUNCTION("XMLCHILDEX")
	USEREXCEPTION("O CÓDIGO-FONTE CLIENT ATUAL REQUER OS EXECUTÁVEIS DO PROTHEUS BUILD [7.00.131227A-20180425 NG] OU SUPERIOR. ATUALIZE O PROTHEUS OU GERE O CÓDIGO-FONTE NOVAMENTE UTILIZANDO O BUILD ATUAL.")
ENDIF
RETURN SELF


WSMETHOD INIT  WSCLIENT WSWS_GERA_LIC
	::OWSPESQUISARRESULT := WS_GERA_LIC_RETORC():NEW()
RETURN


WSMETHOD RESET WSCLIENT WSWS_GERA_LIC
	::CCNUMCNPJ          := NIL 
	::CQTDFONTE          := NIL 
	::CIPSERVCL          := NIL 
	::OWSPESQUISARRESULT := NIL 
	::INIT()
RETURN


WSMETHOD CLONE WSCLIENT WSWS_GERA_LIC
	LOCAL OCLONE := WSWS_GERA_LIC():NEW()
	OCLONE:_URL               := ::_URL 
	OCLONE:CCNUMCNPJ          := ::CCNUMCNPJ
	OCLONE:CQTDFONTE          := ::CQTDFONTE
	OCLONE:CIPSERVCL          := ::CIPSERVCL
	OCLONE:OWSPESQUISARRESULT := IIF( ::OWSPESQUISARRESULT = NIL , NIL , ::OWSPESQUISARRESULT:CLONE() ) 
RETURN OCLONE


// WSDL METHOD PESQUISAR OF SERVICE WSWS_GERA_LIC
WSMETHOD PESQUISAR WSSEND CCNUMCNPJ , CQTDFONTE , CIPSERVCL WSRECEIVE OWSPESQUISARRESULT WSCLIENT WSWS_GERA_LIC
	LOCAL CSOAP  := "" , OXMLRET
	LOCAL CURLWS := SUPERGETMV("MV_LOCX156",,"192.168.0.14:2728") 		// "192.168.0.14:2728" 

	BEGIN WSMETHOD
		CSOAP += '<PESQUISAR XMLNS="HTTP://'+ALLTRIM(CURLWS)+'/">'
		CSOAP += WSSOAPVALUE("CNUMCNPJ" , ::CCNUMCNPJ , CCNUMCNPJ , "STRING" , .T. , .F. , 0 , NIL , .F. , .F.) 
		CSOAP += WSSOAPVALUE("QTDFONTE" , ::CQTDFONTE , CQTDFONTE , "STRING" , .T. , .F. , 0 , NIL , .F. , .F.) 
		CSOAP += WSSOAPVALUE("IPSERVCL" , ::CIPSERVCL , CIPSERVCL , "STRING" , .T. , .F. , 0 , NIL , .F. , .F.) 
		CSOAP += "</PESQUISAR>"
		
		OXMLRET := SVCSOAPCALL(	SELF , CSOAP , ; 
								"HTTP://"+ALLTRIM(CURLWS)+"/PESQUISAR" , ; 
								"DOCUMENT" , "HTTP://"+ALLTRIM(CURLWS)+"/" , , "1.031217" , ; 
								"HTTP://"+ALLTRIM(CURLWS)+"/WS_GERA_LIC.APW" ) 
		::INIT() 
		::OWSPESQUISARRESULT:SOAPRECV( WSADVVALUE( OXMLRET , "_PESQUISARRESPONSE:_PESQUISARRESULT" , "RETORC" , NIL , NIL , NIL , NIL , NIL , NIL ) ) 
	END WSMETHOD

	OXMLRET := NIL 
RETURN .T.


// WSDL DATA STRUCTURE RETORC
WSSTRUCT WS_GERA_LIC_RETORC
	WSDATA   CCRAZSOCI          AS STRING OPTIONAL
	WSMETHOD NEW
	WSMETHOD INIT
	WSMETHOD CLONE
	WSMETHOD SOAPRECV
ENDWSSTRUCT


WSMETHOD NEW   WSCLIENT WS_GERA_LIC_RETORC
	::INIT()
RETURN SELF


WSMETHOD INIT  WSCLIENT WS_GERA_LIC_RETORC
RETURN


WSMETHOD CLONE WSCLIENT WS_GERA_LIC_RETORC
	LOCAL OCLONE := WS_GERA_LIC_RETORC():NEW()
	OCLONE:CCRAZSOCI     := ::CCRAZSOCI
RETURN OCLONE


WSMETHOD SOAPRECV WSSEND ORESPONSE WSCLIENT WS_GERA_LIC_RETORC
	::INIT()
	IF ORESPONSE = NIL 
		RETURN 
	ENDIF 
	::CCRAZSOCI          := WSADVVALUE( ORESPONSE , "_CRAZSOCI" , "STRING" , NIL , NIL , NIL , "S" , NIL , NIL ) 
RETURN



// ======================================================================= \\
FUNCTION LOCA06601(CARQ_WS) 
// ======================================================================= \\
/*
LOCAL OWS       := NIL 
LOCAL NY        := 0 
LOCAL CCNPJ     := SM0->M0_CGC 
LOCAL CRETWS_L  := ""

LOCAL AATUAREA  := GETAREA() 
LOCAL ASM0AREA  := SM0->(GETAREA()) 
LOCAL AEMPSCAD  := {} 							// --> EMPRESAS CONTIDAS NO SIGAMAT.EMP 
LOCAL AEMPSLIB  := {} 
LOCAL CTXTPRIN  := "" 
LOCAL CLIB_SN_  := "" 
LOCAL CLIB_CGC  := "" 

LOCAL CDIRETOR  := "\SYSTEM\" 
LOCAL CARQUIVO  := "" 
LOCAL NARQ 
LOCAL CQUERY    := "" 
LOCAL NQTD_FNT  := 0 
LOCAL CIPSRVCLI := GETSERVERIP() 

DEFAULT CARQ_WS := "SIGAGPF.EMP" 

CARQUIVO := CARQ_WS 

DBSELECTAREA("SM0") 
SM0->(DBGOTOP()) 
WHILE !SM0->(EOF()) 
	// --> SÓ ADICIONA NO AEMPSCAD SE A EMPRESA FOR DIFERENTE.
	IF ASCAN( AEMPSCAD , {|X| X[2] == SM0->M0_CODIGO}) == 0  
		AADD( AEMPSCAD , {SM0->M0_CODIGO , SM0->M0_CGC} ) 
	ENDIF 
	SM0->(DBSKIP()) 
ENDDO 
RESTAREA(ASM0AREA) 
RESTAREA(AATUAREA) 

// --- LEVANTAR A QUANTIDADE DE FONTES NA BASE INSTALADA DO CLIENTE ---
CQUERY := " SELECT COUNT(*) AS CONT_FNT " 															// U.A.3_VERSAO 
CQUERY += " FROM "+RETSQLNAME(_CTBCF_)+" (NOLOCK) " 												// "U.A.3"
CQUERY += " WHERE  D_E_L_E_T_ = '' " 																// U.A.3_CODFON
CQUERY := CHANGEQUERY(CQUERY) 
TCQUERY CQUERY NEW ALIAS "QTF" 

IF QTF->(!EOF()) 
	NQTD_FNT := QTF->CONT_FNT  
ENDIF 
QTF->(DBCLOSEAREA()) 
// --- LEVANTAR A QUANTIDADE DE FONTES NA BASE INSTALADA DO CLIENTE ---

OWS := WSWS_GERA_LIC():NEW() 

FOR NY := 1 TO LEN( AEMPSCAD ) 
	CCNPJ := AEMPSCAD[NY][2] 
	IF OWS:PESQUISAR( CCNPJ , ALLTRIM(STR(NQTD_FNT)) , CIPSRVCLI ) 
		CRETWS_L := OWS:OWSPESQUISARRESULT:CCRAZSOCI 
		IF SUBSTR(CRETWS_L,1,5) <> "ERRO:" 
			AADD( AEMPSLIB , { SUBSTR(CRETWS_L,09,14)  , SUBSTR(CRETWS_L,36,01)  , SUBSTR(CRETWS_L,51,08)  , SUBSTR(CRETWS_L,73,08)  , SUBSTR(CRETWS_L,92,40)  } ) 
		ELSE
			MSGALERT("OCORREU UM ERRO DE AUTENTICAÇÃO NO LICENCIAMENTO! " + CHR(13) + CHR(10) + CRETWS_L) 
		ENDIF                                    			
	ELSE 
		MSGALERT("OCORREU UM ERRO DE CONEXÃO AO WEBSERVICE: " + GETWSCERROR()) 
	ENDIF 
NEXT NY 

IF LEN(AEMPSLIB) > 0 
	CARQUIVO := CDIRETOR  +  CARQUIVO 			//  "\SYSTEM\"  +  "SIGAGPF.EMP" OU "SIGAGPO.EMP" 
	NARQ     := FCREATE(CARQUIVO , 0) 
	IF FERROR() <> 0  .OR.  NARQ < 0 
		MSGALERT("ATENÇÃO: PROBLEMAS NA CRIAÇÃO DO ARQUIVO ["+CARQUIVO+"] !!") 
		FCLOSE(NARQ)
		RETURN NIL
	ENDIF
	IF     CARQ_WS = "SIGAGPF.EMP" 				// --> GPF 
		CTXTPRIN := "$…3B$9°€#ÄÕSÕBKDË!Ë" 	//  $…3B$9°€#ÄÕSÕBKDË!Ë <=> #LICENCIAMENTO GPF# (EMBARALHADO COM "$"[01] "#"[11] "!"[20])        …3B$9°€ÄÕSÕBKDËË <=> #LICENCIAMENTO GPF# (ORIGINAL) 
	ELSEIF CARQ_WS = "SIGAGPO.EMP" 				// --> GPO 
		CTXTPRIN := "$…3B$9°€#ÄÕSÕBKDÂ!Ë" 	//  $…3B$9°€#ÄÕSÕBKDÂ!Ë <=> #LICENCIAMENTO GPO# (EMBARALHADO COM "$"[01] "#"[11] "!"[20])        …3B$9°€ÄÕSÕBKDÂË <=> #LICENCIAMENTO GPO# (ORIGINAL) 
	ENDIF 
	FWRITE( NARQ , CTXTPRIN + CRLF ) 
ENDIF 
NY := 0 
FOR NY := 1 TO LEN(AEMPSLIB) 
	CLIB_CGC := RC4CRYPT( AEMPSLIB[NY][1]+"F" , "0" , .T.) 
	CLIB_CGC := SUBSTR(CLIB_CGC,21,10)+SUBSTR(CLIB_CGC,01,10)+SUBSTR(CLIB_CGC,11,10)
	IF AEMPSLIB[NY][2] = "1" 					// NÃO ESTÁ LIBERADO	 	#SIM# <=> šLB    #NÃO# <=> ‡NB 
		CLIB_SN_ := "‡$NB"
	ELSE										// SIM ESTÁ LIBERADO 		#SIM# <=> šLB    #NÃO# <=> ‡NB 
		CLIB_SN_ := "š$LB"
	ENDIF 
	CTXTPRIN     := "0B6D48FA178A1471" 			// 0B6D48FA178A1471 <=> #CNPJ: # (EMBARALHADO)     178A14710B6D48FA <=> #CNPJ: # (ORIGINAL) 
	CTXTPRIN     += CLIB_CGC 
	CTXTPRIN     += CLIB_SN_
	CTXTPRIN     += "006D48FA178D1B75" 			// 006D48FA178D1B75 <=> #DATA#   (EMBARALHADO)     178D1B75006D48FA <=> #DATA#   (ORIGINAL) 
	IF CARQUIVO = "\SYSTEM\SIGAGPF.EMP" 		// --> GPF 
		CTXTPRIN += RC4CRYPT("#"+AEMPSLIB[NY][4]+"#" , "1234" , .F.) 
	ENDIF 
	IF CARQUIVO = "\SYSTEM\SIGAGPO.EMP" 		// --> GPO 
		CTXTPRIN += RC4CRYPT("#"+AEMPSLIB[NY][3]+"#" , "1234" , .F.) 
	ENDIF 
	FWRITE( NARQ , CTXTPRIN + CRLF ) 
NEXT NY 
IF LEN(AEMPSLIB) > 0 
	CTXTPRIN := RC4CRYPT("#FINAL DE ARQUIVO#"+DTOS(DATE())+"#" , "0" , .F.)					// «9ÏÎ‚7ÔCQß£& 3ÌÈ%ÞDW4‡»ß  <=>  #FINAL DE ARQUIVO#20190520#
	FWRITE( NARQ , CTXTPRIN + CRLF ) 
	FCLOSE(NARQ) 
ENDIF 
*/
RETURN 



/*
         1         2         3         4         5         6         7         8         9         0         1         2         3 
123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012
A1_CGC:[00299104000149] A1_MSBLQL:[2] A1_ZDATAGO:[20220731] A1_ZDATAGF:[20191231] A1_NOME:[CR ALMEIDA S/A ENGENHARIA E CONSTRUCOES ]
*/

/*
----------------                              ------                ----------
#CNPJ: # (FIXO)                               #SIM#                 #20190615#
----------------                              ------                ----------
0B6D48FA178A1471D245C55F18B84F94B9FA4AE41304CFš$LB006D48FA178D1B75&{AžÊÜ1<:8
                ------------------------------      ----------------
                N U M E R O     D O    C N P J      #DATA# (FIXO)
                ------------------------------      ----------------
SUBSTR( "0B6D48FA178A1471" + SUBSTR(RC4CRYPT(SM0->M0_CGC+"F","123456789",.F.),1,15) + SPACE(20)  , 1 , 30) + "š$LB"
*/

/*
$…3B$9°€#ÄÕSÕBKDË!Ë
0B6D48FA178A1471ÙHXFXÍÑ™ µ4               š$LB006D48FA178D1B75&{AžÊÝ5>>8
0B6D48FA178A1471D245C55F18B84F94B9FA4AE41304CFš$LB006D48FA178D1B75&{AžÊÜ1<:8
0B6D48FA178A1471D245C15F18B94B93B7F242EC1004CFš$LB006D48FA178D1B75&{AžÊÜ1<:8
0B6D48FA178A1471D245C25618BA4B97B8FB42E21604CFš$LB006D48FA178D1B75&{AžÊÜ1<:8
0B6D48FA178A1471D245C95618BA4B97B4F743E31304CFš$LB006D48FA178D1B75&{AžÊÜ1<:8
«9ÏÎ‚7ÔCQß£& 3ÌÈ%ÞDW4‡»ß
*/

/*
--> CNPJ 
CPNJ               CRIPTO ORIGINAL                   CRIPTO EMBARALHADO 
00299104000149F    B84F94B9FA4AE41304CFD245C55F18    D245C55F18B84F94B9FA4AE41304CF
14571987000109F    B94B93B7F242EC1004CFD245C15F18    D245C15F18B94B93B7F242EC1004CF
24188961000130F    BA4B97B8FB42E21604CFD245C25618    D245C25618BA4B97B8FB42E21604CF
24144874000180F    BA4B97B4F743E31304CFD245C95618    D245C95618BA4B97B4F743E31304CF
                   AAAAAAAAAABBBBBBBBBBCCCCCCCCCC    CCCCCCCCCCAAAAAAAAAABBBBBBBBBB
*/
