#INCLUDE "loca046.ch" 
/*/{PROTHEUS.DOC} LOCA046.PRW
ITUP BUSINESS - TOTVS RENTAL
TELA GERENCIAMENTO MANUTENÇÃO DE C.T.R.C. - OPERACIONAL
@TYPE FUNCTION
@AUTHOR FRANK ZWARG FUGA
@SINCE 03/12/2020
@VERSION P12
@HISTORY 03/12/2020, FRANK ZWARG FUGA, FONTE PRODUTIZADO.
/*/

#INCLUDE "PROTHEUS.CH"
#INCLUDE "TOPCONN.CH"
#INCLUDE "RWMAKE.CH"
#INCLUDE "MSMGADD.CH"

#COMMAND @ <NROW>, <NCOL> BMPBUTTON TYPE <NTYPE> ACTION <CACTION> [OBJECT <OBMT>] [<LENABLE:ENABLE>] ;
=> [ <OBMT> := ] SBUTTON():NEW(<NROW>, <NCOL>, <NTYPE>, [{|| <CACTION>}],,<LENABLE>)

FUNCTION LOCA046()
LOCAL AROTCTRC := { { STR0001	, "EVAL(BMANUTRC)"	, 0 , 4},; //"MANUTENCAO"
					{ STR0002		, "EVAL(BGERAC)"	, 0 , 4},; //"GERA"
					{ STR0003		, "EVAL(BIMPRIMEC)"	, 0 , 4},; //"IMPRIME"
					{ STR0004		, "EVAL(BESTORNOC)"	, 0 , 4},; //"ESTORNO"
					{ STR0005, "EVAL(BCOMPLEMC)"	, 0 , 4}} //"COMPLEMENTAR"

LOCAL ALEGENDA := { { STR0006     , "EVAL(BLEGENDA)"  , 0 , 6}} //"LEGENDA"

LOCAL ACORES   :=  {}

AADD(ACORES,{ "!EMPTY(FQ5_NUMCTR) .AND. FQ5_NUMCTR <> '-'" , 'BR_VERMELHO' }) 	// CTRC GERADO
AADD(ACORES,{ " EMPTY(FQ5_NUMCTR) .OR.  FQ5_NUMCTR = '-' " , 'BR_VERDE'	   }) 	// NADA GERADO

PRIVATE LCTRCTELA  := .T.
PRIVATE CPRJOBRA   := ""
PRIVATE BMANUTRC   := {|| LCTRCTELA:=.T. , LOCF004A("A")} 		// MANUTENCAO CTRC E CTRB
PRIVATE BGERAC     := {|| LOCA034()}   						// GERAR CTRC
PRIVATE BIMPRIMEC  := {|| LOCR008()}   						// IMPRIMIR CTRC
PRIVATE BESTORNOC  := {|| LOCA035()}   						// ESTORNAR CTRC
PRIVATE BCOMPLEMC  := {|| DTQCOMP()}							// COMPLEMENTO CTRC
PRIVATE BLEGENDA   := {|| LOCFLEG()}
PRIVATE BFILTRABRW := {|| NIL}
PRIVATE AINDICE    := {}
PRIVATE CCONDFIL   := ""

PRIVATE AROTINA   := {{STR0007   , "AXPESQUI" , 0,1} ,; //"PESQUISAR"
					  {STR0008  , "AXVISUAL" , 0,2} ,; //"VISUALIZAR"
					  {STR0009     , AROTCTRC   , 0,4},; //"C.T.R.C"
					  {"LEGENDA(F5)" , ALEGENDA   , 0,6}}

PRIVATE CDELFUNC  := ".T." 										// VALIDACAO PARA A EXCLUSAO. PODE-SE UTILIZAR EXECBLOCK
PRIVATE CSTRING   := "FQ5"
PRIVATE CCADASTRO := STR0010 //"MANUTENÇÃO C.T.R.C"

PUBLIC LCOPIA 	  := .F.

//IF !LOCA061() 												// --> VALIDAÇÃO DO LICENCIAMENTO (WS) DO GPO 
//	RETURN 
//ENDIF 

CCONDFIL := "FQ5_FILIAL == '"+XFILIAL("FQ5")+"' .AND. "
CCONDFIL += "(FQ5_TPAS == 'T' .OR. FQ5_TPAS == 'M') "
CCONDFIL += ".AND. FQ5_STATUS <> '9' " 							// NÃO EXIBIR AS CANCELADAS
CCONDFIL += ".AND. !(EMPTY(FQ5->FQ5_DATFEC) .AND. EMPTY(FQ5->FQ5_DATENC) .AND. FQ5->FQ5_STATUS == '1') "
//CCONDFIL+=".AND. EMPTY(FQ5->FQ5_JUNTO)  "
//CCONDFIL+=".AND. LEFT(FQ5_AS,2) != '02' " 					// NÃO EXIBIR AS DE LOCAÇÃO - COMENTADO POR, POIS A CUNZOLO IRÁ EMITIR CT-E PARA ESTE TIPO DE AS.

BFILTRABRW := {|| FILBROWSE("FQ5",@AINDICE,@CCONDFIL) }
LJMSGRUN(STR0011,, {|| EVAL(BFILTRABRW) }) //"POR FAVOR AGUARDE, FILTRANDO INFORMAÇÕES..."

DBSELECTAREA("FQ5")
DBSETORDER(1)
DBSELECTAREA(CSTRING)

SET KEY VK_F5 TO LOCFLEG() 

MBROWSE(6, 1, 22, 75,CSTRING,,,,,,ACORES)

SET KEY VK_F5 TO

DBSELECTAREA("FQ5")
DBCLEARFILTER()

RETURN .T.



// ======================================================================= \\
STATIC FUNCTION LOCF004A(POPC)
// ======================================================================= \\

LOCAL AAREA       := GETAREA()
LOCAL CTITJAN     := STR0012 //"MANUTENCAO C.T.R.C"
LOCAL NSTYLE 
LOCAL NPOS 
LOCAL ABUTTONS
LOCAL CSTATSPROG  := "4" 
LOCAL AOPCCMB     := MONTACOMBO("FQ5_TPCTRC") 

PRIVATE LGERADO   := .T.
PRIVATE LINCLUI   := IIF(POPC == "I" , .T. , .F.)
PRIVATE LALTERA   := IIF(POPC == "A" , .T. , .F.)
PRIVATE LINCCTRB  := IIF(POPC == "B" , .T. , .F.)

PRIVATE NOPC      := POPC
PRIVATE AHEADER   := {}
PRIVATE ACOLS     := {}
PRIVATE ATITLES   := {}
PRIVATE APAGES    := {}

PRIVATE ACALC	  := {}
PRIVATE AOBJECTS  := {}
PRIVATE AINFO     := {}
PRIVATE APOSGET   := {}
PRIVATE APOSOBJ   := {}
PRIVATE CORIGEM   := SPACE(40)
PRIVATE CDESTINO  := ""
PRIVATE OARIAL12N1:= TFONT():NEW("ARIAL",12,16,,.T.,,,,.T.,.F.)
PRIVATE OARIAL12N2:= TFONT():NEW("ARIAL",12,16,,.T.,,,,.T.,.F.)

PRIVATE NFOLDERVEI:=0,NFOLDERMOT:=0,NFOLDERNOT:=0,NFOLDERFRE:=0
PRIVATE NFOLDERPER:=0,NFOLDEREQU:=0,NFOLDERCAR:=0
PRIVATE ODLG , ODLGVEI , ODLGMOT , ODLGNOT , ODLGFRE , ODLGPER , ODLGEQU , ODLGCAR
PRIVATE OFRETEP,OFRETEV ,OBASEICM ,OALIQICM , OVALICM  ,OBASEADV ,OALIQADV , OVALADV  , OFRETET                                                     
PRIVATE OCLI,OLOJ,ONOM,OORI,OORIUF,ODES,ODESUF,OVLRINF,OCONDPAG,ODCON,OCONTRA,OTCONTRA,OSTATUS,OTES,OTES2,OPLACCAV,OPLACCAR,ONOMMOT,OCFOP,OCFOP2,ODEVFRE,OCCUSTO,OUFCOLE,OUFENTR,OCARREG,ODESCAR,OOBSCONTR,OOBSSEG,OPAGO,ODESCPAG
PRIVATE CCLI,CLOJ,CNOM,CORI,CORIUF,CDES,CDESUF,NVLRINF,CCONDPAG,CDCON,CCONTRA,CTCONTRA,CSTATUS,CTES,CTES2,CPLACCAV,CPLACCAR,CNOMMOT,CCFOP,CCFOP2,CDEVFRE,CCCUSTO,CUFCOLE,CUFENTR,CCARREG,CDESCAR,COBSCONTR,COBSSEG,CPAGO,CDESCPAG
PRIVATE OCODORI,OCODFIM,CCODORI,CCODFIM,OCODDES,OTPTRA,OCODIRI,CCODIRI,OAFRMM,NAFRMM,CNAVEG,ONAVEG,CDIRNAV,ODIRNAV
PRIVATE NFRETEP:=NFRETEV:=NBASEICM:=NALIQICM:=NVALICM:=NBASEADV:=NALIQADV:=NVALADV:=NFRETET:=NVLRINF:=NALIQADV:=NBASEADV:=NVALADV:=NFRETEP:=NALIQICM:= 0
PRIVATE NBLIN1:= NBCOL1:= NBLIN2:= NBCOL2:= 0

PRIVATE CPROJETO := COBRA := CVIAGEM := ""
PRIVATE OFILORI,CFILORI:="01"

PRIVATE OPROJETO , CPROJETO := FQ5->FQ5_SOT
PRIVATE OOBRA    , COBRA    := FQ5->FQ5_OBRA         
PRIVATE OCTRC    , CCTRC    := FQ5->FQ5_NUMCTR         
PRIVATE OTPCTRC  , CTPCTRC  := IIF(EMPTY(FQ5->FQ5_TPCTRC),"NORMAL","COMPL."+AOPCCMB[ASCAN(AOPCCMB, {|X| X[3]==FQ5->FQ5_TPCTRC}), 4])

PRIVATE OTIPO , OCHK , OTOMADOR
PRIVATE CCODCLI	 := CRIAVAR("ZA0_CLI")
PRIVATE CLOJA	 := CRIAVAR("ZA0_LOJA")
PRIVATE CNOAS    := CRIAVAR("FQ5_AS")
PRIVATE CCODREM  := CRIAVAR("DTC_CLIREM")
PRIVATE CCODDES  := CRIAVAR("DTC_CLIDES")
PRIVATE CCODCON  := CRIAVAR("DTC_CLICON")
PRIVATE CLOJREM  := CRIAVAR("DTC_LOJREM")
PRIVATE CLOJDES  := CRIAVAR("DTC_LOJDES")
PRIVATE CLOJCON  := CRIAVAR("DTC_LOJCON")
PRIVATE CTIPNFC  := CRIAVAR("DTC_TIPNFC")

PRIVATE CTIPO     := SPACE(1)
PRIVATE CTIPTRA   := SPACE(1)
PRIVATE ATIPO     := {'1=CIF','2=FOB'}
PRIVATE ATOMADOR  := {'1=REMETENTE','2=DEVEDOR','3=DESTINATÁRIO'}
PRIVATE ATPTRA    := {'1=RODOVIARIO','3=AQUAVIARIO'}
//PRIVATE ANAVEG  := {'0=INTERIOR','1=CABOTAGEM'}
//PRIVATE ADIRNAV := {'N=NORTE','L=LESTE','S=SUL','O=OESTE'}
PRIVATE CDESREM   := CRIAVAR("A1_NOME")
PRIVATE CDESDES   := CRIAVAR("A1_NOME")
PRIVATE CDESCON   := CRIAVAR("A1_NOME")
PRIVATE ODESCON , ODESDES , ODESREM 
PRIVATE CCONDPG   := SPACE(03)
PRIVATE CCIFFOB
PRIVATE CTOMADOR  := SPACE(1)
PRIVATE LVER      := .T.    
PRIVATE LDESTICM  := .T.  
PRIVATE CALIASTMP :=	GETNEXTALIAS() // INCLUIDO CONFORME ITEM DO PROJETO AVATAR (TRANSP04)

PRIVATE NVALESTAD:=NCARDES:=NVALESCOL:=NVALPEDAG:=NVALSCOM:=NVALCCOM:=NACUMUL:=NFRETEPAUX:=NDESCCOMISS:=NDESCCOMV:=NVALCONTAINER := 0 //NDESCOMV=VISUAL
PRIVATE OVALESTAD,OCARDES,OVALESCOL,OVALPEDAG,OVALSCOM,OVALCCOM,OFRETEPAUX,ODESCCOMV,OVALCONTAINER

NSTYLE   := GD_INSERT + GD_UPDATE + GD_DELETE
ABUTTONS := {} 

DBSELECTAREA("FP0")
DBSETORDER(1)
MSSEEK(XFILIAL("FP0") + CPROJETO )
                                  
DBSELECTAREA("AAM")
DBSETORDER(1)
MSSEEK(XFILIAL("AAM") + FQ5->FQ5_CONTRA )

CCODCLI	:= AAM->AAM_CODCLI
CLOJA   := AAM->AAM_LOJA
CNOM    := POSICIONE("SA1",1,XFILIAL("SA1")+CCODCLI+CLOJA ,"A1_NOME")

DBSELECTAREA("SA1")
DBSETORDER(1)
MSSEEK(XFILIAL("SA1") + FP0->FP0_CLI+FP0->FP0_LOJA )
CCODCLI := SA1->A1_COD
CLOJA   := SA1->A1_LOJA
CNOM    := POSICIONE("SA1",1,XFILIAL("SA1")+CCODCLI+CLOJA ,"A1_NOME")

DBSELECTAREA("ZA6")
DBSETORDER(1)
ZA6->(DBSEEK(XFILIAL("ZA6") + CPROJETO +COBRA))

OFONT1 := OARIAL12N1  //SAY
OFONT2 := OARIAL12N2  //GET

DBSELECTAREA("FQ5")
IF !EMPTY(FQ5->FQ5_NUMCTR) .AND. FQ5->FQ5_NUMCTR <> "-"
	MSGALERT(STR0013 + CHR(13) + ; //"CTRC  PARA ESTA VIAGEM JÁ SE ENCONTRA GERADO."
	         STR0014 , STR0015) //"O MESMO SERÁ ABERTO APENAS PARA SUA CONSULTA."###"GPO - LOCT004.PRW"
//	RETURN 
    LGERADO:= .T.
ELSE
    LGERADO:= .F.    
ENDIF

/*BEGINDOC
//ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
//³QUERY PARA ATENDER A NESSCIDADE DO ITEM TRANSP04 DO PROJETO AVATAR       ³
//ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
ENDDOC*/
BEGINSQL ALIAS CALIASTMP   
	%NOPARSER%
	
	SELECT FPM_FROTA, FPM_FROTA1 
	FROM %TABLE:ZLE% ZLE, %TABLE:DTQ% DTQ, %TABLE:DA4% DA4
	WHERE 	FPM_VIAGEM 			=	DTQ.FQ5_VIAGEM
			AND FPM_AS     		=	DTQ.FQ5_AS
			AND FQ5_OBRA   		=	ZLE.FPM_OBRA
			AND	DA4.DA4_COD		=	ZLE.FPM_CODMOT
			AND FPM_STATUS 		=	%EXP:CSTATSPROG%
			AND FPM_FILIAL 		=	%XFILIAL:ZA0%
			AND FPM_AS     		=	%EXP:FQ5->FQ5_AS%				
			AND ZLE.%NOTDEL%
			AND DTQ.%NOTDEL%
			AND DA4.%NOTDEL%
	ORDER BY 1,2			
ENDSQL

CCODORI := SPACE(06)
CORI    := SPACE(30)
CORIUF  := SPACE(02)
CCODFIM := SPACE(06)
CDES	:= SPACE(30)
CDESUF  := SPACE(02)
CCARREG := SPACE(30)
CUFCOLE := SPACE(02)
CDESCAR := SPACE(30)
CUFENTR := SPACE(02)
CCCUSTO	:= SPACE(20)
CCONDPAG:= SPACE(03)
CDCON	:= SPACE(30)
CTES    := SPACE(03)
CCFOP	:= SPACE(05)
CDEVFRE := SPACE(01)
CPAGO	:= SPACE(01)
COBSSEG	:= SPACE(100)
CTPTRA	:= SPACE(01)
CCODIRI := SPACE(10)
CNAVEG  := SPACE(1) 
CDESCPAG:=SPACE(15)
NALIQICM:= 0
CNOAS    :=SPACE(LEN(FQ5->FQ5_AS))
REGTOMEMORY("DTC")

IF LALTERA
	
	CPROJETO  := FQ5->FQ5_SOT
	COBRA     := FQ5->FQ5_OBRA
	CVIAGEM   := FQ5->FQ5_VIAGEM
	CFILORI	  := FQ5->FQ5_FILORI
	CNOAS     := FQ5->FQ5_AS
	LDESTICM  := FQ5->FQ5_DESICM
	
	NLOCBAR := AT("/",FQ5->FQ5_ORIGEM)
	CAUXORI := SUBSTR(FQ5->FQ5_ORIGEM,1,NLOCBAR-1)
	ATAMSX3 := TAMSX3("FQ5_ORIGEM")
	CORI	:= ALLTRIM(CAUXORI)+SPACE(ATAMSX3[1]-LEN(CAUXORI))
	CORIUF	:= SUBSTR(FQ5->FQ5_ORIGEM,LEN(TRIM(FQ5->FQ5_ORIGEM))-1,2)
	
	NLOCBAR := AT("/",FQ5->FQ5_DESTIN)
	CAUXDES := SUBSTR(FQ5->FQ5_DESTIN,1,NLOCBAR-1)
	ATAMSX3 := TAMSX3("FQ5_DESTIN")
	CDES	:= ALLTRIM(CAUXDES)+SPACE(ATAMSX3[1]-LEN(CAUXDES))
	CDESUF	:= PADR(SUBSTR(FQ5->FQ5_DESTIN,LEN(TRIM(FQ5->FQ5_DESTIN))-1,2),2)
	
	NFRETET	 := FQ5->FQ5_TOTFRE
	NFRETEP	 := FQ5->FQ5_VLRINF
	NVLINF 	 := FQ5->FQ5_VLRINF
  	NVALICM	 := FQ5->FQ5_VALICM
	NVALADV	 := FQ5->FQ5_VALADV
	NBASEICM := FQ5->FQ5_BASICM
	NBASEADV := FQ5->FQ5_BASADV
	NALIQICM := FQ5->FQ5_PERICM
	NALIQADV := FQ5->FQ5_PERADV
	CTES	 := FQ5->FQ5_TES
	CCFOP	 := FQ5->FQ5_CFOP
	CTES2	 := FQ5->FQ5_TES2
	CCFOP2	 := FQ5->FQ5_CFOP2
	CCONDPAG := FQ5->FQ5_CONDPG
	CDCON	 := FQ5->FQ5_DCOND
	CCCUSTO	 := FQ5->FQ5_CCC
	CPAGO	 := FQ5->FQ5_PAGO  
	COBSCONTR:= FQ5->FQ5_OBSCTR
	CCODORI  := FQ5->FQ5_CODORI
	CCODFIM  := FQ5->FQ5_CODDES
	CTPTRA	 := FQ5->FQ5_TIPTRA
	CCODIRI  := FQ5->FQ5_IRIN
	NAFRMM   := FQ5->FQ5_AFRMM
	CNAVEG	 := FQ5->FQ5_NAVEG
	CDIRNAV  := FQ5->FQ5_DIRNAV
 //	CPLACCAV := FQ5->FQ5_PLACAV
 //	CPLACCAR := FQ5->FQ5_PLACAR                                                    
 //	CNOMMOT	 := FQ5->FQ5_MOTORI
	NVALESTAD  := FQ5->FQ5_VRESTA
	NCARDES	   := FQ5->FQ5_CARDES
	NVALESCOL  := FQ5->FQ5_VRESCO
	NVALPEDAG  := FQ5->FQ5_VRPEDA
	NVALSCOM   := FQ5->FQ5_VRSCOM
	NVALCCOM   := FQ5->FQ5_VRCCOM
	NFRETEPAUX := FQ5->FQ5_XFRETE
	NDESCCOMV  := FQ5->FQ5_DESCOM	                                                                               
	NVALCONTAINER := FQ5->FQ5_VRCONT //VALOR CONTAINER

	IF LGERADO .OR. FQ5->FQ5_NUMCTR = '-'
		NFRETEP	:= FQ5->FQ5_TOTFRE
		NFRETET	:= FQ5->FQ5_VLRINF
	ENDIF                          
	IF NVLINF  == 0
		NVLINF  := FQ5->FQ5_TOTFRE
	ENDIF
	IF LEN(ALLTRIM(COBSCONTR)) == 0
       COBSCONTR := VEROBS(CTES)
    ENDIF   
	COBSSEG  := FQ5->FQ5_OBSERV
	CNOAS    := FQ5->FQ5_AS
	
	DBSELECTAREA("DTC")
	DBORDERNICKNAME("DTCIND10")
	IF MSSEEK(IIF(LEN(ALLTRIM(XFILIAL("DTC")))==2 .AND. LEN(XFILIAL("DTC"))==4,CFILANT,XFILIAL("DTC")) + FQ5->FQ5_SOT + FQ5->FQ5_OBRA + FQ5->FQ5_VIAGEM )
		
		CTIPNFC  := DTC->DTC_TIPNFC
		CCODREM  := DTC->DTC_CLIREM
		CLOJREM  := DTC->DTC_LOJREM
		CTIPO	 := DTC->DTC_TIPFRE
		CTOMADOR := IIF(DTC->(FIELDPOS("DTC_TOMADO"))>0, DTC->DTC_TOMADO, CTOMADOR)
		
		IF !EMPTY(CCODREM)
			CDESREM := POSICIONE("SA1",1,XFILIAL("SA1") + CCODREM + CLOJREM ,"A1_NOME")
		ENDIF
		
		CCODDES  := DTC->DTC_CLIDES
		CLOJDES  := DTC->DTC_LOJDES
		IF !EMPTY(CCODDES)
			CDESDES :=  POSICIONE("SA1",1,XFILIAL("SA1") + CCODDES + CLOJDES ,"A1_NOME")
		ENDIF
		
		CCODCON  := DTC->DTC_CLICON
		CLOJCON  := DTC->DTC_LOJCON
		IF !EMPTY(CCODCON)
			CDESCON :=  POSICIONE("SA1",1,XFILIAL("SA1") + CCODCON + CLOJCON,"A1_NOME" )
		ENDIF       
		IF LEN(CCONDPAG) == 0 
			IF LEN(ZA6->ZA6_CONDPAG) == 0   
				CCPROJETO:= ZA6->ZA6_PROJET
				DBSELECTAREA("ZA6")
				ZA6->(DBSKIP())
				IF SUBSTR(ZA6->ZA6_PROJET,1,11)<>CCPROJETO      
					ZA6->(DBSKIP(-1))
				ENDIF
			ENDIF  
			CCONDPAG := ZA6->ZA6_CONDPAG                               
			CDCON    := POSICIONE("SE4",1,XFILIAL("SE4"+ALLTRIM(CCONDPAG),"E4_DESCRI"))
			DBSELECTAREA("FQ5")
		ENDIF
	ENDIF
	DBSELECTAREA('DTR')
	DBSETORDER(7)
  	IF MSSEEK(IIF(LEN(ALLTRIM(XFILIAL("DTR")))==2 .AND. LEN(XFILIAL("DTR"))==4,CFILANT,XFILIAL("DTR")) + FQ5->FQ5_SOT + FQ5->FQ5_OBRA + FQ5->FQ5_VIAGEM )
	   LVEIC :=.T.
	ELSE
	   LVEIC :=.F.
	ENDIF   
	DBSELECTAREA("FQ5")
	
ENDIF

ASIZEAUT 	 := MSADVSIZE()

IF OMAINWND:NCLIENTWIDTH > 800
	AADD( AOBJECTS, {  100, 008, .T., .T. } ) 	// ENCHOICE
	AADD( AOBJECTS, {  100, 092, .T., .T. } ) 	//MSGETDADOS
ELSE
	AADD( AOBJECTS, {  100, 030, .T., .T. } ) 	// ENCHOICE
	AADD( AOBJECTS, {  100, 070, .T., .T. } ) 	// MSGETDADOS
ENDIF

AINFO 	:= {ASIZEAUT[1],ASIZEAUT[2],ASIZEAUT[3],ASIZEAUT[4],3,3}
APOSOBJ := MSOBJSIZE( AINFO, AOBJECTS, .T. , .F. )
APOSGET := MSOBJGETPOS((ASIZEAUT[3]-ASIZEAUT[1]),315,{{004,024,240,270}} )

NBLIN1  := 002
NBCOL1  := 003
NBLIN2  := APOSOBJ[2,3]-APOSOBJ[2,1]-15  		// ALTURA
NBCOL2  := APOSOBJ[2,4]-07

// --> MONTAGEM DA TELA QUE SEHRA APRESENTADA PARA USUARIO (LAY-OUT)
DEFINE MSDIALOG ODLG FROM 0,0 TO ASIZEAUT[6],ASIZEAUT[5] TITLE OEMTOANSI(CTITJAN) OF OMAINWND PIXEL

	NFOLDERFRE := 0								// DADOS DO FRETE
	NFOLDERVEI := 0								// VEICULO
	NFOLDERNOT := 0								// NOTA DO CLIENTE
	
	AADD(ATITLES,STR0016      ) ; NFOLDERFRE:=LEN(ATITLES) //"DADOS DO FRETE"
	AADD(ATITLES,STR0017   ) ; NFOLDERVEI:=LEN(ATITLES) //"VEÍCULO/MOTORISTA"
	AADD(ATITLES,STR0018     ) ; NFOLDERNOT:=LEN(ATITLES) //"NF'S DO CLIENTE"
	
	NLIN1 := APOSOBJ[2,1]
	NCOL1 := APOSOBJ[2,2]
	NLIN2 := APOSOBJ[2,4]-APOSOBJ[2,2]  		// LARGURA
	NCOL2 := APOSOBJ[2,3]-APOSOBJ[2,1]  		// ALTURA
	
	@ NLIN1+15,NCOL1 TO NLIN2+15,NCOL2 OF ODLG PIXEL
	
	OFOLDER:=TFOLDER():NEW(0     ,0     ,ATITLES  ,APAGES     ,ODLG   ,         ,          ,          ,.T.       , .F. )
	OFOLDER:ALIGN:=CONTROL_ALIGN_ALLCLIENT
	
	FOR NPOS:=1 TO LEN(ATITLES)
		OFOLDER:ADIALOGS[NPOS]:OFONT:=ODLG:OFONT
	NEXT NPOS 

	// --> CONSISTENCIA A CADA MUDANCA DE PASTA DO OBJETO FOLDER
	OFOLDER:BSETOPTION:={|NINDO|LOCA04601(NINDO,OFOLDER:NOPTION,@ODLG,@OFOLDER)}
	
	NLIN1 := APOSOBJ[1,1]
	NCOL1 := APOSOBJ[1,2]
	NLIN2 := APOSOBJ[1,3]
	NCOL2 := APOSOBJ[1,4]
	
	IF NFOLDERFRE > 0 							// FRETE
		NLIN1 := 002
		NCOL1 := 003
		NLIN2 := APOSOBJ[2,3]-APOSOBJ[2,1]-15 	// ALTURA
		NCOL2 := APOSOBJ[2,4]-07
		FFOLDERFRE(NFOLDERFRE)
	ENDIF 

	IF NFOLDERVEI>0 							// VEICULO
		CALIAS   := "DTR"
		CCHAVE   := IIF(LEN(ALLTRIM(XFILIAL(CALIAS)))==2 .AND. LEN(XFILIAL(CALIAS))==4,CFILANT,XFILIAL(CALIAS))+CPROJETO+COBRA+TRIM(CVIAGEM) //XFILIAL(CALIAS)+CPROJETO+COBRA+TRIM(CVIAGEM)
		CCONDICAO:= 'DTR_FILIAL+DTR_SOT+DTR_OBRA+DTR_VIAGEM=="'+CCHAVE+'"'
		NINDICE  := 7 							// DTR_FILIAL+DTR_FILORI+DTR_VIAGEM+DTR_ITEM
		CFILTRO  := CCONDICAO
		FFOLDERVEI(NFOLDERVEI,CCHAVE,CCONDICAO,NINDICE,CALIAS,CFILTRO)
	ENDIF

	IF NFOLDERNOT>0  							// NOTA FISCAL DO CLIENTE 
		CALIAS    := "DTC"
		CCHAVE    := IIF(LEN(ALLTRIM(XFILIAL(CALIAS)))==2 .AND. LEN(XFILIAL(CALIAS))==4,CFILANT,XFILIAL(CALIAS))+CPROJETO+COBRA+TRIM(CVIAGEM)
		CCONDICAO := 'DTC_FILIAL+DTC_SOT+DTC_OBRA+DTC_VIAGEM=="'+CCHAVE+'"'
		NINDICE   := 10 						// DTC_FILIAL+DTC_SOT+DTC_VIAGEM
		CFILTRO   := CCONDICAO
		FFOLDERNOT(NFOLDERNOT,CCHAVE,CCONDICAO,NINDICE,CALIAS,CFILTRO)
	ENDIF

	@ NLIN1,NCOL1-05 TO NLIN1+35,NCOL1+545 OF OFOLDER:ADIALOGS[1] PIXEL
	
	@ NLIN1+06,NCOL1+005 SAY   OEMTOANSI(STR0019)       SIZE 100,8              OF OFOLDER:ADIALOGS[1] PIXEL COLOR CLR_BLUE FONT OFONT1 //"NO.AS:"
	@ NLIN1+05,NCOL1+080 MSGET ONOAS     VAR CNOAS       SIZE 170,8 WHEN .F.     OF OFOLDER:ADIALOGS[1] PIXEL COLOR CLR_BLUE FONT OFONT2
	
	@ NLIN1+06,NCOL1+260 SAY   OEMTOANSI(STR0020)      SIZE 100,8              OF OFOLDER:ADIALOGS[1] PIXEL COLOR CLR_BLUE FONT OFONT1 //"VIAGEM:"
	@ NLIN1+05,NCOL1+306 MSGET OPROJETO  VAR CVIAGEM     SIZE  70,8 WHEN LINCLUI OF OFOLDER:ADIALOGS[1] PIXEL COLOR CLR_BLUE FONT OFONT2
	
	@ NLIN1+21,NCOL1+005 SAY   OEMTOANSI(STR0021) SIZE 100,8              OF OFOLDER:ADIALOGS[1] PIXEL COLOR CLR_BLUE FONT OFONT1 //"NRO.PROJETO:"
	@ NLIN1+20,NCOL1+080 MSGET OPROJETO  VAR CPROJETO    SIZE 170,8 WHEN .F.     OF OFOLDER:ADIALOGS[1] PIXEL COLOR CLR_BLUE FONT OFONT2
	
	@ NLIN1+21,NCOL1+260 SAY   OEMTOANSI(STR0022)        SIZE 100,8              OF OFOLDER:ADIALOGS[1] PIXEL COLOR CLR_BLUE FONT OFONT1 //"OBRA:"
	@ NLIN1+20,NCOL1+306 MSGET OOBRA     VAR COBRA       SIZE  35,8 WHEN .F.     OF OFOLDER:ADIALOGS[1] PIXEL COLOR CLR_BLUE FONT OFONT2
	IF LGERADO
		@ NLIN1+06,NCOL1+390 SAY   OEMTOANSI(STR0023) SIZE 100,8              OF OFOLDER:ADIALOGS[1] PIXEL COLOR CLR_BLUE FONT OFONT1 //"NO.CTRC:"
		@ NLIN1+05,NCOL1+455 MSGET OCTRC VAR CCTRC       SIZE  35,8 WHEN .F.     OF OFOLDER:ADIALOGS[1] PIXEL COLOR CLR_BLUE FONT OFONT2
	ENDIF

	@ NLIN1+21,NCOL1+390 SAY   OEMTOANSI(STR0024)   SIZE 100,8              OF OFOLDER:ADIALOGS[1] PIXEL COLOR CLR_BLUE FONT OFONT1 //"TIPO.CTRC:"
	@ NLIN1+20,NCOL1+455 MSGET OTPCTRC   VAR CTPCTRC     SIZE  70,8 WHEN .F.     OF OFOLDER:ADIALOGS[1] PIXEL COLOR CLR_BLUE FONT OFONT2

ACTIVATE MSDIALOG ODLG CENTERED ON INIT ENCHOICEBAR(ODLG,{||FSALVAR(ODLG)},{||FSAIR(ODLG)},,ABUTTONS)

RESTAREA(AAREA)

RETURN 



// ======================================================================= \\
STATIC FUNCTION FSALVAR(ODLG)
// ======================================================================= \\

//LOCAL AAREA:=GETAREA()
LOCAL LRET := .T.

IF !LGERADO
	IF VALIDNOT()  .AND. VALIDCDPG() .AND. VLDFROTA()
		IF MSGYESNO(STR0025) //"CONFIRMA A ATUALIZAÇÃO DAS TABELAS ??"
			IF ATU_DTQ()
				FSALVARVEI()  	// VEÍCULO
				FSALVARNOT()  	// GRAVA NFE
				IF .T.			// MSGYESNO("TABELAS ATUALIZADAS COM SUCESSO. DESEJA SAIR ??")
					CONFIRMSX8()
					ODLG:END()
				ENDIF
			ENDIF
		ENDIF
	ELSE
		LRET := .F.
	ENDIF 
ELSE
	MSGALERT(STR0026 , STR0015)  //"C.T.R.C PARA ESTA VIAGEM JA SE ENCONTRA GERADO.VERIFIQUE !"###"GPO - LOCT004.PRW"
	ODLG:END()
ENDIF                                                                           

//RESTAREA(AAREA)

RETURN LRET



// ======================================================================= \\
STATIC FUNCTION FSAIR(ODLG)
// ======================================================================= \\

IF .T. 							// MSGYESNO("SAIR SEM GRAVAR. CONFIRMA ??")
	ODLG:END()
ENDIF

ROLLBACKSX8()

RETURN



// ======================================================================= \\
STATIC FUNCTION ATU_DTQ()
// ======================================================================= \\

LOCAL NSAVESX8 
LOCAL CCHAVE     := "" 

PRIVATE CAUTORIZ := ""
//PRIVATE CTIPOVIA := "1" 		// 1=NORMAL
PRIVATE CROTA    := "PADRAO" 	// ROTA
PRIVATE CSERTMS  := "2" 		// 2=TRANSPORTE
PRIVATE CTIPTRA  := "1" 		// DLC -> 1=RODOVIÁRIO
PRIVATE ATABAUX  := {}

NSAVESX8 := GETSX8LEN()

DBSELECTAREA("FQ5")

CCHAVE  := XFILIAL("FQ5")+CPROJETO+COBRA+CVIAGEM
CCHAVE2 := XFILIAL("FQ5")+CPROJETO+COBRA

CORIGEM	:= TRIM(CORI) +"/"+ TRIM(CORIUF)
CDESTINO:= TRIM(CDES) +"/"+ TRIM(CDESUF)
FQ5->(DBSETORDER(RETORDEM("FQ5","FQ5_FILIAL+FQ5_SOT+FQ5_OBRA+FQ5_VIAGEM")))
_OPER   := .T.
IF FQ5->(DBSEEK(CCHAVE))
	RECLOCK("FQ5", .F. )
ELSE
	_OPER   := .T.
	IF LINCLUI .OR. LINCCTRB   //POPC = "I" .OR. POPC = "B"
		_STATUS := IIF(LINCLUI,"V/Z","A/L")
		FQ5->(DBSEEK(CCHAVE2))
		WHILE FQ5->(!EOF()) .AND. CPROJETO  = FQ5->FQ5_SOT .AND.  FQ5->FQ5_OBRA = COBRA
			IF FQ5->FQ5_SITUAC $ _STATUS
				_OPER   := .F.
			ENDIF
			IF !_OPER
				EXIT
			ENDIF
			FQ5->(DBSKIP())
		ENDDO 
	ENDIF
	IF _OPER
		RECLOCK("FQ5", .T. )
		AADD(ATABAUX,{"FQ5_FILIAL",'CFILANT' })
		AADD(ATABAUX,{"FQ5_SOT",'CPROJETO'			})
		AADD(ATABAUX,{"FQ5_OBRA",'COBRA'			})
		AADD(ATABAUX,{"FQ5_FILORI",'"01"'           })
		AADD(ATABAUX,{"FQ5_TIPVIA",'CTIPOVIA'       })
		AADD(ATABAUX,{"FQ5_DATGER",'DDATABASE'      })
		AADD(ATABAUX,{"FQ5_HORGER",'SUBS(TIME(),1,2)+SUBS(TIME(),4,2)'})
		AADD(ATABAUX,{"FQ5_VIAGEM",'CVIAGEM'		})
		AADD(ATABAUX,{"FQ5_CODCLI",'CCODCLI'		})
		AADD(ATABAUX,{"FQ5_LOJA"  ,'CLOJA'			})
		AADD(ATABAUX,{"FQ5_NOMCLI",'CNOM'	   		})
		AADD(ATABAUX,{"FQ5_SERTMS",'CSERTMS'        })
		AADD(ATABAUX,{"FQ5_TIPTRA",'CTPTRA'         })
		AADD(ATABAUX,{"FQ5_STATUS",'"1"'            })
		AADD(ATABAUX,{"FQ5_QTDPER",'0'              })
		AADD(ATABAUX,{"FQ5_DIRNAV",'CDIRNAV'        })
		AADD(ATABAUX,{"FQ5_NAVEG" ,'CNAVEG'         })
	ELSE
	    RECLOCK("FQ5", .F. )
	ENDIF                    
	
ENDIF

IF EMPTY(FQ5_NUMCTR)
	_CNUMCTR := "-"
	AADD(ATABAUX,{'FQ5_NUMCTR'  ,'_CNUMCTR' })
ENDIF	

AADD(ATABAUX,{'FQ5_ORIGEM','CORIGEM'	})  //CIDADE+'/'+ESTADO
AADD(ATABAUX,{'FQ5_DESTIN','CDESTINO'	})  //CIDADE+'/'+ESTADO
AADD(ATABAUX,{'FQ5_CARREG','CCARREG'	})
AADD(ATABAUX,{'FQ5_UFCOLE','CUFCOLE'	})
AADD(ATABAUX,{'FQ5_DESCAR','CDESCAR'	})
AADD(ATABAUX,{'FQ5_UFENTR','CUFENTR'	})
AADD(ATABAUX,{'FQ5_TOTFRE','NFRETEP'	})
AADD(ATABAUX,{'FQ5_VLRINF','NFRETET'	})
AADD(ATABAUX,{'FQ5_VALICM','NVALICM'	})
AADD(ATABAUX,{'FQ5_VALADV','NVALADV'	})
AADD(ATABAUX,{'FQ5_BASICM','NBASEICM'	})
AADD(ATABAUX,{'FQ5_BASADV','NBASEADV'	})
AADD(ATABAUX,{'FQ5_PERICM','NALIQICM'	})
AADD(ATABAUX,{'FQ5_PERADV','NALIQADV'	})
AADD(ATABAUX,{'FQ5_TES'   ,'CTES'		})
AADD(ATABAUX,{'FQ5_CONDPG','CCONDPAG'	})
AADD(ATABAUX,{'FQ5_DCOND' ,'CDCON'		})
AADD(ATABAUX,{'FQ5_CCC'   ,'CCCUSTO'	})
AADD(ATABAUX,{'FQ5_PAGO'  ,'CPAGO'		})
AADD(ATABAUX,{'FQ5_OBSCTR','COBSCONTR'	})
AADD(ATABAUX,{'FQ5_OBSERV','COBSSEG'	})
AADD(ATABAUX,{'FQ5_DESICM','LDESTICM'	})
AADD(ATABAUX,{'FQ5_CFOP'  ,'CCFOP'  	})
AADD(ATABAUX,{"FQ5_TIPTRA",'CTPTRA'     }) 
AADD(ATABAUX,{'FQ5_CODORI','CCODORI'	})
AADD(ATABAUX,{'FQ5_CODDES','CCODFIM'	})
AADD(ATABAUX,{'FQ5_AFRMM','NAFRMM'		})
AADD(ATABAUX,{'FQ5_IRIN','CCODIRI'		})
AADD(ATABAUX,{"FQ5_DIRNAV",'CDIRNAV'    })
AADD(ATABAUX,{"FQ5_NAVEG" ,'CNAVEG'     })
//AADD(ATABAUX,{'FQ5_PLACAV','CPLACCAV'	})
//AADD(ATABAUX,{'FQ5_PLACAR','CPLACCAR'	})
//AADD(ATABAUX,{'FQ5_MOTORI','CNOMMOT'	}) 
AADD(ATABAUX,{'FQ5_TES2'   ,'CTES2'		})
AADD(ATABAUX,{'FQ5_CFOP2'  ,'CCFOP2'  	})
      
//NDESCCOMISS := (NVALESTAD+NCARDES+NVALCCOM+NVALESCOL+NFRETEPAUX) - (NFRETET)
NDESCCOMISS := (NVALESCOL+NVALPEDAG+NVALSCOM+NVALADV+NVALICM)
NDESCCOMISS := ABS(NDESCCOMISS)
AADD(ATABAUX,{'FQ5_VRESTA'  ,'NVALESTAD'  	})
AADD(ATABAUX,{'FQ5_CARDES'  ,'NCARDES'  	})
AADD(ATABAUX,{'FQ5_VRESCO'  ,'NVALESCOL'  	})
AADD(ATABAUX,{'FQ5_VRPEDA'  ,'NVALPEDAG'  	})
AADD(ATABAUX,{'FQ5_VRSCOM'  ,'NVALSCOM' 	})
AADD(ATABAUX,{'FQ5_VRCCOM'  ,'NVALCCOM'  	})
AADD(ATABAUX,{'FQ5_DESCOM'  ,'NDESCCOMISS' 	})
AADD(ATABAUX,{'FQ5_XFRETE'  ,'NFRETEPAUX' 	})
AADD(ATABAUX,{'FQ5_VRCONT'  ,'NVALCONTAINER' 	})

FQ5->(FGRAVAPPP(ATABAUX,"FQ5","FQ5"))

FQ5->(MSUNLOCK())

IF LINCLUI
	CONFIRMSX8()
ENDIF
  
RETURN(.T.)



// ======================================================================= \\
STATIC FUNCTION FSALVARVEI 			// GRAVA VEÍCULO
// ======================================================================= \\

LOCAL AGRAVADOS:={}  //GRAVADOS
LOCAL NPOS := 0

PRIVATE AHEADER,ACOLS,CITEM

// INICIALIZA O AHEADER
AHEADER := ODLGVEI:AHEADER
ACOLS   := ODLGVEI:ACOLS

// ACUMULA O ACOLS CORRENTE NO ACOLS COM TODOS OS REGISTROS
// ACOLS:=FACU_ACOLS(ODLGVEI:ACOLS,ODLGVEI_ACOLS,ODLGVEI:AHEADER,"DTR_ITEM")

DBSELECTAREA("DTR")  //VEÍCULOS
DBSETORDER(1)  //DTR_FILIAL+DTR_FILORI+DTR_VIAGEM+DTR_ITEM
FOR NPOS:=1 TO LEN(ACOLS)
	//CITEM:=ACOLS[NPOS][ASCAN(AHEADER,{|X|ALLTRIM(X[2])=="DTR_ITEM"})]
	CITEM:= IF( GDFIELDPOS("DTR_ITEM")<>0, GDFIELDGET("DTR_ITEM",NPOS),CITEM) // ALTERADO POR FERNANDO NAKAHARA DIA 17/06/2011
	IF EMPTY(CITEM)
	  CITEM:="01"
	ENDIF
	  
	IF !ACOLS[NPOS,LEN(AHEADER)+1] .AND. !EMPTY(CITEM)  //DELETED
		DBSEEK(IIF(LEN(ALLTRIM(XFILIAL("DTR")))==2 .AND. LEN(XFILIAL("DTR"))==4,CFILANT,XFILIAL("DTR"))+CFILORI+CVIAGEM+CITEM)
		IF EOF()
			RECLOCK("DTR", .T. )
		ELSE
			RECLOCK("DTR", .F. )
		ENDIF
		
		DTR->(FGRAVATUDO(NPOS,ACOLS,AHEADER))  //GRAVA TODOS OS CAMPOS DO ACOLS
		
		DTR->DTR_FILIAL  :=IIF(LEN(ALLTRIM(XFILIAL("DTR")))==2 .AND. LEN(XFILIAL("DTR"))==4,CFILANT,XFILIAL("DTR"))//CFILANT //XFILIAL("DTR")
		DTR->DTR_FILORI  :=CFILORI
		DTR->DTR_VIAGEM  :=CVIAGEM
		DTR->DTR_SOT     :=CPROJETO
		DTR->DTR_OBRA    :=COBRA
		AADD(AGRAVADOS,RECNO())  //GRAVADOS
		DTR->(MSUNLOCK()) 
	
	// RETIRADO POR TIAGO OBARA DE OLIVEIRA (BIALE) - 11/07/2011	
	ELSE
		IF DBSEEK(IIF(LEN(ALLTRIM(XFILIAL("DTR")))==2 .AND. LEN(XFILIAL("DTR"))==4,CFILANT,XFILIAL("DTR"))+CFILORI+CVIAGEM+CITEM)
			RECLOCK("DTR", .F. )
			DBDELETE()
			MSUNLOCK()
		ENDIF
	// RETIRADO POR TIAGO OBARA DE OLIVEIRA (BIALE) - 11/07/2011
	ENDIF
NEXT

//ALTERAÇÃO PARA ATENDER CT-E POR FERNANDO WILLIAN DE SOUZA FURTADO
DBSELECTAREA("DUP")
DBSETORDER(3)
IF MSSEEK(XFILIAL("DUP") + FQ5->FQ5_SOT + FQ5->FQ5_OBRA + FQ5->FQ5_VIAGEM + 'CT')
	RECLOCK("DUP",.F.)
ELSE
	RECLOCK("DUP",.T.)
ENDIF
DUP->DUP_FILORI := FQ5->FQ5_FILORI
DUP->DUP_VIAGEM := FQ5->FQ5_VIAGEM
DUP->DUP_ITEDTR := "CT"		//GRAVANDO ESSE CODIGO PARA NÃO GERAR PROBLEMAS NO CTRB
DUP->DUP_CODMOT := IIF(LEN(ACOLS)>0,GDFIELDGET("DTR_CODMOT",1),"")
DUP->DUP_SOT    := FQ5->FQ5_SOT
DUP->DUP_OBRA   := FQ5->FQ5_OBRA
DUP->(MSUNLOCK()) 

RETURN



// ======================================================================= \\
STATIC FUNCTION FSALVARNOT() 		// GRAVA NFE
// ======================================================================= \\

LOCAL AHEADER,ACOLS
LOCAL NPOS 
LOCAL AVIAGEM     := {}  
LOCAL NDTC_RENO   := 0  
LOCAL NPOS_DELETE := 0  
LOCAL NRECNO_GRAV := 0 

CNUMNFC := "      "
CSERNFC := "   "
CCLIREM := "      "
CLOJREM := "  "

DBSELECTAREA("DTP")
DBSETORDER(3)  					// FILIAL + FILORI + VIAGEM

DBSEEK(XFILIAL("DTP")+FQ5->FQ5_FILORI+FQ5->FQ5_VIAGEM , .T. )

DBSELECTAREA("DTC")
DBORDERNICKNAME("DTCIND09")

CVIAGEM := FQ5->FQ5_VIAGEM
AHEADER := ODLGNOT:AHEADER
ACOLS   := ODLGNOT:ACOLS

IF DTC->( DBSEEK(IIF(LEN(ALLTRIM(XFILIAL("DTC")))==2 .AND. LEN(XFILIAL("DTC"))==4,CFILANT,XFILIAL("DTC"))+CVIAGEM) )
	NDTC_RENO := DTC->( RECNO() )
	WHILE DTC->(!EOF()) .AND. DTC->DTC_FILIAL == IIF(LEN(ALLTRIM(XFILIAL("DTC")))==2 .AND. LEN(XFILIAL("DTC"))==4,CFILANT,XFILIAL("DTC")) .AND. DTC->DTC_VIAGEM == CVIAGEM
		AADD(AVIAGEM , DTC->(RECNO())) 
		DTC->( DBSKIP() )
	ENDDO
	DTC->( DBGOTO(NDTC_RENO) )
ENDIF

FOR NPOS:=1 TO LEN(ACOLS)
	CNUMNFC:=GDFIELDGET("DTC_NUMNFC" , NPOS, .F., AHEADER, ACOLS)
	CSERNFC:=GDFIELDGET("DTC_SERNFC" , NPOS, .F., AHEADER, ACOLS)
	CCLIREM:=GDFIELDGET("DTC_CLIREM" , NPOS, .F., AHEADER, ACOLS)
	CLOJREM:=GDFIELDGET("DTC_LOJREM" , NPOS, .F., AHEADER, ACOLS)
	
	IF !ACOLS[NPOS,LEN(AHEADER)+1] .AND. !EMPTY(CNUMNFC)  //DELETED
		//
		IF NPOS <= LEN(AVIAGEM)  // SE JÁ EXISTE REGISTRO COM ESTE NUMERO DE VIAGEM, ALTERA.
			DTC->(DBGOTO(AVIAGEM[NPOS]))
			RECLOCK("DTC", .F. )
		ELSE
			RECLOCK("DTC", .T. )
		ENDIF

		DTC->DTC_FILIAL := IIF(LEN(ALLTRIM(XFILIAL("DTC")))==2 .AND. LEN(XFILIAL("DTC"))==4,CFILANT,XFILIAL("DTC")) //CFILANT//XFILIAL("DTC")
		DTC->DTC_LOTNFC := M->DTC_LOTNFC
		DTC->DTC_FILORI := CFILORI
		DTC->DTC_NUMNFC := GDFIELDGET("DTC_NUMNFC" , NPOS, .F., AHEADER, ACOLS)
	/*	DTC->DTC_CLIREM := CCODREM		// GDFIELDGET("DTC_CLIREM" , NPOS, .F., AHEADER, ACOLS)
		DTC->DTC_LOJREM := CLOJREM		// GDFIELDGET("DTC_LOJREM" , NPOS, .F., AHEADER, ACOLS)
		DTC->DTC_CLIDES := CCODDES		// GDFIELDGET("DTC_CLIDES" , NPOS, .F., AHEADER, ACOLS)
		DTC->DTC_LOJDES := CLOJDES		// GDFIELDGET("DTC_LOJDES" , NPOS, .F., AHEADER, ACOLS)
		DTC->DTC_CLIDEV := CCODCON		// GDFIELDGET("DTC_CLIDEV" , NPOS, .F., AHEADER, ACOLS)//GDFIELDGET("DTC_CLIDEV" , NPOS, .F., AHEADER, ACOLS)
		DTC->DTC_LOJDEV := CLOJCON		// GDFIELDGET("DTC_LOJDEV" , NPOS, .F., AHEADER, ACOLS)//GDFIELDGET("DTC_LOJDEV" , NPOS, .F., AHEADER, ACOLS) */
		DTC->DTC_DATENT := GDFIELDGET("DTC_DATENT" , NPOS, .F., AHEADER, ACOLS)
		DTC->DTC_ORIGEM := CORIGEM
		DTC->DTC_DESTIN := CDESTINO
		DTC->DTC_DEVFRE := GDFIELDGET("DTC_DEVFRE" , NPOS, .F., AHEADER, ACOLS)
		DTC->DTC_SERTMS := M->DTC_SERTMS
		DTC->DTC_TIPTRA := M->DTC_TIPTRA
		DTC->DTC_SERVIC := M->DTC_SERVIC
		DTC->DTC_SELORI := M->DTC_SELORI
		DTC->DTC_CDRORI := M->DTC_CDRORI
		DTC->DTC_CDRDES := M->DTC_CDRDES
		DTC->DTC_VLRINF := M->DTC_VLRINF
	 //	DTC->DTC_TIPFRE := M->DTC_TIPFRE
		DTC->DTC_VLRINF := NVLRINF

		DTC->(FGRAVATUDO(NPOS,ACOLS,AHEADER))  //GRAVA TODOS OS CAMPOS DO ACOLS  
		
		DTC->DTC_TIPFRE:=CTIPO
		IF DTC->(FIELDPOS("DTC_TOMADO")) > 0
			DTC->DTC_TOMADO:=CTOMADOR
		ENDIF
		DTC->DTC_CLIREM:=CCODREM//GDFIELDGET("DTC_CLIREM" , NPOS, .F., AHEADER, ACOLS)
		DTC->DTC_LOJREM:=CLOJREM//GDFIELDGET("DTC_LOJREM" , NPOS, .F., AHEADER, ACOLS)
		DTC->DTC_CLIDES:=CCODDES//GDFIELDGET("DTC_CLIDES" , NPOS, .F., AHEADER, ACOLS)
		DTC->DTC_LOJDES:=CLOJDES//GDFIELDGET("DTC_LOJDES" , NPOS, .F., AHEADER, ACOLS)
		DTC->DTC_CLIDEV:=CCODCON//GDFIELDGET("DTC_CLIDEV" , NPOS, .F., AHEADER, ACOLS)//GDFIELDGET("DTC_CLIDEV" , NPOS, .F., AHEADER, ACOLS)
		DTC->DTC_LOJDEV:=CLOJCON//GDFIELDGET("DTC_LOJDEV" , NPOS, .F., AHEADER, ACOLS)//GDFIELDGET("DTC_LOJDEV" , NPOS, .F., AHEADER, ACOLS)
		DTC->DTC_CLICON:=CCODCON//GDFIELDGET("DTC_CLIDEV" , NPOS, .F., AHEADER, ACOLS)//GDFIELDGET("DTC_CLIDEV" , NPOS, .F., AHEADER, ACOLS)
		DTC->DTC_LOJCON:=CLOJCON//GDFIELDGET("DTC_LOJDEV" , NPOS, .F., AHEADER, ACOLS)//GDFIELDGET("DTC_LOJDEV" , NPOS, .F., AHEADER, ACOLS)
		DTC->DTC_FILIAL  :=IIF(LEN(ALLTRIM(XFILIAL("DTC")))==2 .AND. LEN(XFILIAL("DTC"))==4,CFILANT,XFILIAL("DTC")) //CFILANT//XFILIAL("DTC")
	 //	DTC->DTC_TIPNFC:=M->DTC_TIPNFC  //0=NORMAL/1=DEVOLUÇÃO PARCIAL
		DTC->DTC_CODPRO:="999900011"
		DTC->DTC_FILORI:=CFILANT
	 //	DTC->DTC_LOTNFC:=DTP->DTP_LOTNFC
		DTC->DTC_CDRCAL:=M->DTC_CDRDES
		DTC->DTC_CLICAL:=M->DTC_CLIDES
		DTC->DTC_LOJCAL:=M->DTC_LOJDES
		DTC->DTC_VIAGEM:=FQ5->FQ5_VIAGEM
		DTC->DTC_CONTRA:=FQ5->FQ5_CONTRA
		DTC->DTC_EQUIP :=FQ5->FQ5_EQUIP
		DTC->DTC_SOT   := CPROJETO
		DTC->DTC_OBRA  := COBRA
	 //	DTC->DTC_TIPNFC:='0'
		DTC->DTC_SELORI:=STRZERO(2,LEN(DTC->DTC_SELORI))		
		NRECNO_GRAV++
		MSUNLOCK()
		
	 //	MSMM(DTC->DTC_CODOBS,,,COBSCONTR,1,,,"DTC","DTC_CODOBS")
	ENDIF
NEXT
// EXLUI OS QUE SOBRARAM NA GRAVAÇÃO DO ACOLS (OS DELETADOS NO ACOLS E ESTÃO NA TABELA DTC)
IF LEN(AVIAGEM) > NRECNO_GRAV
	FOR NPOS_DELETE := NRECNO_GRAV+1 TO LEN(AVIAGEM)
		DTC->( DBGOTO(AVIAGEM[NPOS_DELETE]) )
		DTC->( RECLOCK("DTC", .F. ) )
		DTC->( DBDELETE() )
		DTC->( MSUNLOCK() )
	NEXT NPOS_DELETE
ENDIF

RETURN 



// ======================================================================= \\
STATIC FUNCTION FGRAVAPPP(ATABAUX , CALIPUT , CALIGET) 
// ======================================================================= \\

LOCAL NPOS,CCAMPOPUT,CCAMPOGET

FOR NPOS:=1 TO LEN(ATABAUX)
	CCAMPOPUT := ATABAUX[NPOS,1]
	CCAMPOGET := ATABAUX[NPOS,2]
	(CALIPUT)->(&CCAMPOPUT) := (CALIGET)->(&CCAMPOGET) 
NEXT NPOS 

RETURN(.T.)



// ======================================================================= \\
FUNCTION LOCA04601(NINDO , NESTOU , ODLG , OFOLDER) 
// ======================================================================= \\

LOCAL ACOLS 
LOCAL LRET     := .T. 
LOCAL NPOSREM  := 0
LOCAL NPOSDES  := 0
LOCAL NPOSCON  := 0
LOCAL NPOSCOD  := 0 , NPOSNOME := 0 
LOCAL NPOSTPNF := 0
LOCAL NPOSTOMA := 0
LOCAL NX       := 0 
LOCAL I        := 0 

ACOLS       := {} 

NPOSTPNF	:= ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_TIPNFC"})

NPOSCOD     := ASCAN(ODLGVEI:AHEADER,{|X| ALLTRIM(X[2]) == "DTR_CODMOT"})
NPOSNOME    := ASCAN(ODLGVEI:AHEADER,{|X| ALLTRIM(X[2]) == "DTR_NOMMOT"})

NPOSCODR    := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_CLIREM"})
NPOSLOJR    := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_LOJREM"})
NPOSREM     := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_NOMREM"})

NPOSCODM    := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_CLIDES"})
NPOSLOJM    := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_LOJDES"})
NPOSDES     := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_NOMDES"})

NPOSCODC    := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_CLICON"})
NPOSLOJC    := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_LOJCON"})
NPOSCON     := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_NOMCON"})

NPOSCODD    := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_CLIDEV"})
NPOSLOJD    := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_LOJDEV"})
NPOSDEV     := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_NOMDEV"})

NPOSTIPF    := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_TIPFRE"})

IF DTC->(FIELDPOS("DTC_TOMADO"))>0
	NPOSTOMA    := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_TOMADO"})
ENDIF

FOR NX	:=	1 TO LEN(ODLGNOT:ACOLS)
	ODLGNOT:ACOLS[NX][NPOSCODR] :=  CCODREM
	ODLGNOT:ACOLS[NX][NPOSLOJR] :=  CLOJREM
	ODLGNOT:ACOLS[NX][NPOSREM]  :=  POSICIONE("SA1",1,IIF(LEN(ALLTRIM(XFILIAL("DTC")))==2 .AND. LEN(XFILIAL("DTC"))==4,CFILANT,XFILIAL("DTC")) + CCODREM + CLOJREM , "A1_NOME")
	
	ODLGNOT:ACOLS[NX][NPOSCODM] :=  CCODDES
	ODLGNOT:ACOLS[NX][NPOSLOJM] :=  CLOJDES
	ODLGNOT:ACOLS[NX][NPOSDES]  :=  POSICIONE("SA1",1,IIF(LEN(ALLTRIM(XFILIAL("DTC")))==2 .AND. LEN(XFILIAL("DTC"))==4,CFILANT,XFILIAL("DTC")) + CCODDES + CLOJDES , "A1_NOME")

	ODLGNOT:ACOLS[NX][NPOSTIPF] :=  CTIPO

	IF NPOSTOMA > 0
		ODLGNOT:ACOLS[NX][NPOSTOMA] :=  CTOMADOR
	ENDIF

	ODLGNOT:ACOLS[NX][NPOSCODD] := CCODCON
	ODLGNOT:ACOLS[NX][NPOSLOJD] := CLOJCON
	ODLGNOT:ACOLS[NX][NPOSDEV]  := POSICIONE("SA1",1,IIF(LEN(ALLTRIM(XFILIAL("DTC")))==2 .AND. LEN(XFILIAL("DTC"))==4,CFILANT,XFILIAL("DTC")) + CCODCON + CLOJCON , "A1_NOME")
	
	ODLGNOT:ACOLS[NX][NPOSCODC] := CCODCON
	ODLGNOT:ACOLS[NX][NPOSLOJC] := CLOJCON
	ODLGNOT:ACOLS[NX][NPOSCON]  := POSICIONE("SA1",1,IIF(LEN(ALLTRIM(XFILIAL("DTC")))==2 .AND. LEN(XFILIAL("DTC"))==4,CFILANT,XFILIAL("DTC")) + CCODCON + CLOJCON , "A1_NOME")
	
//	ODLGNOT:ACOLS[NX][NPOSTPNF] := CTIPNFC
NEXT NX

IF LEN(ODLGVEI:ACOLS) > 1 
	FOR NX := 1 TO LEN(ODLGVEI:ACOLS)
		ODLGVEI:ACOLS[NX][NPOSCOD]  := ODLGVEI:ACOLS[1][NPOSCOD]
		ODLGVEI:ACOLS[NX][NPOSNOME] := ODLGVEI:ACOLS[1][NPOSNOME]
	NEXT NX
ENDIF

IF VALTYPE(ODLGNOT:ACOLS[ODLGNOT:OBROWSE:NAT][10]) <> "U"
	NBASEADV := 0
	FOR I:= 1 TO LEN(ODLGNOT:ACOLS)
		NBASEADV := NBASEADV + GDFIELDGET("DTC_VALOR" , I , .F. , ODLGNOT:AHEADER , ODLGNOT:ACOLS) 
	NEXT I 
ENDIF

ODLGVEI:OBROWSE:REFRESH()
ODLGNOT:OBROWSE:REFRESH()
OFOLDER:REFRESH()
ODLG:REFRESH()

RETURN(LRET) 



// ======================================================================= \\
STATIC FUNCTION FFOLDERVEI(NFOLDER,CCHAVE,CCONDICAO,NINDICE,CALIAS,CFILTRO)
// ======================================================================= \\

LOCAL NSTYLE   := GD_INSERT + GD_UPDATE + GD_DELETE
LOCAL ACPOSNAO := {"DTR_FILORI","DTR_VIAGEM","DTR_FILVGE","DTR_NUMVGE","DTR_SOT","DTR_OBRA","DTR_TIPO",;
				   "DTR_MODRB1","DTR_QTDEIX","DTR_MODRB2","DTR_REBTRF","DTR_VALRB1","DTR_VALRB2","DTR_SLDREC",;
				   "DTR_DTVENC","DTR_TPTIAD","DTR_TPTSLD","DTR_PERMUL","DTR_CAREN","DTR_DTPROG","DTR_CODLCR","DTR_IRPF",;
				   "DTR_INSS","DTR_DATA","DTR_EXPFOL","DTR_USERGI","DTR_USERGA","DTR_PAGICM","DTR_DIARIA","DTR_DTCREL","DTR_DTDREL"}

// --> MONTANDO AHEADER PARA GETDADOS
AVTEMP   := LOCA036("DTR",ACPOSNAO)
AVHEADER := ACLONE(AVTEMP[1])

// --> MONTANDO ACOLS  PARA GETDADOS
AVTEMP   := LOCA03601("DTR",AVHEADER,4,NINDICE,IIF(LEN(ALLTRIM(XFILIAL("DTR")))==2 .AND. LEN(XFILIAL("DTR"))==4,CFILANT,XFILIAL("DTR"))+DTR->DTR_SOT+DTR->DTR_OBRA+DTR->DTR_VIAGEM, {|| IIF(LEN(ALLTRIM(XFILIAL("DTR")))==2 .AND. LEN(XFILIAL("DTR"))==4,CFILANT,XFILIAL("DTR"))+DTR->DTR_SOT+DTR->DTR_OBRA+DTR->DTR_VIAGEM == IIF(LEN(ALLTRIM(XFILIAL("DTR")))==2 .AND. LEN(XFILIAL("DTR"))==4,CFILANT,XFILIAL("DTR")) + CPROJETO + COBRA+CVIAGEM } )
AVCOLS   := ACLONE(AVTEMP[1])
//ACOLS[1,1]:="01"

NSTYLE := IIF(LGERADO,0,NSTYLE)  //2=VISUALIZAR

ODLGVEI:=MSNEWGETDADOS():NEW(NBLIN1,NBCOL1,NBLIN2,NBCOL2,NSTYLE,"ALLWAYSTRUE","ALLWAYSTRUE","+DTR_ITEM",,,110,,,.T.,OFOLDER:ADIALOGS[NFOLDER],AVHEADER,AVCOLS)
ODLGVEI:BCHANGE	:=	{|| CHGLINVEI() }
ODLGVEI:BFIELDOK:=	{|| ATUVEIINF() }

RETURN



// ======================================================================= \\
STATIC FUNCTION FFOLDERNOT(NFOLDER,CCHAVE,CCONDICAO,NINDICE,CALIAS,CFILTRO)
// ======================================================================= \\

LOCAL NSTYLE   := GD_INSERT + GD_UPDATE + GD_DELETE
LOCAL ACPOSNAO := {"DTC_VIAGEM","DTC_SERTMS","DTC_TIPTRA","DTC_DESTPT","DTC_DESSVT","DTC_FILIAL","DTC_LOTNFC","DTC_FILCFS","DTC_NUMSOL",;
					"DTC_FILDPC","DTC_ESTORN","DTC_QTDUNI","DTC_ENDTMS","DTC_INSREM","DTC_SQIREM",;
					"DTC_INSDES","DTC_SQEDES","DTC_SQIDES","DTC_NUMCOT","DTC_SQICON","DTC_ALIANC","DTC_DESALI","DTC_DPCLOC","DTC_VALDPC",;
					"DTC_CLICAL","DTC_LOJCAL","DTC_NOMCAL","DTC_SEQVIA","DTC_EQUIP","DTC_PERC","DTC_CONTRA","DTC_ORIGEM","DTC_DESTIN","DTC_DEVFRE",;
					"DTC_KM","DTC_RECEBE","DTC_HORENT","DTC_DTENTR","DTC_HORCOL","DTC_DATCOL","DTC_OBS","DTC_EDI","DTC_CODOBS","DTC_VLRINF",;
					"DTC_DESSER","DTC_SELORI","DTC_CDRORI","DTC_REGORI","DTC_CDRDES","DTC_REGDES","DTC_CDRCAL","DTC_REGCAL","DTC_DOC",;
					"DTC_SERIE","DTC_CDRPER","DTC_DOCPER","DTC_REGPER","DTC_DESPRO","DTC_CODPRO","DTC_BASSEG",;
					"DTC_INSDPC","DTC_SQIDPC","DTC_INSCON","DTC_FILORI","DTC_USERGA","DTC_USERGI","DTC_FILDOC","DTC_SERVIC",;
					"DTC_DISTIV","DTC_MODELO","DTC_ICMRET","DTC_MOEDA","DTC_CLINOT","DTC_LOJNOT","DTC_ROTA",;
					"DTC_VALSEG","DTC_MOENFC","DTC_RECISS","DTC_PESLIQ","DTC_INCOTE","DTC_EXCTDA",;
					"DTC_SOT","DTC_OBRA","DTC_NOMNOT","DTC_DOCANE","DTC_CODDCA","DTC_DESROT",;
					"DTC_NFELET","DTC_EMINFE","DTC_CODNFE","DTC_PRVENT","DTC_NFENTR","DTC_FILOCO","DTC_NUMOCO"	} 

NSTYLE := IIF(LGERADO,0,NSTYLE)  //2=VISUALIZAR

// --> MONTANDO AHEADER PARA GETDADOS
ATEMP   := LOCA036("DTC",ACPOSNAO)
AHEADER := ACLONE(ATEMP[1])

// --> MONTANDO ACOLS  PARA GETDADOS
ATEMP   := LOCA03601("DTC",AHEADER,4,NINDICE,IIF(LEN(ALLTRIM(XFILIAL("DTC")))==2 .AND. LEN(XFILIAL("DTC"))==4,CFILANT,XFILIAL("DTC"))+DTC->DTC_SOT+DTC->DTC_OBRA+DTC->DTC_VIAGEM, {|| IIF(LEN(ALLTRIM(XFILIAL("DTC")))==2 .AND. LEN(XFILIAL("DTC"))==4,CFILANT,XFILIAL("DTC"))+DTC->DTC_SOT+DTC->DTC_OBRA+DTC->DTC_VIAGEM == IIF(LEN(ALLTRIM(XFILIAL("DTC")))==2 .AND. LEN(XFILIAL("DTC"))==4,CFILANT,XFILIAL("DTC")) + CPROJETO + COBRA +CVIAGEM} )
ACOLS   := ACLONE(ATEMP[1])

ODLGNOT:=MSNEWGETDADOS():NEW(NBLIN1,NBCOL1,NBLIN2,NBCOL2,NSTYLE,"LOCA04602()","ALLWAYSTRUE","+DTC_FILDOC",,,110,,,.T.,OFOLDER:ADIALOGS[NFOLDER],AHEADER,ACOLS)
ODLGNOT:BCHANGE	:=	{|| CHGLINNOT() }
ODLGNOT:BFIELDOK:=	{|| ATUNFINFO() }

RETURN



// ======================================================================= \\
STATIC FUNCTION FFOLDERFRE(NFOLDER)
// ======================================================================= \\

LOCAL NLIN := 10
LOCAL OSCR

OSCR:= TSCROLLBOX():NEW(OFOLDER:ADIALOGS[NFOLDER],040,000,210,550,.T.,.T.,.T.) // CRIA CONTROLES

@ 013+NLIN,005 SAY OEMTOANSI(STR0027      ) SIZE 25,8 PIXEL OF OSCR //"CLIENTE"
@ 013+NLIN,050 SAY OEMTOANSI(STR0028         ) SIZE 25,8 PIXEL OF OSCR //"LOJA"
@ 013+NLIN,095 SAY OEMTOANSI(STR0029         ) SIZE 25,8 PIXEL OF OSCR //"NOME"

@ 021+NLIN,005 MSGET OCLI     VAR CCODCLI	PICTURE "@!" SIZE 030,8 WHEN .F. PIXEL OF OSCR
@ 021+NLIN,050 MSGET OLOJ     VAR CLOJA		PICTURE "@!" SIZE 015,8 WHEN .F. PIXEL OF OSCR
@ 021+NLIN,095 MSGET ONOM     VAR CNOM		PICTURE "@!" SIZE 176,8 WHEN .F. PIXEL OF OSCR

@ 013+NLIN,282 SAY OEMTOANSI(STR0030      ) SIZE 50,8 PIXEL OF OSCR //"TIPO FRETE"
@ 021+NLIN,282 MSCOMBOBOX OTIPO VAR CTIPO ITEMS ATIPO WHEN !LGERADO SIZE 080, 05 OF OSCR PIXEL 

@ 013+NLIN,382 SAY OEMTOANSI(STR0031      ) SIZE 50,8 PIXEL OF OSCR //"TOMADOR"
@ 021+NLIN,382 MSCOMBOBOX OTOMADOR VAR CTOMADOR ITEMS ATOMADOR WHEN !LGERADO SIZE 080, 05 OF OSCR PIXEL 

@ 033+NLIN,005 SAY OEMTOANSI(STR0032      ) SIZE 50,8 PIXEL OF OSCR //"TP. TRANSPORTE"
@ 041+NLIN,005 MSCOMBOBOX OTPTRA VAR CTPTRA ITEMS ATPTRA WHEN !LGERADO SIZE 080, 05 OF OSCR PIXEL

@ 033+NLIN,100 SAY OEMTOANSI(STR0033      ) SIZE 40,8 PIXEL OF OSCR //"COND.PAGTO"
@ 041+NLIN,100 MSGET OCONDPAG VAR CCONDPAG  F3 "SE4" WHEN !LGERADO VALID EXISTCPO("SE4",CCONDPAG) .AND. !EMPTY(CCONDPAG) .AND. (CDCON:=POSICIONE("SE4",1,XFILIAL("SE4")+ALLTRIM(CCONDPAG),"E4_DESCRI"))  SIZE 030,8 PIXEL OF OSCR 

//@ 033+NLIN,095 SAY OEMTOANSI("TP. NAVEGACAO"      ) SIZE 50,8 PIXEL OF OSCR
//@ 041+NLIN,095 MSCOMBOBOX ONAVEG VAR CNAVEG ITEMS ANAVEG WHEN !LGERADO SIZE 080, 05 OF OSCR PIXEL

//@ 033+NLIN,282 SAY OEMTOANSI("DIR. NAVEGAÇÃO"      ) SIZE 50,8 PIXEL OF OSCR
//@ 041+NLIN,282 MSCOMBOBOX ODIRNAV VAR CDIRNAV ITEMS ADIRNAV WHEN !LGERADO SIZE 080, 05 OF OSCR PIXEL

@ 033+NLIN,282 SAY OEMTOANSI(STR0034 ) SIZE 50,8 PIXEL OF OSCR //"DESC.COND.PAGTO"
@ 041+NLIN,282 MSGET ODCON  VAR CDCON    PICTURE "@!" SIZE 100,8 WHEN .F. PIXEL OF OSCR


@ 052+NLIN,005 SAY OEMTOANSI(STR0035   ) SIZE 50,8 PIXEL OF OSCR //"REMETENTE"
@ 060+NLIN,005 MSGET OCODREM  VAR CCODREM	 WHEN !LGERADO VALID FNOME("1",CCODREM,CLOJREM) PICTURE "@!" F3 'SA1' SIZE 50,8 PIXEL OF OSCR //VALID GRVODLGNO1(CCODREM)
@ 060+NLIN,055 MSGET OLOJREM  VAR CLOJREM	 WHEN !LGERADO VALID FNOME("1",CCODREM,CLOJREM) PICTURE "@!" SIZE 030,8 PIXEL OF OSCR
@ 060+NLIN,100 MSGET ODESREM  VAR CDESREM	 PICTURE "@!" SIZE 176,8 WHEN .F. PIXEL OF OSCR  
                                                                    

//@ 052+NLIN,282 SAY OEMTOANSI("PLACA CAVALO"   ) SIZE 50,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER]
//@ 060+NLIN,282 MSGET OPLACCAV  VAR CPLACCAV	 WHEN !LGERADO PICTURE "@R !!!-9999" SIZE 30,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER]

//@ 071+NLIN,282 SAY OEMTOANSI("PLACA CARRETA"   ) SIZE 50,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER]
//@ 079+NLIN,282 MSGET OPLACCAR  VAR CPLACCAR	 WHEN !LGERADO PICTURE "@R !!!-9999" SIZE 30,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER]

//@ 088+NLIN,282 SAY OEMTOANSI("NOME MOTORISTA"   ) SIZE 50,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER]
//@ 097+NLIN,282 MSGET ONOMMOT  VAR CNOMMOT	 WHEN !LGERADO PICTURE "@!" SIZE 100,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER]


@ 071+NLIN,005 SAY OEMTOANSI(STR0036   ) SIZE 50,8 PIXEL OF OSCR //"DETINATARIO"
@ 079+NLIN,005 MSGET OCODDES  VAR CCODDES	 WHEN !LGERADO VALID FNOME("2",CCODDES,CLOJDES) .AND. REGRA() PICTURE "@!" F3 'SA1' SIZE 50,8 PIXEL OF OSCR //VALID GRVODLGNO2(CCODDES)
@ 079+NLIN,055 MSGET OLOJDES  VAR CLOJDES	 WHEN !LGERADO VALID FNOME("2",CCODDES,CLOJDES) PICTURE "@!" SIZE 030,8 PIXEL OF OSCR
@ 079+NLIN,100 MSGET ODESDES  VAR CDESDES	 PICTURE "@!" SIZE 176,8 WHEN .F. PIXEL OF OSCR

@ 088+NLIN,005 SAY OEMTOANSI(STR0037   ) SIZE 50,8 PIXEL OF OSCR //"CONSIGNATARIO"
@ 097+NLIN,005 MSGET OCODCON  VAR CCODCON	 WHEN !LGERADO VALID FNOME("3",CCODCON,CLOJCON) PICTURE "@!"  F3 'SA1' SIZE 50,8 PIXEL OF OSCR //VALID GRVODLGNO3(CCODCON)
@ 097+NLIN,055 MSGET OLOJCON  VAR CLOJCON	 WHEN !LGERADO VALID FNOME("3",CCODCON,CLOJCON) PICTURE "@!" SIZE 030,8 PIXEL OF OSCR
@ 097+NLIN,100 MSGET ODESCON  VAR CDESCON	 PICTURE "@!" SIZE 176,8 WHEN .F. PIXEL OF OSCR

@ 110+NLIN,005 SAY OEMTOANSI(STR0038       ) SIZE 50,8 PIXEL OF OSCR //"CIDADE ORIGEM"
@ 110+NLIN,109 SAY OEMTOANSI(STR0039                  ) SIZE 16,8 PIXEL OF OSCR //"UF"
@ 110+NLIN,175 SAY OEMTOANSI(STR0040      ) SIZE 50,8 PIXEL OF OSCR //"CIDADE DESTINO"
@ 110+NLIN,282 SAY OEMTOANSI(STR0039                  ) SIZE 16,8 PIXEL OF OSCR //"UF"
@ 110+NLIN,320 SAY OEMTOANSI(STR0041                 ) SIZE 16,8 PIXEL OF OSCR COLOR CLR_HBLUE     //"TES"
@ 110+NLIN,360 SAY OEMTOANSI(STR0042                 ) SIZE 16,8 PIXEL OF OSCR COLOR CLR_HBLUE //"CFOP"

@ 118+NLIN,005 MSGET OORI     VAR CORI     	WHEN !LGERADO PICTURE "@!" SIZE 100,8 PIXEL OF OSCR VALID !EMPTY(CORI)
@ 118+NLIN,109 MSGET OORIUF   VAR CORIUF   	WHEN !LGERADO PICTURE "@!" SIZE 014,8 PIXEL OF OSCR F3 "12" VALID EXISTCPO("SX5","12"+CORIUF) .AND. !EMPTY(CORIUF)
@ 118+NLIN,175 MSGET ODES     VAR CDES     	WHEN !LGERADO PICTURE "@!" SIZE 100,8 PIXEL OF OSCR VALID !EMPTY(CDES)
@ 118+NLIN,282 MSGET ODESUF   VAR CDESUF   	WHEN !LGERADO PICTURE "@!" SIZE 014,8 PIXEL OF OSCR F3 "12" VALID !EMPTY(CDESUF) .AND. EXISTCPO("SX5","12"+CDESUF) 
@ 118+NLIN,320 MSGET OTES     VAR CTES     	F3 "SF4" WHEN !LGERADO VALID VLDTES() SIZE 014,8 PIXEL OF OSCR						// VLDTES(CTES) 
@ 118+NLIN,360 MSGET OCFOP    VAR CCFOP   	WHEN !LGERADO VALID !EMPTY(CCFOP) SIZE 014,8 PIXEL OF OSCR

@ 130+NLIN,005 SAY OEMTOANSI(STR0043       ) SIZE 50,8 PIXEL OF OSCR //"COD.MUNIC.ORIGEM"
@ 130+NLIN,175 SAY OEMTOANSI(STR0044      ) SIZE 50,8 PIXEL OF OSCR //"COD.MUNIC.DESTINO"
@ 138+NLIN,005 MSGET OCODORI  VAR CCODORI  	F3 "CC2" WHEN !LGERADO PICTURE "@!" SIZE 100,8 PIXEL OF OSCR VALID !EMPTY(CCODORI)
@ 138+NLIN,175 MSGET OCODFIM  VAR CCODFIM 	F3 "CC2" WHEN !LGERADO PICTURE "@!" SIZE 100,8 PIXEL OF OSCR VALID !EMPTY(CCODFIM)

//@ 130+NLIN,320 SAY OEMTOANSI("TES AFRMM"       ) SIZE 50,8 PIXEL OF OSCR
//@ 130+NLIN,360 SAY OEMTOANSI("CFOP AFRMM"      ) SIZE 50,8 PIXEL OF OSCR
//@ 138+NLIN,320 MSGET OTES2  VAR CTES2  	F3 "SF4" WHEN !LGERADO VALID VLDTES() PICTURE "@!" SIZE 014,8 PIXEL OF OSCR 		// VLDTES(CTES2) 
//@ 138+NLIN,360 MSGET OCFOP2 VAR CCFOP2 	WHEN !LGERADO VALID !EMPTY(CCFOP2) .OR. CTPTRA == '1'  PICTURE "@!" SIZE 014,8 PIXEL OF OSCR 

//155;170;185
                                    
//NVALESTAD:=NCARDES:=NVALESCOL:=NVALPEDAG:=NVALSCOM:=NVALCCOM
// ########## 1 COLUNA ###########
@ 155+NLIN,005 SAY OEMTOANSI(STR0045   ) SIZE 50,8 PIXEL OF OSCR  //"VALOR ESTÁDIA"
@ 155+NLIN,045 MSGET OVALESTAD  VAR NVALESTAD  PICTURE "@E 999,999,999.99"   WHEN !LGERADO SIZE 046,8 PIXEL OF OSCR

@ 170+NLIN,005 SAY OEMTOANSI(STR0046  ) SIZE 50,8 PIXEL OF OSCR //"CARGA/DESCARGA"
@ 170+NLIN,045 MSGET OCARDES  VAR NCARDES     PICTURE "@E 999,999,999.99"  WHEN !LGERADO SIZE 046,8 PIXEL OF OSCR

@ 185+NLIN,005 SAY OEMTOANSI(STR0047  ) SIZE 50,8 PIXEL OF OSCR //"VALOR ESCOLTA"
@ 185+NLIN,045 MSGET OVALESCOL  VAR NVALESCOL     PICTURE "@E 999,999,999.99"  WHEN !LGERADO SIZE 046,8 PIXEL OF OSCR

// ########## 2 COLUNA ###########
@ 155+NLIN,150 SAY OEMTOANSI(STR0048    ) SIZE 50,8 PIXEL OF OSCR //"VALOR PEDÁGIO"
@ 155+NLIN,195 MSGET OVALPEDAG VAR NVALPEDAG    WHEN LVER .AND. !LGERADO PICTURE "@E 999,999,999.99"  SIZE 046,8 PIXEL OF OSCR

@ 170+NLIN,150 SAY OEMTOANSI(STR0049 ) SIZE 50,8 PIXEL OF OSCR //"VAL. S/ COMIS."
@ 170+NLIN,195 MSGET OVALSCOM VAR NVALSCOM    PICTURE "@E 999,999,999.99" WHEN !LGERADO SIZE 046,8 PIXEL OF OSCR

@ 155+NLIN,300 SAY OEMTOANSI(STR0050 ) SIZE 50,8 PIXEL OF OSCR //"VALOR CONTAINER"
@ 155+NLIN,350 MSGET OVALCONTAINER VAR NVALCONTAINER PICTURE "@E 999,999,999.99" WHEN !LGERADO SIZE 046,8 PIXEL OF OSCR

@ 170+NLIN,300 SAY OEMTOANSI(STR0051 ) SIZE 50,8 PIXEL OF OSCR //"DESCONT COMIS."
@ 170+NLIN,350 MSGET ODESCCOMV VAR NDESCCOMV    PICTURE "@E 999,999,999.99" WHEN .F. SIZE 046,8 PIXEL OF OSCR

@ 185+NLIN,150 SAY OEMTOANSI(STR0052 ) SIZE 50,8 PIXEL OF OSCR //"VAL. C/ COMIS."
@ 185+NLIN,195 MSGET OVALCCOM VAR NVALCCOM    PICTURE "@E 999,999,999.99" WHEN !LGERADO SIZE 046,8 PIXEL OF OSCR

@ 185+NLIN,300 SAY OEMTOANSI(STR0053 ) SIZE 50,8 PIXEL OF OSCR //"FRETE "
IF EMPTY(FQ5->FQ5_TPCTRC)
	@ 185+NLIN,350 MSGET OFRETEPAUX VAR NFRETEPAUX    PICTURE "@E 999,999,999.99" WHEN !LGERADO VALID IIF(EMPTY(FQ5->FQ5_TPCTRC),(FCALCTOTAL(NVLINF,1) ) .AND. !EMPTY(NFRETEPAUX),.T.) SIZE 046,8 PIXEL OF OSCR
ELSE
	@ 185+NLIN,350 MSGET OFRETEPAUX VAR NFRETEPAUX    PICTURE "@E 999,999,999.99" WHEN !LGERADO VALID IIF(FQ5->FQ5_TPCTRC $ "1",(FCALCTOTAL(NVLINF,1) ) ,.T.) SIZE 046,8 PIXEL OF OSCR
ENDIF

// ########## 1 COLUNA ###########
@ 200+NLIN,005 SAY OEMTOANSI(STR0054   ) SIZE 50,8 PIXEL OF OSCR COLOR CLR_BLUE //"FRETE PESO"
//@ 155+NLIN,045 MSGET OFRETEP  VAR NFRETEP  PICTURE "@E 9,999,999.99"  WHEN NFRETEP == 0 VALID (FCALCTOTAL(NVLINF,1)) .AND. !EMPTY(NFRETEP) SIZE 046,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER]
//@ 155+NLIN,045 MSGET OFRETEP  VAR NFRETEP  PICTURE "@E 9,999,999.99"   WHEN !LGERADO VALID (!EMPTY(NFRETEP) .OR. !EMPTY(FQ5->FQ5_CTRORI)) .OR. (FCALCTOTAL(NVLINF,1)) SIZE 046,8 PIXEL OF OFOLDER:ADIALOGS[NFOLDER]
@ 200+NLIN,045 MSGET OFRETEP  VAR NFRETEP  PICTURE "@E 999,999,999.99"   WHEN .F. VALID IIF(EMPTY(FQ5->FQ5_TPCTRC) .OR. FQ5->FQ5_TPCTRC $ "1",(FCALCTOTAL(NVLINF,1) ) .AND. !EMPTY(NFRETEP),.T.) SIZE 046,8 PIXEL OF OSCR

@ 215+NLIN,005 SAY OEMTOANSI(STR0055  ) SIZE 50,8 PIXEL OF OSCR //"FRETE VALOR"
@ 215+NLIN,045 MSGET OVALADV  VAR NVALADV     PICTURE "@E 999,999,999.99"  WHEN !LGERADO VALID FCALCTOTAL(NVLINF,2) SIZE 046,8 PIXEL OF OSCR

@ 230+NLIN,005 SAY OEMTOANSI(STR0056  ) SIZE 50,8 PIXEL OF OSCR //"TOTAL FRETE"
@ 230+NLIN,045 MSGET OFRETET  VAR NFRETET     PICTURE "@E 9999,999,999.99"  WHEN .F. VALID FCALCTOTAL(NVLINF,2) SIZE 046,8 PIXEL OF OSCR

// ########## 2 COLUNA ###########
@ 200+NLIN,150 SAY OEMTOANSI(STR0057    ) SIZE 50,8 PIXEL OF OSCR //"ALIQ ICMS"
@ 200+NLIN,195 MSGET OALIQICM VAR NALIQICM    WHEN LVER .AND. !LGERADO PICTURE "@E 999,999,999.99"  VALID FCALCTOTAL(NVLINF,2) SIZE 046,8 PIXEL OF OSCR

@ 215+NLIN,150 SAY OEMTOANSI(STR0058 ) SIZE 50,8 PIXEL OF OSCR //"% AD-VALOREM"
//@ 215+NLIN,195 MSGET OALIQADV VAR NALIQADV    PICTURE "@E 999,999,999.999" WHEN !LGERADO VALID FCALCTOTAL(NVLINF,2) SIZE 046,8 PIXEL OF OSCR
@ 215+NLIN,195 MSGET OALIQADV VAR NALIQADV    PICTURE "@E 999,999,999.999" WHEN !LGERADO VALID FCALCTOTAL(NVLINF,1) SIZE 046,8 PIXEL OF OSCR

@ 230+NLIN,150	CHECKBOX OCHK VAR LDESTICM WHEN !LGERADO PROMPT STR0059 SIZE 70, 10 OF OSCR //"DESTACA ICMS NA N.F."
               
// ########## 3 COLUNA ###########
@ 200+NLIN,300 SAY OEMTOANSI(STR0060   ) SIZE 50,8 PIXEL OF OSCR //"VALOR ICMS"
@ 200+NLIN,350 MSGET OVALICM  VAR NVALICM     WHEN LVER .AND. !LGERADO PICTURE "@E 999,999,999.99"  VALID FCALCTOTAL(NVLINF,2) SIZE 046,8 PIXEL OF OSCR

@ 215+NLIN,300 SAY OEMTOANSI(STR0061    ) SIZE 50,8 PIXEL OF OSCR //"BASE ICMS"
@ 215+NLIN,350 MSGET OBASEICM VAR NBASEICM    WHEN LVER .AND. !LGERADO PICTURE "@E 9,999,999.99"  VALID FCALCTOTAL(NVLINF,2) SIZE 046,8 PIXEL OF OSCR

@ 230+NLIN,300 SAY OEMTOANSI(STR0062  ) SIZE 50,8 PIXEL OF OSCR //"BASE AD-VAL"
//@ 230+NLIN,350 MSGET OBASEADV VAR NBASEADV    PICTURE "@E 999,999,999.99"  WHEN !LGERADO VALID FCALCTOTAL(NVLINF,2) SIZE 046,8 PIXEL OF OSCR
@ 230+NLIN,350 MSGET OBASEADV VAR NBASEADV    PICTURE "@E 999,999,999.99"  WHEN !LGERADO VALID FCALCTOTAL(NVLINF,1) SIZE 046,8 PIXEL OF OSCR

//@ 200+NLIN,300 SAY OEMTOANSI("VAL. AFRMM"  ) SIZE 50,8 PIXEL OF OSCR
//@ 200+NLIN,350 MSGET OAFRMM  VAR NAFRMM     PICTURE "@E 9999,999,999.99"  WHEN !LGERADO SIZE 046,8 PIXEL OF OSCR

//@ 215+NLIN,300 SAY OEMTOANSI("COD. IRIN"  ) SIZE 50,8 PIXEL OF OSCR
//@ 215+NLIN,350 MSGET OCODIRI     VAR CCODIRI     	WHEN !LGERADO PICTURE "@!" SIZE 70,8 PIXEL OF OSCR

@ 245+NLIN,005 SAY  OEMTOANSI(STR0063      ) SIZE 50,8 PIXEL OF OSCR //"OBS.CTR"
@ 255+NLIN,005 GET OOBSCONTR VAR COBSCONTR    WHEN !LGERADO MEMO SIZE 230,170 PIXEL OF OSCR


OCLI:SETFOCUS()

RETURN NIL



// ======================================================================= \\
STATIC FUNCTION FCALCTOTAL(LTOTAL,NX)  //CALCULA O FRETE
// ======================================================================= \\

IF EMPTY(FQ5->FQ5_CTRORI) .OR. FQ5->FQ5_TPCTRC $ "1"
	DBSELECTAREA("SF4")
	DBSETORDER(1)                       
	IF !EMPTY(CTES)
	   MSSEEK(XFILIAL("SF4") + CTES )
	   IF NX==1 	   	   			   

		ADDVALOR()

	   	 IF LEN(ACALC) == 2
	   	 	IF NFRETEP == ACALC[2]
	   	 		LTOTAL := ACALC[1]
	   	 	ELSE
	   	 		LTOTAL = NFRETEP
	   	 		ACALC	:=	{}
	   	 		AADD(ACALC,NFRETEP)
	   	 	ENDIF
	   	 ELSE
		   	AADD(ACALC,NFRETEP)
	   	 	LTOTAL = NFRETEP
	   	 ENDIF
	   	
      //	LTOTAL:=FQ5->FQ5_VLRINF
      //	IF LTOTAL == 0 .OR. LTOTAL > NFRETEP
	      
	      //ENDIF
	//      NFRETEP := 0
	//      NVALADV := 0 
	//      NBASEICM:= 0 
	//      NVALICM := 0 
	//      NPERICM := 0 
	   ENDIF     

	   IF SF4->F4_LFICM == "T" .OR. SF4->F4_LFICM == "O"   
	      IF NX==1

			_NVALDIF := (NBASEADV * (NALIQADV/100)) / (1-(NALIQICM / 100))	// ANTIGO FRETE VALOR
			_NVALDIF -= NBASEADV * (NALIQADV/100)							// NOVO   FRETE VALOR

//			LTOTAL += _NVALDIF												// SOMAMOS A DIFERENÇA NO FRETE PESO

	         NFRETEP := LTOTAL / (1-(NALIQICM / 100))
	         NFRETEP += _NVALDIF
          ENDIF
//	      NVALADV := (NBASEADV * (NALIQADV/100)) / (1-(NALIQICM / 100))		// RETIRA-SE O ICMS DO AD-VALOREM - CRISTIAM ROSSI EM 26/01/2016 - SOLICITANTE CAUÊ
	      NVALADV := NBASEADV * (NALIQADV/100)
	      NBASEICM:=(NFRETEP+NVALADV)    
	      NVALICM := NBASEICM * (NALIQICM/100)
	      IF SF4->F4_LFICM == "T"
	         LDESTICM:= .T.
	      ENDIF    
	   ELSE
	      NVALADV := (NBASEADV * (NALIQADV/100)) 
	      NBASEICM:= 0
	      NVALICM := 0
	      NPERICM := 0
	   ENDIF

	   NPERADV := NVALADV / NBASEADV * 100
	   IF     CTPTRA == "3" .AND. CNAVEG = "0" 
		   NAFRMM :=  NFRETEP * 0.4
	   ELSEIF CTPTRA == "3" .AND. CNAVEG = "1" 
		   NAFRMM :=  NFRETEP * 0.1
	   ENDIF

	   NFRETET:=NFRETEP+NVALADV+NAFRMM
	   OFRETEP:REFRESH()
	   OFRETET:REFRESH()  
	   IF LEN(ALLTRIM(COBSCONTR)) == 0
	   	VEROBS(CTES,NVALICM,NFRETET-NVALICM)
	   ENDIF
	ELSE
	   MSGALERT(STR0064 , STR0015)  //"ATENÇÃO... TES NÃO FOI DIGITADA"###"GPO - LOCT004.PRW"
	   IF NFRETEP==0
	      NFRETEP:=1
	   ENDIF   
	   OTES:SETFOCUS()
	ENDIF  
	OBASEICM:REFRESH()
	OALIQICM:REFRESH()
	OVALICM:REFRESH()
	OBASEADV:REFRESH()
	OALIQADV:REFRESH()
	OVALADV:REFRESH()
	OFRETEP:REFRESH()
	OFRETET:REFRESH()  
	OOBSCONTR:REFRESH()
	OFOLDER:REFRESH()
ENDIF

IF	LEN(ACALC) == 1 
	AADD(ACALC,NFRETEP)
ENDIF

RETURN(.T.)



/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±ÉÍÍÍÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍ»±±
±±ºPROGRAMA  ³FGRAVATUDO º AUTOR ³ MICROSIGA          º DATA ³ 23/04/2008 º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºDESCRICAO ³                                                            º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºUSO       ³ ESPECIFICO GPO                                             º±±
±±ÈÍÍÍÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß
*/
STATIC FUNCTION FGRAVATUDO(NPOSCOLS,ACOLS,AHEADER)

LOCAL NPOS,CCAMPO

FOR NPOS:=1 TO LEN(AHEADER)
	IF !AHEADER[NPOS,8]=="XXM"  //8=TIPO
		CCAMPO := AHEADER[NPOS,2] 
		(ALIAS())->(&CCAMPO):=ACOLS[NPOSCOLS,NPOS]
	ENDIF
NEXT

RETURN(.T.)



/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±ÉÍÍÍÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍ»±±
±±ºPROGRAMA  ³ LOCFLEG   º AUTOR ³ IT UP BUSINESS     º DATA ³ 26/04/2008 º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºDESCRICAO ³ LEGENDA C.T.R.C                                            º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºUSO       ³ ESPECIFICO GPO                                             º±±
±±ÈÍÍÍÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß
*/
STATIC FUNCTION LOCFLEG()

BRWLEGENDA(CCADASTRO,'LEGENDA',{{'BR_VERMELHO' , 'C.T.R.C - GERADO'   },;
                                {'BR_VERDE'    , 'VIAGEM SEM C.T.R.C' }} )

RETURN(.T.)



// ======================================================================= \\
STATIC FUNCTION VALIDNOT()
// ======================================================================= \\

LOCAL NX   := 0
LOCAL LRET := .T.

LOCAL CCLIAUX,CLOJAUX,CPLAAUX  //VW

FOR NX := 1 TO LEN(ODLGNOT:ACOLS)
	IF EMPTY(GDFIELDGET("DTC_CLIDEV", NX , .F., ODLGNOT:AHEADER, ODLGNOT:ACOLS))
		MSGALERT(STR0065 , STR0015)  //"OBRIGATORIAMENTE DEVE SER INFORMADO O CÓDIGO DO DEVEDOR. VERIFIQUE!"###"GPO - LOCT004.PRW"
		LRET := .F.
		EXIT
	ENDIF
	
	IF EMPTY(GDFIELDGET("DTC_TIPNFC", NX , .F., ODLGNOT:AHEADER, ODLGNOT:ACOLS))
		MSGALERT(STR0066 , "GPO - LOCT004.PRW")  //"OBRIGATORIAMENTE DEVE SER INFORMADO O TIPO DE NOTA FISCAL!"
		LRET := .F.
		EXIT
	ENDIF
	
	IF EMPTY(GDFIELDGET("DTC_NUMNFC", NX , .F., ODLGNOT:AHEADER, ODLGNOT:ACOLS))
		MSGALERT(STR0067 , "GPO - LOCT004.PRW") //"OBRIGATORIAMENTE DEVE SER INFORMADO A NF CLIENTE!"
		LRET := .F.
		EXIT
	ENDIF 
	
	IF EMPTY(GDFIELDGET("DTC_DPROD", NX , .F., ODLGNOT:AHEADER, ODLGNOT:ACOLS)) .AND. EMPTY(FQ5->FQ5_TPCTRC)//SÓ QUANDO FOR CTRC NORMAL, E NÃO COMPLEMENTAR.
		MSGALERT(STR0068 , "GPO - LOCT004.PRW")  //"OBRIGATORIAMENTE DEVE SER INFORMADO A DESCRIÇÃO DO PRODUTO!"
		LRET := .F.
		EXIT
	ENDIF

	IF EMPTY(GDFIELDGET("DTC_XCODOP", NX , .F., ODLGNOT:AHEADER, ODLGNOT:ACOLS))  //VW
		CCLIAUX := GDFIELDGET("DTC_CLICON", NX , .F., ODLGNOT:AHEADER, ODLGNOT:ACOLS)
		CLOJAUX := GDFIELDGET("DTC_LOJCON", NX , .F., ODLGNOT:AHEADER, ODLGNOT:ACOLS)
		IF !EMPTY(CCLIAUX)
			// removido na 94
			//CPLAAUX:=POSICIONE("SA1",1,XFILIAL("SA1") + CCLIAUX + CLOJAUX,"A1_XCODPL")
			//IF !EMPTY(CPLAAUX)
			//	MSGALERT("OBRIGATORIAMENTE DEVE SER INFORMADA A OPERACAO VW!" , "GPO - LOCT004.PRW")
			//	LRET := .F.
			//	EXIT
			//ENDIF
		ENDIF
	ENDIF 
NEXT NX

RETURN LRET



// ======================================================================= \\
STATIC FUNCTION VALIDCDPG()
// ======================================================================= \\

LOCAL LRET := .T.

IF LEN(CCONDPG) == 0
	MSGALERT(STR0069 , "GPO - LOCT004.PRW")  //"OBRIGATORIAMENTE DEVE SER INFORMADO A CONDIÇÃO DE PAGAMENTO. VERIFIQUE!"
	LRET := .F.
ENDIF                            

RETURN LRET



// ======================================================================= \\
STATIC FUNCTION FNOME(COPC,CVAR1,CVAR2)
// ======================================================================= \\

LOCAL CEST		
LOCAL LESTRANG	

IF COPC == "1"
	CDESREM := POSICIONE("SA1",1,XFILIAL("SA1") + CVAR1 + CVAR2 , "A1_NOME" )
ELSEIF  COPC == "2"
	CDESDES := POSICIONE("SA1",1,XFILIAL("SA1") + CVAR1 + CVAR2 , "A1_NOME" )
ELSEIF COPC == "3"
	CDESCON := POSICIONE("SA1",1,XFILIAL("SA1") + CVAR1 + CVAR2 , "A1_NOME" )		
	IF !EMPTY(CCFOP)	
		CEST		:=	POSICIONE('SA1',1,XFILIAL('SA1')+CCODCON+CLOJCON,"A1_EST")
		LESTRANG	:=	POSICIONE('SA1',1,XFILIAL('SA1')+CCODCON+CLOJCON,"A1_TIPO") == 'X'
		DO CASE		      
		CASE CEST == GETMV("MV_ESTADO") .AND. !LESTRANG
			CCFOP	:=	'5'+SUBSTR(CCFOP,2,3)
		CASE LESTRANG
			CCFOP	:=	'7'+SUBSTR(CCFOP,2,3)
		OTHERWISE
			CCFOP	:=	'6'+SUBSTR(CCFOP,2,3)
		ENDCASE
		OCFOP:REFRESH()
	ENDIF
ENDIF

ODESREM:REFRESH()
ODESDES:REFRESH()
ODESCON:REFRESH()

RETURN .T.



// ======================================================================= \\
STATIC FUNCTION VERIMP(CTES)
// ======================================================================= \\

DBSELECTAREA("SF4")
DBSETORDER(1)
MSSEEK(XFILIAL("SF4") + CTES )
IF SF4->F4_LFICM == "T"  .OR. SF4->F4_LFICM == "O" 
	LVER:=.T.
ELSE
	LVER:=.F.
ENDIF  

ODLG:REFRESH()

RETURN .T.



// ======================================================================= \\
STATIC FUNCTION REGRA()
// ======================================================================= \\

NPOSCODD  := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_CLIDEV"})
NPOSLOJD  := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_LOJDEV"})
NPOSDEV   := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_NOMDEV"})

//IF      CTIPO == "2" .AND. CCODREM+CLOJREM <> CCODCLI+CLOJA .AND. CCODDES+CLOJDES <> CCODCLI+CLOJA
	CCODCON := CCODCLI
	CLOJCON := CLOJA
	CDESCON := POSICIONE("SA1",1,XFILIAL("SA1") + CCODCLI + CLOJA , "A1_NOME")

//ELSEIF CTIPO == "1" .AND. CCODREM+CLOJREM == CCODCLI+CLOJA
 //	ODLGNOT:ACOLS[ODLGNOT:OBROWSE:NAT][1] := CCODCLI
 //	ODLGNOT:ACOLS[ODLGNOT:OBROWSE:NAT][2] := CLOJA
 //	ODLGNOT:ACOLS[ODLGNOT:OBROWSE:NAT][3] := POSICIONE("SA1",1,XFILIAL("SA1") + CCODCLI + CLOJA , "A1_NOME")
	
//ELSEIF  CTIPO == "2" .AND. CCODREM+CLOJREM <> CCODCLI+CLOJA .AND. CCODDES+CLOJDES == CCODCLI+CLOJA
	ODLGNOT:ACOLS[ODLGNOT:OBROWSE:NAT][NPOSCODD] := CCODCLI
	ODLGNOT:ACOLS[ODLGNOT:OBROWSE:NAT][NPOSLOJD] := CLOJA
	ODLGNOT:ACOLS[ODLGNOT:OBROWSE:NAT][NPOSDEV]  := POSICIONE("SA1",1,XFILIAL("SA1") + CCODCLI + CLOJA , "A1_NOME")

//ENDIF

ODLG:REFRESH()

RETURN .T. 



// ======================================================================= \\
STATIC FUNCTION VEROBS(CTES,NVAL1,NVAL2)
// ======================================================================= \\

LOCAL AAREAANT := GETAREA()
LOCAL CRET     := ""   

COBSCONTR      := ""
DBSELECTAREA("SF4")
DBSETORDER(1) 

IF DBSEEK(XFILIAL("SF4")+CTES)
	IF !EMPTY(F4_FORMULA)  
		COBSCONTR := FORMULA(F4_FORMULA)
	//	+"* VALOR DO ICMS "+TRANSFORM(NVAL1,"@E 999,999.99")+"* VALOR A PAGAR "+TRANSFORM(NVAL2,"@E 999,999.99")  
   	ENDIF
ENDIF
//OOBSCONTR:REFRESH()

RESTAREA(AAREAANT)

RETURN CRET                   



// ======================================================================= \\
STATIC FUNCTION DTQCOMP() 
// ======================================================================= \\
// GERO UMA VIAGEM COMPLEMENTAR PARA EMITIR UM CTRC COMPLEMENTAR

LOCAL NAREADTQ := FQ5->(GETAREA())
LOCAL NRECDTQ  := FQ5->(RECNO())
LOCAL CCTRC1   := FQ5->FQ5_NUMCTR
LOCAL CVIAGEM1 := FQ5->FQ5_VIAGEM
LOCAL CSOT     := FQ5->FQ5_SOT
LOCAL COBRA    := FQ5->FQ5_OBRA
LOCAL CTIPCTRC := ""	

IF EMPTY(FQ5->FQ5_NUMCTR) .OR. FQ5->FQ5_NUMCTR = "-"
	MSGALERT(STR0070 + CHR(13) + ; //"SÓ É PERMITIDO A GERAÇÃO DE CTRC COMPLEMENTAR"
		     STR0071 , STR0015) //"PARA DOCUMENTOS (CTRC) JÁ GERADOS NO SISTEMA."###"GPO - LOCT004.PRW"
	RESTAREA(NAREADTQ)
	RETURN(.F.)
ELSEIF !EMPTY(FQ5->FQ5_CTRDES)
 /*	MSGALERT("CTRC JÁ POSSUI COMPLEMENTO GERADO NA VIAGEM " + FQ5->FQ5_CTRDES + "." + CHR(13) + ;
	         "VOCÊ SÓ PODE GERAR CTRC COMPLEMENTAR PARA A MESMA." , "GPO - LOCT004.PRW") 
	RESTAREA(NAREADTQ)
	RETURN(.F.) */
ENDIF 

IF !EMPTY(FQ5->FQ5_TPCTRC) //SE DIFERENTE, É CTRC COMPLEMENTAR,E NÃO PODE GERAR COMPLEMENTO DO COMPLEMENTO.
	MSGALERT(STR0070 + CHR(13) + ; //"SÓ É PERMITIDO A GERAÇÃO DE CTRC COMPLEMENTAR"
		     STR0072 , STR0015) //"PARA DOCUMENTOS (CTRC) ORIGEM."###"GPO - LOCT004.PRW"
	RESTAREA(NAREADTQ)
	RETURN(.F.)
ENDIF

CTIPCTRC := CRIACBOBOX()

IF !MSGYESNO(STR0073 + CVIAGEM1 + " ?" , "GPO - LOCT004.PRW")  //"CONFIRMA A GERAÇÃO DE UM CTRC COMPLEMENTAR PARA A VIAGEM "
	RESTAREA(NAREADTQ)
	RETURN(.F.)
ENDIF

BEGIN TRANSACTION

CVIAGEM := GETSX8NUM("FQ5", "FQ5_VIAGEM" )

IF  LOCA00108("FQ5",1,"FQ5_FILIAL+FQ5_VIAGEM",XFILIAL("FQ5")+CVIAGEM1,{{"FQ5_VIAGEM",CVIAGEM},;
                                                                        {"FQ5_PERADV",0},;
                                                                        {"FQ5_VLRINF",0},;
                                                                        {"FQ5_VALADV",0},;
                                                                        {"FQ5_DATGER",DDATABASE},;
                                                                        {"FQ5_HORGER",SUBSTR(TIME(),1,2)+SUBSTR(TIME(),4,2)},;
                                                                        {"FQ5_NUMCTR",""},;
                                                                        {"FQ5_SERCTR",""},;
                                                                        {"FQ5_ENCERR","1"},;
                                                                        {"FQ5_OBSCTR",STR0074 + CCTRC1 + ", VIAGEM " + CVIAGEM1},; //"COMPLEMENTAR AO CTRC NUMERO "
                                                                        {"FQ5_NUMPV" ,""},;
                                                                        {"FQ5_NUMCTC",""},;
                                                                        {"FQ5_FORCTC",""},;
                                                                        {"FQ5_LOJCTC",""},;
                                                                        {"FQ5_NOMCTC",""},;
                                                                        {"FQ5_NTCLI" ,""},;
                                                                        {"FQ5_VALCAR",0},;
                                                                        {"FQ5_CONHEC",""},;
                                                                        {"FQ5_OBSCTB",""},;
                                                                        {"FQ5_OBSCOM",""},;
                                                                        {"FQ5_NUMSLD",""},;
                                                                        {"FQ5_TPCTRC",CTIPCTRC},;
                                                                        {"FQ5_CTRDES",""},;
                                                                        {"FQ5_CTRORI",CVIAGEM1}})	// DUPLICA O REGISTRO DA TABELA INFORMADA
    /*LOCA00108("DTC",9,"DTC_FILIAL+DTC_VIAGEM",XFILIAL("DTC")+CVIAGEM1,{{ADUPLDTC},;            //NAO ESTAVA FUNCIONANDO POR CAUSA DO INDICE
    																	{"DTC_DOC"   ,""},;
    																	{"DTC_SERIE" ,""},;
    																	{"DTC_VIAGEM",CVIAGEM}})*/	//DUPLICA O REGISTRO DA TABELA INFORMADA  
    				 
    GETDTCDUPL(CSOT,COBRA,CVIAGEM1,CVIAGEM) //DUPLICA DTC

	_CCHAVE := "DTR_FILIAL+DTR_SOT+DTR_OBRA+DTR_VIAGEM"

	// TRATATIVA POIS TEM DIVERGENCIA NO XFILIAL CARREGA 2 SENDO QUE É 4
	CFIL := (XFILIAL('DTR'))  
	IF LEN(ALLTRIM(CFIL)) = 2
		CFIL := CFILANT 
	ENDIF 
			
    LOCA00108("DTR" , 7 , _CCHAVE , CFIL+CSOT+COBRA+CVIAGEM1 ,  {{"DTR_VIAGEM",CVIAGEM},;
                                                                  {"DTR_INSRET",0},;
                                                                  {"DTR_VALFRE",0},;
                                                                  {"DTR_VALPDG",0},;
                                                                  {"DTR_ADIFRE",0},;
                                                                  {"DTR_SLDREC",0},;
                                                                  {"DTR_DTVENC",CTOD("//")},;
                                                                  {"DTR_IRPF",0},;
                                                                  {"DTR_INSS",0},;
                                                                  {"DTR_DATA",CTOD("//")}})	//DUPLICA O REGISTRO DA TABELA INFORMADA
	CONFIRMSX8()
	RESTAREA(NAREADTQ)
	FQ5->(DBGOTO(NRECDTQ))
	RECLOCK("FQ5", .F. )
	FQ5_CTRDES := CVIAGEM
	MSUNLOCK()
	MSGINFO(STR0075 + CVIAGEM + STR0076 , STR0015) //"CTRC COMPLEMENTAR GERADO COM SUCESSO ! VIAGEM "###" GERADA."###"GPO - LOCT004.PRW"
ELSE
	ROLLBACKSX8()
	RESTAREA(NAREADTQ)
	FQ5->(DBGOTO(NRECDTQ))
	MSGINFO(STR0077 , STR0015)  //"CTRC COMPLEMENTAR NÃO FOI GERADO ! "###"GPO - LOCT004.PRW"
ENDIF

RESTAREA(NAREADTQ)
FQ5->(DBGOTO(NRECDTQ))

END TRANSACTION

RETURN 



/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±ÉÍÍÍÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍ»±±
±±ºPROGRAMA  ³ PESQZLE   º AUTOR ³ IT UP BUSINESS     º DATA ³ 15/02/2011 º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºDESCRICAO ³ EFETUA A ATUALIZAÇÃO DOS DADOS CONFORME PROGRAMAÇÃO DIARIA º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºUSO       ³ OPERACIONAL (TRANSP04-AVATAR)                              º±±
±±ÈÍÍÍÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß
*/
/*	// --> NÃO EXISTE CHAMADA NESTE FONTE.
STATIC FUNCTION PESQZLE(CPAR)

LOCAL CRET := CPAR

DBSELECTAREA(CALIASTMP)
DBGOTOP()

DO CASE 
CASE VALTYPE(CPAR) == "CARRETA"
   	CRET := POSICIONE("ST9",1,XFILIAL("ST9")+(CALIASTMP)->FPM_FROTA,"T9_PLACA")
CASE VALTYPE(CPAR) == "CAVALO" .AND. PCOUNT() <> 2
	CRET := POSICIONE("ST9",1,XFILIAL("ST9")+(CALIASTMP)->FPM_FROTA1,"T9_PLACA")
OTHERWISE
	CRET := SPACE(08)
ENDCASE

RETURN CRET
*/



/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±ÉÍÍÍÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍ»±±
±±ºPROGRAMA  ³ CHGLINNOT º AUTOR ³ IT UP BUSINESS     º DATA ³ 12/06/2012 º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºDESCRICAO ³                                                            º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºUSO       ³ ESPECIFICO GPO                                             º±±
±±ÈÍÍÍÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß
*/
STATIC FUNCTION CHGLINNOT()

LOCAL NPOSREM  := 0, NPOSCODR := 0, NPOSLOJR := 0 
LOCAL NPOSDES  := 0, NPOSCODM := 0, NPOSLOJM := 0 
LOCAL NPOSCON  := 0, NPOSCODC := 0, NPOSLOJC := 0 
LOCAL NPOSDEV  := 0, NPOSCODD := 0, NPOSLOJD := 0 
LOCAL NPOSTIPF := 0, NPOSCFOP := 0,	NPOSVALOR:=	0, NPOSTOMA:= 0
LOCAL NPOSCTEA := 0, NPOSDPCE := 0, NPOSTIPA := 0
LOCAL NPOSSERD := 0, NPOSCTRD := 0, NPOSCLID := 0
LOCAL NPOSNOMD := 0

NPOSCODR    := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_CLIREM"})
NPOSLOJR    := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_LOJREM"})
NPOSREM     := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_NOMREM"})

NPOSCODM    := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_CLIDES"})
NPOSLOJM    := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_LOJDES"})
NPOSDES     := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_NOMDES"})

NPOSCODC    := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_CLICON"})
NPOSLOJC    := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_LOJCON"})
NPOSCON     := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_NOMCON"})

NPOSCODD    := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_CLIDEV"})
NPOSLOJD    := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_LOJDEV"})
NPOSDEV     := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_NOMDEV"})

NPOSTIPF    := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_TIPFRE"})

IF DTC->(FIELDPOS("DTC_TOMADO")) > 0
	NPOSTOMA    := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_TOMADO"})
ENDIF

NPOSCFOP    := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_CF"})

NPOSVALOR   := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_VALOR"}) 

NPOSCTEA    := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_CTEANT"})
NPOSDPCE    := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_DPCEMI"})
NPOSTIPA    := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_TIPANT"})
NPOSSERD    := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_SERDPC"})
NPOSCTRD    := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_CTRDPC"})

NPOSCLID    := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_CLIDPC"})
NPOSLOJD    := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_LOJDPC"})
NPOSNOMD    := ASCAN(ODLGNOT:AHEADER,{|X| ALLTRIM(X[2]) == "DTC_NOMDPC"})

IF LEN(ODLGNOT:ACOLS) > 1 .AND. ODLGNOT:OBROWSE:NAT > 1

	ODLGNOT:ACOLS[ODLGNOT:OBROWSE:NAT][NPOSCODR] := ODLGNOT:ACOLS[(ODLGNOT:OBROWSE:NAT-1)][NPOSCODR]
	ODLGNOT:ACOLS[ODLGNOT:OBROWSE:NAT][NPOSLOJR] := ODLGNOT:ACOLS[(ODLGNOT:OBROWSE:NAT-1)][NPOSLOJR]
	ODLGNOT:ACOLS[ODLGNOT:OBROWSE:NAT][NPOSREM]  := ODLGNOT:ACOLS[(ODLGNOT:OBROWSE:NAT-1)][NPOSREM]

	ODLGNOT:ACOLS[ODLGNOT:OBROWSE:NAT][NPOSCODM] := ODLGNOT:ACOLS[(ODLGNOT:OBROWSE:NAT-1)][NPOSCODM]
	ODLGNOT:ACOLS[ODLGNOT:OBROWSE:NAT][NPOSLOJM] := ODLGNOT:ACOLS[(ODLGNOT:OBROWSE:NAT-1)][NPOSLOJM]
	ODLGNOT:ACOLS[ODLGNOT:OBROWSE:NAT][NPOSDES]  := ODLGNOT:ACOLS[(ODLGNOT:OBROWSE:NAT-1)][NPOSDES]

	ODLGNOT:ACOLS[ODLGNOT:OBROWSE:NAT][NPOSTIPF] := ODLGNOT:ACOLS[(ODLGNOT:OBROWSE:NAT-1)][NPOSTIPF]

	IF NPOSTOMA > 0
		ODLGNOT:ACOLS[ODLGNOT:OBROWSE:NAT][NPOSTOMA] := ODLGNOT:ACOLS[(ODLGNOT:OBROWSE:NAT-1)][NPOSTOMA]
	ENDIF

	ODLGNOT:ACOLS[ODLGNOT:OBROWSE:NAT][NPOSCODD] := ODLGNOT:ACOLS[(ODLGNOT:OBROWSE:NAT-1)][NPOSCODD]
	ODLGNOT:ACOLS[ODLGNOT:OBROWSE:NAT][NPOSLOJD] := ODLGNOT:ACOLS[(ODLGNOT:OBROWSE:NAT-1)][NPOSLOJD]
	ODLGNOT:ACOLS[ODLGNOT:OBROWSE:NAT][NPOSDEV]  := ODLGNOT:ACOLS[(ODLGNOT:OBROWSE:NAT-1)][NPOSDEV]

	ODLGNOT:ACOLS[ODLGNOT:OBROWSE:NAT][NPOSCODC] := ODLGNOT:ACOLS[(ODLGNOT:OBROWSE:NAT-1)][NPOSCODC]
	ODLGNOT:ACOLS[ODLGNOT:OBROWSE:NAT][NPOSLOJC] := ODLGNOT:ACOLS[(ODLGNOT:OBROWSE:NAT-1)][NPOSLOJC]
	ODLGNOT:ACOLS[ODLGNOT:OBROWSE:NAT][NPOSCON]  := ODLGNOT:ACOLS[(ODLGNOT:OBROWSE:NAT-1)][NPOSCON]

	ODLGNOT:ACOLS[ODLGNOT:OBROWSE:NAT][NPOSCFOP]  := ODLGNOT:ACOLS[(ODLGNOT:OBROWSE:NAT-1)][NPOSCFOP]
	
	ODLGNOT:ACOLS[ODLGNOT:OBROWSE:NAT][NPOSCTEA] := ODLGNOT:ACOLS[(ODLGNOT:OBROWSE:NAT-1)][NPOSCTEA]
	ODLGNOT:ACOLS[ODLGNOT:OBROWSE:NAT][NPOSDPCE] := ODLGNOT:ACOLS[(ODLGNOT:OBROWSE:NAT-1)][NPOSDPCE]
	ODLGNOT:ACOLS[ODLGNOT:OBROWSE:NAT][NPOSTIPA] := ODLGNOT:ACOLS[(ODLGNOT:OBROWSE:NAT-1)][NPOSTIPA]
	ODLGNOT:ACOLS[ODLGNOT:OBROWSE:NAT][NPOSSERD] := ODLGNOT:ACOLS[(ODLGNOT:OBROWSE:NAT-1)][NPOSSERD]
	ODLGNOT:ACOLS[ODLGNOT:OBROWSE:NAT][NPOSCTRD] := ODLGNOT:ACOLS[(ODLGNOT:OBROWSE:NAT-1)][NPOSCTRD]
	
	ODLGNOT:ACOLS[ODLGNOT:OBROWSE:NAT][NPOSCLID] := ODLGNOT:ACOLS[(ODLGNOT:OBROWSE:NAT-1)][NPOSCLID]
	ODLGNOT:ACOLS[ODLGNOT:OBROWSE:NAT][NPOSLOJD] := ODLGNOT:ACOLS[(ODLGNOT:OBROWSE:NAT-1)][NPOSLOJD]
	ODLGNOT:ACOLS[ODLGNOT:OBROWSE:NAT][NPOSNOMD] := ODLGNOT:ACOLS[(ODLGNOT:OBROWSE:NAT-1)][NPOSNOMD]
						
ENDIF

ODLGNOT:OBROWSE:REFRESH()

RETURN 



/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±ÉÍÍÍÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍ»±±
±±ºPROGRAMA  ³ CHGLINVEI º AUTOR ³ IT UP BUSINESS     º DATA ³ 12/06/2012 º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºDESCRICAO ³                                                            º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºUSO       ³ ESPECIFICO GPO                                             º±±
±±ÈÍÍÍÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß
*/
STATIC FUNCTION CHGLINVEI()

LOCAL NPOSCOD  := 0, NPOSNOME := 0

NPOSCOD     := ASCAN(ODLGVEI:AHEADER,{|X| ALLTRIM(X[2]) == "DTR_CODMOT"})
NPOSNOME    := ASCAN(ODLGVEI:AHEADER,{|X| ALLTRIM(X[2]) == "DTR_NOMMOT"}) 

IF LEN(ODLGVEI:ACOLS) > 1 .AND. ODLGVEI:OBROWSE:NAT > 1
	ODLGVEI:ACOLS[ODLGVEI:OBROWSE:NAT][NPOSCOD] 	:= ODLGVEI:ACOLS[(ODLGVEI:OBROWSE:NAT-1)][NPOSCOD]
	ODLGVEI:ACOLS[ODLGVEI:OBROWSE:NAT][NPOSNOME] 	:= ODLGVEI:ACOLS[(ODLGVEI:OBROWSE:NAT-1)][NPOSNOME]
ENDIF

ODLGVEI:OBROWSE:REFRESH()

RETURN



/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±ÉÍÍÍÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍ»±±
±±ºPROGRAMA  ³ VLDLINNOT º AUTOR ³ IT UP BUSINESS     º DATA ³ 12/07/2012 º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºDESCRICAO ³                                                            º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºUSO       ³ ESPECIFICO GPO                                             º±±
±±ÈÍÍÍÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß
*/
FUNCTION LOCA04602()

LOCAL LRET
LOCAL CNFEID	:=	GDFIELDGET("DTC_NFEID" ,ODLGNOT:OBROWSE:NAT,.F.,ODLGNOT:AHEADER,ODLGNOT:ACOLS)
LOCAL CSERIE	:=	GDFIELDGET("DTC_SERNFC",ODLGNOT:OBROWSE:NAT,.F.,ODLGNOT:AHEADER,ODLGNOT:ACOLS)
LOCAL CNUMDOC	:=	GDFIELDGET("DTC_NUMNFC",ODLGNOT:OBROWSE:NAT,.F.,ODLGNOT:AHEADER,ODLGNOT:ACOLS)
LOCAL DEMISSAO	:=	GDFIELDGET("DTC_EMINFC",ODLGNOT:OBROWSE:NAT,.F.,ODLGNOT:AHEADER,ODLGNOT:ACOLS)
LOCAL NBASICM	:=	GDFIELDGET("DTC_BASICM",ODLGNOT:OBROWSE:NAT,.F.,ODLGNOT:AHEADER,ODLGNOT:ACOLS)
LOCAL NVALICM	:=	GDFIELDGET("DTC_VALICM",ODLGNOT:OBROWSE:NAT,.F.,ODLGNOT:AHEADER,ODLGNOT:ACOLS)
LOCAL NVALOR	:=	GDFIELDGET("DTC_VALOR" ,ODLGNOT:OBROWSE:NAT,.F.,ODLGNOT:AHEADER,ODLGNOT:ACOLS)
//LOCAL NBASST	:=	GDFIELDGET("DTC_BASESU",ODLGNOT:OBROWSE:NAT,.F.,ODLGNOT:AHEADER,ODLGNOT:ACOLS)
//LOCAL NVALST	:=	GDFIELDGET("DTC_VALIST",ODLGNOT:OBROWSE:NAT,.F.,ODLGNOT:AHEADER,ODLGNOT:ACOLS)

LOCAL CCODOPERAC:=	GDFIELDGET("DTC_XCODOP" ,ODLGNOT:OBROWSE:NAT,.F.,ODLGNOT:AHEADER,ODLGNOT:ACOLS)
LOCAL CCLIAUX	:=	GDFIELDGET("DTC_CLICON" ,ODLGNOT:OBROWSE:NAT,.F.,ODLGNOT:AHEADER,ODLGNOT:ACOLS)
LOCAL CLOJAUX	:=	GDFIELDGET("DTC_LOJCON" ,ODLGNOT:OBROWSE:NAT,.F.,ODLGNOT:AHEADER,ODLGNOT:ACOLS)
LOCAL CPLAAUX

IF !EMPTY(CNFEID)
	LRET := .T.
ELSE
	IF	!EMPTY(CSERIE) .AND. !EMPTY(CNUMDOC) .AND. !EMPTY(DEMISSAO) .AND. !EMPTY(NBASICM) .AND. !EMPTY(NVALICM) .AND. !EMPTY(NVALOR)
		LRET	:=	.T.
	ELSE
		AVISO(STR0078,STR0079,{"OK"}) //"ALERTA"###"CAMPOS REFERENTE A NOTA FISCAL DO CLIENTE NÃO PREENCHIDOS, FAVOR PREENCHER!"
		LRET := .F.
	ENDIF
ENDIF

IF LRET
	IF EMPTY(CCODOPERAC)  //VW
		IF !EMPTY(CCLIAUX)
			// removido na 94
			//CPLAAUX:=POSICIONE("SA1",1,XFILIAL("SA1") + CCLIAUX + CLOJAUX,"A1_XCODPL")
			//IF !EMPTY(CPLAAUX)
			//	MSGALERT("OBRIGATORIAMENTE DEVE SER INFORMADA A OPERACAO VW!" , "GPO - LOCT004.PRW")
			//	LRET := .F.
			//ENDIF
		ENDIF
	ENDIF 
ENDIF 

RETURN LRET



/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±ÉÍÍÍÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍ»±±
±±ºPROGRAMA  ³ ATUNFINFO º AUTOR ³ IT UP BUSINESS     º DATA ³ 01/09/2013 º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºDESCRICAO ³                                                            º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºUSO       ³ ESPECIFICO GPO                                             º±±
±±ÈÍÍÍÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß
*/
STATIC FUNCTION ATUNFINFO()

LOCAL CCAMPO	:=	REPLACE(REPLACE(READVAR(),'M->',''),'DTC->','')
LOCAL NAT		:=	ODLGNOT:OBROWSE:NAT

IF CCAMPO == 'DTC_VALOR'
	// ---- ATUALIZA BASEADV ---- //
	NBASEADV	:=	&(READVAR()) // RETORNA O VALOR INFORMADO NO CAMPO
                                                                  
	// RECUPERA A INFORMAÇÃO DAS OUTRAS LINHAS E INCREMENTA O VALOR DA BASEADV
	AEVAL(ODLGNOT:ACOLS,{|X,NLIN| IF( NAT == NLIN,,NBASEADV += GDFIELDGET("DTC_VALOR" ,NLIN,.F.,ODLGNOT:AHEADER,ODLGNOT:ACOLS) ) })
	
	// ATUALIZA OBJETO NA TELA
	OBASEADV:REFRESH()
	// ---- FIM ---- //
ENDIF
	
RETURN .T.



/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±ÉÍÍÍÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍ»±±
±±ºPROGRAMA  ³ ATUVEIINF º AUTOR ³ IT UP BUSINESS     º DATA ³ 01/09/2013 º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºDESCRICAO ³                                                            º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºUSO       ³ ESPECIFICO GPO                                             º±±
±±ÈÍÍÍÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß
*/
STATIC FUNCTION ATUVEIINF()

LOCAL CCAMPO	:=	REPLACE(REPLACE(READVAR(),'M->',''),'DTR->','')
LOCAL CCODIGO	
LOCAL CNOME		
	
	IF CCAMPO	==	"DTR_CODMOT"
		
		CCODIGO	:=	&(READVAR())
		CNOME	:=	POSICIONE("DA4",1,XFILIAL("DA4")+CCODIGO,"DA4_NOME")
		
		AEVAL(ODLGVEI:ACOLS,{|X,NLIN| GDFIELDPUT("DTR_CODMOT" ,CCODIGO ,NLIN,ODLGVEI:AHEADER,ODLGVEI:ACOLS,.F.), GDFIELDPUT("DTR_NOMMOT" ,CNOME ,NLIN,ODLGVEI:AHEADER,ODLGVEI:ACOLS,.F.)})
		ODLGVEI:OBROWSE:REFRESH()  
		
	ENDIF
	
RETURN .T.



/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±ÉÍÍÍÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍ»±±
±±ºPROGRAMA  ³ VLDTES    º AUTOR ³ IT UP BUSINESS     º DATA ³ 01/09/2013 º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºDESCRICAO ³                                                            º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºUSO       ³ ESPECIFICO GPO                                             º±±
±±ÈÍÍÍÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß
*/
STATIC FUNCTION VLDTES()

LOCAL LRET 		:= (EXISTCPO("SF4",CTES) .AND. !EMPTY(CTES) .AND. VAL(CTES) >= 500 .AND. VERIMP(CTES))
LOCAL CEST		
LOCAL LESTRANG	

IF LRET
	CCFOP		:= POSICIONE('SF4',1,XFILIAL('SF4')+CTES,'F4_CF')		
	CEST		:= POSICIONE('SA1',1,XFILIAL('SA1')+CCODCON+CLOJCON,"A1_EST")
	LESTRANG	:= POSICIONE('SA1',1,XFILIAL('SA1')+CCODCON+CLOJCON,"A1_TIPO") == 'X'
	
	IF CTPTRA == "3"
		CCFOP2  := POSICIONE('SF4',1,XFILIAL('SF4')+CTES2,'F4_CF')
		
		DO CASE		      
		CASE CEST == GETMV("MV_ESTADO") .AND. !LESTRANG
			CCFOP2	:=	'5'+SUBSTR(CCFOP2,2,3)
		CASE LESTRANG
			CCFOP2	:=	'7'+SUBSTR(CCFOP2,2,3)
		OTHERWISE
			CCFOP2	:=	'6'+SUBSTR(CCFOP2,2,3)
		ENDCASE
		
		OCFOP2:REFRESH()
	ENDIF 

	DO CASE		      
	CASE CEST == GETMV("MV_ESTADO") .AND. !LESTRANG
		CCFOP	:=	'5'+SUBSTR(CCFOP,2,3)
	CASE LESTRANG
		CCFOP	:=	'7'+SUBSTR(CCFOP,2,3)
	OTHERWISE
		CCFOP	:=	'6'+SUBSTR(CCFOP,2,3)
	ENDCASE
	
	OCFOP:REFRESH()
	
ENDIF

RETURN LRET



/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±ÉÍÍÍÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍ»±±
±±ºPROGRAMA  ³ VLDFROTA  º AUTOR ³ IT UP BUSINESS     º DATA ³ 25/02/2013 º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºDESCRICAO ³                                                            º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºUSO       ³ ESPECIFICO GPO                                             º±±
±±ÈÍÍÍÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß
*/
STATIC FUNCTION VLDFROTA()

LOCAL _NPOS      := 0 
LOCAL CRETORNO   := .T.
LOCAL CMOTORIS   := ""
//LOCAL CVEICULO := ""

// VERIFICA CADASTRO DA FROTA/VEICULO.
FOR _NPOS := 1 TO LEN(ODLGVEI:ACOLS) 	

 //	CVEICULO := ODLGVEI:ACOLS[_NPOS][ASCAN(ODLGVEI:AHEADER,{|X|ALLTRIM(X[2])=="DTR_CODVEI"})]
	CMOTORIS := ODLGVEI:ACOLS[_NPOS][ASCAN(ODLGVEI:AHEADER,{|X|ALLTRIM(X[2])=="DTR_CODMOT"})]  
	/*
	DBSELECTAREA("DA3")
	DBSETORDER(1)
	IF DBSEEK( XFILIAL("DA3") + CVEICULO )
		IF !EMPTY(DA3->DA3_RENAVA)
			IF LEN(DA3->DA3_RENAVA) < 9
		   		MSGALERT("CÓDIGO DO RENAVAM INVÁLIDO DA FROTA: " + CVEICULO , "GPO - LOCT004.PRW") 
		   		CRETORNO := .F.
			ENDIF
		ELSE
			MSGINFO("CADASTRE O RENAVAM DO VEICULO: " + CVEICULO)
			CRETORNO := .F.
		ENDIF
		IF EMPTY(DA3->DA3_TIPTRA)
			MSGINFO("CADASTRE O TIPO DE TRANSPORTE DO VEICULO: " + CVEICULO)
			CRETORNO := .F.
		ENDIF 
	ELSE
		MSGINFO("VERIFIQUE A FROTA DIGITADA: " + CVEICULO)
		CRETORNO := .F.
	ENDIF
*/	
	// VERIFICA CADASTRO DO MOTORISTA, SE O TIPO NÃO FOR MARITIMO
	IF FQ5->FQ5_TPAS != "M"
		DBSELECTAREA("DA4")
		DBSETORDER(1)
		IF DBSEEK( XFILIAL("DA4") + CMOTORIS ) 
			IF EMPTY(DA4->DA4_FORNEC)
				MSGALERT(STR0080 , STR0015) //"CODIGO DO FORNECEDOR NÃO AMARRADO NO CADASTRO DO MOTORISTA"###"GPO - LOCT004.PRW"
		   		CRETORNO := .F.
			ENDIF
			IF DA4->DA4_TIPMOT == "2" .AND. CRETORNO//VALIDA SE O MOTORISTA E TERCEIRO .AND. EXISTE CADASTRO
				DBSELECTAREA("SA2")
				DBSETORDER(1)
				IF DBSEEK( XFILIAL("SA2") + DA4->DA4_FORNEC )
					IF SA2->A2_MSBLQL == "1"
						MSGALERT(STR0081 + DA4->DA4_FORNEC , STR0015) //"CÓDIGO DO FORNECEDOR ESTÁ BLOQUEADO, POR FAVOR VERIFIQUE: "###"GPO - LOCT004.PRW"
						CRETORNO := .F.	
					ELSEIF EMPTY(SA2->A2_RNTRC)
						MSGALERT(STR0082 + DA4->DA4_FORNEC , STR0015)  //"O FORNECEDOR É TERCEIRO E NÃO TEM CADASTRO REGISTRO NACIONAL DE TRANSPORTADORES RODOVIÁRIOS DE CARGAS PREENCHIDO: "###"GPO - LOCT004.PRW"
						CRETORNO := .F.	
					ENDIF
				ELSE
					MSGALERT(STR0083 , STR0015) //"VERIFIQUE O FORNECEDOR CADASTRADO NO MOTORISTA, CODIGO NÃO EXISTE"###"GPO - LOCT004.PRW"
					CRETORNO := .F.
				ENDIF
			ENDIF
		ELSE
			MSGINFO(STR0084+CMOTORIS+STR0085 , STR0015)  //"MOTORISTA ["###"] NÃO POSSUI CADASTRO NA FILIAL !"###"GPO - LOCT004.PRW"
		ENDIF
	ENDIF

NEXT _NPOS 

RETURN CRETORNO



// ======================================================================= \\
STATIC FUNCTION CRIACBOBOX()
// ======================================================================= \\
// CRIAR PERGUNTA COM O TIPO DE COMPLEMENTO(VALOR OU ICMS)

LOCAL ACOMBO  := {} 
LOCAL CCOMBO  := ""
LOCAL NRESULT := SPACE(01)

DBSELECTAREA("SX3")
DBSETORDER(2)
IF DBSEEK("FQ5_TPCTRC")
	CCOMBO := X3CBOX()	
ENDIF 

ACOMBO := STRTOKARR(CCOMBO,";")
    
DEFINE MSDIALOG ODLGUSER TITLE STR0005 FROM 000,000 TO 150,300 PIXEL OF OMAINWND //"COMPLEMENTAR"
	@ 025,020 SAY STR0086 OF ODLGUSER PIXEL //"SELECIONE A OPÇÃO:"
 //	@ 025,025 SAY "SELECIONE A OPÇÃO:" SIZE 200,15 OF ODLGUSER		
	@ 035,020 COMBOBOX OCOMBO1 VAR NRESULT ITEMS ACOMBO SIZE 80,010 OF ODLGUSER PIXEL 
	@ 035,105 BUTTON STR0087 SIZE 35,14 PIXEL OF ODLGUSER ACTION (ODLGUSER:END()) //"CONFIRMAR"
		
 //	@ C(041),C(071) BUTTON "CANCELAR" SIZE C(037),C(012) PIXEL OF _ODLG ACTION (_ODLG:END())	 
 //	OCOMBO1:BCHANGE := {|| SELECTCOMBO(CRESULT) }
ACTIVATE MSDIALOG ODLGUSER CENTERED
	 
RETURN(NRESULT)



// ======================================================================= \\
STATIC FUNCTION GETDTCDUPL(CSOT , COBRA , CVIAGEM1 , CVIAGEM) 
// ======================================================================= \\

LOCAL AAREA    := GETAREA()
LOCAL AAREADTC
LOCAL ADTC     := {}
LOCAL NX       := 0 
      
DBSELECTAREA("DTC")
DBORDERNICKNAME("DTCIND10")
DBSEEK(IIF(LEN(ALLTRIM(XFILIAL("DTC")))==2 .AND. LEN(XFILIAL("DTC"))==4,CFILANT,XFILIAL("DTC")) + CSOT + COBRA + CVIAGEM1 )
WHILE !DTC->(EOF()) .AND. DTC->(DTC_FILIAL+DTC_SOT+DTC_OBRA+DTC_VIAGEM) == IIF(LEN(ALLTRIM(XFILIAL("DTC")))==2 .AND. LEN(XFILIAL("DTC"))==4,CFILANT,XFILIAL("DTC"))+ CSOT + COBRA + CVIAGEM1

	FOR NX := 1 TO DTC->(FCOUNT())		// ARMAZENO OS DADOS PARA DUPLICAR O REGISTRO
		AADD(ADTC, DTC->(FIELDGET(NX)))
	NEXT NX  
	
	AAREADTC	:= DTC->(GETAREA())																		
	RECLOCK("DTC",.T.)
	FOR NX := 1 TO DTC->(FCOUNT())
		DTC->(FIELDPUT(NX, ADTC[NX]))
	NEXT NX
	DTC->DTC_DOC 	:= ""
	DTC->DTC_SERIE	:= ""
	DTC->DTC_VIAGEM := CVIAGEM
	MSUNLOCK()
	RESTAREA(AAREADTC)
		
	DTC->(DBSKIP())
ENDDO

RESTAREA(AAREA)

RETURN



// ======================================================================= \\
STATIC FUNCTION ADDVALOR()
// ======================================================================= \\

LOCAL NVAL := NVALESTAD + NCARDES + NVALESCOL + NVALPEDAG + NVALSCOM + NVALCCOM
	               
//	IF NACUMUL <> NVAL 
//		NFRETEP += NVAL-NACUMUL
//		IF LEN(ACALC) > 0
//			ACALC[1] += NVAL-NACUMUL
//			NFRETEP += NVAL-NACUMUL//ACALC[1]
//			NACUMUL := NVAL			
//		ENDIF  
		NFRETEP := NFRETEPAUX + NVAL
		/*
		NFRETEP += NVALESTAD 
		NFRETEP += NCARDES 
		NFRETEP += NVALESCOL 
		NFRETEP += NVALPEDAG 
		NFRETEP += NVALSCOM 
		NFRETEP += NVALCCOM
		*/
    //	OFRETEP:REFRESH()
    //	OFOLDER:REFRESH()

RETURN(.T.)
