#INCLUDE "loca061.ch"  
/*/{PROTHEUS.DOC} LOCA061.PRW
ITUP BUSINESS - TOTVS RENTAL
CONECTA WEBSERVICE - LICENCIAMENTO - mantido para compatibilidade entre versões antigas
@TYPE FUNCTION
@AUTHOR FRANK ZWARG FUGA
@SINCE 03/12/2020
@VERSION P12
@HISTORY 03/12/2020, FRANK ZWARG FUGA, FONTE PRODUTIZADO.
/*/
#INCLUDE "PROTHEUS.CH"
#INCLUDE "TOPCONN.CH"
#INCLUDE "TBICONN.CH"

FUNCTION LOCA061(LMSGWS) 
/*
LOCAL AATUAREA := GETAREA() 
LOCAL ASM0AREA := SM0->(GETAREA()) 
LOCAL LRETOK   := .T. 
LOCAL CFILVALI := "\SYSTEM\SIGAGPO.EMP" 
LOCAL NOPENX   := 0 
LOCAL CBUFFER  := "" 
LOCAL LARQVALI := .T. 
LOCAL LTEMFINA := .F. 
LOCAL LDATVALI := .F. 
LOCAL CDESCNPJ := "" 
LOCAL CDESOKSN := "" 
LOCAL CDESDATA := "" 
LOCAL AEMPLIBE := {} 
LOCAL ARECNSM0 := {} 
LOCAL NZ       := 0 
LOCAL LTEMLICX := .T. 

PRIVATE CMSGALEINF := STR0001  //"GPO - LOCCWS01.PRW"

DEFAULT LMSGWS := .T. 

IF !FILE(CFILVALI) 							// --> SE ARQUIVO ARQUIVO NÃO EXISTE.
	// --> TENTA REALIZAR A ATUALIZAÇÃO DE LICENÇA VIA WS.
	LJMSGRUN( STR0002 , , {|| LOCA06101("SIGAGPO.EMP") , INKEY(5)} )  //"LICENCIAMENTO NÃO ENCONTRADO, AGUARDE ATUALIZAÇÃO..."
ENDIF 

IF FILE(CFILVALI) 

	NOPENX   := FT_FUSE(CFILVALI) 
	IF NOPENX = -1 							// --> NÃO CONSEGUIU ABRIR.
		IF LMSGWS
			MSGALERT(STR0003 , CMSGALEINF)  //"NÃO FOI POSSÍVEL ABRIR O ARQUIVO DE LICENCIAMENTO ! "
		ELSE 
			CONOUT(CMSGALEINF + STR0004)  //" - LICENCIAMENTO NÃO AUTORIZADO ! ARQUIVO INVÁLIDO OU CORROMPIDO ! "
		ENDIF 
		RETURN .F.  
	ENDIF 
	
	NLINHA := 1 
	
	WHILE !FT_FEOF()           				// --> LAÇO PRA VARRER TODOS AS LINHAS DO ARQUIVO HTML. 
		CBUFFER := FT_FREADLN() 

		IF NLINHA = 1 
			IF EMPTY(CBUFFER) 
				IF LMSGWS
					MSGALERT(STR0005 , CMSGALEINF)  //"LICENCIAMENTO NÃO AUTORIZADO ! ARQUIVO INVÁLIDO OU CORROMPIDO ! "
				ELSE 
					CONOUT(CMSGALEINF + STR0004)  //" - LICENCIAMENTO NÃO AUTORIZADO ! ARQUIVO INVÁLIDO OU CORROMPIDO ! "
				ENDIF 
				LARQVALI := .F. 
				EXIT 
			ENDIF 
			IF RC4CRYPT( SUBSTR(CBUFFER,02,9) + SUBSTR(CBUFFER,12,9) + SUBSTR(CBUFFER,22,1) , "123456789" , .F. ) <> STR0006 	//  $…3B$9°€#ÄÕSÕBKDÂ!Ë <=> #LICENCIAMENTO GPO# (EMBARALHADO COM "$"[01] "#"[11] "!"[20])        …3B$9°€ÄÕSÕBKDÂË <=> #LICENCIAMENTO GPO# (ORIGINAL)  //"#LICENCIAMENTO GPO#"
				IF LMSGWS 
					MSGALERT(STR0007 , CMSGALEINF)  //"LICENCIAMENTO NÃO AUTORIZADO ! ARQUIVO INVÁLIDO OU CORROMPIDO !!"
				ELSE 
					CONOUT(CMSGALEINF + STR0008)  //" - LICENCIAMENTO NÃO AUTORIZADO ! ARQUIVO INVÁLIDO OU CORROMPIDO !!"
				ENDIF 
				LARQVALI := .F. 
				EXIT 
			ENDIF 

		ELSEIF SUBSTR( RC4CRYPT(CBUFFER , "0" , .F.) , 01 , 18) = STR0009								//  «9ÏÎ‚7ÔCQß£& 3ÌÈ%ÞDW4‡»ß  <=>  #FINAL DE ARQUIVO#20190520# //"#FINAL DE ARQUIVO#"
			LTEMFINA := .T. 
			EXIT 

		ELSE 
			IF RC4CRYPT( SUBSTR(CBUFFER,09,8)+SUBSTR(CBUFFER,01,8) , "123456789" , .F. , .T.) <> STR0010 		//  0B6D48FA178A1471 <=> #CNPJ: # (EMBARALHADO)     178A14710B6D48FA <=> #CNPJ: # (ORIGINAL)  //"#CNPJ: #"
				IF LMSGWS 
					MSGALERT(STR0007 , CMSGALEINF)  //"LICENCIAMENTO NÃO AUTORIZADO ! ARQUIVO INVÁLIDO OU CORROMPIDO !!"
				ELSE
					CONOUT(CMSGALEINF + STR0008)  //" - LICENCIAMENTO NÃO AUTORIZADO ! ARQUIVO INVÁLIDO OU CORROMPIDO !!"
				ENDIF 
				LARQVALI := .F. 
				EXIT 
			ENDIF  
			CDESOKSN := RC4CRYPT( SUBSTR(CBUFFER,47,3)+SUBSTR(CBUFFER,51,2) , "123456789" , .F.) 					//  #SIM# <=> šLB    #NÃO# <=> ‡NB
			IF .NOT. CDESOKSN $ "#SIM#|#NAO#"
				IF LMSGWS 
					MSGALERT(STR0011 , CMSGALEINF)  //"LICENCIAMENTO NÃO AUTORIZADO ! ARQUIVO INVÁLIDO OU CORROMPIDO !!!"
				ELSE 
					CONOUT(CMSGALEINF + STR0012)  //" - LICENCIAMENTO NÃO AUTORIZADO ! ARQUIVO INVÁLIDO OU CORROMPIDO !!!"
				ENDIF 
				LARQVALI := .F. 
				EXIT 
			ENDIF 
			IF RC4CRYPT( SUBSTR(CBUFFER,61,8)+SUBSTR(CBUFFER,53,8) , "123456789" , .F. , .T.) <> "#DATA: #" 		//  006D48FA178D1B75 <> "#DATA#" (EMBARALHADO)        178D1B75006D48FA <=> "#DATA#" (ORIGINAL) 
				IF LMSGWS 
					MSGALERT(STR0013 , CMSGALEINF)  //"LICENCIAMENTO NÃO AUTORIZADO ! ARQUIVO INVÁLIDO OU CORROMPIDO !!!!"
				ELSE
					CONOUT(CMSGALEINF + STR0013)  //"LICENCIAMENTO NÃO AUTORIZADO ! ARQUIVO INVÁLIDO OU CORROMPIDO !!!!"
				ENDIF 
				LARQVALI := .F. 
				EXIT 
			ENDIF 

			CDESCNPJ := SUBSTR(RC4CRYPT( SUBSTR(CBUFFER,27,10)+SUBSTR(CBUFFER,37,10)+SUBSTR(CBUFFER,17,10) , "0" , .F. , .T.),1,14) 
			CDESDATA := RC4CRYPT( SUBSTR(CBUFFER,69,10) , "1234" , .F.) 
			IF .NOT. ( SUBSTR(CDESDATA,01,1) = "#"  .AND.  SUBSTR(CDESDATA,10,1) = "#" ) 
				IF LMSGWS 
					MSGALERT(STR0014 , CMSGALEINF)  //"LICENCIAMENTO NÃO AUTORIZADO ! ARQUIVO INVÁLIDO OU CORROMPIDO !!!!!"
				ELSE
					CONOUT(CMSGALEINF + STR0015)  //" - LICENCIAMENTO NÃO AUTORIZADO ! ARQUIVO INVÁLIDO OU CORROMPIDO !!!!!"
				ENDIF 
				LARQVALI := .F. 
				EXIT 
			ENDIF 
			IF LARQVALI					// --> O ARQUIVO ESTÁ VALIDO ! 
				IF CDESOKSN = "#SIM#" 
					AADD( AEMPLIBE , {CDESCNPJ , SUBSTR(CDESDATA,2,8)} ) 		// --> DATA NO ARQUIVO CRIPTOGRAFADO  (GPO OU GPF) 
				ENDIF 
			ENDIF 

		ENDIF 

		FT_FSKIP() 
		NLINHA := NLINHA + 1 
	ENDDO 

ELSE 
	IF LMSGWS 
		MSGALERT(STR0016 , CMSGALEINF)  //"LICENCIAMENTO NÃO AUTORIZADO ! ARQUIVO NÃO EXISTE !!!"
	ELSE
		CONOUT(CMSGALEINF + STR0017)  //" - LICENCIAMENTO NÃO AUTORIZADO ! ARQUIVO NÃO EXISTE !!!"
	ENDIF 	
	LRETOK := .F. 

ENDIF 

// --> FECHA O ARQUIVO HTML. 
FT_FUSE() 

DBSELECTAREA("SM0") 
SM0->(DBGOTOP()) 
WHILE !SM0->(EOF()) 
	// --> SÓ ADICIONA NO ARECNSM0 SE A EMPRESA FOR DIFERENTE.
	IF ASCAN( ARECNSM0 , {|X| X[2] == SM0->M0_CODIGO}) == 0  
		AADD( ARECNSM0 , {SM0->M0_CODIGO , SM0->M0_CGC} ) 
	ENDIF 
	SM0->(DBSKIP()) 
ENDDO 
RESTAREA(ASM0AREA) 

IF LTEMFINA .AND. LARQVALI 
	FOR NZ := 1 TO LEN(AEMPLIBE) 
		IF ASCAN( ARECNSM0 , {|X| X[2] == AEMPLIBE[NZ][1]}) <> 0 
			IF     STOD(AEMPLIBE[NZ][2]) - DATE() >= 0  .AND.  STOD(AEMPLIBE[NZ][2]) - DATE() <= 30 
				MSGALERT(STR0018+(ALLTRIM(STR(STOD(AEMPLIBE[NZ][2]) - DATE())))+STR0019 , CMSGALEINF)  //"FALTAM ["###"] DIAS PARA O VENCIMENTO DA LICENÇA DO GPO !!!"
				LJMSGRUN( STR0020 , , {|| LOCA06101("SIGAGPO.EMP") , INKEY(5)} )  //"LICENCIAMENTO PRESTES A VENCER, AGUARDE ATUALIZAÇÃO..."
				LDATVALI := .T. 
				EXIT 
			ELSEIF STOD(AEMPLIBE[NZ][2]) - DATE() >  30
				LDATVALI := .T. 
				EXIT 
			ELSEIF DATE() >= STOD(AEMPLIBE[NZ][2]) 
				LDATVALI := .F. 
				IF EMPTY(STOD(AEMPLIBE[NZ][2])) 
					LTEMLICX := .F. 
				ENDIF 
			ENDIF 
		ENDIF 
	NEXT NZ 
	IF ! LDATVALI 
		IF LMSGWS 
			IF LTEMLICX
				MSGALERT(STR0021 , CMSGALEINF)  //"LICENÇA DO GPO EXPIRADA !"
			ELSE 
				MSGALERT(STR0022   , CMSGALEINF)  //"EMPRESA NÃO POSSUI LICENÇA !"
			ENDIF 
		ELSE
			IF LTEMLICX
				CONOUT(CMSGALEINF + STR0023)  //" - LICENÇA DO GPO EXPIRADA !"
			ELSE 
				CONOUT(CMSGALEINF + STR0024)  //" - EMPRESA NAO POSSUI LICENÇA !"
			ENDIF 
		ENDIF 
		LJMSGRUN( STR0025 , , {|| LOCA06101("SIGAGPO.EMP") , INKEY(5)} )  //"LICENCIAMENTO EXPIRADO, AGUARDE ATUALIZAÇÃO..."
		LRETOK := .F. 
	ENDIF 
ELSE 
	LJMSGRUN( STR0026 , , {|| LOCA06101("SIGAGPO.EMP") , INKEY(5)} )  //"LICENCIAMENTO CORROMPIDO, AGUARDE ATUALIZAÇÃO..."
	LRETOK := .F. 
ENDIF 

RESTAREA(AATUAREA) 

RETURN LRETOK */
Return .T.



// ======================================================================= \\
FUNCTION LOCA06101(CARQ_WS) 
// ======================================================================= \\
// --> GERA O ARQUIVO ".EMP" CRIPTOGRAFADO COM OS DADOS DO LICENCIAMENTO.
/*
LOCAL OWS       := NIL 
LOCAL NY        := 0 
LOCAL CCNPJ     := SM0->M0_CGC 
LOCAL CRETWS_L  := ""

LOCAL AATUAREA  := GETAREA() 
LOCAL ASM0AREA  := SM0->(GETAREA()) 
LOCAL AEMPSCAD  := {} 							// --> EMPRESAS CONTIDAS NO SIGAMAT.EMP 
LOCAL AEMPSLIB  := {} 
LOCAL CTXTPRIN  := "" 
LOCAL CLIB_SN_  := "" 
LOCAL CLIB_CGC  := "" 

LOCAL CDIRETOR  := "\SYSTEM\" 
LOCAL CARQUIVO  := "" 
LOCAL NARQ 
LOCAL NQTD_FNT  := 0 
LOCAL CIPSRVCLI := GETSERVERIP() 

DEFAULT CARQ_WS := "SIGAGPO.EMP" 

CARQUIVO := CARQ_WS 

DBSELECTAREA("SM0") 
SM0->(DBGOTOP()) 
WHILE !SM0->(EOF()) 
	// --> SÓ ADICIONA NO AEMPSCAD SE A EMPRESA FOR DIFERENTE.
	IF ASCAN( AEMPSCAD , {|X| X[2] == SM0->M0_CODIGO}) == 0  
		AADD( AEMPSCAD , {SM0->M0_CODIGO , SM0->M0_CGC} ) 
	ENDIF 
	SM0->(DBSKIP()) 
ENDDO 
RESTAREA(ASM0AREA) 
RESTAREA(AATUAREA) 

OWS := WSWS_GERA_LIC():NEW() 

FOR NY := 1 TO LEN( AEMPSCAD ) 
	CCNPJ := AEMPSCAD[NY][2] 
	IF OWS:PESQUISAR( CCNPJ , ALLTRIM(STR(NQTD_FNT)) , CIPSRVCLI ) 
		CRETWS_L := OWS:OWSPESQUISARRESULT:CCRAZSOCI 
		IF SUBSTR(CRETWS_L,1,5) <> STR0027  //"ERRO:"
			AADD( AEMPSLIB , { SUBSTR(CRETWS_L,09,14)  , SUBSTR(CRETWS_L,36,01)  , SUBSTR(CRETWS_L,51,08)  , SUBSTR(CRETWS_L,73,08)  , SUBSTR(CRETWS_L,92,40)  } ) 
		ENDIF 
	ELSE 
		MSGALERT(STR0028 + GETWSCERROR())  //"OCORREU UM ERRO DE CONEXÃO AO WEBSERVICE: "
	ENDIF 
NEXT NY 

IF LEN(AEMPSLIB) > 0 
	CARQUIVO := CDIRETOR  +  CARQUIVO 			//  "\SYSTEM\"  +  "SIGAGPF.EMP" OU "SIGAGPO.EMP" 
	NARQ     := FCREATE(CARQUIVO , 0) 
	IF FERROR() <> 0  .OR.  NARQ < 0 
		MSGALERT(STR0029+CARQUIVO+"] !!")  //"ATENÇÃO: PROBLEMAS NA CRIAÇÃO DO ARQUIVO ["
		FCLOSE(NARQ)
		RETURN NIL
	ENDIF
	IF     CARQ_WS = "SIGAGPF.EMP" 				// --> GPF 
		CTXTPRIN := "$…3B$9°€#ÄÕSÕBKDË!Ë" 	//  $…3B$9°€#ÄÕSÕBKDË!Ë <=> #LICENCIAMENTO GPF# (EMBARALHADO COM "$"[01] "#"[11] "!"[20])        …3B$9°€ÄÕSÕBKDËË <=> #LICENCIAMENTO GPF# (ORIGINAL) 
	ELSEIF CARQ_WS = "SIGAGPO.EMP" 				// --> GPO 
		CTXTPRIN := "$…3B$9°€#ÄÕSÕBKDÂ!Ë" 	//  $…3B$9°€#ÄÕSÕBKDÂ!Ë <=> #LICENCIAMENTO GPO# (EMBARALHADO COM "$"[01] "#"[11] "!"[20])        …3B$9°€ÄÕSÕBKDÂË <=> #LICENCIAMENTO GPO# (ORIGINAL) 
	ENDIF 
	FWRITE( NARQ , CTXTPRIN + CRLF ) 
ENDIF 
NY := 0 
FOR NY := 1 TO LEN(AEMPSLIB) 
	CLIB_CGC := RC4CRYPT( AEMPSLIB[NY][1]+"F" , "0" , .T.) 
	CLIB_CGC := SUBSTR(CLIB_CGC,21,10)+SUBSTR(CLIB_CGC,01,10)+SUBSTR(CLIB_CGC,11,10)
	IF AEMPSLIB[NY][2] = "1" 					// NÃO ESTÁ LIBERADO	 	#SIM# <=> šLB    #NÃO# <=> ‡NB 
		CLIB_SN_ := "‡$NB"
	ELSE										// SIM ESTÁ LIBERADO 		#SIM# <=> šLB    #NÃO# <=> ‡NB 
		CLIB_SN_ := "š$LB"
	ENDIF 
	CTXTPRIN     := "0B6D48FA178A1471" 			// 0B6D48FA178A1471 <=> #CNPJ: # (EMBARALHADO)     178A14710B6D48FA <=> #CNPJ: # (ORIGINAL) 
	CTXTPRIN     += CLIB_CGC 
	CTXTPRIN     += CLIB_SN_
	CTXTPRIN     += "006D48FA178D1B75" 			// 006D48FA178D1B75 <=> #DATA#   (EMBARALHADO)     178D1B75006D48FA <=> #DATA#   (ORIGINAL) 
	IF CARQUIVO = "\SYSTEM\SIGAGPF.EMP" 		// --> GPF 
		CTXTPRIN += RC4CRYPT("#"+AEMPSLIB[NY][4]+"#" , "1234" , .F.) 						// AEMPSLIB[04] = VENCTO GPF  (A1_ZDATAGF) 
	ENDIF 
	IF CARQUIVO = "\SYSTEM\SIGAGPO.EMP" 		// --> GPO 
		CTXTPRIN += RC4CRYPT("#"+AEMPSLIB[NY][3]+"#" , "1234" , .F.) 						// AEMPSLIB[03] = VENCTO GPO  (A1_ZDATAGO)  
	ENDIF 
	FWRITE( NARQ , CTXTPRIN + CRLF ) 
NEXT NY 
IF LEN(AEMPSLIB) > 0 
	CTXTPRIN := RC4CRYPT(STR0009+DTOS(DATE())+"#" , "0" , .F.)					// «9ÏÎ‚7ÔCQß£& 3ÌÈ%ÞDW4‡»ß  <=>  #FINAL DE ARQUIVO#20190520# //"#FINAL DE ARQUIVO#"
	FWRITE( NARQ , CTXTPRIN + CRLF ) 
	FCLOSE(NARQ) 
ENDIF 
*/
RETURN 


/*
--> CNPJ 
CPNJ               CRIPTO ORIGINAL                   CRIPTO EMBARALHADO 
00299104000149F    B84F94B9FA4AE41304CFD245C55F18    D245C55F18B84F94B9FA4AE41304CF
14571987000109F    B94B93B7F242EC1004CFD245C15F18    D245C15F18B94B93B7F242EC1004CF
24188961000130F    BA4B97B8FB42E21604CFD245C25618    D245C25618BA4B97B8FB42E21604CF
24144874000180F    BA4B97B4F743E31304CFD245C95618    D245C95618BA4B97B4F743E31304CF
                   AAAAAAAAAABBBBBBBBBBCCCCCCCCCC    CCCCCCCCCCAAAAAAAAAABBBBBBBBBB
*/

/*
----------------                              ------                ----------
#CNPJ: # (FIXO)                               #SIM#                 #20190615#
----------------                              ------                ----------
         1         2         3         4         5         6         7
123456789012345678901234567890123456789012345678901234567890123456789012345678
0B6D48FA178A1471D245C55F18B84F94B9FA4AE41304CFš$LB006D48FA178D1B75&{AžÊÜ1<:8
                ------------------------------      ----------------
                N U M E R O     D O    C N P J      #DATA# (FIXO)
                ------------------------------      ----------------
*/
