/*/{PROTHEUS.DOC} LOCA069.PRW  
ITUP BUSINESS - TOTVS RENTAL
CALCULA O TOTAL DE ICMS POR LINHA
@TYPE FUNCTION
@AUTHOR FRANK ZWARG FUGA
@SINCE 03/12/2020
@VERSION P12
@HISTORY 03/12/2020, FRANK ZWARG FUGA, FONTE PRODUTIZADO.
/*/

FUNCTION LOCA069()
LOCAL NVALISS  := 0    
LOCAL CTPISS   := GDFIELDGET("ZA7_TPISS")       
LOCAL NPERCISS := GDFIELDGET("ZA7_PERISS")
LOCAL NXFRETE  := GDFIELDGET("ZA7_XFRETE")
LOCAL CFOCO    := READVAR()

DO CASE	
CASE CFOCO == "M->ZA7_TPISS"
	CTPISS   := M->ZA7_TPISS
CASE CFOCO == "M->ZA7_PERISS"
	NPERCISS := M->ZA7_PERISS 
CASE CFOCO == "M->ZA7_XFRETE"
	NXFRETE  := M->ZA7_XFRETE
END CASE

IF     CTPISS == "N"
	NVALISS := (NXFRETE / ((100-NPERCISS)/100)) - NXFRETE
ELSEIF CTPISS == "I"
	NVALISS := NXFRETE * (NPERCISS/100)  
ENDIF  

ACOLS[N][ASCAN(AHEADER,{|X|ALLTRIM(X[2])=="ZA7_VRISS"})] := NVALISS

RETURN .T.
