/*/{PROTHEUS.DOC} LOCA016.PRW  
ITUP BUSINESS - TOTVS RENTAL
@TYPE FUNCTION
@AUTHOR FRANK ZWARG FUGA
@SINCE 03/12/2020
@VERSION P12
@HISTORY 03/12/2020, FRANK ZWARG FUGA, FONTE PRODUTIZADO.
/*/

#INCLUDE "PROTHEUS.CH"
#INCLUDE "TOPCONN.CH"
#INCLUDE "PARMTYPE.CH"
/*
CONSULTORIA   : IT UP BUSINESS
DESENVOLVEDOR : IT UP BUSINESS
DESCRICAO     : RETORNA O CODIGO DO PRODUTO
CHAMADA(S)    : PLOC05102 / LOCT111
*/
FUNCTION LOCA016(CTOPPR) 
LOCAL CPROD := SPACE(1) 

IF MSFILE("SZ5"+CEMPANT+"0") 
	DBSELECTAREA("SZ5")
	DBSETORDER(1)
	IF SZ5->(DBSEEK(XFILIAL("SZ5")+CTOPPR)) 
		CPROD := SZ5->Z5_IT_PRD 
	ENDIF 
ENDIF 

RETURN CPROD 



/*
CONSULTORIA   : IT UP BUSINESS
DESENVOLVEDOR : IT UP BUSINESS
DESCRICAO     : RETORNA SE O USUARIOS DO USUARIO X ROTINA E SEUS ACESSOS.
PARAMETROS    : EXP1: USUARIO LOGADO
                EXP1: ROTINA DE ACESSO
                EXP2: CODIGO DE LIBERACAO
RETORNO       : AACESSO {USUARIO,ACESSOS}
*/
/*
// ======================================================================= \\
FUNCTION LOCA01601(_CUSER , CROTINA) 
// ======================================================================= \\
// --> NÃO EXISTE NENHUMA CHAMADA EM FONTE / CAMPO / MENU.
LOCAL 	AACESSOS := {}

DEFAULT	_CUSER   := RETCODUSR() 			// --> CASO NAO SEJA INFORMADO USUARIO O SISTEMA ASSUME O USUARIO LOGADO.

DBSELECTAREA("FQ1")
DBSETORDER(1)
IF FQ1->(DBSEEK(XFILIAL("FQ1") + _CUSER + CROTINA,.T.))
	AADD(AACESSOS,{_CUSER,CROTINA,ALLTRIM(FQ1->FQ1_CC)})
ENDIF

RETURN AACESSOS
*/



/*
CONSULTORIA   : IT UP BUSINESS
DESENVOLVEDOR : IT UP BUSINESS
DESCRICAO     : RETORNA SE O PEDIDO DE COMPRA ESTA BLOQUEADO
PARAMETROS    : EXP1: FILIAL
                EXP1: NUMERO DO PEDIDO DE COMPRA
RETORNO       : LRET => .T. PEDIDO DE COMPRA BLOQUEADO  |  F = PEDIDO DE COMPRA LIBERADO 
                NA TABELA SC7 PESQUISE PELO CAMPO C7_CONAPRO O CONTEÚDO VAI ESTAR COM "B" BLOQUEADO OU COMO "L" LIBERADO, 
                DESTA FORMA VOCÊ CONSEGUE SELECIONAR QUAIS PEDIDOS ESTÃO BLOQUEADOS OU LIBERADOS.
*/
/*
// ======================================================================= \\
FUNCTION LOCA01602(CASF) 
// ======================================================================= \\
// --> NÃO EXISTE NENHUMA CHAMADA EM FONTE / CAMPO / MENU - DESCONTINUADO

LOCAL LRET    := .F.
LOCAL CQUERY  := SPACE(1) 

DEFAULT CASF  := SPACE(1)

CQUERY:= " SELECT * FROM "+RETSQLNAME("SC1")+" SC1 WHERE SC1.D_E_L_E_T_ = '' AND C1_CLVL ='"+CASF+"'" 
TCQUERY CQUERY NEW ALIAS "C1TMP"

IF C1TMP->(!EOF())
	IF C1TMP->C1_PEDIDO == ''
		LRET := .T.
	ELSE
		CQUERY := " SELECT C7_CONAPRO "
		CQUERY += " FROM "+RETSQLNAME("SC7")+" SC7"
		CQUERY += " WHERE SC7.D_E_L_E_T_ = '' " 
		CQUERY += " 	AND C7_FILIAL 	= '"+C1TMP->C1_FILIAL+"'"
		CQUERY += " 	AND C7_NUM 		= '"+C1TMP->C1_PEDIDO+"'"
		CQUERY += " 	AND C7_CONAPRO 	= 'B'"
		TCQUERY CQUERY NEW ALIAS "C7TMP"
	
		IF C7TMP->(!EOF()) 			// CASO NAO ENCONTRE REGISTRO O PEDIDO NAO ESTA BLOQUEADO
			LRET := .T.
		ENDIF

		C7TMP->(DBCLOSEAREA())
	ENDIF
ENDIF

C1TMP->(DBCLOSEAREA())

RETURN LRET 
*/
