#INCLUDE "loca022.ch" 
/*/{PROTHEUS.DOC} LOCA022.PRW 
ITUP BUSINESS - TOTVS RENTAL
VALIDAÇÃO PARA BLOQUEAR ALTERAÇÃO DE TES CASO NÃO CONTROLE ESTOQUE SOMENTE PARA PRODUTOS ACESSORIOS
@TYPE FUNCTION
@AUTHOR FRANK ZWARG FUGA
@SINCE 03/12/2020
@VERSION P12
@HISTORY 03/12/2020, FRANK ZWARG FUGA, FONTE PRODUTIZADO.
/*/

#INCLUDE "PROTHEUS.CH"

FUNCTION LOCA022(CTIPO,CPRODUTO,CTES)
LOCAL LRET     := .T.
LOCAL AAREA    := GETAREA()
LOCAL AAREASA1 := SA1->(GETAREA())
LOCAL LVALIDA  := .T.
//CAL CPRODUTO := SB1->B1_COD 		// --> ALTERADO POR PARA PEGAR O CAMPO EM EDIÇÃO NA TELA

DBSELECTAREA("ST9")
ST9->(DBSETORDER(7)) 				// FILIAL+CODIGO ESTOQUE

DBSELECTAREA("SF4")
SF4->(DBSETORDER(1)) 				// FILIAL+CODIGO 
SF4->(DBSEEK(XFILIAL("SF4")+CTES))

/* 	// --> RETIRADO PARA TORNAR A ROTINA MAIS DINÂMICA.
IF    CTIPO == "E" 					// ENTRADA
	SF4->(DBSEEK(XFILIAL("SF4")+M->D1_TES))
 //	CPRODUTO := M->D1_COD 			// PEGAR O CAMPO EM EDIÇÃO NA TELA
ELSEIF CTIPO == "S" 				// SAIDA
	SF4->(DBSEEK(XFILIAL("SF4")+M->C6_TES))	
 //	CPRODUTO := M->C6_PRODUTO 		// PEGAR O CAMPO EM EDIÇÃO NA TELA
ENDIF  
*/

IF CTIPO == "S"
	LVALIDA := VALIDATES()
ENDIF

IF LVALIDA 							// SE VALIDA TES
	IF ST9->(DBSEEK(XFILIAL("ST9")+CPRODUTO))
		IF ST9->T9_TIPOSE == "A" 
			IF SF4->F4_ESTOQUE <> "S" 
				MSGALERT(STR0001 , STR0002)  //"PARA O PRODUTO ACESSÓRIO A TES DEVERÁ ATUALIZAR ESTOQUE, ALTERAR A TES INFORMADA"###"GPO - LCVREST.PRW"
				LRET := .F. 
			ENDIF 
		ENDIF 
	ENDIF 
ENDIF 

RESTAREA(AAREASA1) 
RESTAREA(AAREA) 

RETURN LRET           



// ======================================================================= \\
STATIC FUNCTION VALIDATES()
// ======================================================================= \\

LOCAL LRET := .F. 

DBSELECTAREA("SA1") 
DBSETORDER(1) 
DBSEEK(XFILIAL("SA1")+M->C5_CLIENTE) 

IF ALLTRIM(SA1->A1_CGC) <> ALLTRIM(SM0->M0_CGC) 	// SE CNPJ FOR DIFERENTE DO CNPJ DO SIGAMAT, FAZER VALIDAÇÃO.
	LRET := .T. 
ENDIF 
	
RETURN(LRET)
