/*/{PROTHEUS.DOC} LOCA067.PRW  
ITUP BUSINESS - TOTVS RENTAL
CALCULA O TOTAL DE ICMS POR LINHA EQUIPAMENTO
@TYPE FUNCTION
@AUTHOR FRANK ZWARG FUGA
@SINCE 03/12/2020
@VERSION P12
@HISTORY 03/12/2020, FRANK ZWARG FUGA, FONTE PRODUTIZADO.
/*/

FUNCTION LOCA067()
LOCAL NFRETEP := 0
LOCAL NTOTAL  := 0
LOCAL NVALICM := 0

NTOTAL  := ACOLS[N][ASCAN(AHEADER,{|X|ALLTRIM(X[2])=="FP4_VRSEGU"})]+ACOLS[N][ASCAN(AHEADER,{|X|ALLTRIM(X[2])=="FP4_VRHOR"})]+ACOLS[N][ASCAN(AHEADER,{|X|ALLTRIM(X[2])=="FP4_VLPEDA"})]
NFRETEP := NTOTAL/(1-(M->FP4_PERICM/100))
NVALICM := NFRETEP * (M->FP4_PERICM/100)
ACOLS[N][ASCAN(AHEADER,{|X|ALLTRIM(X[2])=="FP4_VRICMS"})]:=NVALICM

RETURN(.T.)
