#INCLUDE "loca009.ch" 
/*/{PROTHEUS.DOC} LOCA009.PRW
ITUP BUSINESS - TOTVS RENTAL
GERA REGISTROS NA ABA RESPONSABILIDADES
@TYPE FUNCTION
@AUTHOR FRANK ZWARG FUGA
@SINCE 03/12/2020
@VERSION P12
@HISTORY 03/12/2020, FRANK ZWARG FUGA, FONTE PRODUTIZADO.
/*/
#INCLUDE "TOTVS.CH"

FUNCTION LOCA009(CCAMPO)
LOCAL   AAREA     := GETAREA()
LOCAL   CBECH     := SPACE(3)
LOCAL   CALIASQRY := GETNEXTALIAS()
LOCAL   NFOUND    := 0
LOCAL   NPOS
LOCAL   CQUERY
LOCAL   NVALOR    := 0
LOCAL   CSEQRES   := "000"
LOCAL   CZABCAMPO := ""
LOCAL   AZABRESP  := {}

DEFAULT CCAMPO    := ""

DO CASE
CASE CCAMPO == "FP4_VLPEDA"
	CZABCAMPO := "PEDAGIO"
	NVALOR    := M->FP4_VLPEDA
	
CASE CCAMPO == "FP4_VRDES" 
	CZABCAMPO := "DESMOB"
	NVALOR    := M->FP4_VRDES
	
CASE CCAMPO == "FP4_VRMOB" 
	CZABCAMPO := "MOBILIZ"
	NVALOR    := M->FP4_VRMOB
	
OTHERWISE 
	MSGALERT(STR0001+CCAMPO+STR0002 , STR0003)  //"O CAMPO "###" NÃO TEM RELAÇÃO COM UMA RESPONSABILIDADE, VERIFIQUE!"###"GPO - GERARESP.PRW"
	RETURN .F.

ENDCASE

CQUERY := " SELECT FP7_CODIGO, FP7_DESCRI FROM " + RETSQLNAME("FP7")
CQUERY += " WHERE  FP7_FILIAL = '"+XFILIAL("FP7")+"'"
CQUERY += "   AND  UPPER(FP7_DESCRI) LIKE '%"+ CZABCAMPO +"%'"
CQUERY += "   AND  D_E_L_E_T_ = ' '"
DBUSEAREA(.T.,"TOPCONN",TCGENQRY(,, CQUERY), CALIASQRY,.F.,.T.)

IF (CALIASQRY)->( EOF() )
	(CALIASQRY)->( DBCLOSEAREA() )
	RESTAREA( AAREA )
	
	MSGALERT(STR0004+CZABCAMPO+STR0005 , STR0003) //"NÃO FOI ENCONTRADA RESPONSABILIDADE COM A DESCRIÇÃO "###", VERIFIQUE!"###"GPO - GERARESP.PRW"
	RETURN .F.
ENDIF

AZABRESP := (CALIASQRY)->( { FP7_CODIGO, FP7_DESCRI } )

(CALIASQRY)->(DBCLOSEAREA())

//FOBRA()

DO CASE
CASE FP0->FP0_TIPOSE == "E"			// EQUIPAMENTO
	CBECH := CSEQGUI
	
CASE FP0->FP0_TIPOSE == "T"			// TRANSPORTE
	CBECH := CSEQTRA
	
CASE FP0->FP0_TIPOSE == "L"			// LOCAÇÃO
	CBECH := CSEQGRU
ENDCASE

FOR NPOS := 1 TO LEN(ORES_COLS)
	WOBRA    := ORES_COLS[NPOS][ASCAN(ODLGRES:AHEADER,{|X|ALLTRIM(X[2])=="FP6_OBRA"   })]
	WLOCACAO := ORES_COLS[NPOS][ASCAN(ODLGRES:AHEADER,{|X|ALLTRIM(X[2])=="FP6_SEQGUI" })]
	WCODIGO  := ORES_COLS[NPOS][ASCAN(ODLGRES:AHEADER,{|X|ALLTRIM(X[2])=="FP6_CODIGO" })]
	WSEQRES  := ORES_COLS[NPOS][ASCAN(ODLGRES:AHEADER,{|X|ALLTRIM(X[2])=="FP6_SEQRES" })]
	IF COBRA == WOBRA .AND. WLOCACAO == CBECH
		IF CSEQRES < WSEQRES
			CSEQRES := WSEQRES
		ENDIF
		IF NFOUND == 0 .AND. WCODIGO == AZABRESP[1] .AND. ! ATAIL( ODLGRES:ACOLS[NPOS] )			// DELETADO?
			NFOUND := NPOS
		ENDIF
	ENDIF
NEXT

IF NFOUND > 0						// ATUALIZA O VALOR
	ORES_COLS[NFOUND][ASCAN(ODLGRES:AHEADER,{|X|ALLTRIM(X[2])=="FP6_VALCOB" })] := NVALOR
	RESTAREA( AAREA )
	RETURN .T.
ENDIF


ATMP := ACLONE( ORES_COLS0[1] )		// CRIANDO A LINHA

FOR NPOS := 1 TO LEN( ODLGRES:AHEADER ) 
	IF ALLTRIM(ODLGRES:AHEADER[NPOS, 2]) == "FP6_OBRA"
		ATMP[NPOS] := COBRA
	ENDIF
	IF ALLTRIM(ODLGRES:AHEADER[NPOS, 2]) == "FP6_SEQGUI"
		ATMP[NPOS] := CBECH
	ENDIF
	IF ALLTRIM(ODLGRES:AHEADER[NPOS, 2]) == "FP6_SEQRES"
		ATMP[NPOS] := SOMA1( CSEQRES )
	ENDIF
	IF ALLTRIM(ODLGRES:AHEADER[NPOS, 2]) == "FP6_CODIGO"
		ATMP[NPOS] := AZABRESP[1]
	ENDIF
	IF ALLTRIM(ODLGRES:AHEADER[NPOS, 2]) == "FP6_DESCRI"
		ATMP[NPOS] := AZABRESP[2]
	ENDIF
	IF ALLTRIM(ODLGRES:AHEADER[NPOS, 2]) == "FP6_VALCOB"
		ATMP[NPOS] := NVALOR
	ENDIF
	IF ALLTRIM(ODLGRES:AHEADER[NPOS, 2]) == "FP6_RESPON"
		ATMP[NPOS] := "D"
	ENDIF
NEXT

AADD( ORES_COLS, ACLONE( ATMP ) )	// ADICIONA A NOVA RESPONSABILIDADE

RESTAREA( AAREA )

RETURN .T.
