#INCLUDE "locr008.ch" 
/*/{PROTHEUS.DOC} LOCR008.PRW
ITUP BUSINESS - TOTVS RENTAL
IMPRESSรO DA C.T.R.C
@TYPE FUNCTION
@AUTHOR FRANK ZWARG FUGA
@SINCE 03/12/2020
@VERSION P12
@HISTORY 03/12/2020, FRANK ZWARG FUGA, FONTE PRODUTIZADO.
/*/

#INCLUDE "PROTHEUS.CH"

FUNCTION LOCR008()
// --> DECLARACAO DE VARIAVEIS
LOCAL CDESC1         := STR0001 //"ESTE PROGRAMA TEM COMO OBJETIVO IMPRIMIR A NOTA FISCAL "
LOCAL CDESC2         := STR0002 //"C.T.R.C DE ACORDO COM OS PARAMETROS INFORMADOS PELO USUARIO."
LOCAL CDESC3         := STR0003 //"NOTA DE CONHECIMENTO DE FRETE C.T.R.C"
LOCAL TITULO         := STR0003 //"NOTA DE CONHECIMENTO DE FRETE C.T.R.C"
LOCAL NLIN           := 80
LOCAL CABEC1         := ""
LOCAL CABEC2         := ""
LOCAL AORD           := {} 
LOCAL IMPRIME 

PRIVATE LEND         := .F.
PRIVATE LABORTPRINT  := .F.
PRIVATE LIMITE       := 220
PRIVATE TAMANHO      := "G"
PRIVATE NOMEPROG     := "CTRC" 		// COLOQUE AQUI O NOME DO PROGRAMA PARA IMPRESSAO NO CABECALHO
PRIVATE NTIPO        := 18
PRIVATE ARETURN      := { "ZEBRADO", 1, "ADMINISTRACAO", 2, 2, 1, "", 1}
PRIVATE NLASTKEY     := 0
PRIVATE CPERG        := "LOCP014"
PRIVATE CBTXT        := SPACE(10)
PRIVATE CBCONT       := 00
PRIVATE CONTFL       := 01
PRIVATE M_PAG        := 01
PRIVATE NQTDVO       := 0
PRIVATE WNREL        := NOMEPROG 	// COLOQUE AQUI O NOME DO ARQUIVO USADO PARA IMPRESSAO EM DISCO
PRIVATE CSTRING      := "FQ5"

IMPRIME := .T.

DBSELECTAREA("FQ5")
IF EMPTY(FQ5->FQ5_NUMCTR)
	MSGALERT(STR0004 , STR0005)  //"C.T.R.C PARA ESTA VIAGEM NAO SE ENCONTRA GERADO.VERIFIQUE !"###"GPO - LOCI012.PRW"
	RETURN 
ENDIF 

DBSELECTAREA("FQ5")
DBSETORDER(1)

PERGUNTE(CPERG,.F.)

// --> MONTA A INTERFACE PADRAO COM O USUARIO... 
WNREL := SETPRINT(CSTRING,NOMEPROG,CPERG,@TITULO,CDESC1,CDESC2,CDESC3,.F.,AORD,.T.,TAMANHO,,.F.)

IF NLASTKEY == 27
	RETURN
ENDIF

SETDEFAULT(ARETURN,CSTRING)

IF NLASTKEY == 27
	RETURN
ENDIF

NTIPO := IF(ARETURN[4]==1,15,18)

// --> PROCESSAMENTO. RPTSTATUS MONTA JANELA COM A REGUA DE PROCESSAMENTO.
VERIMP()

RPTSTATUS({|| RUNREPORT(CABEC1,CABEC2,TITULO,NLIN) },TITULO)

RETURN



/*/
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัอออออออออออหอออออออัออออออออออออออออออออหออออออัออออออออออออปฑฑ
ฑฑบFUNO    ณ RUNREPORT บ AUTOR ณ SERGIO CELESTINO   บ DATA ณ 29/04/2008 บฑฑ
ฑฑฬออออออออออุอออออออออออสอออออออฯออออออออออออออออออออสออออออฯออออออออออออนฑฑ
ฑฑบDESCRIO ณ FUNCAO AUXILIAR CHAMADA PELA RPTSTATUS. A FUNCAO RPTSTATUS บฑฑ
ฑฑบ          ณ MONTA A JANELA COM A REGUA DE PROCESSAMENTO.               บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUSO       ณ PROGRAMA PRINCIPAL                                         บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
/*/
STATIC FUNCTION RUNREPORT(CABEC1,CABEC2,TITULO,NLIN)

LOCAL NTOTAL     := NQTDTO := 0   
LOCAL CESPECIE   := ""
LOCAL LICM       := .T.
LOCAL COBS01     := ""
LOCAL COBS02     := ""
LOCAL COBS03     := ""
LOCAL _CTPFRE    := ""
LOCAL C_DIVERSOS := ""
LOCAL CNUMNFC    := "" 
LOCAL NTOTLN     := 0
LOCAL NQTDLN     := 0
LOCAL NQTVLN     := 0
LOCAL COBSER     := ""   
LOCAL NX         := 0 
LOCAL LVEZ 

AAREASF2 := SF2->(GETAREA())
AAREASD2 := SD2->(GETAREA())
AAREASF4 := SF4->(GETAREA())
AAREADTC := DTC->(GETAREA())
AAREADTR := DTR->(GETAREA())
AAREADTR := DUP->(GETAREA())

DBSELECTAREA("ZL8")
DBSETORDER(1)
MSSEEK(XFILIAL("ZL8") + FQ5->FQ5_SOT + FQ5->FQ5_OBRA + FQ5->FQ5_VIAGEM )

DBSELECTAREA("SF2")
DBSETORDER(1)
MSSEEK(XFILIAL("SF2") + FQ5->FQ5_NUMCTR + FQ5->FQ5_SERCTR )

DBSELECTAREA("SD2")
DBSETORDER(3)
MSSEEK(XFILIAL("SD2") + FQ5->FQ5_NUMCTR + FQ5->FQ5_SERCTR )

DBSELECTAREA("DTC")
DBSETORDER(7)
MSSEEK(XFILIAL("DTC") + PADR(FQ5->FQ5_NUMCTR,LEN(DTC->DTC_DOC)) + FQ5->FQ5_SERCTR + FQ5->FQ5_FILORI)

DBSELECTAREA("DTR")
DBSETORDER(1)
MSSEEK(XFILIAL("DTR") + FQ5->FQ5_FILORI + FQ5->FQ5_VIAGEM )

DBSELECTAREA("DUP")
DBSETORDER(1)
MSSEEK(XFILIAL("DUP") + FQ5->FQ5_FILORI + FQ5->FQ5_VIAGEM )

DBSELECTAREA("SF4")
DBSETORDER(1)
MSSEEK(XFILIAL("SF4") + FQ5->FQ5_TES )

IF ALLTRIM(SF4->F4_CREDST) == "2"
   LICM := .F.
ENDIF

DBSELECTAREA("FQ5")

IF EMPTY(FQ5->FQ5_CFOP)
	@ 012,096 PSAY SF4->F4_CF
ELSE	
	@ 012,096 PSAY FQ5->FQ5_CFOP
ENDIF    

@ 013,106 PSAY SF2->F2_EMISSAO
   
// INFORMACOES REMETENTE / DESTINATARIO                                                                 
@ 015,018 PSAY SUBSTR(POSICIONE("SA1", 1 , XFILIAL("SA1") + DTC->DTC_CLIREM + DTC->DTC_LOJREM  , "A1_NOME"   ),1,40)  // NOME DO REMETENTE
@ 015,090 PSAY SUBSTR(POSICIONE("SA1", 1 , XFILIAL("SA1") + DTC->DTC_CLIDES + DTC->DTC_LOJDES  , "A1_NOME"   ),1,40)  // NOME DO DESTINATARIO
   
@ 016,018 PSAY SUBSTR(POSICIONE("SA1", 1 , XFILIAL("SA1") + DTC->DTC_CLIREM + DTC->DTC_LOJREM  , "A1_END"    ),1,60)  // ENDERECO DO REMETENTE   
@ 016,090 PSAY SUBSTR(POSICIONE("SA1", 1 , XFILIAL("SA1") + DTC->DTC_CLIDES + DTC->DTC_LOJDES  , "A1_END"    ),1,60)  // ENDERECO DO DESTINATARIO  
  
@ 017,018 PSAY SUBSTR(POSICIONE("SA1", 1 , XFILIAL("SA1") + DTC->DTC_CLIREM + DTC->DTC_LOJREM  , "A1_BAIRRO" ),1,30)  // BAIRRO DO REMETENTE         
@ 017,051 PSAY SUBSTR(POSICIONE("SA1", 1 , XFILIAL("SA1") + DTC->DTC_CLIREM + DTC->DTC_LOJREM  , "A1_MUN"    ),1,25)  // MUNICIPIO DO REMETENTE
@ 017,075 PSAY SUBSTR(POSICIONE("SA1", 1 , XFILIAL("SA1") + DTC->DTC_CLIREM + DTC->DTC_LOJREM  , "A1_EST"    ),1,02)  // ESTADO DO REMETENTE
@ 017,091 PSAY SUBSTR(POSICIONE("SA1", 1 , XFILIAL("SA1") + DTC->DTC_CLIDES + DTC->DTC_LOJDES  , "A1_BAIRRO" ),1,30)  // BAIRRO DO DESTINATARIO          
@ 017,120 PSAY SUBSTR(POSICIONE("SA1", 1 , XFILIAL("SA1") + DTC->DTC_CLIDES + DTC->DTC_LOJDES  , "A1_MUN"    ),1,25)  // MUNICIPIO DO DESTINATARIO
@ 017,145 PSAY SUBSTR(POSICIONE("SA1", 1 , XFILIAL("SA1") + DTC->DTC_CLIDES + DTC->DTC_LOJDES  , "A1_EST"    ),1,02)  // ESTADO DO DESTINATARIO
   
@ 018,018 PSAY POSICIONE("SA1", 1 , XFILIAL("SA1") + DTC->DTC_CLIREM + DTC->DTC_LOJREM  , "A1_CGC"    ) 			  // CNPJ,CPF DO REMETENTE
@ 018,052 PSAY POSICIONE("SA1", 1 , XFILIAL("SA1") + DTC->DTC_CLIREM + DTC->DTC_LOJREM  , "A1_INSCR"  ) 			  // INSCRICAO DO REMETENTE
@ 018,090 PSAY POSICIONE("SA1", 1 , XFILIAL("SA1") + DTC->DTC_CLIDES + DTC->DTC_LOJDES  , "A1_CGC"    ) 			  // CNPJ,CPF DO DESTINATARIO
@ 018,121 PSAY POSICIONE("SA1", 1 , XFILIAL("SA1") + DTC->DTC_CLIDES + DTC->DTC_LOJDES  , "A1_INSCR"  ) 			  // INSCRICAO DO DESTINATARIO 
     
// INFORMACAO CONSIGNATARIO 
@ 020,018 PSAY POSICIONE("SA1", 1 , XFILIAL("SA1") + DTC->DTC_CLICON + DTC->DTC_LOJCON  , "A1_NOME"   )   //NOME CONSIGNATARIO
@ 021,018 PSAY POSICIONE("SA1", 1 , XFILIAL("SA1") + DTC->DTC_CLICON + DTC->DTC_LOJCON  , "A1_END"    )   //ENDERECO CONSIGNATARIO
@ 022,018 PSAY POSICIONE("SA1", 1 , XFILIAL("SA1") + DTC->DTC_CLICON + DTC->DTC_LOJCON  , "A1_BAIRRO" )   //BAIRRO CONSIGNATARIO
@ 022,051 PSAY POSICIONE("SA1", 1 , XFILIAL("SA1") + DTC->DTC_CLICON + DTC->DTC_LOJCON  , "A1_MUN"    )   //MUNICIPIO CONSIGNATARIO
@ 022,075 PSAY POSICIONE("SA1", 1 , XFILIAL("SA1") + DTC->DTC_CLICON + DTC->DTC_LOJCON  , "A1_EST"    )   //ESTADO CONSIGNATARIO
@ 023,018 PSAY POSICIONE("SA1", 1 , XFILIAL("SA1") + DTC->DTC_CLICON + DTC->DTC_LOJCON  , "A1_CGC"    )   //CNPJ CONSIGNATARIO
@ 023,052 PSAY POSICIONE("SA1", 1 , XFILIAL("SA1") + DTC->DTC_CLICON + DTC->DTC_LOJCON  , "A1_INSCR"  )   //INSCR. CONSIGNATARIO

NLIN := 26
NVEZ := 0     
DBSELECTAREA("DTC")
WHILE !EOF() .AND. DTC->DTC_DOC + DTC->DTC_SERIE == FQ5->FQ5_NUMCTR + FQ5->FQ5_SERCTR
	IF DTC->DTC_VIAGEM == FQ5->FQ5_VIAGEM
		//DBSELECTAREA("SX5")
		//DBSETORDER(1)
		//IF DBSEEK(XFILIAL("SX5") + "MG" + ALLTRIM(DTC->DTC_CODEMB) )
		//	CESPECIE := SX5->X5_DESCRI
		//ENDIF   
		CESPECIE := posicione("SX5",1,xFilial("SX5")+"MG"+ALLTRIM(DTC->DTC_CODEMB),"X5_DESCRI")
       
		IF NLIN == 29  
			C_DIVERSOS := ALLTRIM(DTC->DTC_DPROD)
			CNUMNFC    := DTC->DTC_NUMNFC
			NTOTLN     := NTOTLN + DTC->DTC_VALOR 								// TOTAL DO VALOR
			NQTDLN     := NQTDLN + DTC->DTC_PESO  								// TOTAL DO PESO
			NQTVLN     := NQTVLN + DTC->DTC_QTDVOL 
			COBSER     := COBSER+DTC->DTC_NUMNFC+"-"+STR0006+TRANSFORM(DTC->DTC_VALOR, "@E 999,999,999.99")+ " /" //"R$ "
			LVEZ       := .T. 
			NVEZ       := NVEZ+1
		ELSE
			@ NLIN,010 PSAY ALLTRIM(DTC->DTC_DPROD)    							// DESCRICAO DO PRODUTO
			@ NLIN,072 PSAY DTC->DTC_NUMNFC            							// NUMERO DA NOTA FISCAL         
			@ NLIN,095 PSAY TRANSFORM(DTC->DTC_VALOR, "@E 9999,999,999.99")    	// VALOR  DA NOTA FISCAL            
			@ NLIN,120 PSAY TRANSFORM(DTC->DTC_PESO , "@E 999,999")           	// PESO
			@ NLIN,130 PSAY TRANSFORM(DTC->DTC_QTDVOL,"@E 9,999")            	// QUANTIDADE VOLUME
			@ NLIN,138 PSAY CESPECIE                   							// ESPECIE(CAIXA,TAMBOR...ETC..)
			LVEZ := .F.
			NLIN++
		ENDIF 
		NTOTAL  := NTOTAL + DTC->DTC_VALOR 										// TOTAL DO VALOR
		NQTDTO  := NQTDTO + DTC->DTC_PESO  										// TOTAL DO PESO
		NQTDVO  := NQTDVO + DTC->DTC_QTDVOL
		_CTPFRE := FQ5->FQ5_TIPVIA 												// DTC->DTC_TIPFRE
	ENDIF
		
	DBSELECTAREA("DTC")
	DBSKIP() 
ENDDO

IF LVEZ        
	IF NVEZ >=2   
		C_DIVERSOS := 'DIVERSOS'
		CNUMNFC    := 'VIDE OBS'
	ENDIF   
	@ NLIN,010 PSAY ALLTRIM(C_DIVERSOS)    										// DESCRICAO DO PRODUTO
	IF CNUMNFC == 'VIDE OBS'
		CCOL := 10                 												// NUMERO DA NOTA FISCAL         
	ELSE
		CCOL := 0
	ENDIF    
	@ NLIN,072+CCOL PSAY CNUMNFC              									// NUMERO DA NOTA FISCAL         
	@ NLIN,095+CCOL PSAY TRANSFORM(NTOTLN, "@E 9999,999,999.99")         	 	// VALOR  DA NOTA FISCAL            
	@ NLIN,120+CCOL PSAY TRANSFORM(NQTDLN, "@E 999,999")           				// PESO
	@ NLIN,130+CCOL PSAY TRANSFORM(NQTVLN, "@E 9,999")            				// QUANTIDADE VOLUME
	@ NLIN,140+CCOL PSAY CESPECIE                   							// ESPECIE(CAIXA,TAMBOR...ETC..)
ENDIF 
    
// TOTAIS
@ 031,095 PSAY TRANSFORM(NTOTAL,"@E 9999,999,999.99")   						// NUMERO DA NOTA FISCAL           
@ 031,120 PSAY TRANSFORM(NQTDTO,"@E 999,999")   								// TOTAL DO PESO
@ 031,130 PSAY TRANSFORM(NQTDVO,"@E 9,999")   									// TOTAL DO VOLUME
        
@ 034,010 PSAY "CP" 
@ 034,016 PSAY FQ5->FQ5_PLACAV 													// PLACA DO VEICULO
@ 034,028 PSAY FQ5->FQ5_PLACAR 													// PLACA DO REBOQUE

@ 034,065 PSAY DTR->DTR_QTDEIX  												// QUANTIDADE DE EIXOS DO VEICULO 
    
// MOTORISTA
@ 034,076 PSAY FQ5->FQ5_MOTORI 													// NOME DO MOTORISTA
@ 034,119 PSAY POSICIONE("DA4", 2 , XFILIAL("DA4") + FQ5->FQ5_MOTORI , "DA4_CGC") PICTURE "@R 99.999.999/9999-99" // NUMERO DO CPF DO MOTORISTA
@ 034,140 PSAY FQ5->FQ5_NUMCTR 													// NUMERO DA NOTA FISCAL CTRC
   
// COMPOSICAO DO FRETE
@ 037,010 PSAY TRANSFORM(FQ5->FQ5_TOTFRE,"@E 999,999,999.99") 					// PESO DO FRETE
@ 037,023 PSAY TRANSFORM(FQ5->FQ5_VALADV,"@E 999,999,999.99") 					// ADVALOREM
@ 037,047 PSAY "0,00"          													// SEGURO
@ 037,062 PSAY "0,00"          													// CAMPO BRANCO
@ 037,069 PSAY TRANSFORM(DTR->DTR_VALPDG,"@E 9,999.99") 						// VALOR DO PEDAGIO
@ 037,080 PSAY TRANSFORM(FQ5->FQ5_VLRINF,"@E 9,999,999.99") 					// VALOR TOTAL DO FRETE
   
IF FQ5->FQ5_DESICM 
    @037,098 PSAY TRANSFORM(FQ5->FQ5_BASICM,"@E 9,999,999.99") 					// BASE DO ICMS 
    @037,110 PSAY TRANSFORM(FQ5->FQ5_PERICM,"@E 999.99") 						// ALIQUOTA DO ICMS  
    @037,122 PSAY TRANSFORM(FQ5->FQ5_VALICM,"@E 999,999.99") 					// VALOR DO ICMS
ELSE
	@ 037,098 PSAY "0,00" 														// BASE DO ICMS 
	@ 037,112 PSAY "0,00" 														// ALIQUOTA DO ICMS 
	@ 037,122 PSAY "0,00" 														// VALOR DO ICMS 
ENDIF
    
@ 037,147 PSAY "0,00"             
@ 039,010 PSAY SUBSTR(FQ5->FQ5_ORIGEM,1,40) 									// COLETA
@ 039,080 PSAY SUBSTR(FQ5->FQ5_DESTIN,1,40) 									// ENTREGA
_NTMOBS := LEN(FQ5->FQ5_OBSCTR+COBSER)
COBS    := SPACE(01) 
COBS01  := SPACE(01) 
COBS02  := SPACE(01) 
COBS03  := SPACE(01) 

// COMPOSIวAO DAS LINHAS DE OBSERVAวีES.    
IF _NTMOBS > 0 
	COBS := FQ5->FQ5_OBSCTR+" "+COBSER 
	IF LEN(COBS) > 100
		COBS01 := SUBSTR(COBS,1,100)
		FOR NX := 2 TO 3 
			IF NX == 2
				COBS02 := SUBSTR(COBS,(100*(NX-1))+1,100)   
			ELSE
				COBS03 := SUBSTR(COBS,(100*(NX-1))+1,100)      
			ENDIF
		NEXT NX 
	ELSE
		COBS01 := SUBSTR(COBS,1,100)
	ENDIF
ELSE
	COBS01 := SUBSTR(COBS01,1,IIF(LEN(COBS01)<100,LEN(COBS01),100))
	COBS02 := SUBSTR(COBS02,1,IIF(LEN(COBS02)<100,LEN(COBS01),100))
	COBS03 := SUBSTR(COBS03,1,IIF(LEN(COBS03)<100,LEN(COBS01),100))
ENDIF

@ 041,012 PSAY COBS01
@ 041,125 PSAY " "              				// VERIFICAR
@ 041,145 PSAY IIF(_CTPFRE=="1","CIF","FOB") 	// TIPO DE FRETE
@ 042,012 PSAY COBS02
@ 043,012 PSAY COBS03
    
// --> FINALIZA A EXECUCAO DO RELATORIO... 
AAREASF2 := SF2->(GETAREA())
AAREASD2 := SD2->(GETAREA())
AAREASF4 := SF4->(GETAREA())
AAREADTC := DTC->(GETAREA())
AAREADTR := DTR->(GETAREA())
AAREADTR := DUP->(GETAREA())

SET DEVICE TO SCREEN

SETPGEJECT(.F.)

// --> SE IMPRESSAO EM DISCO, CHAMA O GERENCIADOR DE IMPRESSAO... 
IF ARETURN[5]==1
	DBCOMMITALL()
	SET PRINTER TO
	OURSPOOL(WNREL)
ENDIF

MS_FLUSH()

RETURN



/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัอออออออออออหอออออออัออออออออออออออออออออหออออออัออออออออออออปฑฑ
ฑฑบPROGRAMA  ณ VERIMP    บ AUTOR ณ IT UP BUSINESS     บ DATA ณ 14/04/2008 บฑฑ
ฑฑฬออออออออออุอออออออออออสอออออออฯออออออออออออออออออออสออออออฯออออออออออออนฑฑ
ฑฑบUSO       ณ ESPECIFICO GPO                                             บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/
STATIC FUNCTION VERIMP()

LOCAL NLIN := 80

IF ARETURN[5]==2
	
	NOPC     := 1 
	#IFNDEF WINDOWS
		CCOR := "B/BG" 
	#ENDIF 

	WHILE .T.
		SETPRC(0,0)
		DBCOMMITALL()
		
		@ NLIN,054 PSAY "*"
		
		#IFNDEF WINDOWS
			SET DEVICE TO SCREEN
			DRAWADVWINDOW(STR0007,10,25,14,56) //" FORMULARIO "
			SETCOLOR(CCOR)
			@ 12,27 SAY STR0008 //"FORMULARIO ESTA POSICIONADO?"
			NOPC := MENUH({STR0009,STR0010,STR0011},14,26,"B/W,W+/N,R/W","SNC","",1) //"SIM"###"NAO"###"CANCELA IMPRESSAO"
			SET DEVICE TO PRINT
		#ELSE
			IF     MSGYESNO(STR0012) //"FOMULARIO ESTA POSICIONADO ? "
				NOPC := 1
			ELSEIF MSGYESNO(STR0013) //"TENTA NOVAMENTE ? "
				NOPC := 2
			ELSE
				NOPC := 3
			ENDIF
		#ENDIF
		
		DO CASE
		CASE NOPC==1
			LCONTINUA:=.T.
			EXIT
		CASE NOPC==2
			LOOP
		CASE NOPC==3
			LCONTINUA:=.F.
			RETURN
		ENDCASE
	ENDDO 

ENDIF

RETURN
