/*/{PROTHEUS.DOC} LOCR011.PRW 
ITUP BUSINESS - TOTVS RENTAL
AUTORIZACAO DE SERVICO DE GUINDASTE
@TYPE FUNCTION
@AUTHOR FRANK ZWARG FUGA
@SINCE 03/12/2020
@VERSION P12
@HISTORY 03/12/2020, FRANK ZWARG FUGA, FONTE PRODUTIZADO.
/*/

#INCLUDE "PROTHEUS.CH"
#INCLUDE "TOPCONN.CH"

FUNCTION LOCR011(_CNRAS,_CFILEPDF)
LOCAL XALIAS 	 := GETAREA()
LOCAL AAREAZA0   := FP0->(GETAREA())
LOCAL AAREADTQ   := FQ5->(GETAREA())
LOCAL AITENS	 := {}
LOCAL OFONTX     := TFONT():NEW("ARIAL",12,16,,.T.,,,,.T.,.F.)
LOCAL NI         := 0 

PRIVATE CCABEC   := ""
PRIVATE CPERG    := "LOCP015" 					// CRIAR PERGUNTA
PRIVATE NVALOR   := 0
PRIVATE CCODCLI  :=""
PRIVATE CLJCLIE  :=""
PRIVATE CINCR    :=""
PRIVATE CGC      :=""
PRIVATE CENDERE  :=""
PRIVATE	CBAIRRO  :=""
PRIVATE CMUNICI  :=""
PRIVATE	CESTADO  :=""
PRIVATE	CCEP     :=""
PRIVATE CTEL     :=""
PRIVATE CCONTATO :=""
PRIVATE CENDCOB  :=""
PRIVATE CBAICOB  :=""
PRIVATE CMUNCOB  :=""
PRIVATE CESTCOB  :=""
PRIVATE CCEPCOB  :=""
PRIVATE LPDF     := .F.
PRIVATE AASF     := {}

DEFAULT _CNRAS	 := ""
DEFAULT _CFILEPDF := ""

IF !EMPTY(_CFILEPDF)
	LPDF := .T.
ENDIF

IF EMPTY(_CNRAS)
	FQ5->(DBSETORDER(8)) 						// --> INDICE 08: FQ5_FILIAL + FQ5_SOT + FQ5_OBRA + FQ5_AS     NICKNAME: ITUPDTQ008 
	FQ5->(DBSEEK(XFILIAL("FQ5")+FP0->FP0_PROJET))
	AADD(AITENS , {"TODAS"})
	WHILE FQ5->(!EOF()) .AND. FQ5->FQ5_SOT = FP0->FP0_PROJET

		AADD(AITENS, {FQ5->FQ5_AS}) 

		FQ5->(DBSKIP())
	ENDDO 
	
	LCANCEL := .F. 
	ODLG3  	:= NIL 
	CRET    := "" 
	DEFINE MSDIALOG ODLG3 TITLE "GPO - LOCI022.PRW" FROM 000,000 TO 450,735     OF ODLG3 PIXEL
		@ 010,005 SAY     "AS'S DO PROJETO: "+FP0->FP0_PROJET      FONT OFONTX  OF ODLG3 PIXEL 
		@ 025,005 SAY     "SELECIONE NA AS E APERTE <ENTER> OU <DUPLO CLIQUE> " OF ODLG3 PIXEL 
		@ 040,005 LISTBOX OLBXITENS FIELDS HEADER "SELECIONE A AS" SIZE 360,170 OF ODLG3 PIXEL ON DBLCLICK ((CRET := AITENS[OLBXITENS:NAT][01],ODLG3:END())) 
		OLBXITENS:SETARRAY(AITENS)
		OLBXITENS:BLINE := {|| {AITENS[OLBXITENS:NAT][01]}}
		OLBXITENS:REFRESH()
		ODLG3:REFRESH()
	ACTIVATE MSDIALOG ODLG3 CENTERED
ELSE
	CRET := _CNRAS
ENDIF

IF EMPTY(CRET)
	RESTAREA(AAREAZA0)
	RESTAREA(AAREADTQ)
	RESTAREA(XALIAS)
	RETURN(NIL)
ENDIF

DBSELECTAREA("FQ5")
DBSETORDER(9)
DBSEEK(XFILIAL("FQ5")+CRET)

IF FQ5->FQ5_TPAS == "F" .OR. LEFT(CRET,6) == "BR-SF-"
	LOCA030(CRET,_CFILEPDF)
	RESTAREA(AAREAZA0)
	RESTAREA(AAREADTQ)
	RESTAREA(XALIAS)
	RETURN(NIL)
ENDIF

// PREENCHE COM OS DADOS DA PROPOSTA
CCODCLI := FP0->FP0_CLI
CLJCLIE := FP0->FP0_LOJA

CINCR   := FP0->FP0_CLIINS
CGC     := FP0->FP0_CLICGC
CENDERE := FP0->FP0_CLIEND
CBAIRRO := FP0->FP0_CLIBAI
CMUNICI := FP0->FP0_CLIMUN
CESTADO := FP0->FP0_CLIEST
CCEP    := FP0->FP0_CLICEP

CCONTATO := ALLTRIM(FP0->FP0_CLICON)
CTEL     := "( "+FP0->FP0_CLIDDD+" )" + " "+ FP0->FP0_CLITEL

CENDCOB := FP0->FP0_CLIEND
CBAICOB := FP0->FP0_CLIBAI
CMUNCOB := FP0->FP0_CLIMUN
CESTCOB := FP0->FP0_CLIEST
CCEPCOB := FP0->FP0_CLICEP

IF !EMPTY(FP0->FP0_CLI) .AND. !EMPTY(FP0->FP0_LOJA)
	AAREASA1 := SA1->( GETAREA() )
	DBSELECTAREA("SA1")
	DBSETORDER(1)
	IF MSSEEK(XFILIAL("SA1") + FP0->FP0_CLI + FP0->FP0_LOJA )
		//DADOS CADASTRAIS
		CCODCLI := SA1->A1_COD
		CLJCLIE := SA1->A1_LOJA
		
		CINCR   := FP0->FP0_CLIINS
		CGC     := FP0->FP0_CLICGC
		CENDERE := FP0->FP0_CLIEND
		CBAIRRO := FP0->FP0_CLIBAI
		CMUNICI := FP0->FP0_CLIMUN
		CESTADO := FP0->FP0_CLIEST
		CCEP    := FP0->FP0_CLICEP
		
		IF !EMPTY(SA1->A1_ENDCOB)
			CENDCOB := SA1->A1_ENDCOB
			CBAICOB := SA1->A1_BAIRROC
			CMUNCOB := SA1->A1_MUNC
			CESTCOB := SA1->A1_ESTC
			CCEPCOB := SA1->A1_CEPC
		ELSE
			CENDCOB := SA1->A1_END
			CBAICOB := SA1->A1_BAIRRO
			CMUNCOB := SA1->A1_MUN
			CESTCOB := SA1->A1_EST
			CCEPCOB := SA1->A1_CEP
		ENDIF
		CTEL     := "( "+SA1->A1_DDD+" )" + " "+ SA1->A1_TEL
		CCONTATO := SA1->A1_CONTATO
		
		IF EMPTY(CCONTATO)
			CCONTATO := ALLTRIM(FP0->FP0_CLICON)
		ENDIF
		
	ENDIF
	RESTAREA(AAREASA1)
ENDIF

FQ5->(DBSEEK(XFILIAL("FQ5")+FP0->FP0_PROJET))

// --> SELECAO DA IMPRESSORA. 
IF ! LPDF
	OOBJPRINT:= TMSPRINTER():NEW(CCABEC)
	OOBJPRINT:SETSIZE( 210, 297 )
ELSE
	OOBJPRINT := FWMSPRINTER():NEW(_CFILEPDF,6,.F.,,.T.)
	OOBJPRINT:SETRESOLUTION(290)
	OOBJPRINT:SETPORTRAIT()
	OOBJPRINT:SETPAPERSIZE(2)				// A4
	OOBJPRINT:SETMARGIN(60,60,60,60) 		// NESQUERDA, NSUPERIOR, NDIREITA, NINFERIOR
	OOBJPRINT:CPATHPDF := ALLTRIM(GETTEMPPATH())
 //	CRET := "TODAS"
ENDIF

LJMSGRUN("POR FAVOR AGUARDE, AUTORIZAÇÃO DE SERVIÇO...",,{|| IMP_GRUA() })

// --> MOSTRA RELATORIO PARA IMPRIMIR.
IF ! LPDF
	OOBJPRINT:PREVIEW()
ELSE
	OOBJPRINT:PREVIEW("PDF")
ENDIF

FOR NI := 1 TO LEN(AASF)					// EMISSÃO DE ASF QUANDO USUÁRIO SELECIONAR TODAS ASS
	LOCA030(AASF[NI],_CFILEPDF)
NEXT NI 

RESTAREA(XALIAS)

RETURN(NIL)



/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±ÉÍÍÍÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍ»±±
±±ºPROGRAMA  ³ IMP_GRUA  º AUTOR ³ IT UP BUSINESS     º DATA ³ 30/06/2007 º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºDESCRICAO ³ IMPRESSAO DA AUTORIZACAO DE GUINDASTE                      º±±
±±ÈÍÍÍÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß
*/
STATIC FUNCTION IMP_GRUA()

PRIVATE OFONT1  := TFONT():NEW("ARIAL"     ,11,IIF(LPDF,10,11),,.F.,,,,,.F.)   // NORMAL
PRIVATE OFONT2  := TFONT():NEW("ARIAL"     ,18,IIF(LPDF,17,18),,.T.,,,,,.F.)   // NEGRITO
PRIVATE OFONT3  := TFONT():NEW("ARIAL"     ,11,IIF(LPDF,10,11),,.T.,,,,,.T.)   // NEGRITO / SUBLINHADO
PRIVATE OFONT4  := TFONT():NEW("ARIAL"     ,10,IIF(LPDF,09,10),,.F.,,,,,.F.)   // NORMAL
PRIVATE OFONT5  := TFONT():NEW("ARIAL"     ,10,IIF(LPDF,09,10),,.T.,,,,,.F.)   // NEGRITO
PRIVATE OFONT6  := TFONT():NEW("ARIAL"     ,10,IIF(LPDF,09,10),,.T.,,,,,.T.)   // NEGRITO / SUBLINHADO
PRIVATE OFONT7  := TFONT():NEW("VENDANA"   ,07,IIF(LPDF,06,07),,.F.,,,,,.F.)   // NORMAL
PRIVATE OFONT8  := TFONT():NEW("VENDANA"   ,07,IIF(LPDF,06,07),,.F.,,,,,.T.)   // SUBLINHADO
PRIVATE OFONT9  := TFONT():NEW("ARIAL"     ,08,IIF(LPDF,07,08),,.F.,,,,,.F.)   // NORMAL
PRIVATE OFONT10 := TFONT():NEW("ARIAL"     ,08,IIF(LPDF,07,08),,.T.,,,,,.F.)   // NEGRITO
PRIVATE OFONT11 := TFONT():NEW("ARIAL"     ,07,IIF(LPDF,06,07),,.F.,,,,,.F.)   // NORMAL
PRIVATE OFONT12 := TFONT():NEW("ARIAL"     ,07,IIF(LPDF,06,07),,.T.,,,,,.F.)   // NORMAL

// --> CRIA AS TABELAS TEMPORARIA PARA GERACAO DO RELATORIO. 
AAREAZA0:=FP0->(GETAREA())
AAREAZA1:=FP1->(GETAREA())
AAREAZA5:=FP4->(GETAREA())
AAREAZA6:=ZA6->(GETAREA())
AAREASE4:=SE4->(GETAREA())

FQ5->(DBSETORDER(8))
FQ5->(DBSEEK(XFILIAL("FQ5")+FP0->FP0_PROJET))

IMPREL()
OOBJPRINT:ENDPAGE()

RESTAREA(AAREAZA0)
RESTAREA(AAREAZA1)
RESTAREA(AAREAZA5)
RESTAREA(AAREAZA6)
RESTAREA(AAREASE4)

RETURN(NIL)



/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±ÉÍÍÍÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍ»±±
±±ºPROGRAMA  ³ IMPREL    º AUTOR ³ IT UP BUSINESS     º DATA ³ 30/06/2007 º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºUSO       ³ ESPECIFICO GPO                                             º±±
±±ÈÍÍÍÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß
*/
STATIC FUNCTION IMPREL()

LOCAL NLIN       := 400
LOCAL NAUX       := 0
LOCAL NCOL1      := 0
LOCAL NCOL2      := 0
LOCAL NCALC	     := 0
LOCAL NCALCT     := 0
LOCAL NLINHA     := 1760
LOCAL LCHEK      := .T.
LOCAL CTPLOCACAO := ""
LOCAL LOBS       := .F.
LOCAL I          := 0 

WHILE FQ5->(!EOF()) .AND. FQ5->FQ5_SOT = FP0->FP0_PROJET
	
	IF CRET <> "TODAS" .AND. ALLTRIM(CRET)<>ALLTRIM(FQ5->FQ5_AS)
		FQ5->(DBSKIP())
		LOOP
	ENDIF
	
	IF FQ5->FQ5_TPAS == "F"
		IF CRET == "TODAS"
			AADD(AASF, FQ5->FQ5_AS)
		ENDIF
		FQ5->(DBSKIP())
		LOOP
	ENDIF
	
	DBSELECTAREA("FP1")
	DBSETORDER(1)
	MSSEEK(XFILIAL("FP1") + FQ5->FQ5_SOT + FQ5->FQ5_OBRA )
	
	DBSELECTAREA("FP4")
	DBSETORDER(2)
	MSSEEK(XFILIAL("FP4") +  FQ5->FQ5_SOT + FQ5->FQ5_OBRA + FQ5->FQ5_AS +FQ5->FQ5_VIAGEM )//PROJETO + OBRA + AS + VIAGEM
	
	CTPPAG    := IIF(FP4->FP4_TIPPAG=="1", "DA ENTREGA DA NF "           ,;
	IIF(FP4->FP4_TIPPAG=="2", "DO FECHAMENTO DA MEDICAO "   ,;
	IIF(FP4->FP4_TIPPAG=="3", "DO ENCERRAMENTO DO SERVICO " ,;
	IIF(FP4->FP4_TIPPAG=="4", "DO INICIO DO SERVICO "       ,;
	IIF(FP4->FP4_TIPPAG=="6", "PAGAMENTO EFETUADO "       ,;
	IIF(FP4->FP4_TIPPAG=="7", "APROVAÇÃO BM "       ," " ))))))
	
	DBSELECTAREA("SE4")
	DBSETORDER(1)
	MSSEEK(XFILIAL("SE4") + FP4->FP4_CONPAG )
	
	IF FP0->FP0_TIPOSE == "L"
		DBSELECTAREA("ZA6")
		DBSETORDER(1)
		MSSEEK(XFILIAL("ZA6") +  FQ5->FQ5_SOT + FQ5->FQ5_OBRA )
	ENDIF
	
	OOBJPRINT:STARTPAGE()
	
	NLIN   := 400
	NLINHA := 1760
	
	IF CEMPANT == "07"
		OOBJPRINT:SAYBITMAP( 0055, 020,"LOGO.BMP"   , 790, 0380 ) //553 X 224
	ELSE
		OOBJPRINT:SAYBITMAP( 0055, 020,"LOGO.BMP"   , 790, 0380 ) //553 X 224
	ENDIF
	
	DO CASE
		CASE FP0->FP0_TIPOSE == "G"; _CDESC := "EQUIPAMENTO"//"GUINDASTE"
		CASE FP0->FP0_TIPOSE == "R"; _CDESC := "PÓRTICO"
		OTHERWISE                  ; _CDESC := FP0->FP0_TIPOSE
	ENDCASE
	
	OOBJPRINT:SAY( 0050 , 0850 ,  "AUTORIZAÇÃO DE SERVIÇO "                    , OFONT2   , 100 )
	OOBJPRINT:SAY( 0150 , 0850 ,  "NO. AS :" +TRANSFORM(FQ5->FQ5_AS,"@R XX-XXXXX-XXX-XX-XX")                               , OFONT2   , 100 )
	
	OOBJPRINT:SAY( 0250 , 0850 ,  "NO. PROJETO: "+ALLTRIM(FQ5->FQ5_SOT)+;
	" - REVISÃO: " +FP0->FP0_REVISA 						 , OFONT2   , 100 )
	
	OOBJPRINT:SAY( 0350 , 0850 ,  "NO. OBRA: "   +ALLTRIM(FQ5->FQ5_OBRA)+;
	" - REVISÃO DA AS: " +STRZERO(FP4->FP4_REVNAS,2)		 , OFONT2   , 100 )
	
	OOBJPRINT:BOX( 0030 + NLIN , 0050, 150 + NLIN, 2370)
	OOBJPRINT:SAY( 0050 + NLIN , 0060 ,  "EMITIDA EM:"                                   , OFONT10   , 100 )
	OOBJPRINT:SAY( 0050 + NLIN , 0240 ,  DTOC(FP0->FP0_DATINC) + " AS " + TIME()         , OFONT10   , 100 )
	
	OOBJPRINT:SAY( 0100 + NLIN , 0060 ,  "GESTOR:"                                   , OFONT10   , 100 )
	OOBJPRINT:SAY( 0100 + NLIN , 0240 ,  FP0->FP0_VENDED+" - "+POSICIONE("SA3",1,XFILIAL("SA3") + FP0->FP0_VENDED , "A3_NOME" )  , OFONT10   , 100 )
	
	OOBJPRINT:SAY( 0050 + NLIN , 0800 ,  "SERVIÇO: "                                     , OFONT10   , 100 )
	OOBJPRINT:SAY( 0050 + NLIN , 0940 ,  FQ5->FQ5_VIAGEM                                 , OFONT10   , 100 )
	
	OOBJPRINT:SAY( 0050 + NLIN , 1600 ,  "IMPRESSA EM:"                                  , OFONT10   , 100 )
	OOBJPRINT:SAY( 0050 + NLIN , 1850 ,  DTOC(DDATABASE) + " AS " + TIME()               , OFONT10   , 100 )
	
	OOBJPRINT:BOX( 0150 + NLIN , 0050, 0210 + NLIN, 2370)
	OOBJPRINT:SAY( 0160 + NLIN , 0950 ,  "INFORMAÇÕES DO CLIENTE"                                 , OFONT5   , 100 )
	OOBJPRINT:BOX( 0210 + NLIN , 0050, 0610 + NLIN, 2370)
	OOBJPRINT:SAY( 0230 + NLIN , 0060 ,  "CLIENTE: "+CCODCLI+"/"+CLJCLIE+" - "+ALLTRIM(FP0->FP0_CLINOM), OFONT10   , 100 )
	OOBJPRINT:SAY( 0230 + NLIN , 1200 ,  "I.E: "                                                  , OFONT10   , 100 )
	OOBJPRINT:SAY( 0230 + NLIN , 1300 , TRANSFORM(CINCR,"@R 999.999.999-999")                     , OFONT10   , 100 )
	OOBJPRINT:SAY( 0260 + NLIN , 0060 ,  "C.N.P.J:"                                               , OFONT10   , 100 )
	OOBJPRINT:SAY( 0260 + NLIN , 0185 , TRANSFORM(CGC,"@R 99.999.999/9999-99")                    , OFONT10   , 100 )
	
	OOBJPRINT:SAY( 0290 + NLIN , 0060 ,  "END. COMERCIAL:"                                        , OFONT10   , 100 )
	OOBJPRINT:SAY( 0330 + NLIN , 0060 ,  ALLTRIM(CENDERE)                                         , OFONT10   , 100 )
	OOBJPRINT:SAY( 0380 + NLIN , 0060 ,  ALLTRIM(CBAIRRO) +" - "+ ALLTRIM(CMUNICI) +" - " +ALLTRIM(CESTADO)+" - "+ALLTRIM(CCEP)    , OFONT10   , 100 )
	
	OOBJPRINT:SAY( 0290 + NLIN , 1200 ,  "END. COBRANÇA:"                                         , OFONT10   , 100 )
	OOBJPRINT:SAY( 0330 + NLIN , 1200 ,  ALLTRIM(CENDCOB)                                         , OFONT10   , 100 )
	OOBJPRINT:SAY( 0380 + NLIN , 1200 ,  ALLTRIM(CBAICOB) +" - "+ALLTRIM(CMUNCOB) +" - "+ALLTRIM(CESTCOB) +" - "+ALLTRIM(CCEPCOB)  , OFONT10   , 100 )
	
	OOBJPRINT:SAY( 0420 + NLIN , 0060 ,  "TELEFONE: "                                             , OFONT10   , 100 )
	OOBJPRINT:SAY( 0470 + NLIN , 0060 ,  "CONTATO : "                                             , OFONT10   , 100 )
	
	OOBJPRINT:SAY( 0420 + NLIN , 0185 ,  CTEL                                                     , OFONT10   , 100 )
	OOBJPRINT:SAY( 0470 + NLIN , 0185 ,  CCONTATO                                                 , OFONT10   , 100 )
	
	OOBJPRINT:SAY( 0420 + NLIN , 1200 ,  "TELEFONE: "                                             , OFONT10   , 100 )
	OOBJPRINT:SAY( 0470 + NLIN , 1200 ,  "CONTATO : "                                             , OFONT10   , 100 )
	
	OOBJPRINT:SAY( 0420 + NLIN , 1330 ,  CTEL                                                     , OFONT10   , 100 )
	OOBJPRINT:SAY( 0470 + NLIN , 1330 ,  CCONTATO                                                 , OFONT10   , 100 )
	
	OOBJPRINT:BOX( 0610 + NLIN , 0050, 0670 + NLIN, 2370)
	OOBJPRINT:SAY( 0630 + NLIN , 1000 ,  "SERVIÇOS A EXECUTAR"                                    , OFONT5    , 100 )
	
	IF FP0->FP0_TIPOSE == "L"
		COBSVIA := ZA6->ZA6_OBSVIA
	ELSE
		COBSVIA := FP1->FP1_ESCOPO
	ENDIF
	
	XT  := MLCOUNT(COBSVIA,150)
	NAUX:= XT*050
	
	OOBJPRINT:BOX( 0670 + 400 , 0050, 0800 +  NLIN + NAUX  , 2370)
	OOBJPRINT:SAY( 0690 + 400 , 0060 ,  "DESCRIÇÃO:"                                             , OFONT10   , 100 )
	
	NLINSE := 0720 + NLIN
	FOR I:=1 TO XT
		OOBJPRINT:SAY( NLINSE , 0070 ,  MEMOLINE(COBSVIA ,150, I )       , OFONT10   , 100 ) // NLINSE , 0060
		IF NLINSE > 3000
			OOBJPRINT:ENDPAGE()
			OOBJPRINT:STARTPAGE()
			OOBJPRINT:BOX( 0100 , 0050 , 3000 , 2370)
			NLINSE := 150
		ENDIF
		NLINSE := NLINSE + 50
	NEXT I 
	
	NLIN := NLIN + NAUX
	OOBJPRINT:BOX( 0850 + NLIN , 0050, 0910 + NLIN, 2370)
	OOBJPRINT:SAY( 0870 + NLIN , 0060 ,  "INICIO:"                                                , OFONT10   , 100 )
	OOBJPRINT:SAY( 0870 + NLIN , 0180 ,  DTOC(FP4->FP4_DTINI)                                     , OFONT10   , 100 )
	
	OOBJPRINT:SAY( 0870 + NLIN , 0750 ,  "HORA INICIO:"                                           , OFONT10   , 100 )
	OOBJPRINT:SAY( 0870 + NLIN , 0950 ,  SUBS(FP4->FP4_HRINI,1,2)+":"+SUBS(FP4->FP4_HRINI,3,2)    , OFONT10   , 100 )
	
	OOBJPRINT:SAY( 0870 + NLIN , 1450 ,  "TERMINO:"                                               , OFONT10   , 100 )
	OOBJPRINT:SAY( 0870 + NLIN , 1600 ,  DTOC(FP4->FP4_DTFIM)                                     , OFONT10   , 100 )
	
 //	OOBJPRINT:SAY( 0870 + NLIN , 2000 ,  "HORA TERMINO:"                                          , OFONT10   , 100 )
 //	OOBJPRINT:SAY( 0870 + NLIN , 2230 ,  SUBS(FQ5->FQ5_HORFIM,1,2)+":"+SUBS(FQ5->FQ5_HORFIM,3,2)  , OFONT10   , 100 )
	
	OOBJPRINT:BOX( 0910 + NLIN , 0050, 0970 + NLIN, 2370)
	OOBJPRINT:SAY( 0930 + NLIN , 1050 ,  "LOCAL DO SERVIÇO"                                       , OFONT5   , 100 )
	OOBJPRINT:BOX( 0970 + NLIN , 0050, 1150 + NLIN, 2370)
	
	OOBJPRINT:SAY( 0995 + NLIN , 0060 ,  "OBRA:"                                                  , OFONT10   , 100 )
	
	IF FP0->FP0_TIPOSE == "L"
		CNOMEORI := ZA6->ZA6_NOMDES
		CENDORI  := ZA6->ZA6_ENDDES
		CBAIORI  := ZA6->ZA6_BAIDES
		CMUNORI  := ZA6->ZA6_MUNDES
		CESTORI  := ZA6->ZA6_ESTDES
		CCONTORI := ZA6->ZA6_CONDES
		CMAILORI := ZA6->ZA6_EMADES
		CTELORI  := "( "+ZA6->ZA6_DDDDES+" ) "+ZA6->ZA6_TELDES
	ELSE
		CNOMEORI := FP1->FP1_NOMORI
		CENDORI  := FP1->FP1_ENDORI
		CBAIORI  := FP1->FP1_BAIORI
		CMUNORI  := FP1->FP1_MUNORI
		CESTORI  := FP1->FP1_ESTORI
		CCONTORI := FP1->FP1_CONORI
		CMAILORI := FP1->FP1_EMAORI
		CTELORI  := "( "+FP1->FP1_DDDORI+" ) "+FP1->FP1_TELORI
	ENDIF
	
	OOBJPRINT:SAY( 0995 + NLIN , 0180 ,  FP1->FP1_NOMORI                                          , OFONT10   , 100 )
	
	OOBJPRINT:SAY( 0995 + NLIN , 0850 ,  "ENDEREÇO:"                                              , OFONT10   , 100 )
	OOBJPRINT:SAY( 0995 + NLIN , 1080 ,  ALLTRIM(CENDORI)                                                 , OFONT10   , 100 )
	
	OOBJPRINT:SAY( 1025 + NLIN , 0060 ,  "BAIRRO:"                                                , OFONT10   , 100 )
	OOBJPRINT:SAY( 1025 + NLIN , 0180 ,   ALLTRIM(CBAIORI)               , OFONT10   , 100 )
	
	OOBJPRINT:SAY( 1025 + NLIN , 0980 ,  "CIDADE:"                                                , OFONT10   , 100 )
	OOBJPRINT:SAY( 1025 + NLIN , 1150 ,  ALLTRIM(CMUNORI)                                         , OFONT10   , 100 )
	
	OOBJPRINT:SAY( 1025 + NLIN , 1800 ,  "ESTADO:"                                                , OFONT10   , 100 )
	OOBJPRINT:SAY( 1025 + NLIN , 1980 ,  CESTORI                                                  , OFONT10   , 100 )
	
	OOBJPRINT:SAY( 1065 + NLIN , 0060 ,  "CONTATO:"                                               , OFONT10   , 100 )
	OOBJPRINT:SAY( 1065 + NLIN , 0180 ,  ALLTRIM(CCONTORI)                                        , OFONT10   , 100 )
	
	OOBJPRINT:SAY( 1065 + NLIN , 0750 ,  "E-MAIL:"                                                , OFONT10   , 100 )
	OOBJPRINT:SAY( 1065 + NLIN , 0900 ,  ALLTRIM(CMAILORI)                                        , OFONT10   , 100 )
	
	OOBJPRINT:SAY( 1065 + NLIN , 1600 ,  "TELEFONE:"                                              , OFONT10   , 100 )
	OOBJPRINT:SAY( 1065 + NLIN , 1880 ,  ALLTRIM(CTELORI)                                         , OFONT10   , 100 )
	
	OOBJPRINT:BOX( 1150 + NLIN , 0050, 1210 + NLIN, 2370)
	OOBJPRINT:SAY( 1170 + NLIN , 1000 ,  "EQUIPAMENTOS / VALORES"                                 , OFONT5   , 100 )
	OOBJPRINT:BOX( 1210 + NLIN , 0050, 1500 + NLIN, 2370)
	
	OOBJPRINT:SAY( 1220 + NLIN , 0060 ,  "DESCRIÇÃO PRODUTO: "   +ALLTRIM(FP4->FP4_DESPRO)                , OFONT10   , 100 )
	OOBJPRINT:SAY( 1250 + NLIN , 0060 ,  "DESCRIÇÃO EQUIPAMENTO\MÃO DE OBRA: "   +ALLTRIM(FP4->FP4_DESGUI)+" - SÉRIE: "+POSICIONE("ST9",1, XFILIAL("ST9") + FP4->FP4_GUINDA ,"T9_SERIE")                , OFONT10   , 100 )

	OOBJPRINT:SAY( 1220 + NLIN , 0960 ,  "CONFIGURAÇÃO: "+ALLTRIM(FP4->FP4_CONFIG)                , OFONT10   , 100 )
	OOBJPRINT:SAY( 1240 + NLIN , 1860 ,  "FROTA: "       +ALLTRIM(FP4->FP4_GUINDA)                , OFONT10   , 100 )
	
	OOBJPRINT:SAY( 1300 + NLIN , 0060 ,  "MIN.HS.DIA"                                             , OFONT10   , 100 )
	OOBJPRINT:SAY( 1350 + NLIN , 0090 ,  TRANSFORM(FP4->FP4_MINDIA,"@E 9999")                     , OFONT10   , 100 )
	
	OOBJPRINT:SAY( 1300 + NLIN , 0260 ,  "MIN.HS.MÊS"                                             , OFONT10   , 100 )
	
	IF (FP4->FP4_TIPOCA=='M' .AND. FP4->FP4_MINMES <> 1) .OR. FP4->FP4_TIPOCA<>'M'
		OOBJPRINT:SAY( 1350 + NLIN , 0290 ,  TRANSFORM(FP4->FP4_MINMES,"@E 9999")                     , OFONT10   , 100 )
	ENDIF
	
	OOBJPRINT:SAY( 1300 + NLIN , 0490 ,  "TEMPO"                                                  , OFONT10   , 100 )
	OOBJPRINT:SAY( 1350 + NLIN , 0530 ,  TRANSFORM(FP4->FP4_PREDIA,"@E 9999")                     , OFONT10   , 100 )
	
	OOBJPRINT:SAY( 1300 + NLIN , 0650 ,  "BASE CÁLCULO"                                           , OFONT10   , 100 )
	OOBJPRINT:SAY( 1350 + NLIN , 0650 ,  IF(FP4->FP4_TIPOCA=='H','HORA',IF(FP4->FP4_TIPOCA=='D','DIA',IF(FP4->FP4_TIPOCA=='M','MES',IF(FP4->FP4_TIPOCA=='F','FECHADO','' ) ) ) )                                            , OFONT10   , 100 )
	
	OOBJPRINT:SAY( 1300 + NLIN , 0890 ,  "VALOR BASE"                                             , OFONT10   , 100 )
	OOBJPRINT:SAY( 1350 + NLIN , 0880 ,  TRANSFORM(FP4->FP4_VRHOR,"@E 999,999,999.99")            , OFONT10   , 100 )
	
	NVALOR := FP4->FP4_VRMOB + FP4->FP4_VRDES
	
	OOBJPRINT:SAY( 1300 + NLIN , 1120 ,  "VALOR A DISP"                                           , OFONT10   , 100 )
	OOBJPRINT:SAY( 1350 + NLIN , 1140 ,  TRANSFORM(FP4->FP4_VRDIS,"@E 999,999,999.99")            , OFONT10   , 100 )
	
	IF NVALOR == 0
		OOBJPRINT:SAY( 1300 + NLIN , 1360 ,  "TRANSP/PESO"                                            , OFONT10   , 100 )
		OOBJPRINT:SAY( 1350 + NLIN , 1370 ,  TRANSFORM(FP4->FP4_VRPESO,"@E 999,999,999.99")           , OFONT10   , 100 )
		
		OOBJPRINT:SAY( 1300 + NLIN , 1620 ,  "EST.C.PESO"                                            , OFONT10   , 100 )
		OOBJPRINT:SAY( 1350 + NLIN , 1600 ,  TRANSFORM(FP4->FP4_VRESTA,"@E 9,999,999.99")           , OFONT10   , 100 )
		
	ELSE
		OOBJPRINT:SAY( 1300 + NLIN , 1360 ,  "MOB/DESMOB"                                             , OFONT10   , 100 )
		OOBJPRINT:SAY( 1350 + NLIN , 1370 ,  TRANSFORM(NVALOR,"@E 999,999,999.99")                                         , OFONT10   , 100 )
	ENDIF
	
	OOBJPRINT:SAY( 1300 + NLIN , 1830 ,  "SEGURO"                                                 , OFONT10   , 100 )
	OOBJPRINT:SAY( 1350 + NLIN , 1780 ,  TRANSFORM(FP4->FP4_VRSEGU,"@E 999,999,999.99")                                , OFONT10   , 100 )
	
	NCALC:=LOCA041(FP4->FP4_TIPOCA,FP4->FP4_VRHOR,FP4->FP4_PREDIA,FP4->FP4_MINDIA,FP4->FP4_MINMES,FP4->FP4_QTDIA,FP4->FP4_QTMES)
	NCALC:=NCALC+NVALOR+FP4->FP4_VRSEGU+FP4->FP4_VRPESO
	
	// --> SE O ISS ESTIVER INCLUSO NO VALOR, DIMINUIR O MESMO DO SUBTOTAL
	IF FP4->FP4_TPISS == "I"
		NCALC-=FP4->FP4_VRISS
	ENDIF
	
	OOBJPRINT:SAY( 1300 + NLIN , 2000 ,  "SUBTOTAL"                                               , OFONT10   , 100 )
	OOBJPRINT:SAY( 1350 + NLIN , 1950 ,  TRANSFORM(NCALC,"@E 9,999,999,999.99")                , OFONT10   , 100 )
	
	OOBJPRINT:SAY( 1300 + NLIN , 2200 ,  "ISS"                                          , OFONT10   , 100 )
	OOBJPRINT:SAY( 1350 + NLIN , 2125 ,  TRANSFORM(FP4->FP4_VRISS,"@E 9,999,999,999.99")                           , OFONT10   , 100 )
	
	NCALCT:=0
	IF FP4->FP4_TPISS <> "I"
		NCALC:=NCALC+FP4->FP4_VRISS
	ENDIF
	
	NCALCT+=NCALC
	IIF(FP4->FP4_TPISS == "I",NCALCT+=FP4->FP4_VRISS,NCALCT)
	OOBJPRINT:SAY( 1400 + NLIN , 2010 ,  "TOTAL: "                                           , OFONT10   , 100 )
	OOBJPRINT:SAY( 1400 + NLIN , 2130 ,  TRANSFORM(NCALCT,"@E 9,999,999,999.99")               , OFONT10   , 100 )
	
	NLIN+=50
	
 //	OOBJPRINT:BOX( 1370 + NLIN , 0050, 1470 + NLIN, 2370)
	
	OOBJPRINT:SAY( 1410 + NLIN , 0060 ,  "TIPO ISS:"                                         , OFONT10   , 100 )
	OOBJPRINT:SAY( 1410 + NLIN , 0190 ,  IIF(FP4->FP4_TPISS == "I","INCLUSO",IIF(FP4->FP4_TPISS == "N","NAO INCLUSO","N/A") ) , OFONT10   , 100 )
	
	OOBJPRINT:SAY( 1410 + NLIN , 0640 ,  "% ISS: " + TRANSFORM(FP4->FP4_PERISS,"@E 999.999")    , OFONT10   , 100 )
	
	OOBJPRINT:SAY( 1410 + NLIN , 1150 ,  "TIPO DE SEGURO:"                              , OFONT10   , 100 )
	OOBJPRINT:SAY( 1410 + NLIN , 1380 ,  IIF(FP4->FP4_TPSEGU == "I","INCLUSO",IIF(FP4->FP4_TPSEGU == "N","NAO INCLUSO","CLIENTE") ) , OFONT10   , 100 )
	
	OOBJPRINT:SAY( 1410 + NLIN , 1650 ,  "% DE SEGURO: " + TRANSFORM(FP4->FP4_PERSEG,"@E 999.999")    , OFONT10   , 100 )
	
	OOBJPRINT:SAY( 1410 + NLIN , 1970 ,  "% DE M.O: " + TRANSFORM(FP4->FP4_PERMAO,"@E 999.999")        , OFONT10   , 100 )
	
	OOBJPRINT:BOX( 1450 + NLIN , 0050, 1510+NLIN, 2370)
	OOBJPRINT:SAY( 1470 + NLIN , 1080 ,  "MEDIÇÕES"                                     , OFONT5   , 100 )
	OOBJPRINT:BOX( 1510 + NLIN , 0050, 1630 + NLIN, 2370)
	
	IF TRIM(FP4->FP4_TPMEDI) == "S"
		CTPLOCACAO:= "SEMANAL"
	ELSEIF TRIM(FP4->FP4_TPMEDI) == "Q"
		CTPLOCACAO:= "QUINZENAL"
	ELSEIF TRIM(FP4->FP4_TPMEDI) == "M"
		CTPLOCACAO:= "MENSAL"
	ELSEIF TRIM(FP4->FP4_TPMEDI) == "E"
		CTPLOCACAO:= "ENCERRAMENTO"
	ELSEIF EMPTY(FP4->FP4_TPMEDI)
		CTPLOCACAO:= ""
	ENDIF
	
	DO CASE
	CASE FP4->FP4_APOHRS == "1"
		CHRSAPON := "CHEGADA DO EQUIPAMENTO NA OBRA"
	CASE FP4->FP4_APOHRS == "2"
		CHRSAPON := "DA SAIDA APO RETORNO"
	CASE FP4->FP4_APOHRS == "3"
		CHRSAPON := "APOS A MONTAGEM DO EQUIPAMENTO"
	OTHERWISE
		CHRSAPON := ""
	ENDCASE
	
	OOBJPRINT:SAY( 1530 + NLIN , 0060 ,  "LOCAÇÃO:"                                     , OFONT10   , 100 )
	OOBJPRINT:SAY( 1530 + NLIN , 0190 ,  CTPLOCACAO		                                , OFONT10   , 100 )
	
	OOBJPRINT:SAY( 1530 + NLIN , 0720 ,  "APON. HRS:"                                     , OFONT10   , 100 )
	OOBJPRINT:SAY( 1530 + NLIN , 0870 ,  CHRSAPON		                                , OFONT10   , 100 )
	
	OOBJPRINT:SAY( 1530 + NLIN , 1450 ,  "FORMA DE PAGAMENTO:"                          , OFONT10   , 100 )
	OOBJPRINT:SAY( 1530 + NLIN , 1800 ,  ALLTRIM(SE4->E4_DESCRI)+" "+ALLTRIM(CTPPAG)    , OFONT10   , 100 )
	
	IF TRIM(FP4->FP4_TPMEDM) == "S"
		CTPLOCACAO:= "SEMANAL"
	ELSEIF TRIM(FP4->FP4_TPMEDM) == "Q"
		CTPLOCACAO:= "QUINZENAL"
	ELSEIF TRIM(FP4->FP4_TPMEDM) == "M"
		CTPLOCACAO:= "MENSAL"
	ELSEIF TRIM(FP4->FP4_TPMEDM) == "I"
		CTPLOCACAO:= "1A. MEDICAO"
	ELSEIF TRIM(FP4->FP4_TPMEDM) == "O"
		CTPLOCACAO:= "INICIO DA MOBILIZACAO"
	ELSEIF TRIM(FP4->FP4_TPMEDM) == "E"
		CTPLOCACAO:= "ENCERRAMENTO"
	ELSEIF EMPTY(FP4->FP4_TPMEDM)
		CTPLOCACAO:= ""
	ENDIF
	
	OOBJPRINT:SAY( 1580 + NLIN , 0060 ,  "MOBILIZAÇÃO:"                                 , OFONT10   , 100 )
	OOBJPRINT:SAY( 1580 + NLIN , 0230 ,  CTPLOCACAO , OFONT10   , 100 )
	
	IF     TRIM(FP4->FP4_TPMEDD) == "S"
		CTPLOCACAO:= "SEMANAL"
	ELSEIF TRIM(FP4->FP4_TPMEDD) == "Q"
		CTPLOCACAO:= "QUINZENAL"
	ELSEIF TRIM(FP4->FP4_TPMEDD) == "M"
		CTPLOCACAO:= "MENSAL"
	ELSEIF TRIM(FP4->FP4_TPMEDD) == "I"
		CTPLOCACAO:= "JUNTO 1A.MEDICAO"
	ELSEIF TRIM(FP4->FP4_TPMEDD) == "O"
	 //	CTPLOCACAO:= "INICIO DA DESMOBILIZACAO"
		CTPLOCACAO:= "INICIO DO SERVIÇO"
	ELSEIF TRIM(FP4->FP4_TPMEDD) == "E"
	 //	CTPLOCACAO:= "ENCERRAMENTO"
		CTPLOCACAO:= "TÉRMINO DO SERVIÇO"
	ELSEIF TRIM(FP4->FP4_TPMEDD) == "C"
		CTPLOCACAO:= "INICIO DA MOBILIZACAO"
	ELSEIF TRIM(FP4->FP4_TPMEDD) == "N"
		CTPLOCACAO:= "NENHUMA"
	ELSEIF EMPTY(FP4->FP4_TPMEDD)
		CTPLOCACAO:= ""
	ENDIF
	
	OOBJPRINT:SAY( 1580 + NLIN , 1450 ,  "DESMOBILIZAÇÃO:"                              , OFONT10   , 100 )
	OOBJPRINT:SAY( 1580 + NLIN , 1700 ,  CTPLOCACAO , OFONT10   , 100 )
	
	OOBJPRINT:BOX( 1630 + NLIN , 0050, 1860+NLIN, 2370)
	OOBJPRINT:SAY( 1650 + NLIN , 1000 ,  "RESPONSABILIDADES"                            , OFONT5   , 100 )
	
 //	OOBJPRINT:BOX( 1710, 0050, 1730, 2370)
	
	OOBJPRINT:SAY( 1710 + NLIN , 0060 ,  "DESCRIÇÃO:"                                   , OFONT10   , 100 )
	OOBJPRINT:SAY( 1710 + NLIN , 0750 ,  "RESP."                                       , OFONT10   , 100 )
	
	NQUANTZAA := 0
	CQUERY := " SELECT COUNT(*) AS TOTAL "
	CQUERY += " FROM "+RETSQLNAME("FP6")+" "
	CQUERY += " WHERE  FP6_PROJET = '"+FQ5->FQ5_SOT+"' AND FP6_OBRA = '"+FQ5->FQ5_OBRA+"' AND D_E_L_E_T_ = ' ' "
	CQUERY += " 
	
	TCQUERY CQUERY NEW ALIAS "TRB"
	DBSELECTAREA("TRB")
	NTOTRESP := TRB->TOTAL
	NQTDCOL  := NTOTRESP / 2
	NRESTO   := MOD(NQTDCOL,1)
	
	DBSELECTAREA("TRB")
	DBCLOSEAREA()
	
	AAREAZAA := FP6->(GETAREA())
	DBSELECTAREA("FP6")
	DBSETORDER(1)
	DBGOTOP()
	MSSEEK(XFILIAL("FP6") + FQ5->FQ5_SOT + FQ5->FQ5_OBRA )
	NLINBKP := NLIN
	WHILE !EOF() .AND. FP6->FP6_PROJET + FP6->FP6_OBRA == FQ5->FQ5_SOT + FQ5->FQ5_OBRA
		
		OOBJPRINT:SAY( NLINHA + NLIN  , 0060 + NCOL1 ,  FP6->FP6_DESCRI              , OFONT10   , 100 )
		OOBJPRINT:SAY( NLINHA + NLIN  , 0760 + NCOL2 ,  IIF(UPPER(ALLTRIM(FP6->FP6_RESPON))=="C","CLIENTE","PRÓPRIA" ) , OFONT10   , 100 )
		
		NQUANTZAA++
		
		IF ( NLINHA + NLIN >= 3300 .OR. NQUANTZAA >= NQTDCOL ) .AND. LCHEK
			NAUX      := NLINHA + NLIN
			NQUANTZAA := 0
			NCOL1     := 1060
			NCOL2     := 1150
			NLINHA    := 1710
			NLIN      := NLINBKP
			LCHEK     := .F.
			LOBS      := .T.
			OOBJPRINT:SAY( NLINHA + NLIN , 0060 + NCOL1 ,  "DESCRIÇÃO"                                   , OFONT10   , 100 )
			OOBJPRINT:SAY( NLINHA + NLIN , 0760 + NCOL2 ,  "RESP."                                       , OFONT10   , 100 )
		ELSEIF NLINHA + NLIN >= 3300 .AND. !LCHEK
			OOBJPRINT:ENDPAGE()
			OOBJPRINT:STARTPAGE()
			NLIN   := 200
			NLINHA := 000
			NCOL1  := 0
			NCOL2  := 0
			OOBJPRINT:SAY( NLINHA + NLIN , 0060 ,  "DESCRIÇÃO"                                   , OFONT10   , 100 )
			OOBJPRINT:SAY( NLINHA + NLIN , 0750 ,  "RESP."                                       , OFONT10   , 100 )
		ENDIF
		
		DBSELECTAREA("FP6")
		DBSKIP()
		
		NLINHA := NLINHA + 50
		
	ENDDO 
	
	RESTAREA(AAREAZAA)
	
	IF LOBS
		NLINHA := NAUX + 100
	ELSE
		NLINHA := NLINHA + NLIN + 100
	ENDIF
	
	IF NLINHA > 3350
		OOBJPRINT:ENDPAGE()
		OOBJPRINT:STARTPAGE()
		NLIN   := 200
		NLINHA := 000
	ENDIF
	
	OOBJPRINT:SAY( NLINHA , 1050 ,  "OBSERVAÇÕES"                                 , OFONT5   , 100 )
	
	XT   := MLCOUNT(FP1->FP1_OBSVIS,130)
	NAUX := (XT*050)+100
	
	OOBJPRINT:BOX( NLINHA , 0050 , 3350  , 2370)
	
	NLINOBS := NLINHA + 50
	
	IF !EMPTY(FP1->FP1_OBSVIS)
		OOBJPRINT:SAY( NLINOBS , 0060 ,  "OBSERVAÇÃO VISTORIA"        , OFONT10   , 100 )
		NLINOBS := NLINOBS + 50
		FOR I:=1 TO XT
			OOBJPRINT:SAY( NLINOBS , 0060 ,  MEMOLINE(FP1->FP1_OBSVIS ,130, I )       , OFONT10   , 100 )
			IF NLINOBS > 3100
				OOBJPRINT:ENDPAGE()
				OOBJPRINT:STARTPAGE()
				OOBJPRINT:BOX( 0100 , 0050 , 3350 , 2370)
				NLINOBS := 100
			ENDIF
			NLINOBS := NLINOBS + 50
		NEXT
	ENDIF
	
	IF !EMPTY(FP4->FP4_OBSSER)
		XT := MLCOUNT(FP4->FP4_OBSSER,130)
		NLINOBS += 50
		OOBJPRINT:SAY( NLINOBS , 0060 ,  "OBSERVAÇÃO EQUIPAMENTO"        , OFONT10   , 100 )
		NLINOBS := NLINOBS + 50
		FOR I:=1 TO XT
			OOBJPRINT:SAY( NLINOBS , 0060 ,  MEMOLINE(FP4->FP4_OBSSER ,130, I )       , OFONT10   , 100 )
			IF NLINOBS > 3100
				OOBJPRINT:ENDPAGE()
				OOBJPRINT:STARTPAGE()
				OOBJPRINT:BOX( 0100 , 0050 , 3350 , 2370)
				NLINOBS := 150
			ENDIF
			NLINOBS := NLINOBS + 50
		NEXT
	ENDIF
	
	IF !EMPTY(FP1->FP1_OBSFAT)
		XT := MLCOUNT(FP1->FP1_OBSFAT,130)
		NLINOBS += 50
		OOBJPRINT:SAY( NLINOBS , 0060 ,  "OBSERVAÇÃO FATURAMENTO"        , OFONT10   , 100 )
		NLINOBS := NLINOBS + 50
		FOR I:=1 TO XT
			OOBJPRINT:SAY( NLINOBS , 0060 ,  MEMOLINE(FP1->FP1_OBSFAT ,130, I )       , OFONT10   , 100 )
			IF NLINOBS > 3100
				OOBJPRINT:ENDPAGE()
				OOBJPRINT:STARTPAGE()
				OOBJPRINT:BOX( 0100 , 0050 , 3350 , 2370)
				NLINOBS := 150
			ENDIF
			NLINOBS := NLINOBS + 50
		NEXT
	ENDIF
	
	FP5->(DBCLOSEAREA())
	DBSELECTAREA("FP5")
	FP5->(DBCLEARFILTER())
	FP5->(DBSETFILTER({|| ALLTRIM(FP5->FP5_PROJET) == ALLTRIM(FP4->FP4_PROJET) .AND. ALLTRIM(FP5->FP5_OBRA) == ALLTRIM(FP4->FP4_OBRA)},"ALLTRIM(FP5->FP5_PROJET) == ALLTRIM(FP4->FP4_PROJET) .AND. ALLTRIM(FP5->FP5_OBRA) == ALLTRIM(FP4->FP4_OBRA)"))
	FP5->(DBGOTOP())
	
	IF !EMPTY(FP5->FP5_OBSACE)
		XT := MLCOUNT(FP5->FP5_OBSACE,130)
		NLINOBS += 50
		OOBJPRINT:SAY( NLINOBS , 0060 ,  "OBSERVAÇÃO IÇAMENTO"       , OFONT10   , 100 )
		NLINOBS := NLINOBS + 50
		FOR I:=1 TO XT
			OOBJPRINT:SAY( NLINOBS , 0060 ,  MEMOLINE(FP5->FP5_OBSACE ,130, I )       , OFONT10   , 100 )
			IF NLINOBS > 3200
				OOBJPRINT:ENDPAGE()
				OOBJPRINT:STARTPAGE()
				OOBJPRINT:BOX( 0100 , 0050 , 3350 , 2370)
				NLINOBS := 150
			ENDIF
			NLINOBS := NLINOBS + 50
		NEXT
	ENDIF
	
	IF !EMPTY(FP5->FP5_OBS)
		XT := MLCOUNT(FP5->FP5_OBS,130)
		NLINOBS += 50
		OOBJPRINT:SAY( NLINOBS , 0060 ,  "OBSERVAÇÃO"        , OFONT10   , 100 )
		NLINOBS := NLINOBS + 50
		FOR I:=1 TO XT
			OOBJPRINT:SAY( NLINOBS , 0060 ,  MEMOLINE(FP5->FP5_OBS ,130, I )       , OFONT10   , 100 )
			IF NLINOBS > 3200
				OOBJPRINT:ENDPAGE()
				OOBJPRINT:STARTPAGE()
				OOBJPRINT:BOX( 0100 , 0050 , 3350 , 2370)
				NLINOBS := 150
			ENDIF
			NLINOBS := NLINOBS + 50
		NEXT
	ENDIF
	
	OOBJPRINT:ENDPAGE()
	LCHEK  := .T.
	NCOL1  := 0
	NCOL2  := 0
	
	FQ5->(DBSKIP())
ENDDO 

RETURN
