#INCLUDE "locr027.ch" 
/*/{PROTHEUS.DOC} LOCR027.PRW
ITUP BUSINESS - TOTVS RENTAL
RELATORIO DE MINUTA DE FRETE DE LOCAÇÃO DE TRANSPORTE
@TYPE FUNCTION
@AUTHOR FRANK ZWARG FUGA
@SINCE 03/12/2020
@VERSION P12
@HISTORY 03/12/2020, FRANK ZWARG FUGA, FONTE PRODUTIZADO.
/*/

#INCLUDE "PROTHEUS.CH"
#INCLUDE "TBICONN.CH"
#INCLUDE "COLORS.CH"
#INCLUDE "RPTDEF.CH"
#INCLUDE "FWPRINTSETUP.CH"

FUNCTION LOCR027( NPARAMENTR )
LOCAL LADJUSTTOLEGACY := .F. 
LOCAL LDISABLESETUP   := .F. 
LOCAL NRET 

PRIVATE CLOCAL    := "C:\TRANSPORTE\"
PRIVATE CARQUIVO  := STR0001+STR0002+ALLTRIM(FPF->FPF_PROJET)+"_"+STRTRAN(TIME(),":","")+".PDF" //"TRANSPORTE RODOVIARIO "###"PROJETO "
PRIVATE CPROJETO  := FPF->FPF_PROJET
PRIVATE COBRA     := FPF->FPF_OBRA
PRIVATE CAS       := FPF->FPF_AS
PRIVATE DDATA     := FPF->FPF_DATA
PRIVATE CMINUTA   := CEMPANT + FPF->FPF_FILIAL + FPF->FPF_MINUTA
PRIVATE CLSTAS    := ""
PRIVATE NOPC      := NPARAMENTR
PRIVATE I         := 0
PRIVATE NLIN      := 10
PRIVATE NFIM      := 55
PRIVATE CLOGO	  := ""
PRIVATE NVALOR	  := 0
PRIVATE CTIPO	  := ""
PRIVATE CPERG	  := "LOCP066"
PRIVATE L 		  := 1
PRIVATE CTEXTO    := STR0003 //"1A VIA - EMPRESA"
PRIVATE CDESCTIPO := STR0004 //"ENTREGA DE EQUIPAMENTO"
PRIVATE OPRINTER 

NRET := MAKEDIR("C:\TRANSPORTE") 

IF NOPC != 3
	IF NOPC = 1
		LDISABLESETUP := .F.
	ELSE
	  	LDISABLESETUP := .T.
	ENDIF

	OPRINTER := FWMSPRINTER():NEW(CARQUIVO, 6, LADJUSTTOLEGACY,, LDISABLESETUP, , , , , , .F., )
	OPRINTER:CPATHPDF := CLOCAL
	OPRINTER:SETPORTRAIT()
	OPRINTER:SETPAPERSIZE(9)
	IF NOPC = 1
		OPRINTER:SETVIEWPDF( .T. )
	ELSE
		OPRINTER:SETVIEWPDF( .F. )
	ENDIF

	OFONT1 := TFONTEX():NEW(OPRINTER,"TIMES NEW ROMAN",08,08,.T.,.T.,.F.)// 1
	OFONT2 := TFONTEX():NEW(OPRINTER,"TIMES NEW ROMAN",08,08,.F.,.F.,.F.)// 1
	OFONT3 := TFONTEX():NEW(OPRINTER,"TIMES NEW ROMAN",16,16,.T.,.T.,.F.)// 1
ENDIF



// LOGO
IF CFILANT $ "0101|0102|0201|0401"
	CLOGO := GETSRVPROFSTRING("STARTPATH","") + SUPERGETMV("MV_LOCX016",,"\SYSTEM\") // parametro removido do produto      
ELSE
	CLOGO := GETSRVPROFSTRING("STARTPATH","") + SUPERGETMV("MV_LOCX017",,"\SYSTEM\")  // parametro removido do produto
ENDIF

// VERIFICAÇÃO DE CARGAS JUNTAS
FQ5->( DBSETORDER(9) )	//	FQ5_FILIAL, FQ5_AS, FQ5_VIAGEM
FQ5->( DBSEEK( XFILIAL("FQ5") + CAS, .T. ) )
AAREADTQ := FQ5->( GETAREA() )

_ASS        := {}
_FQ5_FILIAL := FQ5->FQ5_FILIAL
_FQ5_SOT    := FQ5->FQ5_SOT
_FQ5_OBRA   := FQ5->FQ5_OBRA
_FQ5_AS     := FQ5->FQ5_AS
_FQ5_SEQCAR := FQ5->FQ5_SEQCAR
_FQ5_JUNTO  := FQ5->FQ5_JUNTO

FQ5->( DBSETORDER(8) )	//	FQ5_FILIAL, FQ5_SOT, FQ5_OBRA, FQ5_AS, R_E_C_N_O_, D_E_L_E_T_
FQ5->( DBSEEK( _FQ5_FILIAL + _FQ5_SOT + _FQ5_OBRA, .T. ) )
WHILE ! FQ5->( EOF() ) .AND. FQ5->FQ5_FILIAL == _FQ5_FILIAL .AND. FQ5->FQ5_SOT == _FQ5_SOT .AND. FQ5->FQ5_OBRA == _FQ5_OBRA
	IF ASCAN( _ASS, {|X| X[4] == FQ5->( RECNO() ) } ) == 0 .AND. (;
		_FQ5_SEQCAR == FQ5->FQ5_JUNTO .OR.;
		( !EMPTY(_FQ5_JUNTO) .AND. _FQ5_JUNTO == FQ5->FQ5_SEQCAR ) .OR.;
		( !EMPTY(_FQ5_JUNTO) .AND. _FQ5_JUNTO == FQ5->FQ5_JUNTO ) .OR.;
		ASCAN( _ASS, {|X| X[2] == FQ5->FQ5_JUNTO } ) > 0 .OR.;
		ASCAN( _ASS, {|X| X[3] == FQ5->FQ5_SEQCAR } ) > 0 )
		
		IF FQ5->FQ5_STATUS == '6'
			AADD( _ASS, { FQ5->FQ5_AS, FQ5->FQ5_SEQCAR, FQ5->FQ5_JUNTO, FQ5->( RECNO() ) } )
			CLSTAS    += IIF( EMPTY(CLSTAS),"", "," ) + "'"+ALLTRIM(FQ5->FQ5_VIAGEM)+"'"
			FQ5->( DBSEEK( _FQ5_FILIAL + _FQ5_SOT + _FQ5_OBRA, .T. ) )
			LOOP
		ENDIF
	ENDIF
	
	FQ5->( DBSKIP() )
ENDDO

IF LEN( _ASS ) == 0
	FQ5->( RESTAREA( AAREADTQ ) )
	IF FQ5->FQ5_STATUS == '6'
		AADD( _ASS, { FQ5->FQ5_AS, FQ5->FQ5_SEQCAR, FQ5->FQ5_JUNTO, FQ5->( RECNO() ) } )
		CLSTAS += "'"+ALLTRIM(FQ5->FQ5_VIAGEM)+"'"
	ENDIF
ENDIF

FQ5->( RESTAREA( AAREADTQ ) )

IF SELECT("TRBZA0") > 0
	TRBFP0->(DBCLOSEAREA())
ENDIF

CSQL:= " SELECT DISTINCT ZA0_CLI,ZA0_LOJA,ZA0_TIPOSE,ZA0_PROJET,ZA0_CLINOM"
CSQL += " ,ISNULL(CONVERT(VARCHAR(2047), CONVERT(VARBINARY(2047), FPS_OBS)),'') AS OBSZLW,FPS_LOCCAR,FPS_ENDORI,FPS_BRRORI,FPS_CIDORI,FPS_UFORI,FPS_LOCDES,FPS_ENDEST,FPS_BRRDES,FPS_CIDEST,FPS_UFDEST "
CSQL += " FROM "+RETSQLNAME("FP0")+ " ZA0"
CSQL += " LEFT JOIN "+RETSQLNAME("FPS")+" ZLW ON FPS_FILIAL='"+XFILIAL("FPS")+"' AND ZA0_PROJET = FPS_PROJET AND ZLW.D_E_L_E_T_ ='' "
CSQL += " WHERE ZA0_FILIAL='"+XFILIAL("FP0")+"'"
CSQL += " AND ZA0_PROJET ='"+CPROJETO+"' "
CSQL += " AND ZA0.D_E_L_E_T_ ='' "

PLSQUERY(CSQL,"TRBZA0")
DBSELECTAREA("TRBZA0")
TRBFP0->(DBGOTOP())

IF EMPTY(TRBFP0->FP0_CLI)
	MSGINFO(STR0005,STR0006) //"NÃO HÁ DADOS A SEREM EXIBIDOS,REVEJA OS PARAMETROS"###"ATENÇÃO"
	RETURN
ENDIF

FDADOS()

TRBFP0->( DBCLOSEAREA() )

RETURN NIL



// ======================================================================= \\
STATIC FUNCTION FDADOS()
// ======================================================================= \\

IF L = 1
	OPRINTER:STARTPAGE()
ELSE
	NFIM := NLIN + 45
ENDIF

CCNPJ:=POSICIONE("SA1",1,XFILIAL("SA1")+TRBFP0->FP0_CLI+TRBFP0->FP0_LOJA,"A1_CGC")

FP1->( DBSETORDER(1) )
FP1->( DBSEEK( XFILIAL("FP1") + CPROJETO + COBRA ) )		// POSICIONAMOS NA OBRA - CRISTIAM ROSSI EM 19/01/2016

OPRINTER:BOX(NLIN,10,NFIM,0590)
NLIN += 10
OPRINTER:SAYBITMAP(NLIN,515,CLOGO,0065,0030 )
NLIN+=2
OPRINTER:SAY(NLIN,020,STR0007+CMINUTA,OFONT3:OFONT) //"MINUTA DE FRETE - "
OPRINTER:SAY(NLIN,300,STR0008+TRBFP0->FP0_PROJET,OFONT3:OFONT) //"PROJETO: "
NLIN += 15
OPRINTER:SAY(NLIN,300,STR0009+ DTOC(FPF->FPF_DATA) ,OFONT3:OFONT) //"DATA: "
OPRINTER:SAY(NLIN,020,STR0010 + CDESCTIPO,OFONT3:OFONT) //"TIPO CARREGAMENTO: "
NLIN += 15
OPRINTER:SAY(NLIN,020,CTEXTO,OFONT3:OFONT)
NLIN+=5
NFIM+=15
OPRINTER:BOX(NLIN,0010,NFIM,0590)
NLIN += 10
OPRINTER:SAY(NLIN,0020,STR0011,OFONT2:OFONT) //"CLIENTE:"
OPRINTER:SAY(NLIN,0050,TRBFP0->FP0_CLINOM,OFONT2:OFONT)
OPRINTER:SAY(NLIN,0315,STR0012,OFONT2:OFONT) //"CNPJ:"
OPRINTER:SAY(NLIN,0335,CCNPJ,OFONT2:OFONT)
NLIN:=NFIM
NFIM+=15
OPRINTER:BOX(NLIN,0010,NFIM,0590)
NLIN += 10
OPRINTER:SAY(NLIN,0020,STR0013,OFONT2:OFONT) //"CARREGAMENTO:"
//	OPRINTER:SAY(0075,0070,DTOC(TRBSUM->ZA7_DTCAR)+" - "+TRANSFORM(TRBSUM->ZA7_HRCAR,"@R 99:99"),OFONT2:OFONT)

//	OPRINTER:SAY(0075,0315,"PRAZO DE VIAGEM:",OFONT2:OFONT)
OPRINTER:SAY(NLIN,0315,STR0014,OFONT2:OFONT) //"DATA LIMITE:"
//	NVALOR:= (VAL(DTOS(TRBFP0->ZA6_DTFIM)))-(VAL(DTOS(TRBFP0->ZA6_DTINI)))
NLIN:=NFIM
NLIN+=0015
OPRINTER:BOX(NLIN,0010,NFIM,0590)
NLIN += 10
OPRINTER:SAY(NLIN,0280,STR0015,OFONT2:OFONT) //"DADOS DO TRANSPORTADOR"


NLIN := NFIM
NFIM += 50
OPRINTER:BOX(NLIN,0010,NFIM,0590)
NLIN += 10
OPRINTER:SAY(NLIN,0020,STR0016   , OFONT2:OFONT) //"VEICULO "
OPRINTER:SAY(NLIN,0200,STR0017  , OFONT2:OFONT) //"N. FROTA "
OPRINTER:SAY(NLIN,0250,STR0018     , OFONT2:OFONT) //"PLACA "
OPRINTER:SAY(NLIN,0300,STR0019 , OFONT2:OFONT) //"MOTORISTA "
OPRINTER:SAY(NLIN,0450,STR0020  , OFONT2:OFONT) //"AUXILIAR "
NLIN += 10

// CONDIÇÃO PARA QUERY CERTA
IF FQ5->FQ5_TPAS == "F" .AND. LEFT(FPF->FPF_AS, 2) == "11" 

	CSQL := "SELECT R_E_C_N_O_ RECORD, FPS_FILIAL, FPS_PROJET, FPS_OBRA, FPS_SEQGUI FROM "+RETSQLNAME("FPS")
	CSQL += " WHERE FPS_VIAGEM = '"+ FQ5->FQ5_VIAGEM +"'"
	CSQL += " AND D_E_L_E_T_=''"
	CALIASQRY := GETNEXTALIAS()
	DBUSEAREA(.T.,"TOPCONN", TCGENQRY(,,CSQL), CALIASQRY, .F., .T.)

	IF (CALIASQRY)->( EOF() )
		MSGALERT(STR0021) //"NÃO HÁ DADOS!"
		RETURN NIL
	ENDIF
	
	FPS->( DBGOTO( (CALIASQRY)->RECORD ) )
	(CALIASQRY)->( DBCLOSEAREA() )

	IF SELECT("TRBTRA") > 0
		TRBTRA->(DBCLOSEAREA())
	ENDIF

	CSQL:= " SELECT DISTINCT FQ5_AS, FPS_X5COD,FPS_DESCRI, ISNULL(FQA_NOMMOT,'') FQA_NOMMOT, ISNULL(FQA_NOMAJU,'') FQA_NOMAJU, T9_CODBEM,T9_PLACA "
	CSQL+= " FROM "+RETSQLNAME("FPS") + " ZLW "
	CSQL+=        " LEFT  JOIN " + RETSQLNAME("FQA") + " ZB2 ON FQA_FILIAL='"+XFILIAL("FQA")+"'AND FPS_VIAGEM = FQA_VIAGEM AND ZB2.D_E_L_E_T_ = '' " 
	CSQL+=        " INNER JOIN " + RETSQLNAME("ST9") + " ST9 ON T9_FILIAL='"+XFILIAL("ST9")+"' AND FPS_X5COD = T9_CODBEM AND ST9.D_E_L_E_T_ = '' " 
	CSQL+=        " INNER JOIN " + RETSQLNAME("FQ5") + " DTQ ON FQ5_FILIAL='"+XFILIAL("FQ5")+"' AND FQ5_VIAGEM = FPS_VIAGEM AND  DTQ.D_E_L_E_T_ = '' " 
	CSQL+= " WHERE FPS_FILIAL='"+FPS->FPS_FILIAL+"' "
	CSQL+= " AND FPS_PROJET = '"+FPS->FPS_PROJET+"' "
	CSQL+= " AND FPS_OBRA = '"+FPS->FPS_OBRA+"' "
	CSQL+= " AND FPS_SEQGUI = '"+FPS->FPS_SEQGUI+"' "
	CSQL+= " AND ZLW.D_E_L_E_T_ ='' "

	PLSQUERY(CSQL,"TRBTRA")
	DBSELECTAREA("TRBTRA")
	TRBTRA->(DBGOTOP())

	N := 1
	WHILE TRBTRA->(! EOF() )
	
		ADADOS := LOCR02701( TRBTRA->FQ5_AS, DDATA, {"ST9->T9_NOME","SB1->B1_DESC","ST9->T9_CODBEM","ST9->T9_PLACA"} )
		IF LEN( ADADOS ) == 0
			TRBTRA->( DBSKIP() )
			LOOP
		ENDIF
		OPRINTER:SAY(NLIN,0020,LEFT( IIF( EMPTY(ADADOS[1,2]), ADADOS[1,1], ADADOS[1,2] ), 40 ),OFONT2:OFONT)
		OPRINTER:SAY(NLIN,0200,ADADOS[1,3],OFONT2:OFONT)
		OPRINTER:SAY(NLIN,0250,ADADOS[1,4],OFONT2:OFONT)
		IF N == 1
			OPRINTER:SAY( NLIN, 300,TRBTRA->FQA_NOMMOT, OFONT2:OFONT)
			OPRINTER:SAY( NLIN, 450,TRBTRA->FQA_NOMAJU, OFONT2:OFONT)
			NLIN+=10 
		ENDIF 
		N++	
	
		TRBTRA->(DBSKIP())
	ENDDO

ELSE

	IF SELECT("TRBTRA") > 0
		TRBTRA->(DBCLOSEAREA())
	ENDIF

	CSQL:= " SELECT FPF_FROTA, ISNULL(B1_DESC, T9_NOME) T9_NOME, T9_PLACA, ISNULL(ZLO1.FPQ_MAT,'') MOTORISTA, ISNULL(ZLO2.FPQ_MAT,'') AJUDANTE  FROM " + RETSQLNAME("FPF") + " ZBX "
	CSQL+= " INNER JOIN " + RETSQLNAME("ST9") + " ST9 ON T9_FILIAL='"+XFILIAL("ST9")+"' AND FPF_FROTA = T9_CODBEM AND ST9.D_E_L_E_T_ = '' "
	CSQL+= " AND T9_TIPOSE='T' "
	
	CSQL+= " LEFT JOIN " + RETSQLNAME("FPQ") + " ZLO1 ON ZLO1.FPQ_FILIAL='"+XFILIAL("FPQ")+"' AND ZLO1.FPQ_PROJET=FPF_PROJET AND ZLO1.FPQ_OBRA=FPF_OBRA AND ZLO1.FPQ_DATA=FPF_DATA "
	CSQL+= 		" AND ZLO1.FPQ_AS=FPF_AS AND ZLO1.FPQ_FUNCAO='M' AND ZLO1.D_E_L_E_T_='' "
	
	CSQL+= " LEFT JOIN " + RETSQLNAME("FPQ") + " ZLO2 ON ZLO2.FPQ_FILIAL='"+XFILIAL("FPQ")+"' AND ZLO2.FPQ_PROJET=FPF_PROJET AND ZLO2.FPQ_OBRA=FPF_OBRA AND ZLO2.FPQ_DATA=FPF_DATA "
	CSQL+= 		" AND ZLO2.FPQ_AS=FPF_AS AND ZLO2.FPQ_FUNCAO='A' AND ZLO2.D_E_L_E_T_='' "
	
	CSQL+= " LEFT JOIN " + RETSQLNAME("SB1") + " SB1 ON B1_FILIAL='"+XFILIAL("SB1")+"' AND B1_COD=T9_CODESTO AND SB1.D_E_L_E_T_='' "
	
	CSQL+= " WHERE FPF_FILIAL = '"+XFILIAL("FPF")+"' "
	CSQL+= " AND FPF_PROJET = '"+CPROJETO+"' "
	CSQL+= " AND FPF_OBRA = '"+COBRA+"' "
	CSQL+= " AND FPF_DATA = '"+DTOS(DDATA)+"' "
	CSQL+= " AND FPF_STATUS <> '5'" // INCLUIDO POR LUCAS CASSIANO 28/01/2016 PARA NAO TRAZER MINUTAS CANCELADAS 
	CSQL+= " AND ZBX.D_E_L_E_T_ = ''"
	PLSQUERY(CSQL,"TRBTRA")
	
	DBSELECTAREA("TRBTRA")
	TRBTRA->(DBGOTOP())
	
	WHILE TRBTRA->(! EOF() )
		OPRINTER:SAY(NLIN,0020,LEFT(TRBTRA->T9_NOME, 40 ),OFONT2:OFONT)
		OPRINTER:SAY(NLIN,0200,TRBTRA->FPF_FROTA,OFONT2:OFONT)
		OPRINTER:SAY(NLIN,0250,TRBTRA->T9_PLACA,OFONT2:OFONT)
		
		IF ! EMPTY( TRBTRA->MOTORISTA )
			DA4->( DBSETORDER(4) )
			IF DA4->( DBSEEK( XFILIAL("DA4")+TRBTRA->MOTORISTA ) )
				OPRINTER:SAY( NLIN, 300, DA4->DA4_NOME, OFONT2:OFONT)
			ENDIF
		ENDIF
		
		IF ! EMPTY( TRBTRA->AJUDANTE )
			DA4->( DBSETORDER(4) )
			IF DA4->( DBSEEK( XFILIAL("DA4")+TRBTRA->AJUDANTE ) )
				OPRINTER:SAY( NLIN, 450, DA4->DA4_NOME, OFONT2:OFONT)
			ENDIF
		ENDIF
		
		NLIN+=10
		TRBTRA->(DBSKIP())
	ENDDO

ENDIF

NLIN:=NFIM
NFIM+=15
OPRINTER:BOX(NLIN,0010,NFIM,0590)
NLIN += 10
OPRINTER:SAY(NLIN,0300,STR0022,OFONT2:OFONT) //"DADOS DAS PEÇAS"

NLIN:=NFIM
NFIM+=65
OPRINTER:BOX(NLIN,0010,NFIM,0590)
NLIN += 10
OPRINTER:SAY(NLIN,0020,STR0023,OFONT1:OFONT) //"NOME: "
OPRINTER:SAY(NLIN,0200,STR0024,OFONT1:OFONT) //"SÉRIE: "
OPRINTER:SAY(NLIN,0250,STR0025,OFONT1:OFONT) //"COMP.: "
OPRINTER:SAY(NLIN,0300,STR0026,OFONT1:OFONT) //"LARGURA: "
OPRINTER:SAY(NLIN,0350,STR0027,OFONT1:OFONT) //"ALTURA: "
OPRINTER:SAY(NLIN,0450,STR0028,OFONT1:OFONT) //"PESO UNITÁRIO: "
OPRINTER:SAY(NLIN,0540,STR0029,OFONT1:OFONT) //"PESO TOTAL: "
NLIN += 10

IF FP0->FP0_TIPOSE == "G" .AND. ST9->T9_TIPOSE = "T"  .AND. FQ5->FQ5_TPAS <> "F"

	IF SELECT("TRBTRA") > 0
		TRBTRA->(DBCLOSEAREA())
	ENDIF

	CSQL:= " SELECT * FROM " + RETSQLNAME("ZZN") + " ZZN "
	CSQL+= " WHERE ZZN_FILIAL = '"+XFILIAL("ZZN")+"' "
	CSQL+= " AND ZZN_PROJET = '"+CPROJETO+"' "
	CSQL+= " AND ZZN_OBRA = '"+COBRA+"' "
	CSQL+= " AND ZZN.D_E_L_E_T_ = ''"
	PLSQUERY(CSQL,"TRBTRA")

	DBSELECTAREA("TRBTRA")
	TRBTRA->(DBGOTOP())
	_NPESOT := 0
	WHILE TRBTRA->(! EOF() )

		OPRINTER:SAY(NLIN, 0020, LEFT(TRBTRA->ZZN_DESC, 40 ),OFONT2:OFONT)
		OPRINTER:SAY(NLIN, 0240, TRANSFORM(TRBTRA->ZZN_COMP, "@E 999,999.99")  , OFONT2:OFONT)
		OPRINTER:SAY(NLIN, 0300, TRANSFORM(TRBTRA->ZZN_LARG , "@E 999,999.99")  , OFONT2:OFONT)
		OPRINTER:SAY(NLIN, 0340, TRANSFORM(TRBTRA->ZZN_ALTU , "@E 9999,999.99") , OFONT2:OFONT)
		OPRINTER:SAY(NLIN, 0450, TRANSFORM(TRBTRA->ZZN_PESO , "@E 999,999.999") , OFONT2:OFONT)
	
		_NPESOT += TRBTRA->ZZN_PESO

		NLIN+=10
		TRBTRA->(DBSKIP())
	ENDDO
	TRBTRA->( DBCLOSEAREA() )

ELSE

	IF SELECT("TRBTRA") > 0
		TRBTRA->(DBCLOSEAREA())
	ENDIF

	//CSQL := " SELECT DISTINCT FP4_AS, FP4_DESGUI, T9_NOME, T9_SERIE, T9_COMPRI, T9_LARGU, T9_ALTUR, T9_PESO FROM "+RETSQLNAME("FP4") + " ZA5 "
	// t9_peso foi removido da 94
	// t9_largu foi removido da 94
	// t9_compri foi removido da 94
	// t9_altur foi removido da 94
	CSQL := " SELECT DISTINCT FP4_AS, FP4_DESGUI, T9_NOME, T9_SERIE  FROM "+RETSQLNAME("FP4") + " ZA5 "
	CSQL += " INNER JOIN " + RETSQLNAME("ST9") + " ST9 ON T9_FILIAL='"+XFILIAL("ST9")+"' AND FP4_GUINDA = T9_CODBEM AND ST9.D_E_L_E_T_ = '' " 
	CSQL += " WHERE FP4_FILIAL='"+FPS->FPS_FILIAL+"' "
	CSQL += " AND FP4_PROJET = '"+FPS->FPS_PROJET+"' "
	CSQL += " AND FP4_OBRA = '"+FPS->FPS_OBRA+"' "
	CSQL += " AND FP4_SEQGUI = '"+FPS->FPS_SEQGUI+"' "
	CSQL += " AND ZA5.D_E_L_E_T_ ='' "

	PLSQUERY(CSQL,"TRBTRA")
	DBSELECTAREA("TRBTRA")
	TRBTRA->(DBGOTOP())
	_NPESOT := 0
	WHILE TRBTRA->(! EOF() )

		//ADADOS := LOCR02701( TRBTRA->FP4_AS, DDATA, {"ST9->T9_NOME","SB1->B1_DESC","ST9->T9_SERIE","ST9->T9_COMPRI","ST9->T9_LARGU","ST9->T9_ALTUR","ST9->T9_PESO"} )
		// t9_peso foi removido da 94
		ADADOS := LOCR02701( TRBTRA->FP4_AS, DDATA, {"ST9->T9_NOME","SB1->B1_DESC","ST9->T9_SERIE"} )
		IF LEN( ADADOS ) == 0
			TRBTRA->( DBSKIP() )
			LOOP
		ENDIF

		_CDESCGUI := IIF( EMPTY( ADADOS[1,2] ), ADADOS[1,1],  ADADOS[1,2] )

		OPRINTER:SAY(NLIN, 0020, LEFT(_CDESCGUI, 40 ),OFONT2:OFONT)
		OPRINTER:SAY(NLIN, 0200, ADADOS[1,3],OFONT2:OFONT)
		OPRINTER:SAY(NLIN, 0240, TRANSFORM(ADADOS[1,4], "@E 999,999.99")  , OFONT2:OFONT)
		OPRINTER:SAY(NLIN, 0300, TRANSFORM(ADADOS[1,5] , "@E 999,999.99")  , OFONT2:OFONT)
		OPRINTER:SAY(NLIN, 0340, TRANSFORM(ADADOS[1,6] , "@E 9999,999.99") , OFONT2:OFONT)
		OPRINTER:SAY(NLIN, 0450, TRANSFORM(ADADOS[1,7] , "@E 999,999.999") , OFONT2:OFONT)

		_NPESOT += ADADOS[1,7]

		NLIN+=10
		TRBTRA->(DBSKIP())
	ENDDO
	TRBTRA->( DBCLOSEAREA() )
ENDIF

IF _NPESOT > 0
	OPRINTER:SAY(NLIN-10,0530,TRANSFORM(_NPESOT, "@E 99,999,999.99") , OFONT2:OFONT)
ENDIF

NLIN:=NFIM

NFIM+=70

OPRINTER:BOX(NLIN,0010,NFIM,0590)
NLIN+=10


OPRINTER:SAY(NLIN   ,0020 , STR0030         , OFONT2:OFONT) //"ORIGEM: "
OPRINTER:SAY(NLIN   ,0070 , STR0031          , OFONT2:OFONT) //"LOCAL: "
OPRINTER:SAY(NLIN   ,0090 , FP1->FP1_NOMORI    , OFONT2:OFONT)
NLIN += 10
OPRINTER:SAY(NLIN   ,0070 , STR0032       , OFONT2:OFONT) //"ENDEREÇO: "
OPRINTER:SAY(NLIN   ,0110 , FP1->FP1_ENDORI    , OFONT2:OFONT)

OPRINTER:SAY(NLIN   ,0300 , STR0033    , OFONT2:OFONT) //"COMPLEMENTO: "
NLIN += 10
OPRINTER:SAY(NLIN   ,0070 , STR0034         , OFONT2:OFONT) //"BAIRRO: "
OPRINTER:SAY(NLIN   ,0100 , FP1->FP1_BAIORI    , OFONT2:OFONT)

OPRINTER:SAY(NLIN   ,0240 , STR0035         , OFONT2:OFONT) //"CIDADE: "
OPRINTER:SAY(NLIN   ,0270 , FP1->FP1_MUNORI    , OFONT2:OFONT)
OPRINTER:SAY(NLIN   ,0540 , STR0036             , OFONT2:OFONT) //"UF: "
OPRINTER:SAY(NLIN   ,0560 , FP1->FP1_ESTORI    , OFONT2:OFONT)
NLIN += 10
OPRINTER:SAY(NLIN   ,0070 , STR0037        , OFONT2:OFONT) //"CONTATO: "
OPRINTER:SAY(NLIN   ,0100 , FP1->FP1_CONORI    , OFONT2:OFONT)
OPRINTER:SAY(NLIN   ,0240 , STR0038       , OFONT2:OFONT) //"TELEFONE: "
OPRINTER:SAY(NLIN   ,0270 , FP1->(ALLTRIM(FP1_DDDORI)+" "+FP1_TELORI),OFONT2:OFONT)

NLIN += 15
OPRINTER:SAY(NLIN   ,0020,STR0039,OFONT2:OFONT) //"DATA/HORA CHEGADA PORTARIA "
OPRINTER:BOX(NLIN-10,0120,NFIM-5,0240)
OPRINTER:SAY(NLIN   ,0320,STR0039,OFONT2:OFONT) //"DATA/HORA CHEGADA PORTARIA "
OPRINTER:BOX(NLIN-10,0420,NFIM-5,0580)
NLIN:=NFIM
NFIM:=NLIN+70
OPRINTER:BOX(NLIN,0010,NFIM,0590)
NLIN += 10

OPRINTER:SAY(NLIN+05,0020 , STR0040        , OFONT2:OFONT) //"DESTINO: "
OPRINTER:SAY(NLIN   ,0070 , STR0031          , OFONT2:OFONT) //"LOCAL: "
OPRINTER:SAY(NLIN   ,0090 , FP1->FP1_NOMDES    , OFONT2:OFONT)
NLIN += 10
OPRINTER:SAY(NLIN   ,0070 , STR0032       , OFONT2:OFONT) //"ENDEREÇO: "
OPRINTER:SAY(NLIN   ,0110 , FP1->FP1_ENDDES    , OFONT2:OFONT)

OPRINTER:SAY(NLIN   ,0300 , STR0033    , OFONT2:OFONT) //"COMPLEMENTO: "
NLIN += 10

OPRINTER:SAY(NLIN   ,0070 , STR0041          , OFONT2:OFONT) //"BAIRRO "
OPRINTER:SAY(NLIN   ,0100 , FP1->FP1_BAIDES    , OFONT2:OFONT)

OPRINTER:SAY(NLIN   ,0240 , STR0042          , OFONT2:OFONT) //"CIDADE "
OPRINTER:SAY(NLIN   ,0270 , FP1->FP1_MUNDES    , OFONT2:OFONT)

OPRINTER:SAY(NLIN   ,0540 , STR0043              , OFONT2:OFONT) //"UF "
OPRINTER:SAY(NLIN   ,0560 , FP1->FP1_ESTDES    , OFONT2:OFONT)

NLIN += 10
OPRINTER:SAY(NLIN   ,0070 , STR0044         , OFONT2:OFONT) //"CONTATO "
OPRINTER:SAY(NLIN   ,0100 , FP1->FP1_CONDES    , OFONT2:OFONT)
OPRINTER:SAY(NLIN   ,0240 , STR0045        , OFONT2:OFONT) //"TELEFONE "
OPRINTER:SAY(NLIN   ,0270 , FP1->(ALLTRIM(FP1_DDDDES)+" "+FP1_TELDES),OFONT2:OFONT)

NLIN += 15
OPRINTER:SAY(NLIN+5,0020,STR0039,OFONT2:OFONT) //"DATA/HORA CHEGADA PORTARIA "
OPRINTER:BOX(NLIN-10,0120,NFIM-5,0240)
OPRINTER:SAY(NLIN+5,0320,STR0039,OFONT2:OFONT) //"DATA/HORA CHEGADA PORTARIA "
OPRINTER:BOX(NLIN-10,0420,NFIM-5,0580)

NLIN := NFIM
NFIM += 40

OPRINTER:BOX(NLIN,0010,NFIM+25,0590)
NLIN += 10
OPRINTER:SAY(NLIN,0020,STR0046,OFONT2:OFONT) //"OBSERVAÇÃO: "
XT  := 4

NLIN:=NFIM
NFIM += 25
NLIN += 10

OPRINTER:SAY(NLIN,0160,"___________________________________________________",OFONT1:OFONT)
OPRINTER:SAY(NLIN,0370,"___________________________________________________",OFONT1:OFONT)
NLIN += 10
OPRINTER:SAY(NLIN,0020,STR0047,OFONT2:OFONT) //"DATA:   _____ / _______/ __________ "
OPRINTER:SAY(NLIN,0160,STR0048,OFONT2:OFONT) //"NOME / RG DO CLIENTE "
OPRINTER:SAY(NLIN,0370,STR0049,OFONT2:OFONT) //"ASSINATURA "

IF L =1
	CTEXTO:=STR0050 //"2A VIA - CLIENTE"
	NLIN += 10
	L:=2
	FDADOS()
ELSE
	IF NOPC != 3
		OPRINTER:ENDPAGE()
	//	U_RELBORDO() 						// RELATÓRIO DE BORDO
		CFILEPRINT := CLOCAL+CARQUIVO
		FILE2PRINTER( CFILEPRINT, "PDF" )
		OPRINTER:PREVIEW()
		FREEOBJ(OPRINTER)
		OPRINTER := NIL	
	ENDIF
ENDIF

RETURN .T.



// ======================================================================= \\
FUNCTION LOCR02701( _AS, _DATA, _CAMPOS )
// ======================================================================= \\
// --> RETORNA DADOS DA ZBX, ST9, SB1
LOCAL AAREA     := GETAREA()
LOCAL AAREAZBX  := FPF->( GETAREA() )
LOCAL AAREAST9  := ST9->( GETAREA() )
LOCAL AAREASB1  := SB1->( GETAREA() )
LOCAL ARET      := {}
LOCAL ATMP
LOCAL CQUERY
LOCAL CALIASQRY := GETNEXTALIAS()
LOCAL NI

ST9->( DBSETORDER(1) )
SB1->( DBSETORDER(1) )

CQUERY := "SELECT R_E_C_N_O_ RECORD FROM "+RETSQLNAME("FPF")
CQUERY += " WHERE FPF_AS='"+ _AS +"'"
CQUERY += " AND FPF_DATA='"+ DTOS(_DATA) +"'"
CQUERY += " AND D_E_L_E_T_= ''"
DBUSEAREA( .T., "TOPCONN", TCGENQRY(,,CQUERY), CALIASQRY, .F., .T.)

WHILE ! (CALIASQRY)->( EOF() )
	FPF->( DBGOTO( (CALIASQRY)->RECORD ) )

	ST9->( DBSEEK( XFILIAL("ST9") + FPF->FPF_FROTA , .F. ) )
	SB1->( DBSEEK( XFILIAL("SB1") + ST9->T9_CODESTO, .F. ) )

	ATMP := {}

	FOR NI := 1 TO LEN( _CAMPOS )
		AADD( ATMP, &( _CAMPOS[NI] ) )
	NEXT NI

	AADD( ARET, ACLONE( ATMP ) )

	(CALIASQRY)->( DBSKIP() )
ENDDO 

FPF->( RESTAREA( AAREAZBX ) )
ST9->( RESTAREA( AAREAST9 ) )
SB1->( RESTAREA( AAREASB1 ) )
RESTAREA( AAREA )

RETURN ACLONE(ARET)
