#INCLUDE "locr016.ch" 
/*/{PROTHEUS.DOC} LOCR016.PRW
ITUP BUSINESS - TOTVS RENTAL
GERA CONTRATO DE LOCA«√O ATRAV…S DA INTEGRA«√O WORD
@TYPE FUNCTION
@AUTHOR FRANK ZWARG FUGA
@SINCE 03/12/2020
@VERSION P12
@HISTORY 03/12/2020, FRANK ZWARG FUGA, FONTE PRODUTIZADO.
/*/

#INCLUDE "PROTHEUS.CH"
#INCLUDE "RWMAKE.CH"
#INCLUDE "TOPCONN.CH"
#INCLUDE "TBICONN.CH"
#INCLUDE "MSOLE.CH"
#INCLUDE "VKEY.CH"

FUNCTION LOCR016()
LOCAL AITENS := {"PDF" , "DOT"} 
LOCAL CCOMBO , CGETSB1 
LOCAL LOK    := .F.

PRIVATE CPATH     := SUPERGETMV("MV_LOCX273",.F.,"\DOT\") 
PRIVATE C_NOMEARQ := SUPERGETMV("MV_LOCX272",.F.,STR0001)  //"MODELO_CONTRATO.DOT"
PRIVATE CARQUIVO  := CPATH + C_NOMEARQ 

PRIVATE LTEM_DOT  := .F. 

IF FILE(CARQUIVO) 
	LTEM_DOT := .T. 
ELSE 
	CGETSB1  := FP0->FP0_PROJET 
ENDIF 

DEFINE MSDIALOG ODLG TITLE STR0002 FROM 000,000 TO 250,370 PIXEL  //"IMPRESS√O DE CONTRATO"
	@ 015,010 SAY    OSAY01   PROMPT STR0003 SIZE 170,010 OF ODLG PIXEL  //"ESTE PROGRAMA FAR¡ A IMPRESS√O DO CONTRATO POSICIONADO !"
  IF LTEM_DOT
	@ 042,010 SAY    OSAY03   PROMPT STR0004     SIZE 040,010 OF ODLG PIXEL  //"TIPO IMPRESS√O :"
	@ 040,055 MSCOMBOBOX OCOMBOBO1 VAR CCOMBO  ITEMS AITENS SIZE 038,010 OF ODLG PIXEL 

	@ 072,010 SAY    OSAY05   PROMPT STR0005     SIZE 040,010 OF ODLG PIXEL //"LOCAL P/ SALVAR:"
	@ 070,055 MSGET  OGETSB1       VAR CGETSB1 WHEN .F.     SIZE 115,010 OF ODLG PIXEL
	//@ 070,170 BUTTON OBTNFILE PROMPT "..."                  SIZE 010,010 ACTION (CGETSB1:=CGETFILE(".DOT",OEMTOANSI(STR0006),1,"C:\",.F.,NOR(GETF_LOCALHARD,GETF_NETWORKDRIVE ),.F.))       OF ODLG PIXEL  //"SELECIONE O LOCAL PARA SALVAR O ARQUIVO"
  ELSE 
	@ 042,010 SAY    OSAY05   PROMPT STR0007          SIZE 040,010 OF ODLG PIXEL  //"CONTRATO : "
	@ 040,055 MSGET  OGETSB1       VAR CGETSB1 WHEN .F.     SIZE 115,010 OF ODLG PIXEL 
  ENDIF 
	@ 100,025 BUTTON OBTNOK   PROMPT STR0008     SIZE 050,010 ACTION (IIF(!EMPTY(CGETSB1) , LJMSGRUN(STR0009 , , {||LOK := LOCR01601(CGETSB1,CCOMBO)}) , LOK:=.F.) , IIF(LOK , ODLG:END() , NIL)) OF ODLG PIXEL  //"IMPRIME CONTRATO"###"AGUARDE, IMPRIMINDO..."
	@ 100,115 BUTTON OBTNOK   PROMPT STR0010             SIZE 050,010 ACTION (LOK:=.F.,ODLG:END()) OF ODLG PIXEL  //"CANCELAR"
ACTIVATE MSDIALOG ODLG CENTERED 

RETURN



// ======================================================================= \\
FUNCTION LOCR01601(CCAMINHO,CCOMBO)
// ======================================================================= \\

//CAL NZAGQUANT := 0 
LOCAL NZAAQUANT := 0 

CCONTA			:= CCAMINHO
CWORD    		:= OLE_CREATELINK()
AZA0AREA 		:= GETAREA("FP0")

DBSELECTAREA("FP6") 			// ITENS
DBSETORDER(1)

DBSELECTAREA("SE4") 			// CONDI«’ES DE PAGAMENTOS
DBSETORDER(1)
SE4->(MSSEEK(XFILIAL("SA1")+FPA->FPA_CONPAG))

DBSELECTAREA("SA1") 			// TABELA CLIENTES
DBSETORDER(1)
SA1->(MSSEEK(XFILIAL("SA1")+FP0->FP0_CLI+FP0->FP0_LOJA))

DBSELECTAREA("FP1") 			// TABELA CLIENTES PROJETOS
DBSETORDER(1)
FP1->(MSSEEK(XFILIAL("FP1")+FP0->FP0_PROJET))

DBSELECTAREA("FPA") 			// TABELA ITENS DO CONTRATO
DBSETORDER(1) 
FPA->(MSSEEK(XFILIAL("FPA")+FP0->FP0_PROJET)) 

DBSELECTAREA("SB1") 			// PRODUTOS
DBSETORDER(1) 
SB1->(MSSEEK(XFILIAL("SB1")+FPA->FPA_PRODUT)) 

IF ! LTEM_DOT
	LOCR01602() 
	RETURN 
ENDIF 

IF (CWORD >= "0")
	OLE_CLOSELINK(CWORD) 		// FECHA O LINK COM O WORD
	CWORD := OLE_CREATELINK()
	OLE_NEWFILE(CWORD,CARQUIVO)
	
	// --> FUNCAO QUE FAZ O WORD APARECER NA AREA DE TRANSFERENCIA DO WINDOWS, 
	//     SENDO QUE PARA HABILITAR/DESABILITAR E SO COLOCAR .T. OU .F.
	OLE_SETPROPERTY(CWORD , OLEWDVISIBLE   , .T.)
	OLE_SETPROPERTY(CWORD , OLEWDPRINTBACK , .F.)
	
	// --> DADOS CADASTRAIS.
	OLE_SETDOCUMENTVAR(CWORD, "CPROJET" , ALLTRIM(FP0->FP0_PROJET))											// NUMERO DO CONTRATO
	OLE_SETDOCUMENTVAR(CWORD, "CDIA"	, DAY(DDATABASE)) 													// DATA DE EMISS√O DA IMPRESS√O DO CONTRATO - DIA
	OLE_SETDOCUMENTVAR(CWORD, "CMES"	, MONTH(DDATABASE)) 												// DATA DE EMISS√O DA IMPRESS√O DO CONTRATO - MES
	OLE_SETDOCUMENTVAR(CWORD, "CANO"	, YEAR(DDATABASE)) 													// DATA DE EMISS√O DA IMPRESS√O DO CONTRATO - ANO
	OLE_SETDOCUMENTVAR(CWORD, "CNOMERE" , ALLTRIM(SA1->A1_NREDUZ))											// LOCAT¡RIA
	OLE_SETDOCUMENTVAR(CWORD, "CCGC"	, ALLTRIM(SA1->A1_CGC))												// CNPJ
	OLE_SETDOCUMENTVAR(CWORD, "CFATURA" , SA1->(ALLTRIM(A1_END)+" "+ALLTRIM(A1_BAIRRO)+" "+ALLTRIM(A1_MUN)+" "+ALLTRIM(A1_EST)+" "+ALLTRIM(A1_CEP)))//FATURAMENTO
	OLE_SETDOCUMENTVAR(CWORD, "CCOBRAN" , SA1->(ALLTRIM(A1_ENDCOB)+" "+ALLTRIM(A1_BAIRRO)+" "+ALLTRIM(A1_MUN)+" "+ALLTRIM(A1_EST)+" "+ALLTRIM(A1_CEP)))					//COBRAN«A
	OLE_SETDOCUMENTVAR(CWORD, "CENTREG" , FP1->(ALLTRIM(FP1_ENDORI)+" "+ALLTRIM(FP1_BAIORI)+" "+ALLTRIM(FP1_MUNORI)+" "+ALLTRIM(FP1_ESTORI)+" "+ALLTRIM(FP1_CEPORI)))	//ENTREGA
	OLE_SETDOCUMENTVAR(CWORD, "CCONDIC" , SE4->E4_DESCRI )													// CONDI«√O DE COBRAN«A  (RECUPERAR A DESCRI«√O DA CONDI«√O DE PAGAMENTO)
	OLE_SETDOCUMENTVAR(CWORD, "CTITPAG" , FPA->FPA_TIPPAG )													// (RECUPERAR A DESCRI«√O DO X3_CBOX CORRESPONDENTE)
	IF     ! EMPTY(FPA->FPA_MINMES) 	// CASO O CAMPO FPA_MINMES ESTEJA DIFERENTE DE ZERO SER¡ APRESENTANDO O FPA_MINMES+HRS/M S
		OLE_SETDOCUMENTVAR(CWORD, "CTITPAG" , STR(FPA->FPA_MINMES) + STR0011) //"HRS/M S"
	ELSEIF ! EMPTY(FPA->FPA_MINMES) 	// O CAMPO FPA_MINMES ESTEJA IGUAL A ZERO SER¡ APRESENTANDO O FPA_MINDIA+HRS/SEMANA.
		OLE_SETDOCUMENTVAR(CWORD, "CTITPAG" , STR(FPA->FPA_MINDIA) + STR0012) //"HRS/SEMANA"
	ENDIF
	
	// --> PRIMEIRA PLANILHA. 
	IF ! EMPTY(FPA->FPA_AS)
		// QUANTIDADE - ESPECIFICA«√O			 - PERÕODO (DIAS) - VALOR UNIT. PERÕODO - VALOR TOTAL 
		// 999		  - DESCRI«√O DO ITEM LOCADO - 999	 		  - R$					- R$ - 
		OLE_SETDOCUMENTVAR(CWORD, "CDESCRI" , FPA->FPA_DESGRU+FPA->FPA_CARAC) 	// ESPECIFICA«√O
		OLE_SETDOCUMENTVAR(CWORD, "CPERIOD" , FPA->FPA_DTFIM-FPA->FPA_DTINI) 	// PERIODO EM DIAS
	/* 	// --> RETIRADO (IF - DEIXADO APENAS CONDICAO DO ELSE) POIS O CAMPO B1_XAGLUT N√O EXISTE NO COMPATIBILIZADOR DO GPO RENTAL
		// FUN«√O QUE SELECONA OS ITENS IGUAIS DA TABELA ZAG QUANDO FOR PRA AGLUTINAR
		IF SB1->B1_XAGLUT == "S"
			SELZAG(FPA_PRODUT)
			NZAGQUANT := 0
			WHILE ZAGTMP->(! EOF())
				NZAGQUANT += ZAGTMP->FPA_QUANT
				ZAGTMP->(DBSKIP())
			ENDDO
			OLE_SETDOCUMENTVAR(CWORD, "NQTDZAA" , NZAGQUANT)
			OLE_SETDOCUMENTVAR(CWORD, "NVALHOR" , IIF(! EMPTY(FPA->FPA_VRHOR),STR(FPA->FPA_VRHOR),"INCLUSO"))  // VALR UNIT¡RIO
			OLE_SETDOCUMENTVAR(CWORD, "NVTOTAL" , IIF(FPA->FPA_VRHOR>0, NZAGQUANT*ZAG-FPA->FPA_VRHOR,"INCLUSO"))
		ELSE
	*/
			OLE_SETDOCUMENTVAR(CWORD, "NQTDZAA" , FPA->FPA_QUANT)
			OLE_SETDOCUMENTVAR(CWORD, "NVALHOR" , FPA->FPA_VRHOR)
			OLE_SETDOCUMENTVAR(CWORD, "NVTOTAL" , FPA->FPA_QUANT*FPA->FPA_VRHOR)
	//	ENDIF
		
		// --> SEGUNDA PLANILHA
		// QUANTIDADE	-ITENS ADICIONAIS	 -VALOR UNIT.	-VALOR TOTAL
		// 999			-DESCRI«√O DO ITEM	 -R$-   	 	-R$-
		IF FP6->(MSSEEK(XFILIAL("FP6")+FPA->(FPA_FILIAL+FPA_PROJET+FPA_OBRA+FPA_SEQGRU)))
			OLE_SETDOCUMENTVAR(CWORD, "CDESCIT" ,FP6->FP6_DESCRI)
			IF FP6->FP6_RESPON == "L"
				SELZAA(FP6->FP6_PROJET)
				NZAAQUANT := 0
				WHILE ZAATMP->(! EOF())
					NZAAQUANT += ZAATMP->FP6_QUANT
					NVALZAACOB += IIF( ZAATMP->FP6_VALCOB > 0, ZAATMP->FP6_VALCOB, 0)
					ZAATMP->(DBSKIP())
				ENDDO
				OLE_SETDOCUMENTVAR(CWORD, "NQTDZAA" , NZAAQUANT)
				OLE_SETDOCUMENTVAR(CWORD, "NVALCOB" , NVALZAACOB/NZAAQUANT)
				OLE_SETDOCUMENTVAR(CWORD, "NVALTOT" , NVALZAACOB)
			ELSE
				OLE_SETDOCUMENTVAR(CWORD, "NQTDZAA" , FP6->FP6_QUANT)
				OLE_SETDOCUMENTVAR(CWORD, "NVALCOB" , IIF(FP6->FP6_VALCOB>0,FP6->FP6_VALCOB,STR0013) ) //"INCLUSO"
				OLE_SETDOCUMENTVAR(CWORD, "NVALTOT" , IIF(FP6->FP6_VALCOB>0,FP6->FP6_QUANT*FP6->FP6_VALCOB,STR0013) ) //"INCLUSO"
			ENDIF
		ENDIF
	ENDIF
	
	// --> ATUALIZA OS CAMPOS DO WORD COM O CONTEUDO DO SETDOCUMENTVAR.
	OLE_UPDATEFIELDS(CWORD)
	
	// --> IMPRIME O DOCUMENTO.
 //	OLE_PRINTFILE(CWORD , "ALL" , , , )
	
	// --> SALVA O ARQUIVO EM FORMATO DOC OU PDF. 
	IF     CCOMBO == "1"
		// --> SALVA O DOCUMENTO
		OLE_SAVEASFILE(CWORD,ALLTRIM(CCONTA)+".DOC") 
		OLE_OPENFILE( CWORD, ALLTRIM(CCONTA)+".DOC") 
		OLE_SAVEASFILE(CWORD,ALLTRIM(CCONTA)+".PDF") 
	ELSEIF CCOMBO == "2"
		EXECINCLIENT(OLESAVEASFILE, {CWORD , ALLTRIM(CCONTA) , "" , "" , "0" , "17"} ) 
	 //	OLE_SAVEASFILE(CWORD,ALLTRIM(CCONTA)+".DOC") 
	ENDIF
	
	// --> ENCERRA A CONEX√O COM O WORD.
	OLE_CLOSELINK(CWORD)
ENDIF

RESTAREA(AZA0AREA)
//DBCLOSEAREA("SB1")
//DBCLOSEAREA("FP6")
//DBCLOSEAREA("SE4")
//DBCLOSEAREA("SA1")
//DBCLOSEAREA("FP1")
//DBCLOSEAREA("FPA")

RETURN 



/*
‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±…ÕÕÕÕÕÕÕÕÕÕ—ÕÕÕÕÕÕÕÕÕÕÕÀÕÕÕÕÕÕÕ—ÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÀÕÕÕÕÕÕ—ÕÕÕÕÕÕÕÕÕÕÕÕª±±
±±∫PROGRAMA  ≥ SELZAG    ∫ AUTOR ≥ IT UP BUSINESS     ∫ DATA ≥ 02/06/2008 ∫±±
±±ÃÕÕÕÕÕÕÕÕÕÕÿÕÕÕÕÕÕÕÕÕÕÕ ÕÕÕÕÕÕÕœÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕ ÕÕÕÕÕÕœÕÕÕÕÕÕÕÕÕÕÕÕπ±±
±±∫DESCRICAO ≥ GERA CONTRATO DE LOCA«√O ATRAV…S DA INTEGRA«√O WORD        ∫±±
±±ÃÕÕÕÕÕÕÕÕÕÕÿÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕπ±±
±±∫USO       ≥ ESPECIFICO GPO - TECNOGERA                                 ∫±±
±±»ÕÕÕÕÕÕÕÕÕÕœÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕº±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ
*/
/* 	// --> RETIRADO POIS O CAMPO B1_XAGLUT N√O EXISTE NO COMPATIBILIZADOR DO GPO RENTAL   (*INICIO*) 
STATIC FUNCTION SELZAG(CPROJETO)

XCQUERY := " SELECT	* "
XCQUERY += " FROM "+RETSQLNAME("FPA")+" "
XCQUERY += " WHERE  FPA_PROJET = "+CPROJETO +" " 
XCQUERY += "   AND  FPA_FILIAL = "+XFILIAL()+" " 
IF SELECT("ZAGTMP") > 0 
	ZAGTMP->(DBCLOSEAREA()) 
ENDIF 
TCQUERY XCQUERY NEW ALIAS "ZAGTMP"

RETURN
*/ 	// --> RETIRADO POIS O CAMPO B1_XAGLUT N√O EXISTE NO COMPATIBILIZADOR DO GPO RENTAL   (*FINAL* ) 



/*
‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±…ÕÕÕÕÕÕÕÕÕÕ—ÕÕÕÕÕÕÕÕÕÕÕÀÕÕÕÕÕÕÕ—ÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÀÕÕÕÕÕÕ—ÕÕÕÕÕÕÕÕÕÕÕÕª±±
±±∫PROGRAMA  ≥ SELZAA    ∫ AUTOR ≥ IT UP BUSINESS     ∫ DATA ≥ 02/06/2008 ∫±±
±±ÃÕÕÕÕÕÕÕÕÕÕÿÕÕÕÕÕÕÕÕÕÕÕ ÕÕÕÕÕÕÕœÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕ ÕÕÕÕÕÕœÕÕÕÕÕÕÕÕÕÕÕÕπ±±
±±∫DESCRICAO ≥ GERA CONTRATO DE LOCA«√O ATRAV…S DA INTEGRA«√O WORD        ∫±±
±±ÃÕÕÕÕÕÕÕÕÕÕÿÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕπ±±
±±∫USO       ≥ ESPECIFICO GPO - TECNOGERA                                 ∫±±
±±»ÕÕÕÕÕÕÕÕÕÕœÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕº±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ
*/
STATIC FUNCTION SELZAA(CPROJETO)

IF SELECT("ZAATMP") > 0
	ZAATMP->(DBCLOSEAREA())
ENDIF
XCQUERY := " SELECT	* "
XCQUERY += " FROM "+RETSQLNAME("FP6")+" "
XCQUERY += " WHERE  FP6_PROJET = "+CPROJETO+" "
XCQUERY +=   " AND  FP6_FILIAL = "+XFILIAL()+" "
TCQUERY XCQUERY NEW ALIAS "ZAATMP"

RETURN



// ======================================================================= \\
FUNCTION LOCR01602()
// ======================================================================= \\

//LOCAL LRET 
//LOCAL APERGS  := {} 
//LOCAL ARET    := {} 
//LOCAL CCODREC := SPACE(08) 

PRIVATE CACESSO := REPLICATE(" ",10) 

/*
AADD( APERGS , {1 , "PROJETO : " , CCODREC , "@!" , ".T." , "FP0" , ".T." , 40 , .F.})

IF PARAMBOX(APERGS , "PARAMETROS - INFORME O CODIGO DO PROJETO " , ARET)
	LRET := .T.
ELSE
	RETURN .F. 
ENDIF 
*/ 

//DEFINE DIALOG OMAINWND TITLE "IMPRESS√O DE PROPOSTA " FROM 180,180 TO 550,700 PIXEL 
	// --> MONTA OBJETO PARA IMPRESS√O 
	OPRINT := TMSPRINTER():NEW(STR0014) //"EXEMPLO TMSPRINTER"
	OPRINT:SETPORTRAIT()
	OPRINT:SETUP()
	OPRINT:STARTPAGE()
	
	OFONT1 := TFONT():NEW("ARIAL",,-18,.T.)
	OFONT3 := TFONT():NEW("ARIAL",,-18,.T.,.T.)			// NEGRITO
	OFONT2 := TFONT():NEW("ARIAL",,-25,.T.,,,,,,.T.)
	NLIN :=  50
	OPRINT:SAY( NLIN,850,""+SA1->A1_MUN+", "+STRZERO(DAY(DATE()),2)+STR0015+MESEXTENSO(MONTH(DATE()))+STR0015+STRZERO(YEAR(DATE()),4)+"" , OFONT1 , 1400 , )  //" DE "###" DE "
	NLIN += 100
	OPRINT:SAY( NLIN,900,STR0016 , OFONT2 , 1400 , ) //"PROPOSTA COMERCIAL"
	NLIN += 200
	OPRINT:SAY( NLIN,010,STR0017                  , OFONT1 , 1400 , ) //"A"
	NLIN +=  50
	OPRINT:SAY( NLIN,010,""+SA1->A1_NOME  , OFONT1 , 1400 , )			// "[NOME DA EMPRESA]"
	NLIN += 150
	OPRINT:SAY( NLIN,010,STR0018	  , OFONT1 , 1400 , ) //"AOS CUIDADOS DE"
	NLIN += 250
	OPRINT:SAY( NLIN,010,STR0019	      , OFONT1 , 1400 , )  //"PREZADOS,"
	NLIN += 150
	OPRINT:SAY( NLIN,100,STR0020 , OFONT1 , 1400 , ) //"APRESENTAMOS A V. SAS., PROPOSTA DE :"
	
	NLIN += 200
	OPRINT:SAY( NLIN,100,STR0021	,OFONT1,1400, ) //"AS EMPRESAS BEM-SUCEDIDAS SABEM POR EXPERIENCIA PROPRIA QUE ASSEGURAR A COMPETITIVIDADE MANTENDO A ESTAVEL "
	NLIN +=  80
	OPRINT:SAY( NLIN,100,STR0022	,OFONT1,1400, ) //"E INOVADORA NAO E TAREFA FACIL. AGILIDADE, VERSATILIDADE E ESPECIALIZACAO PASSAM A SER CADA VEZ MAIS "
	NLIN +=  80
	OPRINT:SAY( NLIN,100,STR0023	,OFONT1,1400, ) //"REQUISITOS PARA SE MANTER NUM MERCADO COMPETITIVO. "
	
	NLIN += 130
	OPRINT:SAY( NLIN,100,STR0024	,OFONT1,1400, ) //"NESSE CENARIO E FUNDAMENTAL BUSCAR UM PARCEIRO QUE FORNECA FERRAMENTAS E POSSIBILITE O DESENVOLVIMENTO "
	NLIN += 80
	OPRINT:SAY( NLIN,100,STR0025	,OFONT1,1400, ) //"DE SOLUCOES ADAPTADAS AS REAIS NECESSIDADES DOS NEGOCIOS DAS EMPRESAS. "
	
	NLIN += 130
	OPRINT:SAY( NLIN,100,STR0026	,OFONT1,1400, ) //"O PROJETO BEM GERIDO E ESTRATEGICAMENTE ALINHADO COM O NEGOCIO DA EMPRESA E ENCARADO COMO UM IMPULSIONADOR "
	NLIN +=  80
	OPRINT:SAY( NLIN,100,STR0027	,OFONT1,1400, ) //"DECISIVO PARA SUPORTAR ALTERACOES,REDUZIR CUSTOS, AUMENTAR A EFICIENCIA, ABRIR NOVOS CANAIS E SUSTENTAR AS "
	NLIN +=  80
	OPRINT:SAY( NLIN,100,STR0028	,OFONT1,1400, ) //"RELACOES COM SEUS CLIENTES. FORNECER MULTIPLAS SOLUCOES E OPCOES DE SERVICOS QUE LHES PROPORCIONAM RESPONDER "
	NLIN +=  80
	OPRINT:SAY( NLIN,100,STR0029	,OFONT1,1400, ) //"ANTECIPADAMENTE AS NECESSIDADES DE SEUS CLIENTES."
	
	NLIN += 180
	OPRINT:SAY( NLIN,10,STR0030	,OFONT1,3000 ) //"DESDE JA AGRADECEMOS A OPORTUNIDADE A NOS CONCEDIDA, E NOS COLOCAMOS A DISPOSICAO PARA QUALQUER ESCLARECIMENTOS."
	
	NLIN += 500
	OPRINT:SAY( NLIN,10,STR0031,OFONT1,3000 ) //"ATENCIOSAMENTE, "
	NLIN +=  50
	OPRINT:SAY( NLIN,10,STR0032,OFONT1,3000 ) //"[VENDEDOR]"
	
 //	OPRINT:SAYBITMAP( 100,200,"C:\DIR\TOTVS.BMP",400,400 )
 //	OPRINT:LINE( 130,10,130,900 )
 //	OPRINT:BOX( 130,10,600,900 )
 //	OBRUSH1 := TBRUSH():NEW( , CLR_YELLOW )
 //	OPRINT:FILLRECT( {100, 10, 200, 200}, OBRUSH1 )
 //	OBRUSH1:END()
	
	// --> VISUALIZA A IMPRESS√O
	OPRINT:ENDPAGE()
	OPRINT:STARTPAGE()
	NLIN :=  50
	OPRINT:SAY( NLIN,900,STR0033,OFONT2,1400, ) //"TERMOS E CONDICOES"
	NLIN += 200
	OPRINT:SAY( NLIN,100,STR0034,OFONT3,3000 ) //"1. OBJETO E VALOR"
	NLIN += 150
	OPRINT:SAY( NLIN,100,STR0035,OFONT1,3000 ) //"PELO PRESENTE INSTRUMENTO O LOCADOR ALUGA A LOCATARIA OS EQUIPAMENTOS, E SE OBRIGA LOCA-LOS NAS CONDICOES"
	NLIN +=  50
	OPRINT:SAY( NLIN,100,STR0036,OFONT1,3000 ) //" ESTABELECIDAS NESTE CONTRATO."
	NLIN += 150
	OPRINT:SAY( NLIN,100,STR0037,OFONT3,3000 ) //"2. ALUGUEIS MENSAIS E REAJUSTES"
	NLIN += 150
	OPRINT:SAY( NLIN,100,STR0038,OFONT3,3000 ) //"3. MANUTENCAO, ASSISTENCIA TECNICA E SEGURO"
	NLIN += 150
	OPRINT:SAY( NLIN,100,STR0039,OFONT3,3000 ) //"4. PRAZO DE VIGENCIA DO CONTRATO"
	NLIN += 150
	OPRINT:SAY( NLIN,100,STR0040,OFONT3,3000 ) //"5. RESCISAO"
	NLIN += 150
	OPRINT:ENDPAGE()
	OPRINT:STARTPAGE()
	NLIN :=  50
	OPRINT:SAY( NLIN,900,STR0041,OFONT2,1400, ) //"TERMO DE ACEITE"
	NLIN += 200
	NLIN += 150
	OPRINT:SAY( NLIN,20,STR0042,OFONT1,3000 ) //"POR ESTARMOS DE ACORDO COM OS TERMOS E CONDICOES APRESENTADAS NA PROPOSTA COMERCIAL ACIMA REFERENCIADA CONFIRMAMOS"
	NLIN +=  50
	OPRINT:SAY( NLIN,20,STR0043,OFONT1,3000 ) //"A AQUISICAO/LOCACAO CONFORME ESCOPO APRESENTADO."
	NLIN += 150
	OPRINT:SAY( NLIN,20,STR0044,OFONT1,3000 ) //"AS INFORMACOES DE NOSSA EMPRESA DEVIDAMENTE PREENCHIDA SERA ENVIADO EM DOCUMENTO EM ANEXO A PROPOSTA PARA QUE SEJA"
	NLIN +=  50
	OPRINT:SAY( NLIN,20,STR0045,OFONT1,3000 ) //"UTILIZADO A FINS DE CADASTROS CONSULTAS OU ELABORACAO DE MINUTA CONTRATUAL."
	NLIN += 150
	OPRINT:ENDPAGE()
	
	OPRINT:PREVIEW()

//ACTIVATE DIALOG OMAINWND CENTERED 

RETURN .T.



/*
// ======================================================================= \\
STATIC FUNCTION UP_PRPG() 
// ======================================================================= \\
// --> FUN«√O AUXILIAR DA FUNCTION LOCR01602() - N√O UTILIZADA.

OPRINT:STARTPAGE()
NLIN :=  50
OPRINT:SAY( NLIN,850,"TERMOS E CONDICOES",OFONT2,1400, )
NLIN += 200
OPRINT:SAY( NLIN,100,"1. OBJETO E VALOR",OFONT3,3000 )
NLIN += 150
OPRINT:SAY( NLIN,100,"PELO PRESENTE INSTRUMENTO O LOCADOR ALUGA ¿ LOCAT¡RIA OS EQUIPAMENTOS ABAIXO DISCRIMINADOS, E SE OBRIGA LOC¡-LOS NAS CONDI«’ES ESTABELECIDAS NESTE CONTRATO.",OFONT1,3000 )
NLIN += 150
OPRINT:SAY( NLIN,100,"2. ALUGU…IS MENSAIS E REAJUSTES",OFONT3,3000 )
NLIN += 150
OPRINT:SAY( NLIN,100,"3. MANUTEN«√O, ASSIST NCIA T…CNICA E SEGURO",OFONT3,3000 )
NLIN += 150
OPRINT:SAY( NLIN,100,"4. PRAZO DE VIG NCIA DO CONTRATO",OFONT3,3000 )
NLIN += 150
OPRINT:SAY( NLIN,100,"5. RESCIS√O",OFONT3,3000 )
NLIN += 150
OPRINT:ENDPAGE()

RETURN
*/


/*
NLIN +=  50
OPRINT:SAY( NLIN,100,"1.1 O PRESENTE CONTRATO SUBSTITUI TODO E QUALQUER ACORDO OU NEGOCIACÃßAÃÉO, VERBAL OU ESCRITO, ANTERIORMENTE FIRMADO PELO CONTRATANTE JUNTO AO VIP OFFICE E CONTEÃùM TODOS OS ERMOS ACORDADOS ENTRE AS PARTES.",OFONT1,3000 )
NLIN +=  50
OPRINT:SAY( NLIN,100,"2. OBJETO DO PRESENTE CONTRATO.",OFONT1,3000 )
NLIN +=  50
OPRINT:SAY( NLIN,100,"2.0. A CESSAÃÉO, A PARTIR DA DATA DE ASSINATURA DO PRESENTE CONTRATO, DO VIP OFFICE AO CONTRATANTE, DOS REFERIDOS EQUIPAMENTOS PARA ESCRITOÃùRIO PARA ATIVIDADE EMPRESARIAL OU PROFISSIONAL NAS DEPENDEÃÇNCIAS DE SEU ESCRITOÃùRIO, EM HORAÃùRIO COMERCIAL, DE SEGUNDA A SAÃùBADO DAS 8:00H AÃÄS 21:45H, EXCETO FERIADOS, MEDIANTE PAGAMENTO MENSAL.",OFONT1,3000 )
NLIN +=  50
OPRINT:SAY( NLIN,100,"3. DOS CUSTOS.",OFONT1,3000 )
NLIN +=  50
OPRINT:SAY( NLIN,100,"3.0. PELA UTILIZACÃßAÃÉO DOS SERVICÃßOS, O CONTRATANTE PAGARAÃù AO VIP OFFICE, A QUANTIA INFORMADA EM SUA PROPOSTA COMERCIAL ACIMA INFORMADA, SENDO QUE A MENSALIDADE DEVERAÃù SER PAGA ANTECIPADAMENTE EM RELACÃßAÃÉO AO SERVICÃßO.",OFONT1,3000 )
NLIN +=  50
OPRINT:SAY( NLIN,100,"3.1. O NAÃÉO PAGAMENTO DA LOCACÃßAÃÉO NO VENCIMENTO DA FATURA IMPLICARAÃù NA IMEDIATA SUSPENSAÃÉO DO DIREITO DE USO DOS BENS CONTRATADOS ATEÃù REGULARIZACÃßAÃÉO DO DEÃùBITO, ALEÃùM DE MULTA DE 2% E JUROS DE MORA DE 0,033% AO MEÃÇS OU FRACÃßAÃÉO.",OFONT1,3000 )
NLIN +=  50
OPRINT:SAY( NLIN,100,"3.2. INADIMPLEÃÇNCIA DO (A) CONTRATANTE POR MAIS DE 30 DIAS CONSECUTIVOS, IMPORTARAÃù NA RESCISAÃÉO DO PRESENTE CONTRATO POR JUSTA CAUSA E SEM O AVISO PREÃùVIO, FICANDO RESGUARDADO O DIREITO DA VIP OFFICE EM VER SEU CREÃùDITO DEVIDAMENTE QUITADO JUDICIAL OU EXTRAJUDICIALMENTE, INCLUSIVE COM JUROS, MULTA E CORRECÃßAÃÉO MONETAÃùRIA, ALEÃùM DE EVENTUAIS DESPESAS DE COBRANCÃßA E HONORAÃùRIOS ADVOCATIÃùCIOS.",OFONT1,3000 )
NLIN +=  50
OPRINT:SAY( NLIN,100,"3.3. O CONTRATANTE AUTORIZA O VIP OFFICE A REALIZAR PROTESTO E INSCREVER SEU NOME NOS OÃùRGAÃÉOS DE PROTECÃßAÃÉO AO CREÃùDITO, TAIS COMO SPC E SERASA, ACASO A INADIMPLEÃÇNCIA PERDURE POR MAIS DE 45 (QUARENTA E CINCO) DIAS.",OFONT1,3000 )
NLIN +=  50
OPRINT:SAY( NLIN,100,"3.4. O VALOR DA MENSALIDADE SERAÃù REVISTO A CADA 12 (DOZE) MESES DE VIGEÃÇNCIA DO CONTRATO, CONTADOS DA ASSINATURA DO MESMO, DE ACORDO COM A VARIACÃßAÃÉO ACUMULADA DO IGPM/FGV. NA AUSEÃÇNCIA DESTE IÃùNDICE SERAÃù ELEITO OUTRO IÃùNDICE CRIADO PELO GOVERNO FEDERAL E, AINDA, EM SUA SUBSTITUICÃßAÃÉO, PELA FUNDACÃßAÃÉO GETUÃùLIO VARGAS.",OFONT1,3000 )
NLIN +=  50
OPRINT:SAY( NLIN,100,"4. DO PRAZO DE VIGEÃÇNCIA.",OFONT1,3000 )
*/
