#INCLUDE "locr028.ch" 
/*/{PROTHEUS.DOC} LOCR028.PRW
ITUP BUSINESS - TOTVS RENTAL
RELATORIO DA MINUTA PLATAFORMA
@TYPE FUNCTION
@AUTHOR FRANK ZWARG FUGA
@SINCE 03/12/2020
@VERSION P12
@HISTORY 03/12/2020, FRANK ZWARG FUGA, FONTE PRODUTIZADO.
/*/

#INCLUDE "PROTHEUS.CH"
#INCLUDE "TBICONN.CH"
#INCLUDE "COLORS.CH"
#INCLUDE "RPTDEF.CH"
#INCLUDE "FWPRINTSETUP.CH"

FUNCTION LOCR028(NOPC, _CPARAM2)
LOCAL LADJUSTTOLEGACY := .F.
LOCAL LDISABLESETUP   := .F.
LOCAL NRET 
LOCAL CDESCRICAO 

PRIVATE CARQUIVO  := STR0001+STR0002+ALLTRIM(FP0->FP0_PROJET)+"_"+STRTRAN(TIME(),":","")+".PDF" //"PLATAFORMA ENTREGUE "###"PROJETO "
PRIVATE CLOCAL    := "C:\PLATAFORMA ENTREGUE\"
PRIVATE CPROJETO  := FPF->FPF_PROJET
PRIVATE COBRA     := FPF->FPF_OBRA
PRIVATE CAS       := FPF->FPF_AS
PRIVATE CMINUTA   := CEMPANT + FPF->FPF_FILIAL + FPF->FPF_MINUTA
PRIVATE OPRINTER
PRIVATE I         :=  0
PRIVATE NLIN      := 10
PRIVATE NFIM      := 55
PRIVATE L		  :=  1
PRIVATE CLOGO	  := ""
PRIVATE NVALOR	  :=  0
PRIVATE CDESCTIPO := _CPARAM2
PRIVATE CTEXTO    := STR0003 //"1A VIA"

NRET       := MAKEDIR(STR0004) //"C:\PLATAFORMA ENTREGUE"
CDESCRICAO := POSICIONE("ST9" , 1 , XFILIAL()+FPF->FPF_FROTA , "T9_NOME") 

IF NOPC = 1
	LDISABLESETUP  := .F.
ELSE
	LDISABLESETUP  := .T. 
ENDIF

OPRINTER := FWMSPRINTER():NEW(CARQUIVO, 6, LADJUSTTOLEGACY,, LDISABLESETUP, , , , , , .F., )
OPRINTER:CPATHPDF := CLOCAL
OPRINTER:SETPORTRAIT()
OPRINTER:SETPAPERSIZE(9)
IF NOPC = 1
	OPRINTER:SETVIEWPDF( .T. )
ELSE
	OPRINTER:SETVIEWPDF( .F. )
ENDIF

OFONT1    := TFONTEX():NEW(OPRINTER,"TIMES NEW ROMAN",08,08,.T.,.T.,.F.)// 1
OFONT2    := TFONTEX():NEW(OPRINTER,"TIMES NEW ROMAN",08,08,.F.,.F.,.F.)// 1
OFONT3    := TFONTEX():NEW(OPRINTER,"TIMES NEW ROMAN",16,16,.T.,.T.,.F.)// 1

// LOGO
IF CFILANT $ "0101|0102|0401"
	CLOGO:=GETSRVPROFSTRING("STARTPATH","") + SUPERGETMV("MV_LOCX016",,"\system\")  // parametro removido do padrão
ELSE
	CLOGO:=GETSRVPROFSTRING("STARTPATH","") + SUPERGETMV("MV_LOCX017",,"\system\")  // parametro removido do padrão
ENDIF

// QUERY
IF SELECT("TRBZA0") > 0
	TRBFP0->(DBCLOSEAREA())
ENDIF

CSQL:= " SELECT ZA0_CLI,ZA0_LOJA,ZA0_TIPOSE,ZA0_PROJET,ZA0_CLINOM,ISNULL(CONVERT(VARCHAR(2047), CONVERT(VARBINARY(2047), FQ7_OBS)),'') AS OBSZUC,FQ7_LOCCAR,FQ7_ENDORI,FQ7_BRRORI,FQ7_CIDORI,FQ7_UFORI,FQ7_LOCDES,FQ7_ENDEST,FQ7_BRRDES,FQ7_CIDEST,FQ7_UFDEST FROM "+RETSQLNAME("FP0")+ " ZA0"
CSQL+= " INNER JOIN "+RETSQLNAME("FQ7")+ " ZUC "
CSQL+= " ON FQ7_FILIAL = '"+XFILIAL("FQ7")+"' AND ZA0_PROJET = FQ7_PROJET AND FQ7_OBRA = '"+COBRA+"' "
CSQL+= " WHERE ZA0_FILIAL='"+XFILIAL("FP0")+"' "
CSQL+= " AND ZA0_PROJET ='"+CPROJETO+"' "
CSQL+= " AND ZA0.D_E_L_E_T_ ='' "
CSQL+= " AND ZUC.D_E_L_E_T_ ='' "
PLSQUERY(CSQL,"TRBZA0")
DBSELECTAREA("TRBZA0")
TRBFP0->(DBGOTOP())

IF EMPTY(TRBFP0->FP0_CLI)
	MSGINFO(STR0005,STR0006)  //"NÃO HÁ DADOS A SEREM EXEBIDOS,REVEJA OS PARAMETROS"###"GPO - RELMINUPA.PRW"
	RETURN
ENDIF

WHILE !TRBFP0->(EOF())
	FDADOS()
	TRBFP0->(DBSKIP())
ENDDO

RETURN .T. 



// ======================================================================= \\
STATIC FUNCTION FDADOS()
// ======================================================================= \\

LOCAL I := 0 

IF L = 1
	OPRINTER:STARTPAGE()
ELSE
	NFIM := NLIN+45
ENDIF
	
CCNPJ:=POSICIONE("SA1",1,XFILIAL("SA1")+TRBFP0->FP0_CLI+TRBFP0->FP0_LOJA,"A1_CGC")

FP1->( DBSETORDER(1) )
FP1->( DBSEEK( XFILIAL("FP1") + CPROJETO + COBRA ) )		// POSICIONAMOS NA OBRA - CRISTIAM ROSSI EM 19/01/2016

OPRINTER:BOX(NLIN,10,NFIM,0590)
NLIN += 10 
OPRINTER:SAYBITMAP(NLIN,515,CLOGO,0065,0030 )
NLIN +=  2
OPRINTER:SAY(NLIN,020,STR0007 + CMINUTA,OFONT3:OFONT) //"MINUTA DE FRETE - "
OPRINTER:SAY(NLIN,300,STR0008+TRBFP0->FP0_PROJET,OFONT3:OFONT) //"PROJETO: "
NLIN += 15 
OPRINTER:SAY(NLIN,300,STR0009+ DTOC(FPF->FPF_DATA) ,OFONT3:OFONT) //"DATA:      "
OPRINTER:SAY(NLIN,020,STR0010+CDESCTIPO,OFONT3:OFONT) //"TIPO CARREGAMENTO: "
NLIN += 15
OPRINTER:SAY(NLIN,020,CTEXTO,OFONT3:OFONT)
NLIN +=  5
NFIM += 15

OPRINTER:BOX(NLIN,0010,NFIM,0590)
NLIN += 10
OPRINTER:SAY(NLIN,0020,STR0011,OFONT2:OFONT) //"CLIENTE:"
OPRINTER:SAY(NLIN,0050,TRBFP0->FP0_CLINOM,OFONT2:OFONT)
OPRINTER:SAY(NLIN,0315,STR0012,OFONT2:OFONT) //"CNPJ:"
OPRINTER:SAY(NLIN,0335,CCNPJ,OFONT2:OFONT)
NLIN := NFIM
NFIM += 15
OPRINTER:BOX(NLIN,0010,NFIM,0590)
NLIN+=10
OPRINTER:SAY(NLIN,0020,STR0013,OFONT2:OFONT) //"CARREGAMENTO:"
OPRINTER:SAY(NLIN,0315,STR0014,OFONT2:OFONT) //"PRAZO DE VIAGEM:"
NLIN:=NFIM
NLIN+=0015
OPRINTER:BOX(NLIN,0010,NFIM,0590)
NLIN+=10
OPRINTER:SAY(NLIN,0280,STR0015,OFONT2:OFONT) //"DADOS DO TRANSPORTADOR"

IF SELECT("TRBTRA") > 0
	TRBTRA->(DBCLOSEAREA())
ENDIF

CSQL:= " SELECT FQ7_X5COD, T9_NOME, T9_CODBEM, T9_PLACA, ISNULL(ZLO1.FPQ_MAT,'') MOTORISTA, ISNULL(ZLO2.FPQ_MAT,'') AJUDANTE  FROM " + RETSQLNAME("FPF") + " ZBX "
CSQL+= " JOIN "+RETSQLNAME("FQ7")+ " ZUC "
CSQL+= " ON FQ7_FILIAL = '"+XFILIAL('FQ7')+"' AND FQ7_PROJET = FPF_PROJET AND FQ7_OBRA = FPF_OBRA AND ZUC.D_E_L_E_T_='' "

CSQL+= " INNER JOIN "+RETSQLNAME("ST9")+ " ST9 "
CSQL+= " ON T9_FILIAL = '"+XFILIAL('ST9')+"' AND FQ7_X5COD = T9_CODBEM AND ST9.D_E_L_E_T_ ='' "

CSQL+= " LEFT JOIN " + RETSQLNAME("FPQ") + " ZLO1 ON ZLO1.FPQ_FILIAL='"+XFILIAL("FPQ")+"' AND ZLO1.FPQ_PROJET=FPF_PROJET AND ZLO1.FPQ_OBRA=FPF_OBRA AND ZLO1.FPQ_DATA=FPF_DATA "
CSQL+= 		" AND ZLO1.FPQ_AS=FPF_AS AND ZLO1.FPQ_FUNCAO='M' AND ZLO1.D_E_L_E_T_='' "

CSQL+= " LEFT JOIN " + RETSQLNAME("FPQ") + " ZLO2 ON ZLO2.FPQ_FILIAL='"+XFILIAL("FPQ")+"' AND ZLO2.FPQ_PROJET=FPF_PROJET AND ZLO2.FPQ_OBRA=FPF_OBRA AND ZLO2.FPQ_DATA=FPF_DATA "
CSQL+= 		" AND ZLO2.FPQ_AS=FPF_AS AND ZLO2.FPQ_FUNCAO='A' AND ZLO2.D_E_L_E_T_='' "

CSQL+= " WHERE FPF_FILIAL='"+XFILIAL('FPF')+"' "
CSQL+= " AND FPF_MINUTA ='"+ SUBSTR(CMINUTA, 7) +"' "
CSQL+= " AND ZBX.D_E_L_E_T_ ='' "
PLSQUERY(CSQL,"TRBTRA")
DBSELECTAREA("TRBTRA")
TRBTRA->(DBGOTOP())

NLIN:=NFIM
NFIM+=50

OPRINTER:BOX(NLIN,0010,NFIM,0590)
NLIN+=10
OPRINTER:SAY(NLIN,0020,STR0016,OFONT2:OFONT) //"VEICULO "
OPRINTER:SAY(NLIN,0200,STR0017,OFONT2:OFONT) //"N. FROTA "
OPRINTER:SAY(NLIN,0250,STR0018,OFONT2:OFONT) //"PLACA "
OPRINTER:SAY(NLIN,0300,STR0019,OFONT2:OFONT) //"MOTORISTA "
OPRINTER:SAY(NLIN,0450,STR0020,OFONT2:OFONT) //"AUXILIAR "
NLIN+=10
WHILE TRBTRA->(!EOF())
	OPRINTER:SAY(NLIN,0020,SUBSTR(TRBTRA->T9_NOME,1,40),OFONT2:OFONT)
	OPRINTER:SAY(NLIN,0200,TRBTRA->T9_CODBEM,OFONT2:OFONT)
	OPRINTER:SAY(NLIN,0250,TRBTRA->T9_PLACA,OFONT2:OFONT)
	
	IF ! EMPTY( TRBTRA->MOTORISTA )
		DA4->( DBSETORDER(4) )
		IF DA4->( DBSEEK( XFILIAL("DA4")+TRBTRA->MOTORISTA ) )
			OPRINTER:SAY( NLIN, 300, DA4->DA4_NOME, OFONT2:OFONT)
		ENDIF
	ENDIF
	
	IF ! EMPTY( TRBTRA->AJUDANTE )
		DA4->( DBSETORDER(4) )
		IF DA4->( DBSEEK( XFILIAL("DA4")+TRBTRA->AJUDANTE ) )
			OPRINTER:SAY( NLIN, 450, DA4->DA4_NOME, OFONT2:OFONT)
		ENDIF
	ENDIF
	
	NLIN+=10
	TRBTRA->(DBSKIP())
ENDDO

NLIN:=NFIM
NFIM+=15
OPRINTER:BOX(NLIN,0010,NFIM,0590)
NLIN+=10
OPRINTER:SAY(NLIN,0300,STR0021,OFONT2:OFONT) //"DADOS DAS PEÇAS"
NLIN:=NFIM
NFIM+=65
OPRINTER:BOX(NLIN,0010,NFIM,0590)
NLIN+=10
OPRINTER:SAY(NLIN,0020,STR0022,OFONT1:OFONT) //"NOME: "
OPRINTER:SAY(NLIN,0250,STR0023,OFONT1:OFONT) //"SÉRIE: "
OPRINTER:SAY(NLIN,0300,STR0024,OFONT1:OFONT) //"COMP.: "
OPRINTER:SAY(NLIN,0350,STR0025,OFONT1:OFONT) //"LARGURA: "
OPRINTER:SAY(NLIN,0400,STR0026,OFONT1:OFONT) //"ALTURA: "
OPRINTER:SAY(NLIN,0450,STR0027,OFONT1:OFONT) //"PESO UNITÁRIO: "
OPRINTER:SAY(NLIN,0540,STR0028,OFONT1:OFONT) //"PESO TOTAL: "

IF SELECT("TRBPEC") > 0
	TRBPEC->(DBCLOSEAREA())
ENDIF

//CSQL:= " SELECT FPA_DESGRU, FPA_VRHOR, FPA_PRODUT, T9_PESO FROM "+RETSQLNAME("FPA")+ " ZAG "
// T9_peso foi removido da 94
CSQL:= " SELECT FPA_DESGRU, FPA_VRHOR, FPA_PRODUT FROM "+RETSQLNAME("FPA")+ " ZAG "
CSQL+= " JOIN "+RETSQLNAME("ST9")+" ST9 ON T9_FILIAL='"+XFILIAL("ST9")+"' AND T9_CODBEM=FPA_GRUA AND ST9.D_E_L_E_T_=''"
CSQL+= " WHERE FPA_FILIAL = '"+XFILIAL("FPA")+"' "
CSQL+= " AND FPA_PROJET ='"+TRBFP0->FP0_PROJET+"' "
CSQL+= " AND FPA_AS ='"+CAS+"' "
CSQL+= " AND ZAG.D_E_L_E_T_ ='' "

PLSQUERY(CSQL,"TRBPEC")
DBSELECTAREA("TRBPEC")
TRBPEC->(DBGOTOP())
NLIN  += 10
NPESO := 0
WHILE TRBPEC->(!EOF())
	//		OPRINTER:SAY(NLIN,0020,TRBPEC->FPA_DESGRU,OFONT1:OFONT)
	SB1->( DBSETORDER(1) )
	IF SB1->( DBSEEK( XFILIAL("SB1") + TRBPEC->FPA_PRODUT ) ) .AND. !EMPTY( SB1->B1_DESC )
		OPRINTER:SAY(NLIN,0020, SB1->B1_DESC, OFONT1:OFONT)
	ELSE
		OPRINTER:SAY(NLIN,0020, TRBPEC->FPA_DESGRU, OFONT1:OFONT)
	ENDIF
	//OPRINTER:SAY(NLIN,0460,CVALTOCHAR(TRBPEC->T9_PESO),OFONT1:OFONT)
	OPRINTER:SAY(NLIN,0460,0,OFONT1:OFONT)
	NLIN+=10
	//NPESO+=TRBPEC->T9_PESO
	// T9_peso foi removido da 94
	NPESO+=0
	TRBPEC->(DBSKIP())
ENDDO
NLIN-=10
OPRINTER:SAY(NLIN,0550,CVALTOCHAR(NPESO),OFONT1:OFONT)

NLIN:=NFIM

NFIM+=70

OPRINTER:BOX(NLIN,0010,NFIM,0590)
NLIN+=10

OPRINTER:SAY(NLIN,0020,STR0029,OFONT2:OFONT) //"ORIGEM: "
OPRINTER:SAY(NLIN,0070,STR0030,OFONT2:OFONT) //"LOCAL: "
IF CDESCTIPO == STR0031 //"RETIRADA DE EQUIPAMENTO"
	OPRINTER:SAY(NLIN,0090,FP1->FP1_NOMORI,OFONT2:OFONT)
ENDIF

NLIN+=10
OPRINTER:SAY(NLIN,0070,STR0032,OFONT2:OFONT) //"ENDEREÇO: "

IF CDESCTIPO == STR0031 //"RETIRADA DE EQUIPAMENTO"
	OPRINTER:SAY(NLIN,0110,FP1->FP1_ENDORI,OFONT2:OFONT)
ENDIF

OPRINTER:SAY(NLIN,0300,STR0033,OFONT2:OFONT) //"COMPLEMENTO: "
NLIN+=10
OPRINTER:SAY(NLIN,0070,STR0034,OFONT2:OFONT) //"BAIRRO: "
IF CDESCTIPO == STR0031 //"RETIRADA DE EQUIPAMENTO"
	OPRINTER:SAY(NLIN,0100,FP1->FP1_BAIORI,OFONT2:OFONT)
ENDIF

OPRINTER:SAY(NLIN,0240,STR0035,OFONT2:OFONT) //"CIDADE: "
IF CDESCTIPO == STR0031 //"RETIRADA DE EQUIPAMENTO"
	OPRINTER:SAY(NLIN,0270,FP1->FP1_MUNORI,OFONT2:OFONT)
ENDIF

OPRINTER:SAY(NLIN,0540,STR0036,OFONT2:OFONT) //"UF: "
IF CDESCTIPO == STR0031 //"RETIRADA DE EQUIPAMENTO"
	OPRINTER:SAY(NLIN,0560,FP1->FP1_ESTORI,OFONT2:OFONT)
ENDIF

NLIN+=10
OPRINTER:SAY(NLIN,0070,STR0037,OFONT2:OFONT) //"CONTATO: "
//OPRINTER:SAY(NLIN,0100,TRBFP0->ZA6_CONORI,OFONT2:OFONT)
IF CDESCTIPO == STR0031 //"RETIRADA DE EQUIPAMENTO"
	OPRINTER:SAY(NLIN,0100,FP1->FP1_CONORI,OFONT2:OFONT)
ENDIF

OPRINTER:SAY(NLIN,0240,STR0038,OFONT2:OFONT) //"TELEFONE: "
//OPRINTER:SAY(NLIN,0270,TRBFP0->ZA6_TELORI,OFONT2:OFONT)
IF CDESCTIPO == STR0031 //"RETIRADA DE EQUIPAMENTO"
	OPRINTER:SAY(NLIN,0270,FP1->(ALLTRIM(FP1_DDDORI)+ FP1_TELORI),OFONT2:OFONT)
ENDIF

NLIN+=15
OPRINTER:SAY(NLIN,0020,STR0039,OFONT2:OFONT) //"DATA/HORA CHEGADA PORTARIA "
OPRINTER:BOX(NLIN-10,0120,NFIM-5,0240)
OPRINTER:SAY(NLIN,0320,STR0039,OFONT2:OFONT) //"DATA/HORA CHEGADA PORTARIA "
OPRINTER:BOX(NLIN-10,0420,NFIM-5,0580)
NLIN:=NFIM
NFIM:=NLIN+70
OPRINTER:BOX(NLIN,0010,NFIM,0590)
NLIN+=10

OPRINTER:SAY(NLIN,0020,STR0040,OFONT2:OFONT) //"DESTINO: "
OPRINTER:SAY(NLIN,0070,STR0030,OFONT2:OFONT) //"LOCAL: "
IF CDESCTIPO == STR0041 //"ENTREGA DE EQUIPAMENTO"
	OPRINTER:SAY(NLIN,0090,FP1->FP1_NOMORI,OFONT2:OFONT)
ENDIF

NLIN+=10
OPRINTER:SAY(NLIN,0070,STR0032,OFONT2:OFONT) //"ENDEREÇO: "
IF CDESCTIPO == STR0041 //"ENTREGA DE EQUIPAMENTO"
	OPRINTER:SAY(NLIN,0110,FP1->FP1_ENDORI,OFONT2:OFONT)
ENDIF

OPRINTER:SAY(NLIN,0300,STR0033,OFONT2:OFONT) //"COMPLEMENTO: "
NLIN+=10
OPRINTER:SAY(NLIN,0070,STR0042,OFONT2:OFONT) //"BAIRRO "
IF CDESCTIPO == STR0041 //"ENTREGA DE EQUIPAMENTO"
	OPRINTER:SAY(NLIN,0100,FP1->FP1_BAIORI,OFONT2:OFONT)
ENDIF

OPRINTER:SAY(NLIN,0240,STR0043,OFONT2:OFONT) //"CIDADE "
IF CDESCTIPO == STR0041 //"ENTREGA DE EQUIPAMENTO"
	OPRINTER:SAY(NLIN,0270,FP1->FP1_MUNORI,OFONT2:OFONT)
ENDIF

OPRINTER:SAY(NLIN,0540,STR0044,OFONT2:OFONT) //"UF "
IF CDESCTIPO == STR0041 //"ENTREGA DE EQUIPAMENTO"
	OPRINTER:SAY(NLIN,0560,FP1->FP1_ESTORI,OFONT2:OFONT)
ENDIF

NLIN+=10
OPRINTER:SAY(NLIN,0070,STR0045,OFONT2:OFONT) //"CONTATO "
IF CDESCTIPO == STR0041 //"ENTREGA DE EQUIPAMENTO"
	OPRINTER:SAY(NLIN,0100,FP1->FP1_CONORI,OFONT2:OFONT)
ENDIF
OPRINTER:SAY(NLIN,0240,STR0046,OFONT2:OFONT) //"TELEFONE "
IF CDESCTIPO == STR0041 //"ENTREGA DE EQUIPAMENTO"
	OPRINTER:SAY(NLIN,0270,FP1->(ALLTRIM(FP1_DDDORI)+ FP1_TELORI),OFONT2:OFONT)
ENDIF

NLIN+=15
OPRINTER:SAY(NLIN+5,0020,STR0039,OFONT2:OFONT) //"DATA/HORA CHEGADA PORTARIA "
OPRINTER:BOX(NLIN-15,0120,NFIM-10,0240)
OPRINTER:SAY(NLIN+5,0320,STR0039,OFONT2:OFONT) //"DATA/HORA CHEGADA PORTARIA "
OPRINTER:BOX(NLIN-15,0420,NFIM-10,0580)

NLIN:=NFIM
NFIM+=40

OPRINTER:BOX(NLIN,0010,NFIM,0590)
OPRINTER:BOX(NLIN,0120,NFIM,0120)
NLIN+=10               

OPRINTER:SAY(NLIN,0020,STR0047,OFONT2:OFONT) //"TREINAMENTO: "
OPRINTER:SAY(NLIN+13,0020,STR0048,OFONT2:OFONT) //"SIM: "
OPRINTER:SAY(NLIN+13,0070,STR0049,OFONT2:OFONT) //"NÃO: "
OPRINTER:BOX(NLIN+5,0040,NLIN+0015,0060) //BOX DE MARCAÇÃO
OPRINTER:BOX(NLIN+5,0090,NLIN+0015,0110) //BOX DE MARCAÇÃO
OPRINTER:SAY(NLIN,0130,STR0050,OFONT2:OFONT) //"OBSERVAÇÃO: "

XT  := 4 //MLCOUNT(COBSVIA,150)

FOR I:=1 TO XT
	IF I =1
		OPRINTER:SAY( NLIN , 0200 ,  MEMOLINE(TRBFP0->OBSZUC,250, I ),OFONT2:OFONT)
	ELSE
		OPRINTER:SAY( NLIN , 0160 ,  MEMOLINE(TRBFP0->OBSZUC ,350, I ),OFONT2:OFONT)
	ENDIF
	NLIN+=10
NEXT I 

NLIN := NFIM

IF CDESCTIPO != STR0031 //"RETIRADA DE EQUIPAMENTO"
	NFIM += 25
	OPRINTER:BOX(NLIN,0010,NFIM,0590)
	NLIN += 10
	OPRINTER:SAY(NLIN,0020,STR0051,OFONT2:OFONT) //"DATA:   _____ / _______/ __________ "
	OPRINTER:SAY(NLIN,0250,"___________________________________________________",OFONT1:OFONT)
	NLIN += 10
	OPRINTER:SAY(NLIN,0250,STR0052,OFONT2:OFONT) //"NOME / RG DO CLIENTE "
ENDIF

IF L =1
	CTEXTO := STR0053 //"2A VIA - CLIENTE"
	NLIN   += 10 
	L      := 2
ELSE
	OPRINTER:ENDPAGE()
	CFILEPRINT := CLOCAL+CARQUIVO
	FILE2PRINTER( CFILEPRINT, "PDF" )
	OPRINTER:PREVIEW()
	FREEOBJ(OPRINTER)
ENDIF

RETURN .T.



/*
// ======================================================================= \\
STATIC FUNCTION FORMRETIRA()
// ======================================================================= \\
// --> NÃO EXISTE CHAMADA DA FUNÇÃO !
LOCAL   _I          := 0 
LOCAL   NTOP        := 20
LOCAL   NTMP

PRIVATE NLEFT       := 10
PRIVATE NMAXWIDTH   := 590

NLIN += 20
NTOP := NLIN

OPRINTER:LINE( NLIN, NLEFT, NLIN, NMAXWIDTH )
NLIN += 3

OPRINTER:SAYALIGN( NLIN, NLEFT, "RETIRADA DE PLATAFORMA EM CLIENTE", OFONT1:OFONT, NMAXWIDTH, 20, , 2 , 1 )
NLIN += 13

OPRINTER:LINE( NLIN, NLEFT, NLIN, NMAXWIDTH )

// -- QUADRO DO TANQUE ------------------ (I) 
NTMP := NLIN															// INÍCIO DO QUADRO
NLIN += 20

OPRINTER:SAY( NLIN, NLEFT + 5, "O TANQUE (DE COMBUSTÍVEL) ESTÁ INDICANDO? ", OFONT1:OFONT)
NLIN += 16

NESPACO := NMAXWIDTH - ( NLEFT+180 )
NTAM    := NESPACO / 4
NPROX   := NLEFT+180

ACOLUNA := {}															// COLUNAS DAS DEMAIS PERGUNTAS
AADD( ACOLUNA, NLEFT + 5 )
AADD( ACOLUNA, NPROX )

OPRINTER:LINE( NTMP, NPROX, NLIN, NPROX )								// PRIMEIRA LINHA
OPRINTER:LINE( NLIN-13, NPROX + 10, NLIN-13, (NPROX + NTAM) - 10 )		// TRACEJADO
OPRINTER:SAYALIGN( NLIN-10, NPROX, "CHEIO", OFONT1:OFONT, NTAM, 20, , 2 , 1 )
NPROX += NTAM

OPRINTER:LINE( NTMP, NPROX, NLIN, NPROX )								// SEGUNDA LINHA
OPRINTER:LINE( NLIN-13, NPROX + 10, NLIN-13, (NPROX + NTAM) - 10 )		// TRACEJADO
OPRINTER:SAYALIGN( NLIN-10, NPROX, "METADE", OFONT1:OFONT, NTAM, 20, , 2 , 1 )
NPROX += NTAM

AADD( ACOLUNA, NPROX )

OPRINTER:LINE( NTMP, NPROX, NLIN, NPROX ) 								// TERCEIRA LINHA
OPRINTER:LINE( NLIN-13, NPROX + 10, NLIN-13, (NPROX + NTAM) - 10 ) 		// TRACEJADO
OPRINTER:SAYALIGN( NLIN-10, NPROX, "MENOS DA METADE", OFONT1:OFONT, NTAM, 20, , 2 , 1 )
NPROX += NTAM

OPRINTER:LINE( NTMP, NPROX, NLIN, NPROX ) 								// QUARTA LINHA
OPRINTER:LINE( NLIN-13, NPROX + 10, NLIN-13, (NPROX + NTAM) - 10 ) 		// TRACEJADO
OPRINTER:SAYALIGN( NLIN-10, NPROX, "VAZIO", OFONT1:OFONT, NTAM, 20, , 2 , 1 )

OPRINTER:LINE( NLIN, NLEFT, NLIN, NMAXWIDTH ) 							// RODAPÉ
NTMP := NLIN 															// INÍCIO DO QUADRO
NLIN += 8
// -- QUADRO DO TANQUE ------------------ (F) 

// -- DEMAIS PERGUNTAS ------------------ (I) 
OPRINTER:SAYALIGN( NLIN, ACOLUNA[2], "SIM", OFONT1:OFONT, ACOLUNA[3]-ACOLUNA[2], 20, , 2 , 1 )
OPRINTER:SAYALIGN( NLIN, ACOLUNA[3], "NÃO", OFONT1:OFONT, NMAXWIDTH -ACOLUNA[3], 20, , 2 , 1 )
NLIN += 12

OPRINTER:LINE( NLIN, ACOLUNA[1], NLIN, NMAXWIDTH )
NLIN += 10

APERGUNT := {}
AADD( APERGUNT, "A CHAVE FOI DEVOLVIDA?" )
AADD( APERGUNT, "O MANUAL FOI DEVOLVIDO?" )
AADD( APERGUNT, "A CAIXA DE MANUAL NA MAUINA ESTÁ EM BOM ESTADO?" )
AADD( APERGUNT, "O CABO DO CARREGADOR ESTÁ EM BOM ESTADO?" )
AADD( APERGUNT, "OS GIROFLEX ESTÃO EM BOM ESTADO?" )

FOR _I := 1 TO LEN( APERGUNT )
	OPRINTER:SAY( NLIN, ACOLUNA[1] + 5, APERGUNT[_I], OFONT2:OFONT)
	NLIN += 3

	IF _I != LEN( APERGUNT )	//	NÃO IMPRIMIR 
		OPRINTER:LINE( NLIN, ACOLUNA[1], NLIN, NMAXWIDTH )
		NLIN += 10
	ENDIF
NEXT

FOR _I := 1 TO LEN( ACOLUNA )
	OPRINTER:LINE( NTMP, ACOLUNA[_I], NLIN, ACOLUNA[_I] )	// COLUNAS
NEXT

OPRINTER:LINE( NLIN, NLEFT, NLIN, NMAXWIDTH )	// RODAPÉ
NLIN += 10
// -- DEMAIS PERGUNTAS ------------------ (F) 

// -- OBSERVAÇÕES ----------------------- (I) 
OPRINTER:SAYALIGN( NLIN, NLEFT, "OBSERVAÇÕES", OFONT1:OFONT, NMAXWIDTH, 20, , 2 , 1 )
NLIN += 10

OPRINTER:LINE( NLIN, NLEFT, NLIN, NMAXWIDTH )	// RODAPÉ
NLIN += 5

OPRINTER:SAYALIGN( NLIN, NLEFT, '(DESCREVA AQUI SUAS OBSERVAÇÕES CASO EXISTA ALGUMA ALTERNATIVA ASSINALADA COM "NÃO")', OFONT1:OFONT, NMAXWIDTH, 20, , 2 , 1 )
NLIN += 10

FOR _I := 1 TO 7
	OPRINTER:LINE( NLIN, NLEFT, NLIN, NMAXWIDTH )	// RODAPÉ
	NLIN += 15
NEXT _I 
// -- OBSERVAÇÕES ----------------------- (F) 

OPRINTER:SAY(NLIN,0020,"DATA:   _____ / _______/ __________ ",OFONT2:OFONT)
OPRINTER:SAY(NLIN,0160,"___________________________________________________",OFONT1:OFONT)
OPRINTER:SAY(NLIN,0370,"___________________________________________________",OFONT1:OFONT)
NLIN += 10
OPRINTER:SAY(NLIN,0160,"NOME / RG DO CLIENTE ",OFONT2:OFONT)
OPRINTER:SAY(NLIN,0370,"ASSINATURA ",OFONT2:OFONT)

NLIN += 15
OPRINTER:LINE( NLIN, NLEFT, NLIN, NMAXWIDTH )	// RODAPÉ

OPRINTER:LINE( NTOP, NLEFT, NLIN, NLEFT )			// COLUNA ESQUERDA
OPRINTER:LINE( NTOP, NMAXWIDTH, NLIN, NMAXWIDTH )	// COLUNA DIREITA

OPRINTER:ENDPAGE()

RETURN NIL
*/
