/*/{PROTHEUS.DOC} LOCR032.PRW 
ITUP BUSINESS - TOTVS RENTAL
Relat๓rio de medi็ใo
@TYPE FUNCTION
@AUTHOR FRANK ZWARG FUGA
@SINCE 03/12/2020
@VERSION P12
@HISTORY 03/12/2020, FRANK ZWARG FUGA, FONTE PRODUTIZADO.
/*/

#INCLUDE "PROTHEUS.CH"
#INCLUDE "TOPCONN.CH"
#INCLUDE "TBICONN.CH"
#INCLUDE "COLORS.CH"
#INCLUDE "RPTDEF.CH"
#INCLUDE "FWPRINTSETUP.CH"

FUNCTION LOCR032()
LOCAL _AAREAOLD       := GETAREA()
LOCAL _AAREAZLF       := FPN->(GETAREA())
LOCAL _AAREAZA5       := FP4->(GETAREA())
LOCAL _AAREAZBB       := FPE->(GETAREA())
LOCAL _AAREASA1       := SA1->(GETAREA())
LOCAL LADJUSTTOLEGACY := .F.
LOCAL LDISABLESETUP   := .F.

PRIVATE NLIN          := 30
PRIVATE CARQUIVO      := "MEDICAO"
PRIVATE CLOGO		  := ""
PRIVATE NPAG		  := 1
PRIVATE CPAG		  := "1"
PRIVATE NCOL		  := 320
PRIVATE NLINE         := 1
PRIVATE NVALGERAL     := 0
PRIVATE LPASSOU       := .F.
PRIVATE CPROJET       := ""
PRIVATE NTOTAL		  := 0
PRIVATE L			  := 1
PRIVATE NMOB		  := 0
PRIVATE NSEG		  := 0
PRIVATE CPERG		  := "LOCP068"
PRIVATE OPRINTER
PRIVATE LFIM		  := .F.
PRIVATE NVALISS		  := 0
PRIVATE NPERISS		  := 0

VALIDPERG() 
IF !PERGUNTE(CPERG,.T.)
	RETURN
ENDIF

OPRINTER := FWMSPRINTER():NEW(CARQUIVO, 6, LADJUSTTOLEGACY,, LDISABLESETUP, , , , , , .F., )
OPRINTER:SETPORTRAIT()
OPRINTER:SETPAPERSIZE(9)
OPRINTER:SETVIEWPDF( .T. )

OFONT2 := TFONTEX():NEW(OPRINTER,"ARIAL",12,12,.T.,.T.,.F.)// 1
OFONT3 := TFONTEX():NEW(OPRINTER,"ARIAL",14,14,.T.,.T.,.F.)// 1
OFONT4 := TFONTEX():NEW(OPRINTER,"ARIAL",12,12,.F.,.F.,.F.)// 1
OFONT5 := TFONTEX():NEW(OPRINTER,"ARIAL",16,16,.T.,.T.,.T.)// 1
OFONT5:OFONT:ITALIC:=.T.

//LOGO
CLOGO:=GETSRVPROFSTRING("STARTPATH","") + "LOGO.JPG"

// QUERY
IF SELECT("TRBZA0") > 0
	TRBFP0->(DBCLOSEAREA())
ENDIF

CSQL := " SELECT DISTINCT A1_NOME,A1_COND,ISNULL(ZA0_NOMECO,A1_CONTATO) A1_CONTATO,ISNULL(ZA0_CLIFAX,A1_FAX) A1_FAX,ISNULL(ZA0_CLITEL,A1_TEL) A1_TEL,ISNULL(ZA0_CLIEMA,A1_EMAIL) A1_EMAIL,A1_END,A1_BAIRRO,A1_MUN,A1_EST,A1_CEP,A1_CGC,A1_INSCR,A1_ENDENT,A1_ENDCOB,A1_ESTC,A1_BAIRROC,A1_MUNC,A1_CEPC,FPN_PROJET,FPN_AS,FPN_OBRA,FPN_VRPEDA,FPN_VLAISS ,FPN_CLIENT"
CSQL += " FROM "+RETSQLNAME("FPN")+ " ZLF"
CSQL +=        " RIGHT JOIN "+RETSQLNAME("SA1")+ " SA1 ON A1_FILIAL='"+XFILIAL("SA1")+"' AND FPN_CLIENT = A1_COD AND FPN_LOJA = A1_LOJA "
CSQL +=        " LEFT  JOIN "+RETSQLNAME("FP0")+ " ZA0 ON ZA0_FILIAL='"+XFILIAL("FP0")+"' AND ZA0_PROJET = FPN_PROJET AND ZA0.D_E_L_E_T_ = '' "
CSQL += " WHERE  FPN_FILIAL ='"+XFILIAL("FPN")+"' "
CSQL +=   " AND  FPN_AS  >= '"+MV_PAR01+"' "
CSQL +=   " AND  FPN_AS  <= '"+MV_PAR02+"' "
CSQL +=   " AND  FPN_COD >= '"+MV_PAR03+"' "
CSQL +=   " AND  FPN_COD <= '"+MV_PAR04+"' "
CSQL +=   " AND  FPN_PROJET ='"+MV_PAR05+"' "
CSQL +=   " AND  FPN_SITUAC NOT IN(6)"
CSQL +=   " AND  SA1.D_E_L_E_T_ ='' "
CSQL +=   " AND  ZLF.D_E_L_E_T_ ='' "
/*
CSQL := " SELECT DISTINCT A1_NOME,A1_COND,A1_CONTATO,A1_FAX,A1_TEL,A1_EMAIL,A1_END,A1_BAIRRO,A1_MUN,A1_EST,A1_CEP,A1_CGC,A1_INSCR,A1_ENDENT,A1_ESTC,A1_BAIRROC,A1_ENDCOB,A1_MUNC,A1_CEPC,FPN_PROJET,FPN_AS,FPN_OBRA,FPN_VRPEDA,FPN_VLAISS ,FPN_CLIENT"
CSQL += " FROM "+RETSQLNAME("FPN")+ " ZLF"
CSQL +=        " RIGHT JOIN "+RETSQLNAME("SA1")+ " SA1 ON A1_FILIAL='"+XFILIAL("SA1")+"' AND FPN_CLIENT = A1_COD AND FPN_LOJA = A1_LOJA "
CSQL += " WHERE  FPN_AS  >= '"+MV_PAR01+"' "
CSQL +=   " AND  FPN_AS  <= '"+MV_PAR02+"' "
CSQL +=   " AND  FPN_COD >= '"+MV_PAR03+"' "
CSQL +=   " AND  FPN_COD <= '"+MV_PAR04+"' "
CSQL +=   " AND  FPN_PROJET ='"+MV_PAR05+"' "
CSQL +=   " AND  FPN_SITUAC NOT IN(6)"
CSQL +=   " AND  SA1.D_E_L_E_T_ ='' "
CSQL +=   " AND  ZLF.D_E_L_E_T_ ='' "
*/
PLSQUERY(CSQL,"TRBZA0")
DBSELECTAREA("TRBZA0")
TRBFP0->(DBGOTOP())

IF EMPTY(TRBFP0->A1_NOME)
	MSGINFO("NรO Hม DADOS A SEREM EXIBIDOS, REVEJA OS PARAMETROS" , "GPO - RMEDICAO.PRW") 
	RETURN
ENDIF

IF ! TRBFP0->(EOF())
	FDADOS()
ENDIF

TRBFP0->( DBCLOSEAREA() )

FP4->(DBCLEARFILTER())
FPA->(DBCLEARFILTER())

RESTAREA( _AAREASA1 )
RESTAREA( _AAREAZBB )
RESTAREA( _AAREAZA5 )
RESTAREA( _AAREAZLF )
RESTAREA( _AAREAOLD )

RETURN .T. 



// ======================================================================= \\
STATIC FUNCTION FDADOS()
// ======================================================================= \\

LOCAL I := 0 

IF CPROJET <> TRBFP0->FPN_PROJET .AND. !EMPTY(TRBFP0->FPN_PROJET) // NESSE CENARIO ATUAL NรO SERม MAIS USADO POIS SO POSSO IMPRIMIR UM UNICO PROJETO PORษM VOU DEIXAR POIS NรO VAI ALTERAR O PROCESSO//
	CPROJET   := TRBFP0->FPN_PROJET
	LPASSOU   := .F.
	NVALGERAL := 0
	NCOL      := 320
	NLIN      := 30
	OPRINTER:STARTPAGE()
	
	IF SELECT("TRBZLF") > 0
		TRBFPN->(DBCLOSEAREA())
	ENDIF
	
	CSQL := " SELECT DISTINCT COUNT(FPN_AS) TOTAL"
	CSQL += " FROM "+RETSQLNAME("FPN")+ " ZLF"
	CSQL += " WHERE  FPN_AS >='"+MV_PAR01+"' "
	CSQL +=   " AND  FPN_AS <='"+MV_PAR02+"' "
	CSQL +=   " AND  FPN_PROJET='"+TRBFP0->FPN_PROJET+"' "
	CSQL +=   " AND  FPN_FILIAL ='"+XFILIAL("FPN")+"'"
	CSQL +=   " AND  FPN_SITUAC NOT IN(6)"
	CSQL +=   " AND  ZLF.D_E_L_E_T_ ='' "
	PLSQUERY(CSQL,"TRBZLF")

	DBSELECTAREA("TRBZLF")
	TRBFPN->(DBGOTOP())
	NTOTAL := TRBFPN->TOTAL 
	L := 1
	IF LPASSOU = .F. // A VARIAVEL L PASSOU ษ PRA OCULTAR O CABEวALHO QUANDO TEM MAIS DE UMA AS NO PROJETO
		
		LPASSOU:=.T.
	 //	OPRINTER:STARTPAGE()
		OPRINTER:SAYBITMAP(NLIN,0010,CLOGO,0130,0065 )
		OPRINTER:SAY(NLIN,0200,SM0->M0_NOMECOM,OFONT3:OFONT)
		NLIN += 10
		OPRINTER:SAY(NLIN,0265,SM0->M0_ENDENT,OFONT2:OFONT)
		NLIN += 10
		OPRINTER:SAY(NLIN,0270,"CNPJ:"+SM0->M0_CGC,OFONT2:OFONT)
		NLIN += 10
		OPRINTER:SAY(NLIN,0275,"INS.EST:"+ALLTRIM(SM0->M0_INSC),OFONT2:OFONT)
		NLIN += 40
		OPRINTER:SAY(NLIN,0200,"FECHAMENTO DE EQUIPAMENTO Nฐ",OFONT5:OFONT)
		OPRINTER:SAY(NLIN,0440,TRBFP0->FPN_PROJET,OFONT3:OFONT)
		NLIN += 20
		OPRINTER:SAY(NLIN,0020,"DATA:" ,OFONT3:OFONT)
		OPRINTER:SAY(NLIN,0060,DTOC(DDATABASE),OFONT4:OFONT)
		OPRINTER:SAY(NLIN,0450,"Nฐ PมGINAS: "+CPAG,OFONT3:OFONT)
		NLIN += 20
		OPRINTER:SAY(NLIN,0020,"CLIENTE:" ,OFONT3:OFONT)
		OPRINTER:SAY(NLIN,0080,TRBFP0->A1_NOME,OFONT4:OFONT)
		NLIN += 10
		OPRINTER:BOX(NLIN,0010,NLIN+40,0590)
		NLIN += 15
		OPRINTER:SAY(NLIN,0020,"CONTATO: ",OFONT3:OFONT)
		OPRINTER:SAY(NLIN,0080,TRBFP0->A1_CONTATO,OFONT4:OFONT)
		NLIN += 20
		OPRINTER:SAY(NLIN,0020,"TEL: ",OFONT3:OFONT)
		OPRINTER:SAY(NLIN,0060,TRBFP0->A1_TEL,OFONT4:OFONT)
		OPRINTER:SAY(NLIN,0190,"FAX: ",OFONT3:OFONT)
		OPRINTER:SAY(NLIN,0230,TRBFP0->A1_FAX,OFONT4:OFONT)
		OPRINTER:SAY(NLIN,0320,"EMAIL: ",OFONT3:OFONT)
		OPRINTER:SAY(NLIN,0370,TRBFP0->A1_EMAIL,OFONT4:OFONT)
		NLIN += 20
		OPRINTER:SAY(NLIN,0020,"ENDEREวO: ",OFONT3:OFONT)
		OPRINTER:SAY(NLIN,0100,TRBFP0->A1_END,OFONT4:OFONT)
		OPRINTER:SAY(NLIN,0400,"BAIRRO: ",OFONT3:OFONT)
		OPRINTER:SAY(NLIN,0460,TRBFP0->A1_BAIRRO,OFONT4:OFONT)
		NLIN += 20
		OPRINTER:SAY(NLIN,0020,"CIDADE: ",OFONT3:OFONT)
		OPRINTER:SAY(NLIN,0080,TRBFP0->A1_MUN,OFONT4:OFONT)
		OPRINTER:SAY(NLIN,0260,"U.F.: ",OFONT3:OFONT)
		OPRINTER:SAY(NLIN,0300,TRBFP0->A1_EST,OFONT4:OFONT)
		OPRINTER:SAY(NLIN,0400,"CEP: ",OFONT3:OFONT)
		OPRINTER:SAY(NLIN,0440,TRBFP0->A1_CEP,OFONT4:OFONT)
		NLIN += 20
		OPRINTER:SAY(NLIN,0020,"CNPJ/CPF: ",OFONT3:OFONT)
		OPRINTER:SAY(NLIN,0080,TRBFP0->A1_CGC,OFONT4:OFONT)
		OPRINTER:SAY(NLIN,0220,"INSCR.EST.: ",OFONT3:OFONT)
		OPRINTER:SAY(NLIN,0290,TRBFP0->A1_INSCR,OFONT4:OFONT)
		OPRINTER:SAY(NLIN,0400,"PED.COMPRA: ",OFONT3:OFONT)
		OPRINTER:SAY(NLIN,0460,"",OFONT3:OFONT)
		
		NLIN += 20
		OPRINTER:SAY(NLIN,0020,"END.COBRANCA: ",OFONT3:OFONT)
		OPRINTER:SAY(NLIN,0120,TRBFP0->A1_ENDCOB,OFONT4:OFONT)
		OPRINTER:SAY(NLIN,0400,"BAIRRO: ",OFONT3:OFONT)
		OPRINTER:SAY(NLIN,0460,TRBFP0->A1_BAIRROC,OFONT4:OFONT)
		NLIN += 20
		OPRINTER:SAY(NLIN,0020,"CIDADE: ",OFONT3:OFONT)
		OPRINTER:SAY(NLIN,0080,TRBFP0->A1_MUNC,OFONT4:OFONT)
		OPRINTER:SAY(NLIN,0260,"U.F.: ",OFONT3:OFONT)
		OPRINTER:SAY(NLIN,0300,TRBFP0->A1_ESTC,OFONT4:OFONT)
		OPRINTER:SAY(NLIN,0400,"CEP: ",OFONT3:OFONT)
		OPRINTER:SAY(NLIN,0490,TRBFP0->A1_CEPC,OFONT4:OFONT)
		NLIN += 20
		
		IF SELECT("TRBCOUNT") > 0
			TRBCOUNT->(DBCLOSEAREA())
		ENDIF
		// TOTAL DE LINHAS PRA PODER CONTROLAR OS DIAS DA MEDIวรO MAIS A DATA COMPLETA
		CSQL:="SELECT COUNT(DISTINCT FPP_DTMEDI) AS TOTAL FROM "+RETSQLNAME("FPN")+ " ZLF "
		CSQL+=" RIGHT JOIN "+RETSQLNAME("FPP")+ " ZLM "
		CSQL+=" ON FPN_COD = FPP_COD "
		CSQL+=" WHERE FPN_AS BETWEEN '"+MV_PAR01+"' AND '" + MV_PAR02 + "'"
		CSQL+=" AND FPN_PROJET = '"+TRBFP0->FPN_PROJET+"'"
		CSQL+=" AND FPN_FILIAL ='"+XFILIAL("FPN")+"'"
		CSQL+=" AND FPP_FILIAL ='"+XFILIAL("FPP")+"'"
		CSQL+= " AND FPN_SITUAC NOT IN(6)"
		CSQL+=" AND ZLF.D_E_L_E_T_=''"
		CSQL+=" AND ZLM.D_E_L_E_T_=''"
		CHANGEQUERY(CSQL)
		DBUSEAREA(.T.,"TOPCONN",TCGENQRY(,,CSQL),"TRBCOUNT",.F.,.T.)
		TRBCOUNT->(DBGOTOP())
		// TRAGO AS DATAS DE MEDIวรO
		IF SELECT("TRBZLM") > 0
			TRBFPP->(DBCLOSEAREA())
		ENDIF
		
		CSQL := " SELECT DISTINCT FPP_DTMEDI "
		CSQL += " FROM "+RETSQLNAME("FPN")+ " ZLF "
		CSQL += " RIGHT JOIN "+RETSQLNAME("FPP")+ " ZLM "
		CSQL += " ON FPN_COD = FPP_COD "
		CSQL += " WHERE FPN_AS BETWEEN '"+MV_PAR01+"' AND '" + MV_PAR02 + "'"
		CSQL += " AND FPN_PROJET = '"+TRBFP0->FPN_PROJET+"'"
		CSQL += " AND FPN_FILIAL ='"+XFILIAL("FPN")+"'"
		CSQL += " AND FPP_FILIAL ='"+XFILIAL("FPP")+"'"
		CSQL += " AND FPN_SITUAC NOT IN(6)"
		CSQL += " AND ZLF.D_E_L_E_T_=''"
		CSQL += " AND ZLM.D_E_L_E_T_=''"
		CHANGEQUERY(CSQL)
		DBUSEAREA(.T.,"TOPCONN",TCGENQRY(,,CSQL),"TRBZLM",.F.,.T.)
		TRBFPP->(DBGOTOP())
		
		OPRINTER:SAY(NLIN,0020,"REFERENTE A LOCAวรO DO(S) EQUIPAMENTO(S) ABAIXO NO(S) DIA(S) (OU MสS): ",OFONT4:OFONT)
		N:=1
		_CDTMIN := ""
		_CDTMAX := ""
		WHILE TRBFPP->(!EOF())
			IF (EMPTY(ALLTRIM(_CDTMIN)) .OR. TRBFPP->FPP_DTMEDI < _CDTMIN) .AND. !EMPTY(ALLTRIM(TRBFPP->FPP_DTMEDI))
				_CDTMIN := TRBFPP->FPP_DTMEDI
			ENDIF
			
			IF (EMPTY(ALLTRIM(_CDTMAX)) .OR. TRBFPP->FPP_DTMEDI > _CDTMAX) .AND. !EMPTY(ALLTRIM(TRBFPP->FPP_DTMEDI))
				_CDTMAX := TRBFPP->FPP_DTMEDI
			ENDIF
			TRBFPP->(DBSKIP())
		ENDDO
		
		_CDTMIN := DTOC(STOD(_CDTMIN))
		_CDTMAX := DTOC(STOD(_CDTMAX))
		
		IF _CDTMIN == _CDTMAX
			OPRINTER:SAY(NLIN,NCOL,_CDTMIN,OFONT4:OFONT)
			NCOL+=40
		ELSE
			OPRINTER:SAY(NLIN,NCOL,_CDTMIN + " ATษ " + _CDTMAX,OFONT4:OFONT)
			NCOL+=65
		ENDIF
		
		IF NCOL < 400	// VAI NA MESMA LINHA DA DATA COMPLETA DE MEDIวรO
			NCOL+=50
			OPRINTER:SAY(NLIN,NCOL,"SEGUE DEMONSTRATIVO DE HORAS: ",OFONT4:OFONT)
		ELSE 			// VAI NA NOVA LINHA
			NCOL:=20
			NLIN += 10
			OPRINTER:SAY(NLIN,NCOL,"SEGUE DEMONSTRATIVO DE HORAS: ",OFONT4:OFONT)
		ENDIF
		
		DBSELECTAREA("FPN")
		FPN->(DBCLEARFILTER())
		FPN->(DBSETFILTER({|| ALLTRIM(FPN->FPN_AS) == ALLTRIM(TRBFP0->FPN_AS) },"ALLTRIM(FPN->FPN_AS) == ALLTRIM(TRBFP0->FPN_AS)"))
		FPN->(DBGOTOP())
		COBS:=FPN->FPN_OBS
		IF !EMPTY (COBS)
			XT  := MLCOUNT(COBS,75)
			FOR I:=1 TO XT
				IF NCOL < 95 //200
					NCOL+=140
				 //	NLIN += 10
					OPRINTER:SAY( NLIN , NCOL ,  MEMOLINE(COBS ,75, I ),OFONT4:OFONT)
				ELSE
					NLIN += 10
					OPRINTER:SAY( NLIN , 0020 ,  MEMOLINE(COBS ,75, I ),OFONT4:OFONT)
				ENDIF
			 //	NLIN += 10
			NEXT I 
		ELSEIF EMPTY(TRBFP0->FPN_PROJET)
			RETURN .F.
		ENDIF

		NLIN += 20
		OPRINTER:SAY(NLIN,0010,"ITEM",OFONT2:OFONT)
		OPRINTER:SAY(NLIN,0040,"PRODUTO",OFONT2:OFONT)
		OPRINTER:SAY(NLIN,0090,"DESCRIวรO",OFONT2:OFONT)
		OPRINTER:SAY(NLIN,0370,"QTDE.(HS)",OFONT2:OFONT)
		OPRINTER:SAY(NLIN,0420,"PREวO/HORA(R$)",OFONT2:OFONT)
		OPRINTER:SAY(NLIN,0500,"TOTAL(R$)",OFONT2:OFONT)
		NLIN += 5
		OPRINTER:LINE(NLIN,0010,NLIN,0590)
		
	ENDIF
	
ENDIF

DBSELECTAREA("FP0")
FP0->(DBCLEARFILTER())
FP0->(DBSETFILTER({|| ALLTRIM(FP0->FP0_PROJET) == ALLTRIM(TRBFP0->FPN_PROJET) },"ALLTRIM(FP0->FP0_PROJET) == ALLTRIM(TRBFP0->FPN_PROJET)"))
FP0->(DBGOTOP())

DBSELECTAREA("FP4")
FP4->(DBCLEARFILTER())
FP4->(DBSETFILTER({|| ALLTRIM(FP4->FP4_AS) == ALLTRIM(TRBFP0->FPN_AS) },"ALLTRIM(FP4->FP4_AS) == ALLTRIM(TRBFP0->FPN_AS)"))
FP4->(DBGOTOP())

DBSELECTAREA("FPA")
FPA->(DBCLEARFILTER())
FPA->(DBSETFILTER({|| ALLTRIM(FPA->FPA_AS) == ALLTRIM(TRBFP0->FPN_AS) },"ALLTRIM(FPA->FPA_AS) == ALLTRIM(TRBFP0->FPN_AS)"))
FPA->(DBGOTOP())

IF FP0->FP0_TIPOSE == "P"
	DBSELECTAREA("FPE")
	DBSETORDER(2)
	DBSEEK(XFILIAL("FPE")+TRBFP0->FPN_PROJET+TRBFP0->FPN_OBRA+FPA->FPA_SEQGRU)
ELSE
	DBSELECTAREA("FPE")
	DBSETORDER(2)
	DBSEEK(XFILIAL("FPE")+TRBFP0->FPN_PROJET+TRBFP0->FPN_OBRA+FP4->FP4_SEQGUI)
ENDIF

CLINE:=CVALTOCHAR(NLINE)

IF FP0->FP0_TIPOSE == "P"
	//BLOCO ABAIXO UNIFICADO EM UMA Sำ QUERY
	CSQL := " SELECT DISTINCT ISNULL(B1_DESC,'') B1_DESC,ISNULL(FPA_PRODUT,B1_COD) B1_COD,FPA_OBRA, FPA_SEQGRU,FPA_AS,"
	CSQL += " 			      FPP_VALHOR VRHOR,"
	CSQL += " 			      SUM(FPP_QTDHR) MINDIA, FPN_VRPEDA, " //MรO DE OBRA TAMBษM PUXAR QUANTIDADE DE HORAS DO FPP_QTDHR
	CSQL += " 			      SUM(FPP_VLRMOB+FPP_VLRDES) TOTMOB, SUM(FPP_VALSEG) TOTSEG, FPP_PERISS"
	CSQL += "  FROM " + RETSQLNAME("FPN") + " ZLF"
	CSQL += "  INNER JOIN " + RETSQLNAME("FPP") + " ZLM"
	CSQL += "     ON FPP_FILIAL = FPN_FILIAL"
	CSQL += "    AND FPP_COD    = FPN_COD"
	CSQL += "    AND ZLM.D_E_L_E_T_ = ''"
	CSQL += "  RIGHT JOIN " + RETSQLNAME("FPA") + " ZAG"
	CSQL += "  ON FPN_AS = FPA_AS"
	CSQL += "  LEFT JOIN " + RETSQLNAME("SB1") + " SB1"
	CSQL += "  ON B1_COD = FPA_PRODUT" 
	CSQL += "  AND B1_FILIAL ='" + XFILIAL("SB1") + "'"
	CSQL += "  AND SB1.D_E_L_E_T_=''"
	CSQL += "  WHERE FPN_FILIAL = '" + XFILIAL("FPN") + "'"
	CSQL += "  AND FPN_AS BETWEEN '" + MV_PAR01 + "' AND '" + MV_PAR02 + "'"
	CSQL += "  AND FPN_PROJET = '" + TRBFP0->FPN_PROJET + "'"
	CSQL += "  AND FPA_FILIAL ='" + XFILIAL("FPA") + "'"
	CSQL += "  AND FPN_FILIAL ='" + XFILIAL("FPN") + "'"
	CSQL += "  AND FPN_SITUAC NOT IN(6)"
	CSQL += "  AND ZLM.FPP_XTIPOH <> 'E'"
	CSQL += "  AND ZLF.D_E_L_E_T_=''"
	CSQL += "  AND ZAG.D_E_L_E_T_=''"
	CSQL += "  GROUP BY B1_DESC, FPA_PRODUT, B1_COD, FPP_VALHOR, FPA_OBRA, FPA_SEQGRU, FPA_AS, FPN_VRPEDA, FPP_PERISS" //MรO DE OBRA TAMBษM PUXAR QUANTIDADE DE HORAS DO FPP_QTDHR
	CSQL += "  ORDER BY FPA_OBRA, FPA_SEQGRU, B1_COD DESC, FPA_AS"
ELSE
	//BLOCO ABAIXO UNIFICADO EM UMA Sำ QUERY
	CSQL := " SELECT DISTINCT ISNULL(FP4_DESPRO,B1_DESC) B1_DESC,ISNULL(FP4_PRODUT,B1_COD) B1_COD,FP4_OBRA, FP4_SEQGUI,FP4_AS,"
	CSQL += " 			      FPP_VALHOR VRHOR,"
	CSQL += " 			      SUM(FPP_QTDHR) MINDIA, FPN_VRPEDA, " //MรO DE OBRA TAMBษM PUXAR QUANTIDADE DE HORAS DO FPP_QTDHR
	CSQL += " 			      SUM(FPP_VLRMOB+FPP_VLRDES) TOTMOB, SUM(FPP_VALSEG) TOTSEG, FPP_PERISS"
	CSQL += "  FROM " + RETSQLNAME("FPN") + " ZLF"
	CSQL += "  INNER JOIN " + RETSQLNAME("FPP") + " ZLM"
	CSQL += "     ON FPP_FILIAL = FPN_FILIAL"
	CSQL += "    AND FPP_COD    = FPN_COD"
	CSQL += "    AND ZLM.D_E_L_E_T_ = ''"
	CSQL += "  RIGHT JOIN " + RETSQLNAME("FP4") + " ZA5"
	CSQL += "  ON FPN_AS = FP4_AS"
	CSQL += "  LEFT JOIN " + RETSQLNAME("SB1") + " SB1"
	CSQL += "  ON B1_COD = FP4_PRODUT" 
	CSQL += "  AND B1_FILIAL ='" + XFILIAL("SB1") + "'"
	CSQL += "  AND SB1.D_E_L_E_T_=''"
	CSQL += "  WHERE FPN_FILIAL = '" + XFILIAL("FPN") + "'"
	CSQL += "  AND FPN_AS BETWEEN '" + MV_PAR01 + "' AND '" + MV_PAR02 + "'"
	CSQL += "  AND FPN_PROJET = '" + TRBFP0->FPN_PROJET + "'"
	CSQL += "  AND FP4_FILIAL ='" + XFILIAL("FP4") + "'"
	CSQL += "  AND FPN_FILIAL ='" + XFILIAL("FPN") + "'"
	CSQL += "  AND FPN_SITUAC NOT IN(6)"
	CSQL += "  AND ZLM.FPP_XTIPOH <> 'E'"
	CSQL += "  AND ZLF.D_E_L_E_T_=''"
	CSQL += "  AND ZA5.D_E_L_E_T_=''"
	CSQL += "  GROUP BY FP4_DESPRO, B1_DESC, FP4_PRODUT, B1_COD, FPP_VALHOR, FP4_OBRA, FP4_SEQGUI, FP4_AS, FPN_VRPEDA, FPP_PERISS" //MรO DE OBRA TAMBษM PUXAR QUANTIDADE DE HORAS DO FPP_QTDHR
	CSQL += "  ORDER BY FP4_OBRA, FP4_SEQGUI, B1_COD DESC, FP4_AS"
ENDIF

IF SELECT("TRBSB1") > 0
	TRBSB1->(DBCLOSEAREA())
ENDIF

TCQUERY CSQL NEW ALIAS "TRBSB1"

WHILE TRBSB1->(!EOF())
	NLIN += 10
	OPRINTER:SAY(NLIN,0010,CLINE,OFONT4:OFONT)
	OPRINTER:SAY(NLIN,0040,TRBSB1->B1_COD,OFONT4:OFONT)
	OPRINTER:SAY(NLIN,0090,SUBSTR(ALLTRIM(TRBSB1->B1_DESC),1,50),OFONT4:OFONT)
	OPRINTER:SAY(NLIN,0370,CVALTOCHAR(TRBSB1->MINDIA)+" HS",OFONT4:OFONT)
	OPRINTER:SAY(NLIN,0420,"R$"+CVALTOCHAR(TRANSFORM(TRBSB1->VRHOR,"@E 999,999,999.99")),OFONT4:OFONT)
	OPRINTER:SAY(NLIN,0500,"R$"+CVALTOCHAR(TRANSFORM(TRBSB1->MINDIA * TRBSB1->VRHOR,"@E 999,999,999.99")),OFONT4:OFONT)
	NLINE++
	CLINE:=CVALTOCHAR(NLINE)
	NVALGERAL+=TRBSB1->MINDIA * TRBSB1->VRHOR
	IF FP0->FP0_TIPOSE == "P"
		CSQL := " SELECT DISTINCT CASE WHEN FPE_DIASEM = '' OR FPE_DIASEM = '0'"
		CSQL += " 					   THEN 0"
		CSQL += " 					   WHEN FPE_DIASEM = '7' "
		CSQL += " 					   THEN 1 "
		CSQL += " 					   WHEN FPE_DIASEM = '1' "
		CSQL += " 					   THEN 2 "
		CSQL += " 					  ELSE FPE_DIASEM END ORDEM, "
		CSQL += "                 CASE WHEN FPE_DIASEM = ''"
		CSQL += " 					   THEN '0'"
		CSQL += " 					  ELSE FPE_DIASEM END FPE_DIASEM,"
		CSQL += " 		  FPE_PORCEN, FPE_TIPOSE, FPE_VALTUR "
		CSQL += "    FROM " + RETSQLNAME("FPA") + " ZAG INNER JOIN " + RETSQLNAME("FPE") + " ZBB"
		CSQL += "      ON FPA_FILIAL = FPE_FILIAL"
		CSQL += "     AND FPA_PROJET = FPE_PROJET"
		CSQL += "     AND FPA_OBRA   = FPE_OBRA"
		CSQL += "     AND FPA_SEQGRU = FPE_SEQGUI"
		CSQL += "     AND FPE_TIPOSE = '2'"
		CSQL += "     AND ZBB.D_E_L_E_T_ = ''"
		CSQL += "   WHERE FPA_FILIAL = '" + XFILIAL("FPA") + "'"
		CSQL += "     AND FPA_PROJET = '" + ALLTRIM(TRBFP0->FPN_PROJET) + "'"
		CSQL += "     AND FPA_AS BETWEEN '" + MV_PAR01 + "' AND '" + MV_PAR02 + "'"
		CSQL += "     AND FPA_OBRA   = '" + ALLTRIM(TRBSB1->FPA_OBRA) + "'"
		CSQL += "     AND FPA_SEQGRU = '" + ALLTRIM(TRBSB1->FPA_SEQGRU) + "'"
		CSQL += "     AND ZAG.D_E_L_E_T_ = ''"
	ELSE
		CSQL := " SELECT DISTINCT CASE WHEN FPE_DIASEM = '' OR FPE_DIASEM = '0'"
		CSQL += " 					   THEN 0"
		CSQL += " 					   WHEN FPE_DIASEM = '7' "
		CSQL += " 					   THEN 1 "
		CSQL += " 					   WHEN FPE_DIASEM = '1' "
		CSQL += " 					   THEN 2 "
		CSQL += " 					  ELSE FPE_DIASEM END ORDEM, "
		CSQL += "                 CASE WHEN FPE_DIASEM = ''"
		CSQL += " 					   THEN '0'"
		CSQL += " 					  ELSE FPE_DIASEM END FPE_DIASEM,"
		CSQL += " 		  FPE_PORCEN, FPE_TIPOSE, FPE_VALTUR "
		CSQL += "    FROM " + RETSQLNAME("FP4") + " ZA5 INNER JOIN " + RETSQLNAME("FPE") + " ZBB"
		CSQL += "      ON FP4_FILIAL = FPE_FILIAL"
		CSQL += "     AND FP4_PROJET = FPE_PROJET"
		CSQL += "     AND FP4_OBRA   = FPE_OBRA"
		CSQL += "     AND FP4_SEQGUI = FPE_SEQGUI"
		IF SUBSTR(TRBSB1->FP4_AS,1,2) == "06"
			CSQL += " AND FPE_TIPOSE = '1'"
		ELSE
			CSQL += " AND FPE_TIPOSE = '2'"
		ENDIF
		CSQL += "     AND ZBB.D_E_L_E_T_ = ''"
		CSQL += "   WHERE FP4_FILIAL = '" + XFILIAL("FP4") + "'"
		CSQL += "     AND FP4_PROJET = '" + ALLTRIM(TRBFP0->FPN_PROJET) + "'"
		CSQL += "     AND FP4_AS BETWEEN '" + MV_PAR01 + "' AND '" + MV_PAR02 + "'"
		CSQL += "     AND FP4_OBRA   = '" + ALLTRIM(TRBSB1->FP4_OBRA) + "'"
		CSQL += "     AND FP4_SEQGUI = '" + ALLTRIM(TRBSB1->FP4_SEQGUI) + "'"
		CSQL += "     AND ZA5.D_E_L_E_T_ = ''"
	ENDIF
	
	IF SELECT("TRBZBB") > 0
		TRBFPE->(DBCLOSEAREA())
	ENDIF
	
	TCQUERY CSQL NEW ALIAS "TRBZBB"
	
	WHILE TRBFPE->(!EOF()) //FPE->(!EOF()) .AND. TRBFP0->FPN_PROJET == FPE->FPE_PROJET  .AND. FPE->FPE_SEQGUI == FP4->FP4_SEQGUI
		// TRAGO OS ACRESCIMOS QUE VEM DA TABELA DE TURNOS
		
		IF SELECT("TRBZLM") > 0
			TRBFPP->(DBCLOSEAREA())
		ENDIF
		
		IF FP0->FP0_TIPOSE == "P"
			CSQL:="SELECT SUM(FPP_QTDHR) TOT,FPP_VALHOR  FROM "+RETSQLNAME("FPN")+ " ZLF "
			CSQL+=" RIGHT JOIN "+RETSQLNAME("FPP")+ " ZLM "
			CSQL+=" ON FPN_COD = FPP_COD "
			CSQL+=" INNER JOIN "+RETSQLNAME("FPA")+ " ZAG "
			CSQL+="  ON FPA_FILIAL = '" + XFILIAL("FP4") + "' "
			CSQL+=" AND FPA_PROJET = FPN_PROJET "
			CSQL+=" AND FPA_AS = FPN_AS "
			CSQL+=" AND ZAG.D_E_L_E_T_ = '' "
			CSQL+=" WHERE FPN_FILIAL = '" + XFILIAL("FPN") + "'"
			CSQL+=" AND FPN_AS BETWEEN '"+MV_PAR01+"' AND '" + MV_PAR02 + "'"
			CSQL+=" AND FPN_PROJET = '"+TRBFP0->FPN_PROJET+"'"
			CSQL+=" AND FPN_FILIAL ='"+XFILIAL("FPN")+"'"
			CSQL+=" AND FPP_FILIAL ='"+XFILIAL("FPP")+"'"
			IF "," $ CVALTOCHAR(TRBFPE->FPE_PORCEN) .OR. "." $ CVALTOCHAR(TRBFPE->FPE_PORCEN)
				CSQL+=" AND FPP_PERHAD IN ('"+STRTRAN(CVALTOCHAR(TRBFPE->FPE_PORCEN),",",".")+"','"+STRTRAN(CVALTOCHAR(TRBFPE->FPE_PORCEN),".",",")+"')"
			ELSE
				CSQL+=" AND FPP_PERHAD ='"+CVALTOCHAR(TRBFPE->FPE_PORCEN)+"'"
			ENDIF
			DO CASE
			CASE TRBFPE->FPE_DIASEM == "1" //DOMINGO OU FERIADO
				CSQL+=" AND (UPPER(DATENAME(DW,CAST(FPP_DTMEDI AS DATE))) IN ('SUNDAY','DOMINGO')"
				CSQL+="  OR EXISTS(SELECT *"
				CSQL+="    FROM " + RETSQLNAME("SX5") + " SX5"
				CSQL+="   WHERE X5_TABELA = '63'"
				CSQL+="     AND X5_FILIAL = FPP_FILIAL"
				CSQL+="     AND (CASE WHEN SUBSTRING(X5_DESCRI,1,8) LIKE '%/%'"
				CSQL+="  			THEN CASE WHEN SUBSTRING(X5_DESCRI,6,1) = '/'"
				CSQL+="  					  THEN SUBSTRING(X5_DESCRI,1,8)"
				CSQL+="  					  ELSE SUBSTRING(X5_DESCRI,1,5) END"
				CSQL+="  			ELSE '' END = SUBSTRING(FPP_DTMEDI,7,2) + '/' + SUBSTRING(FPP_DTMEDI,5,2)"
				CSQL+="      OR CASE WHEN SUBSTRING(X5_DESCRI,1,8) LIKE '%/%'"
				CSQL+="  			THEN CASE WHEN SUBSTRING(X5_DESCRI,6,1) = '/'"
				CSQL+="  					  THEN SUBSTRING(X5_DESCRI,1,8)"
				CSQL+="  					  ELSE SUBSTRING(X5_DESCRI,1,5) END"
				CSQL+="  			ELSE '' END = SUBSTRING(FPP_DTMEDI,7,2) + '/' + SUBSTRING(FPP_DTMEDI,5,2) + '/' + SUBSTRING(FPP_DTMEDI,3,2))"
				CSQL+="     AND SX5.D_E_L_E_T_ = ''))"
			CASE TRBFPE->FPE_DIASEM == "7" //SมBADO
				CSQL+=" AND UPPER(DATENAME(DW,CAST(FPP_DTMEDI AS DATE))) IN ('SATURDAY','SมBADO','SABADO')"
			OTHERWISE
				CSQL+=" AND UPPER(DATENAME(DW,CAST(FPP_DTMEDI AS DATE))) NOT IN ('SATURDAY','SมBADO','SABADO','SUNDAY','DOMINGO')"	
			ENDCASE
			CSQL+=" AND FPP_XTIPOH ='E'"
			CSQL+=" AND FPN_SITUAC NOT IN(6)"
			CSQL+=" AND FPN_AS     = '" + TRBSB1->FPA_AS + "'"
			CSQL+=" AND FPN_OBRA   = '" + TRBSB1->FPA_OBRA + "'"
			CSQL+=" AND ZLF.D_E_L_E_T_=''"
			CSQL+=" AND ZLM.D_E_L_E_T_=''"
			CSQL+=" GROUP BY FPP_VALHOR"
		ELSE
			CSQL:="SELECT SUM(FPP_QTDHR) TOT,FPP_VALHOR  FROM "+RETSQLNAME("FPN")+ " ZLF "
			CSQL+=" RIGHT JOIN "+RETSQLNAME("FPP")+ " ZLM "
			CSQL+=" ON FPN_COD = FPP_COD "
			CSQL+=" INNER JOIN "+RETSQLNAME("FP4")+ " ZA5 "
			CSQL+="  ON FP4_FILIAL = '" + XFILIAL("FP4") + "' "
			CSQL+=" AND FP4_PROJET = FPN_PROJET "
			CSQL+=" AND FP4_AS = FPN_AS "
			CSQL+=" AND ZA5.D_E_L_E_T_ = '' "
			CSQL+=" WHERE FPN_FILIAL = '" + XFILIAL("FPN") + "'"
			CSQL+=" AND FPN_AS BETWEEN '"+MV_PAR01+"' AND '" + MV_PAR02 + "'"
			CSQL+=" AND FPN_PROJET = '"+TRBFP0->FPN_PROJET+"'"
			CSQL+=" AND FPN_FILIAL ='"+XFILIAL("FPN")+"'"
			CSQL+=" AND FPP_FILIAL ='"+XFILIAL("FPP")+"'"
			IF "," $ CVALTOCHAR(TRBFPE->FPE_PORCEN) .OR. "." $ CVALTOCHAR(TRBFPE->FPE_PORCEN)
				CSQL+=" AND FPP_PERHAD IN ('"+STRTRAN(CVALTOCHAR(TRBFPE->FPE_PORCEN),",",".")+"','"+STRTRAN(CVALTOCHAR(TRBFPE->FPE_PORCEN),".",",")+"')"
			ELSE
				CSQL+=" AND FPP_PERHAD ='"+CVALTOCHAR(TRBFPE->FPE_PORCEN)+"'"
			ENDIF
			DO CASE
			CASE TRBFPE->FPE_DIASEM == "1" //DOMINGO OU FERIADO
				CSQL+=" AND (UPPER(DATENAME(DW,CAST(FPP_DTMEDI AS DATE))) IN ('SUNDAY','DOMINGO')"
				CSQL+="  OR EXISTS(SELECT *"
				CSQL+="    FROM " + RETSQLNAME("SX5") + " SX5"
				CSQL+="   WHERE X5_TABELA = '63'"
				CSQL+="     AND X5_FILIAL = FPP_FILIAL"
				CSQL+="     AND (CASE WHEN SUBSTRING(X5_DESCRI,1,8) LIKE '%/%'"
				CSQL+="  			THEN CASE WHEN SUBSTRING(X5_DESCRI,6,1) = '/'"
				CSQL+="  					  THEN SUBSTRING(X5_DESCRI,1,8)"
				CSQL+="  					  ELSE SUBSTRING(X5_DESCRI,1,5) END"
				CSQL+="  			ELSE '' END = SUBSTRING(FPP_DTMEDI,7,2) + '/' + SUBSTRING(FPP_DTMEDI,5,2)"
				CSQL+="      OR CASE WHEN SUBSTRING(X5_DESCRI,1,8) LIKE '%/%'"
				CSQL+="  			THEN CASE WHEN SUBSTRING(X5_DESCRI,6,1) = '/'"
				CSQL+="  					  THEN SUBSTRING(X5_DESCRI,1,8)"
				CSQL+="  					  ELSE SUBSTRING(X5_DESCRI,1,5) END"
				CSQL+="  			ELSE '' END = SUBSTRING(FPP_DTMEDI,7,2) + '/' + SUBSTRING(FPP_DTMEDI,5,2) + '/' + SUBSTRING(FPP_DTMEDI,3,2))"
				CSQL+="     AND SX5.D_E_L_E_T_ = ''))"
			CASE TRBFPE->FPE_DIASEM == "7" //SมBADO
				CSQL+=" AND UPPER(DATENAME(DW,CAST(FPP_DTMEDI AS DATE))) IN ('SATURDAY','SมBADO','SABADO')"
			OTHERWISE
				CSQL+=" AND UPPER(DATENAME(DW,CAST(FPP_DTMEDI AS DATE))) NOT IN ('SATURDAY','SมBADO','SABADO','SUNDAY','DOMINGO')"	
			ENDCASE
			IF TRBFPE->FPE_TIPOSE == "1"
				CSQL += " AND FP4_TIPOSE = 'M'"
			ENDIF
			CSQL+=" AND FPP_XTIPOH ='E'"
			CSQL+=" AND FPN_SITUAC NOT IN(6)"
			CSQL+=" AND FPN_AS     = '" + TRBSB1->FP4_AS + "'"
			CSQL+=" AND FPN_OBRA   = '" + TRBSB1->FP4_OBRA + "'"
			CSQL+=" AND ZLF.D_E_L_E_T_=''"
			CSQL+=" AND ZLM.D_E_L_E_T_=''"
			CSQL+=" GROUP BY FPP_VALHOR"
		ENDIF
		CHANGEQUERY(CSQL)
		DBUSEAREA(.T.,"TOPCONN",TCGENQRY(,,CSQL),"TRBZLM",.F.,.T.)
		TRBFPP->(DBGOTOP())
		
		IF TRBFPP->FPP_VALHOR > 0
			NLIN+=10
		 //	WHILE TRBFPP->(!EOF())
			OPRINTER:SAY(NLIN,0010,CLINE,OFONT4:OFONT)
		 //	OPRINTER:SAY(NLIN,0090,"ACRES. 10% ANTES DAS 07 HS E APำS 18 HS",OFONT4:OFONT)
			DO CASE
			CASE TRBFPE->FPE_DIASEM == "1" //DOMINGO
				OPRINTER:SAY(NLIN,0090,"ACRES. "+CVALTOCHAR(TRBFPE->FPE_PORCEN)+"%"+" AOS DOMINGOS E FERIADOS",OFONT4:OFONT)
			CASE TRBFPE->FPE_DIASEM == "7" //SมBADO
				OPRINTER:SAY(NLIN,0090,"ACRES. "+CVALTOCHAR(TRBFPE->FPE_PORCEN)+"%"+" AOS SมBADOS",OFONT4:OFONT)
			OTHERWISE
				OPRINTER:SAY(NLIN,0090,"ACRES. "+CVALTOCHAR(TRBFPE->FPE_PORCEN)+"%"+" ANTES DAS 07 HS E APำS 18 HS",OFONT4:OFONT)	
			ENDCASE
			OPRINTER:SAY(NLIN,0370,CVALTOCHAR(TRBFPP->TOT)+" HS",OFONT4:OFONT)
			OPRINTER:SAY(NLIN,0420,"R$"+CVALTOCHAR(TRANSFORM(TRBFPE->FPE_VALTUR,"@E 999,999,999.99")),OFONT4:OFONT)
			OPRINTER:SAY(NLIN,0500,"R$"+CVALTOCHAR(TRANSFORM(TRBFPP->TOT * TRBFPE->FPE_VALTUR,"@E 999,999,999.99")),OFONT4:OFONT)
		 //	NLIN += 10
			NLINE++
			CLINE:=CVALTOCHAR(NLINE)
		 //	CITEM:=SOMA1(CVALTOCHAR(CITEM))
			NVALGERAL+=TRBFPP->TOT * TRBFPP->FPP_VALHOR
		ENDIF
		TRBFPE->(DBSKIP())
	ENDDO
	TRBFPE->(DBCLOSEAREA())

	IF NPERISS = 0
		NPERISS:=TRBSB1->FPP_PERISS
	ENDIF

	IF TRBSB1->TOTMOB > 0
		NMOB := TRBSB1->TOTMOB
	ELSE
		NMOB := 0
	ENDIF

	IF TRBSB1->TOTSEG > 0
		NSEG := TRBSB1->TOTSEG
	ELSE
		NSEG := 0
	ENDIF
	
	IF NMOB > 0
		NLIN += 10
		OPRINTER:SAY(NLIN,0010,CLINE,OFONT4:OFONT)
		OPRINTER:SAY(NLIN,0090,"TAXA DE MOBILIZAวรO / DESMOBILIZAวรO",OFONT4:OFONT)
		OPRINTER:SAY(NLIN,0370,"1 HS",OFONT4:OFONT)
		OPRINTER:SAY(NLIN,0420,"R$"+CVALTOCHAR(TRANSFORM(NMOB,"@E 999,999,999.99")),OFONT4:OFONT)
		OPRINTER:SAY(NLIN,0500,"R$"+CVALTOCHAR(TRANSFORM(NMOB,"@E 999,999,999.99")),OFONT4:OFONT)
		NLINE++
		CLINE:=CVALTOCHAR(NLINE)
		NVALGERAL+=NMOB
	ENDIF

	IF NSEG > 0
		NLIN += 10
		OPRINTER:SAY(NLIN,0010,CLINE,OFONT4:OFONT)
		OPRINTER:SAY(NLIN,0090,"SEGURO",OFONT4:OFONT)
		OPRINTER:SAY(NLIN,0370,"",OFONT4:OFONT)
		OPRINTER:SAY(NLIN,0420,"R$"+CVALTOCHAR(TRANSFORM(NSEG,"@E 999,999,999.99")),OFONT4:OFONT)
		OPRINTER:SAY(NLIN,0500,"R$"+CVALTOCHAR(TRANSFORM(NSEG,"@E 999,999,999.99")),OFONT4:OFONT)
		NLINE++
		CLINE:=CVALTOCHAR(NLINE)
		NVALGERAL += NSEG
	ENDIF
	
	IF TRBSB1->FPN_VRPEDA > 0
		NLIN += 10
		OPRINTER:SAY(NLIN,0010,CLINE,OFONT4:OFONT)
		OPRINTER:SAY(NLIN,0090,"PEDมGIOS",OFONT4:OFONT)
		OPRINTER:SAY(NLIN,0370,"1 HS",OFONT4:OFONT)
		OPRINTER:SAY(NLIN,0420,"R$"+CVALTOCHAR(TRANSFORM(TRBSB1->FPN_VRPEDA,"@E 999,999,999.99")),OFONT4:OFONT)
		OPRINTER:SAY(NLIN,0500,"R$"+CVALTOCHAR(TRANSFORM(TRBSB1->FPN_VRPEDA,"@E 999,999,999.99")),OFONT4:OFONT)
	 //	NLIN += 10
		NLINE++
		CLINE:=CVALTOCHAR(NLINE)
		NVALGERAL+=TRBSB1->FPN_VRPEDA
	ENDIF
	
	TRBSB1->(DBSKIP())
ENDDO
TRBSB1->(DBCLOSEAREA())

IF LFIM = .T.
	RETURN .F.
ENDIF

// FAวO A CONSULTA PRA PODER IMPRIMIR OS CUSTOS EXTRAS NO FINAL

// QUERY
IF SELECT("TRBCUS") > 0
	TRBCUS->(DBCLOSEAREA())
ENDIF

CSQL:= " SELECT DISTINCT FPN_AS"
CSQL+= " FROM "+RETSQLNAME("FPN")+ " ZLF"
CSQL+= " WHERE FPN_AS >='"+MV_PAR01+"' "
CSQL+= " AND FPN_AS <='"+MV_PAR02+"' "
CSQL+= " AND FPN_COD>='"+MV_PAR03+"' "
CSQL+= " AND FPN_COD <='"+MV_PAR04+"' "
CSQL+= " AND FPN_PROJET ='"+MV_PAR05+"' "
CSQL+= " AND FPN_SITUAC NOT IN(6)"
CSQL+= " AND ZLF.D_E_L_E_T_ ='' "
PLSQUERY(CSQL,"TRBCUS")
DBSELECTAREA("TRBCUS")
TRBCUS->(DBGOTOP())

WHILE !TRBCUS->(EOF())
	
	IF SELECT("TRBZC1") > 0
		TRBFPG->(DBCLOSEAREA())
	ENDIF
	
	// TRAGO O CUSTO EXTRA
	// QUERY TRAZER O CUSTO EXTRA
	CSQL := " SELECT DISTINCT FPG_PRODUT,FPG_DESCRI,FPG_QUANT,FPG_VALOR,FPG_VLUNIT ,(FPG_QUANT * FPG_VLUNIT) TOTZC1 "
	CSQL += " FROM "+RETSQLNAME("FPG")+" ZC1"
	CSQL += " WHERE  FPG_NRAS ='"+TRBCUS->FPN_AS+"'"
	CSQL +=   " AND  FPG_FILIAL ='"+XFILIAL("FPG")+"'"
	CSQL +=   " AND  ZC1.D_E_L_E_T_=''"
	CSQL += " ORDER BY FPG_PRODUT DESC "
	CHANGEQUERY(CSQL)
	DBUSEAREA(.T.,"TOPCONN",TCGENQRY(,,CSQL),"TRBZC1",.F.,.T.)
	TRBFPG->(DBGOTOP())
	
	WHILE TRBFPG->(!EOF())
		IF TRBFPG->FPG_VLUNIT > 0
			NLIN += 10
			OPRINTER:SAY(NLIN,0010,CLINE,OFONT4:OFONT)
			OPRINTER:SAY(NLIN,0040,TRBFPG->FPG_PRODUT,OFONT4:OFONT)
			OPRINTER:SAY(NLIN,0090,SUBSTR(TRBFPG->FPG_DESCRI,1,50),OFONT4:OFONT)
			OPRINTER:SAY(NLIN,0370,CVALTOCHAR(TRBFPG->FPG_QUANT)+" HS",OFONT4:OFONT)
			OPRINTER:SAY(NLIN,0420,"R$"+CVALTOCHAR(TRANSFORM(TRBFPG->FPG_VLUNIT,"@E 999,999,999.99")),OFONT4:OFONT)
			OPRINTER:SAY(NLIN,0500,"R$"+CVALTOCHAR(TRANSFORM(TRBFPG->TOTZC1,"@E 999,999,999.99")),OFONT4:OFONT)
			NLINE ++
			CLINE := CVALTOCHAR(NLINE)
			NVALGERAL += TRBFPG->TOTZC1
		ENDIF
		TRBFPG->(DBSKIP())
	ENDDO
	
	TRBCUS->(DBSKIP())
ENDDO

// PERCENTUAL SEMPRE SERA O ULTIMO APOS AGREGAR TODOS OS VALORES
IF NPERISS > 0
	NLIN += 10  
	
	NPERISS2 := 100- NPERISS
	NPERISS3 := NPERISS2/100
	NVALISS  := NVALGERAL/NPERISS3
	NRESTO   := 100 - NPERISS2
	NRESTO   := NRESTO/100
	NVALISS  := NVALISS*NRESTO

	OPRINTER:SAY(NLIN,0010,CLINE,OFONT4:OFONT)
	OPRINTER:SAY(NLIN,0090,"ISS "+CVALTOCHAR(NPERISS)+"% S/VALOR TOTAL DA NOTA FISCAL",OFONT4:OFONT)
	OPRINTER:SAY(NLIN,0370,"1 HS",OFONT4:OFONT)
 //	NVALISS  := NVALGERAL/100
 //	NVALISS  := NVALGERAL * NPERISS/100
	NVALGERAL+= NVALISS
	OPRINTER:SAY(NLIN,0420,"R$"+CVALTOCHAR(TRANSFORM(NVALISS,"@E 999,999,999.99")),OFONT4:OFONT)
	OPRINTER:SAY(NLIN,0500,"R$"+CVALTOCHAR(TRANSFORM(NVALISS,"@E 999,999,999.99")),OFONT4:OFONT)
	
	NLINE++
	CLINE:=CVALTOCHAR(NLINE)
ENDIF
NLIN += 20
DBSELECTAREA("SA1")
DBSETORDER(1)
DBSEEK(XFILIAL("SA1")+TRBFP0->FPN_CLIENT)

NVALGERAL:=TRANSFORM(NVALGERAL,"@E 999,999,999.99")
OPRINTER:SAY(NLIN,0450,"TOTAL",OFONT3:OFONT)
OPRINTER:SAY(NLIN,0500,"R$"+CVALTOCHAR(NVALGERAL),OFONT4:OFONT)
NLIN += 10
OPRINTER:SAY(NLIN,0050,"CONDIวรO DE PAGAMENTO:",OFONT2:OFONT)
CCOND:=POSICIONE("SE4",1,XFILIAL("SE4")+SA1->A1_COND,"E4_DESCRI")
OPRINTER:SAY(NLIN,0165,CCOND,OFONT4:OFONT)
NLIN += 5
OPRINTER:BOX(NLIN,0010,NLIN,0590)
NLIN += 20

OPRINTER:ENDPAGE()
NLIN := 30
NPAG ++
CPAG := CVALTOCHAR(NPAG)
/*
IF TRBFP0->FPN_AS <> MV_PAR02
	TRBFP0->(DBSKIP())
	FDADOS()
ENDIF
*/
IF LFIM = .T.
	RETURN .F.
ENDIF

OPRINTER:PREVIEW()
FREEOBJ(OPRINTER)
LFIM := .T.
OPRINTER := NIL

RETURN .T.



/*/
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัอออออออออออหอออออออัอออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบFUNO    ณ VALIDPERG บ AUTOR ณ IT UP BUSINESS    บ DATA ณ  07/05/2002 บฑฑ
ฑฑฬออออออออออุอออออออออออสอออออออฯอออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDESCRIO ณ VERIFICA A EXISTENCIA DAS PERGUNTAS CRIANDO-AS CASO SEJA   บฑฑ
ฑฑบ          ณ NECESSARIO (CASO NAO EXISTAM).                             บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUSO       ณ ESPECIFICO GPO                                             บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
/*/
STATIC FUNCTION VALIDPERG() 

LOCAL _SALIAS := ALIAS()
LOCAL AREGS   := {}
LOCAL I , J 

DBSELECTAREA("SX1")
DBSETORDER(1)
CPERG := PADR(CPERG,10)

//          GRUPO/ORDEM/PERGUNTA                                                            /VARIAVEL /TIPO/TAMANHO/DECIMAL/PRESEL/GSC/VALID                                          /VAR01     /DEF01         /DEF01         /DEF01         /CNT01/VAR02/DEF02        /DEF02        /DEF02        /CNT02/VAR03/DEF03/DEF03/DEF03/CNT03/VAR04/DEF04/DEF04/DEF04/CNT04/VAR05/DEF05/DEF05/DEF05/CNT05/F3    /PYME/SXG/HELP/PICTURE/IDFIL
AADD(AREGS,{CPERG,"01" ,"AS DE?"   ,"PROJETO DE?"   ,"PROJETO DE?"   ,"MV_CH1" ,"C" ,27     ,0      ,0     ,"G",""                                             ,"MV_PAR01",""            ,""            ,""            ,""   ,""   ,""           ,""           ,""           ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,"FPN"    ,"S" ,"" ,"" ,""})
AADD(AREGS,{CPERG,"02" ,"AS ATษ?"   ,"PROJETO ATษ?"   ,"PROJETO ATษ?"   ,"MV_CH2" ,"C" ,27     ,0      ,0     ,"G",""                                             ,"MV_PAR01",""            ,""            ,""            ,""   ,""   ,""           ,""           ,""           ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,"FPN"    ,"S" ,"" ,"" ,""})
AADD(AREGS,{CPERG,"03" ,"MEDIวรO DE?"   ,"CLIENTE DE?"   ,"CLIENTE DE?"   ,"MV_CH3" ,"C" ,6     ,0      ,0     ,"G",""                                             ,"MV_PAR01",""            ,""            ,""            ,""   ,""   ,""           ,""           ,""           ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,"DTQAS"    ,"S" ,"" ,"" ,""})
AADD(AREGS,{CPERG,"04" ,"MEDIวรO ATษ?"   ,"LOJA DE?"   ,"CLIENTE DE?"   ,"MV_CH4" ,"C" ,6     ,0      ,0     ,"G",""                                             ,"MV_PAR01",""            ,""            ,""            ,""   ,""   ,""           ,""           ,""           ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,"DTQAS"    ,"S" ,"" ,"" ,""})
AADD(AREGS,{CPERG,"05" ,"PROJETO?"   ,"PROJETO?"   ,"PROJETO?"   ,"MV_CH5" ,"C" ,22     ,0      ,0     ,"G",""                                             ,"MV_PAR01",""            ,""            ,""            ,""   ,""   ,""           ,""           ,""           ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,""   ,"FP0"    ,"S" ,"" ,"" ,""})

FOR I:=1 TO LEN(AREGS)
	IF !DBSEEK(CPERG+AREGS[I,2])
		RECLOCK("SX1",.T.)
		FOR J:=1 TO FCOUNT()
			IF J <= LEN(AREGS[I])
				FIELDPUT(J,AREGS[I,J])
			ENDIF
		NEXT J 
		MSUNLOCK()
	ENDIF
NEXT I

DBSELECTAREA(_SALIAS)

RETURN
