#INCLUDE "locr006.ch" 
/*/{PROTHEUS.DOC} LOCR006.PRW
ITUP BUSINESS - TOTVS RENTAL
RELATORIO DISPONIBILIDADE DE MAO DE OBRA-CAIXA DE PROCESSO
@TYPE FUNCTION
@AUTHOR FRANK ZWARG FUGA
@SINCE 03/12/2020
@VERSION P12
@HISTORY 03/12/2020, FRANK ZWARG FUGA, FONTE PRODUTIZADO.
/*/

#INCLUDE "PROTHEUS.CH"

FUNCTION LOCR006()
// --> DECLARACAO DE VARIAVEIS                                             ณ
LOCAL CDESC1        := STR0001 //"ESTE PROGRAMA TEM COMO OBJETIVO IMPRIMIR RELATORIO "
LOCAL CDESC2        := STR0002 //"DE ACORDO COM OS PARAMETROS INFORMADOS PELO USUARIO."
LOCAL CDESC3        := STR0003 //"DISPONIBILIDADE DE MAO DE OBRA - CAIXA DE PROCESSO V1.2"
LOCAL TITULO        := STR0004 //"DISPONIBILIDADE DE MAO DE OBRA - CAIXA DE PROCESSO"
LOCAL NLIN          := 80
LOCAL CPERG         := "LOCP011"
LOCAL CABEC2        := ""
LOCAL AORD          := {}       
LOCAL IMPRIME 

PRIVATE CVERLOCD    := "V1.2"
PRIVATE CABEC1      := ""
PRIVATE LEND        := .F.
PRIVATE LABORTPRINT := .F.
PRIVATE LIMITE      := 120
PRIVATE TAMANHO     := "G"
PRIVATE NOMEPROG    := "LOCDISMO V1.2" // COLOQUE AQUI O NOME DO PROGRAMA PARA IMPRESSAO NO CABECALHO
PRIVATE NTIPO       := 18
PRIVATE ARETURN     := { "ZEBRADO", 1, "ADMINISTRACAO", 2, 2, 1, "", 1}
PRIVATE NLASTKEY    := 0
PRIVATE CBTXT       := SPACE(10)
PRIVATE CBCONT      := 00
PRIVATE CONTFL      := 01
PRIVATE M_PAG       := 01
PRIVATE WNREL       := "LOCDISMO12" 	// COLOQUE AQUI O NOME DO ARQUIVO USADO PARA IMPRESSAO EM DISCO
PRIVATE CSTRING := ""

IMPRIME := .T. 

//VALIDPERG(CPERG)
PERGUNTE(CPERG,.T.)

// --> MONTA A INTERFACE PADRAO COM O USUARIO...                           ณ
WNREL := SETPRINT(CSTRING,NOMEPROG,CPERG,@TITULO,CDESC1,CDESC2,CDESC3,.T.,AORD,.T.,TAMANHO,,.T.)


IF EMPTY(MV_PAR07)  .OR. EMPTY(MV_PAR08) 
	MSGALERT(STR0005 , STR0006)  //"PERIODO INICIAL OU FINAL ESTม(รO) EM BRANCO... PRENCHER !"###"GPO - LOCDISMO.PRW"
	RETURN 
ENDIF 

IF NLASTKEY == 27
	RETURN
ENDIF

SETDEFAULT(ARETURN,CSTRING)

IF NLASTKEY == 27
   RETURN
ENDIF

NTIPO := IF(ARETURN[4]==1,15,18)

// --> PROCESSAMENTO. RPTSTATUS MONTA JANELA COM A REGUA DE PROCESSAMENTO.
RPTSTATUS({|| RUNREPORT(CABEC1,CABEC2,TITULO,NLIN) },TITULO)

RETURN



/*/
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัอออออออออออหอออออออัออออออออออออออออออออหออออออัออออออออออออปฑฑ
ฑฑบFUNO    ณ RUNREPORT บ AUTOR ณ IT UP BUSINESS     บ DATA ณ 30/06/2007 บฑฑ
ฑฑฬออออออออออุอออออออออออสอออออออฯออออออออออออออออออออสออออออฯออออออออออออนฑฑ
ฑฑบDESCRIO ณ FUNCAO AUXILIAR CHAMADA PELA RPTSTATUS. A FUNCAO RPTSTATUS บฑฑ
ฑฑบ          ณ MONTA A JANELA COM A REGUA DE PROCESSAMENTO.               บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUSO       ณ PROGRAMA PRINCIPAL                                         บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
/*/   
STATIC FUNCTION RUNREPORT(CABEC1,CABEC2,TITULO,NLIN)

LOCAL CARQUIVO  		// ARQUIVO PADRรO HTML NA PASTA SERVER\SYSTEM
LOCAL NARQ      		// ABERTURA DO ARQUIVO BINมRIO
LOCAL CHTML				// STRINGS TEMPORมRIA PARA ALIMENTAR O ARQUIVO.HTML

	// MONTA JOIN USADO VARIAS VEZES PARA NAO DUPLICAR CODIFICACAO
 	CJOIN := " LEFT JOIN "+ RETSQLNAME("SRJ") + " RJ  ON RJ.D_E_L_E_T_='' AND RJ_FUNCAO = RA_CODFUNC   " + CRLF
 	CJOIN += " LEFT JOIN "+ RETSQLNAME("SRF") + " RF  ON RF.D_E_L_E_T_='' AND RF_MAT=RA_MAT AND RA_FILIAL = RF_FILIAL " + CRLF
   	CJOIN1:= " LEFT JOIN (SELECT 'ALOCADO   ' STAT_MO, ZLD.*,ISNULL(FP1_NOMORI,'SEM ZA1') MUN_OBRA ,FQ5_DESTIN " + CRLF
	CJOIN1+= "            FROM "+ RETSQLNAME("FPL") + " ZLD  " + CRLF
	CJOIN1+= "            LEFT JOIN "+ RETSQLNAME("FQ5") + " DTQ ON FQ5_AS = FPL_AS AND DTQ.D_E_L_E_T_ = '' 
	CJOIN1+= "            LEFT JOIN "+ RETSQLNAME("FP1") + " ZA1 ON FP1_PROJET = FPL_PROJET  AND FP1_OBRA = FPL_OBRA AND ZA1.D_E_L_E_T_ = '' " + CRLF
	CJOIN1+= "            WHERE ZLD.D_E_L_E_T_='' " + CRLF
	CJOIN1 += 		" AND ((FPL_DTINI <= '"  + DTOS(MV_PAR07) + "' AND FPL_DTINI <= '" + DTOS(MV_PAR08)  + "' AND FPL_DTFIM >= '"  + DTOS(MV_PAR07) + "'  AND FPL_DTFIM >= '" + DTOS(MV_PAR08) + "') OR "	// PERอODO TOTALMENTE DENTRO DO LANวAMENTO
	CJOIN1 +=       " (FPL_DTINI >= '"  + DTOS(MV_PAR07) + "' AND FPL_DTINI <= '" + DTOS(MV_PAR08)  + "' AND FPL_DTFIM >= '"  + DTOS(MV_PAR07) + "'  AND FPL_DTFIM <= '" + DTOS(MV_PAR08) + "') OR "	// PERอODO TOTALMENTE FORA DO LANวAMENTO
	CJOIN1 +=       " (FPL_DTINI <= '"  + DTOS(MV_PAR07) + "' AND FPL_DTINI<= '" + DTOS(MV_PAR08)  + "' AND FPL_DTFIM >= '"  + DTOS(MV_PAR07) + "'  AND FPL_DTFIM <= '" + DTOS(MV_PAR08) + "') OR "	// LANวAMENTO TERMINA NO PERอODO
	CJOIN1 +=       " (FPL_DTINI >= '"  + DTOS(MV_PAR07) + "' AND FPL_DTINI<= '" + DTOS(MV_PAR08)  + "' AND FPL_DTFIM >= '"  + DTOS(MV_PAR07) + "'  AND FPL_DTFIM >= '" + DTOS(MV_PAR08) + "'))) MAO  "	// LANวAMENTO INICIA NO PERอODO
	CJOIN1+= " ON RA_MAT = FPL_MATRIC AND FPL_FILIAL = RA_FILIAL            " + CRLF
 
    // MONTA WHERE USADO VARIAS VEZES PARA NAO DUPLICAR CODIFICACAO
	CQRYWHER := " WHERE RA.D_E_L_E_T_ = '' AND RA_FILIAL = '"+ XFILIAL("SRA")+ "' AND RA_TSHEET = 'S' " + CRLF
	CQRYWHER += "       AND RA_MAT BETWEEN '"+MV_PAR01+"' AND '"+MV_PAR02+"' -- MATRICULA DE ATE " + CRLF
	CQRYWHER += "       AND '"+MV_PAR10+"' LIKE '%'+RA_SITFOLH+ '%' -- SITUACAO ESCOLHIDA"+ CRLF
	CQRYWHER += "       AND RA_CODFUNC BETWEEN '"+MV_PAR03+"' AND '"+MV_PAR04+"' -- FUNCAO DE ATE " + CRLF
	CQRYWHER += "       AND ISNULL(FPL_AS,'"+MV_PAR05+"') BETWEEN '"+MV_PAR05+"' AND '"+MV_PAR06+"' -- AS  DE ATE " + CRLF
	IF MV_PAR09 == 1 						// DISPONIVEL 
		CQRYWHER += "  AND FPL_AS IS NULL " + CRLF
	ELSEIF MV_PAR09 == 2					// ALOCADO 
 		CQRYWHER += "  AND FPL_AS IS NOT NULL " + CRLF
	ENDIF
	
	CQRYINT := "SELECT DISTINCT FPL_FILIAL, FPL_MATRIC, FPL_DTINI, FPL_DTFIM "+CRLF
	CQRYINT += "FROM "+ RETSQLNAME("SRA") + " RA "+CRLF
	CQRYINT += CJOIN + CJOIN1 +CQRYWHER		// APROVEITA MONTAGEM FEITA ANTERIORMENTE
	CQRYINT += "                  AND FPL_DTINI BETWEEN '"+DTOS(MV_PAR07)+"' AND '"+DTOS(MV_PAR08)+"' -- PERIODO DE ATE " + CRLF
	CQRYINT += "                  AND FPL_DTFIM BETWEEN '"+DTOS(MV_PAR07)+"' AND '"+DTOS(MV_PAR08)+"'  --PERIODO DE ATE "+ CRLF
	CQRYINT += "ORDER BY 1,2,3   
	
	CARQDIAS := LOCXITU08(CQRYINT,"FPL_MATRIC", "FPL_DTINI","FPL_DTFIM",MV_PAR07, MV_PAR08, "FPL_FILIAL" )

	CQUERY := " SELECT RA_FILIAL, RA_MAT, RA_NOME, RJ_DESC, ISNULL(FPL_AS, '')FPL_AS, ISNULL(STAT_MO, 'DISPONIVEL') STAT_MO,  " + CRLF
	CQUERY += "        ISNULL(FPL_DTINI,'"+DTOS(MV_PAR07)+"')FPL_DTINI, ISNULL(FPL_DTFIM,'"+DTOS(MV_PAR08)+"')FPL_DTFIM, LEFT(ISNULL(MUN_OBRA, 'EMPRESA'),30) MUN_OBRA,  " + CRLF
	CQUERY += "        LEFT(ISNULL(FQ5_DESTIN, ''),30) FQ5_DESTIN, ISNULL(RF_DATABAS, '20200101') VENCTO_FER,RA_SITFOLH " + CRLF
	CQUERY += " FROM "+ RETSQLNAME("SRA") + " RA " + CRLF
	CQUERY += CJOIN +CJOIN1					// APROVEITA MONTAGEM FEITA ANTERIORMENTE
	CQUERY += CQRYWHER 						// APROVEITA MONTAGEM FEITA ANTERIORMENTE

	// CONSIDERA DISPONIVEL TODOS OS BENS QUE NAO TIVEREM A DATA NO ZLD A PARTIR DO ARQUIVO DE APOIO
	CQUERY += "UNION ALL" + CRLF
    CQUERY += " SELECT RA_FILIAL, RA_MAT, RA_NOME, RJ_DESC, '' , 'DISPONIVEL', DTINI, DTFIM, '', '',ISNULL(RF_DATABAS, '20200101') VENCTO_FER,RA_SITFOLH  " + CRLF
	CQUERY += "FROM "+ RETSQLNAME("SRA") + " RA " + CRLF
	CQUERY += CJOIN 
	CQUERY += "JOIN "+CARQDIAS + " DIAS ON DIAS.FPL_MATRIC = RA_MAT  AND DIAS.FPL_FILIAL = RA_FILIAL" + CRLF
	CQUERY += "WHERE RA.D_E_L_E_T_ = ''" + CRLF 
	CQUERY += " ORDER BY RA_NOME, 7,8 " + CRLF
	
	//MEMOWRITE("C:\TEMP\LOCDISMO.SQL", CQUERY) //GRAVA RESULTADO DA QUERY NO TEMP DO USUARIO PARA FACILITAR O SUPORTE

	IF SELECT("TRBMO") > 0
	   TRBMO->(DBCLOSEAREA())
	ENDIF   
	
	DBUSEAREA(.T., "TOPCONN", TCGENQRY(,,CQUERY), "TRBMO", .F., .T.)
	TCSETFIELD("TRBMO","FPL_DTINI" ,"D",8,0)
	TCSETFIELD("TRBMO","FPL_DTFIM" ,"D",8,0)
	TCSETFIELD("TRBMO","VENCTO_FER","D",8,0)
	                      
	// --> MONTA CABECALHO COM TAMANHO DINAMICO PELO RESULTADO DA QUERY
	CABEC1 := PADR(STR0007             , LEN(TRBMO->RA_FILIAL)+1) //"FL"
	CABEC1 += PADR(STR0008         , LEN(TRBMO->RA_MAT)+1) //"MATRIC"
	CABEC1 += PADR(STR0009           , LEN(TRBMO->RA_NOME)+1) //"NOME"
	CABEC1 += PADR(STR0010         , LEN(TRBMO->RJ_DESC)+1) //"FUNCAO"
	CABEC1 += PADR(STR0011            , LEN(TRBMO->FPL_AS)+1) //"AS "
	CABEC1 += PADR(STR0012         , LEN(TRBMO->STAT_MO)+1) //"STATUS"
	CABEC1 += PADR(STR0013        , LEN(DTOC(TRBMO->FPL_DTINI))+1) //"DT INIC"
	CABEC1 += PADR(STR0014         , LEN(DTOC(TRBMO->FPL_DTFIM))+1) //"DT FIM"
	CABEC1 += PADR(STR0015          , LEN(TRBMO->MUN_OBRA)+1) //"LOCAL"
	CABEC1 += PADR(STR0016 , LEN(TRBMO->FQ5_DESTIN)+1) //"MUNICIPIO/OBRA"
	CABEC1 += PADR(STR0017       , LEN(DTOC(TRBMO->VENCTO_FER))+3)  //"VCTO FER"
 //	CABEC1 += PADR("SIT FOLHA" , 9) 

	// desativado por questoes dos debitos tecnicos - Frank 06/04/2022
	IF MV_PAR11 == 1							// SE FOR EXPORTAR PARA O EXCEL - CRISTIAM ROSSI EM 30/08/2011
		/*

		CARQUIVO := CRIATRAB(,.F.)+".HTM"		// ARQUIVO PADRรO HTML NA PASTA SERVER\SYSTEM
		NARQ     := FCREATE(CARQUIVO,0)			// ABERTURA DO ARQUIVO BINมRIO

		CHTML := "<HTML><HEAD><TITLE>DISPONIBILIDADE DE MAO DE OBRA</TITLE></HEAD>" + CRLF
		CHTML += "<BODY><TABLE BORDER='1'><TR>"
		CHTML += "<TD COLSPAN='11'><CENTER><H2>DISPONIBILIDADE DE MAO DE OBRA</H2></CENTER>"
		CHTML += STR0018 + IF( EMPTY(MV_PAR01), "", STR0019+MV_PAR01) + STR0020 + MV_PAR02 //"PARยMETROS: MATRอCULA"###" DE :"###" ATษ: "
		CHTML += STR0021 + IF( EMPTY(MV_PAR03), "", STR0019+MV_PAR03) + STR0020 + MV_PAR04 //" - FUNวรO"###" DE :"###" ATษ: "
		CHTML += STR0022 + IF( EMPTY(MV_PAR05), "", STR0019+MV_PAR05) + STR0020 + MV_PAR06 //" - AS "###" DE :"###" ATษ: "
		CHTML += STR0023 + IF( EMPTY(MV_PAR07), "", STR0019+DTOC(MV_PAR07)) + STR0020 + DTOC(MV_PAR08) //" - PERอODO"###" DE :"###" ATษ: "
		CHTML += STR0024 + ALLTRIM(STR(MV_PAR09)) //" - STATUS MO: "
		CHTML += STR0025 + MV_PAR10 //" - SIT. FOLHA: "
		CHTML += "</TD></TR><TR>"
		CHTML += STR0026 //"<TH>FILIAL</TH>"
		CHTML += STR0027 //"<TH>MATRอCULA</TH>"
		CHTML += STR0028 //"<TH>NOME FUNCIONARIO</TH>"
		CHTML += STR0029 //"<TH>FUNวรO</TH>"
		CHTML += STR0030 //"<TH>AS </TH>"
		CHTML += STR0031 //"<TH>STATUS</TH>"
		CHTML += STR0032 //"<TH>DATA INอCIO</TH>"
		CHTML += STR0033 //"<TH>DATA FIM</TH>"
		CHTML += STR0034 //"<TH>LOCAL</TH>"
		CHTML += STR0035 //"<TH>MUNICอPIO/OBRA</TH>"
		CHTML += STR0036 //"<TH>VENCIMENTO</TH>"
		CHTML += "</TR>" + CRLF
		FWRITE(NARQ,CHTML,LEN(CHTML))
		*/
	ENDIF
	
	// --> SETREGUA -> INDICA QUANTOS REGISTROS SERAO PROCESSADOS PARA A REGUA
	SETREGUA(RECCOUNT())
	
	WHILE TRBMO->(!EOF())

	   // --> VERIFICA O CANCELAMENTO PELO USUARIO...
		IF LABORTPRINT
			@ NLIN,00 PSAY STR0037 //"*** CANCELADO PELO OPERADOR ***"
			EXIT
		ENDIF
	
		// --> IMPRESSAO DO CABECALHO DO RELATORIO...
		IF NLIN > 55 // SALTO DE PมGINA. NESTE CASO O FORMULARIO TEM 55 LINHAS...
			CABEC(TITULO,CABEC1,CABEC2,NOMEPROG,TAMANHO,NTIPO)
			NLIN := 8
		ENDIF

		@ NLIN, 000      PSAY TRBMO->RA_FILIAL                                        
		@ NLIN, PCOL()+1 PSAY TRBMO->RA_MAT    
		@ NLIN, PCOL()+1 PSAY TRBMO->RA_NOME    
		@ NLIN, PCOL()+1 PSAY TRBMO->RJ_DESC    
		@ NLIN, PCOL()+1 PSAY TRBMO->FPL_AS
		@ NLIN, PCOL()+1 PSAY TRBMO->STAT_MO    
		CLODTI := IF(TRBMO->FPL_DTINI < MV_PAR07, MV_PAR07, TRBMO->FPL_DTINI )
		CLODTF := IF(TRBMO->FPL_DTFIM > MV_PAR08, MV_PAR08, TRBMO->FPL_DTFIM)
		@ NLIN, PCOL()+1 PSAY CLODTI    
		@ NLIN, PCOL()+1 PSAY CLODTF 
		@ NLIN, PCOL()+1 PSAY TRBMO->MUN_OBRA  
		@ NLIN, PCOL()+1 PSAY TRBMO->FQ5_DESTIN  
		@ NLIN, PCOL()+1 PSAY TRBMO->VENCTO_FER+365 
	 //	@ NLIN, PCOL()+3 PSAY STRTRAN(PADR(TABELA('31',TRBMO->RA_SITFOLH),9), "SITUACA", "NORMAL") 

		IF MV_PAR11 == 1		// SE FOR EXPORTAR PARA O EXCEL
			/*
			CHTML := '<TR>'
			CHTML += '<TD>&NBSP;' + TRBMO->RA_FILIAL + '</TD>'
			CHTML += '<TD>&NBSP;' + TRBMO->RA_MAT + '</TD>'
			CHTML += '<TD>'       + TRBMO->RA_NOME + '</TD>'
			CHTML += '<TD>&NBSP;' + TRBMO->RJ_DESC + '</TD>'
			CHTML += '<TD>'       + TRBMO->FPL_AS + '</TD>'
			CHTML += '<TD>'       + TRBMO->STAT_MO + '</TD>'
			CHTML += '<TD>'       + DTOC(TRBMO->FPL_DTINI) + '</TD>'
			CHTML += '<TD>'       + DTOC(TRBMO->FPL_DTFIM) + '</TD>'
			CHTML += '<TD>'       + TRBMO->MUN_OBRA + '</TD>'
			CHTML += '<TD>'       + TRBMO->FQ5_DESTIN + '</TD>'
			CHTML += '<TD>'       + DTOC(TRBMO->VENCTO_FER+365) + '</TD></TR>' + CRLF
			FWRITE(NARQ,CHTML,LEN(CHTML))
			*/
		ENDIF
	      	
	    NLIN := NLIN + 1 		// AVANCA A LINHA DE IMPRESSAO
	   
		TRBMO->(DBSKIP()) 		// AVANCA O PONTEIRO DO REGISTRO NO ARQUIVO
		   
	ENDDO

    TRBMO->(DBCLOSEAREA())

	// --> FINALIZA A EXECUCAO DO RELATORIO...
	SET DEVICE TO SCREEN
	
	// --> SE IMPRESSAO EM DISCO, CHAMA O GERENCIADOR DE IMPRESSAO...
	IF ARETURN[5]==1
	   DBCOMMITALL()
	   SET PRINTER TO
	   OURSPOOL(WNREL)
	ENDIF
	
	MS_FLUSH()

	IF MV_PAR11 == 1								// SE FOR EXPORTAR PARA O EXCEL
		/*
		CHTML := ' </TABLE></BODY></HTML>'+CRLF
		FWRITE(NARQ,CHTML,LEN(CHTML))
		FCLOSE(NARQ)								// FECHAMOS O ARQUIVO PADRรO HTML
		CPYS2T(GETSRVPROFSTRING("STARTPATH","")+CARQUIVO, ALLTRIM(GETTEMPPATH()), .T.)	// COPIA ARQUIVO HTML DO SERVER\SYSTEM P/ TEMPORมRIO DO CLIENTE
		FERASE(CARQUIVO)							// REMOVE ARQUIVO DO SERVER\SYSTEM
	
		IF APOLECLIENT("MSEXCEL") 					// SE TEM EXCEL NO CLIENTE. ABRIMOS O EXCEL COM O ARQUIVO HTML
			OEXCELAPP := MSEXCEL():NEW()
			OEXCELAPP:WORKBOOKS:OPEN(ALLTRIM(GETTEMPPATH()) + CARQUIVO)
			OEXCELAPP:SETVISIBLE(.T.)
			OEXCELAPP:DESTROY()
		ELSE										// SE NรO ENCONTROU O EXCEL, O S.O. DECIDE COMO ABRIR
			SHELLEXECUTE("OPEN",ALLTRIM(GETTEMPPATH()) + CARQUIVO,"","",1)
		ENDIF
		*/
	ENDIF

RETURN



// ======================================================================= \\
STATIC FUNCTION VALIDPERG(CPERG)
// ======================================================================= \\
/*
CPERG := PADR(CPERG,10)


PUTSX1(CPERG,"01","MATRIC DE?  ","","","MV_CH1","C",06,00,00,"G","","SRAZLD","","","MV_PAR01","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"02","MATRIC ATE? ","","","MV_CH2","C",06,00,00,"G","","SRAZLD","","","MV_PAR02","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"03","FUNCAO DE?  ","","","MV_CH3","C",05,00,00,"G","","SRJ   ","","","MV_PAR03","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"04","FUNCAO ATE? ","","","MV_CH4","C",05,00,00,"G","","SRJ   ","","","MV_PAR04","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"05","AS  DE?     ","","","MV_CH5","C",27,00,00,"G","","DTQA  ","","","MV_PAR05","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"06","AS  ATE?    ","","","MV_CH6","C",27,00,00,"G","","DTQA  ","","","MV_PAR06","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"07","PERIODO DE? ","","","MV_CH7","D",08,00,00,"G","NAOVAZIO()","      ","","","MV_PAR07","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"08","PERIODO ATE?","","","MV_CH8","D",08,00,00,"G","NAOVAZIO()","      ","","","MV_PAR08","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"09","STATUS MO?  ","","","MV_CH9","N",01,00,00,"C","","      ","","","MV_PAR09","DISPONIVEL","","","","ALOCADO","","","AMBOS","","","","","","","","",,,,"")
PUTSX1(CPERG,"10","SIT. FOLHA? ","","","MV_CHA","C",05,00,00,"G","FSITUACAO()","","","","MV_PAR10","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"11","EXPORTA EXCEL?","","","MV_CHB","N",01,0,0,"C","","      ","","","MV_PAR11","SIM","","","","NรO","","" ,"","","","","","","","","")
*/
RETURN
