#INCLUDE "locr005.ch" 
/*/{PROTHEUS.DOC} LOCR005.PRW
ITUP BUSINESS - TOTVS RENTAL
RELATORIO DISPONIBILIDADE DE FROTA - CAIXA DE PROCESSO
@TYPE FUNCTION
@AUTHOR FRANK ZWARG FUGA
@SINCE 03/12/2020
@VERSION P12
@HISTORY 03/12/2020, FRANK ZWARG FUGA, FONTE PRODUTIZADO.
/*/

#INCLUDE "PROTHEUS.CH"

FUNCTION LOCR005()
LOCAL CDESC1         	:= STR0001 //"ESTE PROGRAMA TEM COMO OBJETIVO IMPRIMIR RELATORIO "
LOCAL CDESC2         	:= STR0002 //"DE ACORDO COM OS PARAMETROS INFORMADOS PELO USUARIO."
LOCAL CDESC3         	:= STR0003 //"DISPONIBILIDADE DE FROTA - CAIXA DE PROCESSO"
LOCAL TITULO       		:= STR0003 //"DISPONIBILIDADE DE FROTA - CAIXA DE PROCESSO"
LOCAL NLIN         		:= 80
LOCAL CPERG        		:= "LOCP061"
LOCAL CABEC2       		:= ""
LOCAL AORD 				:= {}       
LOCAL IMPRIME 

PRIVATE CABEC1       	:= ""
PRIVATE LEND         	:= .F.
PRIVATE LABORTPRINT  	:= .F.
PRIVATE LIMITE          := 120
PRIVATE TAMANHO         := "G"
PRIVATE NOMEPROG        := "LOCDISFRV1_3" // COLOQUE AQUI O NOME DO PROGRAMA PARA IMPRESSAO NO CABECALHO
PRIVATE NTIPO           := 18
PRIVATE ARETURN         := { "ZEBRADO", 1, "ADMINISTRACAO", 2, 2, 1, "", 1}
PRIVATE NLASTKEY        := 0
PRIVATE CBTXT      		:= SPACE(10)
PRIVATE CBCONT     		:= 00
PRIVATE CONTFL     		:= 01
PRIVATE M_PAG      		:= 01
PRIVATE WNREL      		:= "LOCDISFRV13" // COLOQUE AQUI O NOME DO ARQUIVO USADO PARA IMPRESSAO EM DISCO
PRIVATE CSTRING 		:= ""

IMPRIME := .T. 
                                                                          
//VALIDPERG(CPERG)
PERGUNTE(CPERG,.T.)

WNREL := SETPRINT(CSTRING,NOMEPROG,CPERG,@TITULO,CDESC1,CDESC2,CDESC3,.T.,AORD,.T.,TAMANHO,,.T.)

IF EMPTY(MV_PAR03) .OR. EMPTY(MV_PAR04) 
	MSGALERT(STR0004, STR0005)  //"PERIODO INICIAL OU FINAL ESTA EM BRANCO... PREENCHER !"###"GPO - LOCDISFR.PRW"
	RETURN
ENDIF

IF NLASTKEY == 27
	RETURN
ENDIF

SETDEFAULT(ARETURN,CSTRING)

IF NLASTKEY == 27
   RETURN
ENDIF

NTIPO := IF(ARETURN[4]==1,15,18)

RPTSTATUS({|| RUNREPORT(CABEC1,CABEC2,TITULO,NLIN) },TITULO)

RETURN                             

/*
‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±⁄ƒƒƒƒƒƒƒƒƒƒ¬ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒø±±
±±≥DESCRIáÖO ≥ PROCESSAMENTO E EXECUCAO DO RELATORIO                        ≥±±
±±√ƒƒƒƒƒƒƒƒƒƒ≈ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒ¥±±
±±≥ USO      ≥ ESPECIFICO GPO                                               ≥±±
±±¿ƒƒƒƒƒƒƒƒƒƒ¡ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒŸ±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ
*/

STATIC FUNCTION RUNREPORT(CABEC1,CABEC2,TITULO,NLIN)
Local carqdias := ""

IF !SX5->(DBSEEK(XFILIAL("SX5")+"ZL"))
	Return .F.
EndIf

CQRYWHER := ""
IF MV_PAR05 <> "1"
	CQRYWHER += " ( (ZLG.FPO_DTINI <= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= "  + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM >= " + DTOS(MV_PAR04) + " ) OR "	
	CQRYWHER += "   (ZLG.FPO_DTINI >= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= "  + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM <= " + DTOS(MV_PAR04) + " ) OR "	
	CQRYWHER += "   (ZLG.FPO_DTINI <= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= "  + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM <= " + DTOS(MV_PAR04) + " ) OR "	
	CQRYWHER += "   (ZLG.FPO_DTINI >= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= "  + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM >= " + DTOS(MV_PAR04) + " ) )  AND "	
ENDIF
CQRYWHER += " ZLG.FPO_NRAS BETWEEN   '"+MV_PAR07+"' AND '"+MV_PAR08+"'" + CRLF
CQRYWHER += " AND ZLG.FPO_OBRA BETWEEN   '"+MV_PAR13+"' AND '"+MV_PAR14+"'" + CRLF
CQRYWHER += " AND ZLG.D_E_L_E_T_ = ''  AND FPO_CODBEM = ''" + CRLF                                                                              

CQRYCLI := " AND ((ZLG.FPO_CODCLI BETWEEN '"+MV_PAR09+"' AND '"+MV_PAR10+"'" + CRLF
CQRYCLI += " AND ZLG.FPO_LOJA BETWEEN   '"+MV_PAR11+"' AND '"+MV_PAR12+"') 
IF EMPTY(MV_PAR05)
	CQRYCLI += " OR (FPO_CODCLI = '' AND FPO_LOJA = '' ) " + CRLF// AND FPO_STATUS IN ('C','9')
ENDIF
CQRYCLI += " )" + CRLF


// MONTA ARQUIVO DE TRABALHO DE APOIO PARA DISPONIBILIDADES
CQRYWHER := ""
IF MV_PAR05 <> "1"
	CQRYWHER += " ( (ZLG.FPO_DTINI <= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= "  + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM >= " + DTOS(MV_PAR04) + " ) OR "	// PERÕODO TOTALMENTE DENTRO DO LAN«AMENTO
	CQRYWHER += "   (ZLG.FPO_DTINI >= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= "  + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM <= " + DTOS(MV_PAR04) + " ) OR "	// PERÕODO TOTALMENTE FORA DO LAN«AMENTO
	CQRYWHER += "   (ZLG.FPO_DTINI <= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= "  + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM <= " + DTOS(MV_PAR04) + " ) OR "	// LAN«AMENTO TERMINA NO PERÕODO
	CQRYWHER += "   (ZLG.FPO_DTINI >= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= "  + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM >= " + DTOS(MV_PAR04) + " ) )  AND "	// LAN«AMENTO INICIA NO PERÕODO
ENDIF
CQRYWHER += " ZLG.FPO_NRAS BETWEEN   '"+MV_PAR07+"' AND '"+MV_PAR08+"'-- ASG DE/ATE" + CRLF
CQRYWHER += " AND ZLG.FPO_OBRA BETWEEN   '"+MV_PAR13+"' AND '"+MV_PAR14+"'--OBRA DE/ATE" + CRLF
CQRYWHER += " AND ZLG.D_E_L_E_T_ = ''  AND FPO_CODBEM = ''" + CRLF                                                                              

CQRYCLI := " AND ((ZLG.FPO_CODCLI BETWEEN '"+MV_PAR09+"' AND '"+MV_PAR10+"'--CLIENTE DE/ATE" + CRLF
CQRYCLI += " AND ZLG.FPO_LOJA BETWEEN   '"+MV_PAR11+"' AND '"+MV_PAR12+"') 
IF EMPTY(MV_PAR05)
	CQRYCLI += " OR (FPO_CODCLI = '' AND FPO_LOJA = '' ) " + CRLF// AND FPO_STATUS IN ('C','9')
ENDIF
CQRYCLI += " )--LOJA DE/ATE" + CRLF
   
CQRYWHT9 := " AND T9_CODBEM  BETWEEN '"+MV_PAR01+"' AND '"+MV_PAR02+"' AND  T9_SITBEM='A' AND T9_TIPOSE IN ('E','L','M','P') -- FROTA DE ATE" + CRLF

CTMPCLI := CRIATRAB(,.F.)
CQRYINT := "SELECT DISTINCT FPO_FROTA, FPO_DTINI, FPO_DTFIM "
CQRYINT += "INTO  " + CTMPCLI + CRLF
CQRYINT += "FROM "+ RETSQLNAME("FPO") + " ZLG " + CRLF
CQRYINT += "JOIN "+ RETSQLNAME("ST9") + " T9 ON T9_CODBEM = FPO_FROTA AND T9.D_E_L_E_T_= '' " + CRLF
CQRYINT += "WHERE "+ CQRYWHER+CQRYCLI+CQRYWHT9 + " AND FPO_STATUS NOT IN ('A','E','S') " //APROVEITA MONTAGEM DE CONDICAO FEITA ANTERIORMENTE
CQRYINT += "AND ZLG.D_E_L_E_T_= '' "
CQRYINT += "ORDER BY 1,2,3   
TCSQLEXEC(CQRYINT)

CQRYINT := "SELECT DISTINCT FPO_FROTA, FPO_DTINI, FPO_DTFIM "
CQRYINT += "FROM "+ RETSQLNAME("FPO") + " ZLG " + CRLF
CQRYINT += "JOIN "+ RETSQLNAME("ST9") + " T9 ON T9_CODBEM = FPO_FROTA AND T9.D_E_L_E_T_= '' " + CRLF
CQRYINT += "WHERE "+ CQRYWHER+CQRYWHT9 + " AND FPO_STATUS NOT IN ('A','E','S','C') " //APROVEITA MONTAGEM DE CONDICAO FEITA ANTERIORMENTE
CQRYINT += "AND ZLG.D_E_L_E_T_= '' "
CQRYINT += "ORDER BY 1,2,3   "

// desativado pelos debitos tecnicos
//CARQDIAS := U_LOCDIASG(CQRYINT,"FPO_FROTA", "FPO_DTINI","FPO_DTFIM",MV_PAR03, MV_PAR04 )           

CQUERY := "SELECT FPO_FROTA, T9_CODFA,SUBSTRING(T9_NOME,1,30) T9_NOME, FPO_LOCAL, FPO_DTINI, FPO_DTFIM, " + CRLF
CQUERY += "       UPPER(SUBSTRING(X5_DESCRI,1,11)) STAT_FR,"+ CRLF
CQUERY += "       RTRIM(SUBSTRING(FPO_NOMCLI,1,30))+'/'+ISNULL(RTRIM(SUBSTRING(FP1_NOMORI,1,30)),'')  CLI_OBRA, " + CRLF
CQUERY += "       ISNULL(RTRIM(SUBSTRING(FP1_MUNORI,1,20))+ '/'+ FP1_ESTORI,'') MUN_OBRA, FPO_STATUS, FPO_FILNF, 'B' ORIGEM, FPO_STATUS, FPO_CODCLI, FPO_LOJA " + CRLF
CQUERY += "FROM "+ RETSQLNAME("FPO") + " ZLG " + CRLF
CQUERY += "JOIN "+ RETSQLNAME("ST9") + " T9 ON T9_CODBEM = ZLG.FPO_FROTA AND T9.D_E_L_E_T_ = ''" + CRLF
CQUERY += "LEFT JOIN "+ RETSQLNAME("SX5") + " STAT ON X5_TABELA = 'ZL' AND FPO_STATUS = X5_CHAVE AND STAT.D_E_L_E_T_ = '' " + CRLF
CQUERY += "LEFT JOIN "+ RETSQLNAME("FP1") + " ZA1 ON FP1_PROJET = FPO_PROJET  AND FP1_OBRA = FPO_OBRA AND ZA1.D_E_L_E_T_ = '' "+CRLF
//CQUERY += "WHERE " + CQRYWHER+CQRYCLI+CQRYWHT9 //APROVEITA MONTAGEM DE CONDICAO FEITA ANTERIORMENTE
CQUERY += "WHERE " + CQRYWHER+CQRYWHT9 //APROVEITA MONTAGEM DE CONDICAO FEITA ANTERIORMENTE
//IF !EMPTY(MV_PAR07)
//	CQUERY += CQRYCLI
//ENDIF

IF !EMPTY(MV_PAR05) .AND. MV_PAR05=="1"
	CRESFIL := ""
	CQRYFIL := "SELECT DISTINCT FPO_FROTA "
	CQRYFIL += "FROM "+RETSQLNAME("FPO") + " ZLG "
	CQRYFIL += "WHERE "
	CQRYFIL += "((ZLG.FPO_DTINI <= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= " + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM >= " + DTOS(MV_PAR04) + ") OR "	// PERÕODO TOTALMENTE DENTRO DO LAN«AMENTO
	CQRYFIL += "(ZLG.FPO_DTINI >= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= "  + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM <= " + DTOS(MV_PAR04) + ") OR "	// PERÕODO TOTALMENTE FORA DO LAN«AMENTO
	CQRYFIL += "(ZLG.FPO_DTINI <= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= "  + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM <= " + DTOS(MV_PAR04) + ") OR "	// LAN«AMENTO TERMINA NO PERÕODO
	CQRYFIL += "(ZLG.FPO_DTINI >= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= "  + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM >= " + DTOS(MV_PAR04) + "))  AND  "	// LAN«AMENTO INICIA NO PERÕODO
	CQRYFIL += "ZLG.FPO_NRAS BETWEEN   '"+MV_PAR07+"' AND '"+MV_PAR08+"' " + CRLF
	CQRYFIL += "AND ZLG.FPO_OBRA BETWEEN   '"+MV_PAR13+"' AND '"+MV_PAR14+"' " + CRLF
	CQRYFIL += "AND ZLG.D_E_L_E_T_ = ''  AND FPO_CODBEM = ''" + CRLF                                                                              
	CQRYFIL += "AND ((ZLG.FPO_CODCLI BETWEEN '"+MV_PAR09+"' AND '"+MV_PAR10+"' "+ CRLF
	CQRYFIL += "AND ZLG.FPO_LOJA BETWEEN   '"+MV_PAR11+"' AND '"+MV_PAR12+"') )
	DBUSEAREA(.T., "TOPCONN", TCGENQRY(,,CQRYFIL), "TRBFIL", .F., .T.)
	IF !TRBFIL->(EOF())
		CRESFIL += "("
		WHILE !TRBFIL->(EOF())
			CRESFIL += "'"+ALLTRIM(TRBFIL->FPO_FROTA)+"',"
			TRBFIL->(DBSKIP())
		ENDDO
	ENDIF
	TRBFIL->(DBCLOSEAREA())
	CRESFIL := SUBSTR(CRESFIL,1,LEN(CRESFIL)-1)+")" 

	IF !EMPTY(CRESFIL)
		CQUERY += "	UNION " + CRLF
		CQUERY += "	SELECT FPO_FROTA, T9_CODFA,SUBSTRING(T9_NOME,1,30) T9_NOME, FPO_LOCAL, FPO_DTINI, FPO_DTFIM, " + CRLF
		CQUERY += "	       UPPER(SUBSTRING(X5_DESCRI,1,11)) STAT_FR," + CRLF
		CQUERY += "	       RTRIM(SUBSTRING(FPO_NOMCLI,1,30))+'/'+ISNULL(RTRIM(SUBSTRING(FP1_NOMORI,1,30)),'')  CLI_OBRA, " + CRLF
		CQUERY += "	       ISNULL(RTRIM(SUBSTRING(FP1_MUNORI,1,20))+ '/'+ FP1_ESTORI,'') MUN_OBRA, FPO_STATUS, FPO_FILNF, 'B' ORIGEM, FPO_STATUS, FPO_CODCLI, FPO_LOJA " + CRLF
		CQUERY += "	FROM " + RETSQLNAME("FPO")+ " ZLG " + CRLF
		CQUERY += "	JOIN " + RETSQLNAME("ST9")+ " T9 ON T9_CODBEM = ZLG.FPO_FROTA AND T9.D_E_L_E_T_ = '' " + CRLF
		CQUERY += "	LEFT JOIN " + RETSQLNAME("SX5")+ " STAT ON X5_TABELA = 'ZL' AND FPO_STATUS = X5_CHAVE AND STAT.D_E_L_E_T_ = '' " + CRLF
		CQUERY += "	LEFT JOIN " + RETSQLNAME("FP1")+ " ZA1 ON FP1_PROJET = FPO_PROJET  AND FP1_OBRA = FPO_OBRA AND ZA1.D_E_L_E_T_ = '' 	" + CRLF
		CQUERY += "	WHERE " + CRLF
		CQUERY += " ZLG.D_E_L_E_T_ = '' " + CRLF
		CQUERY += " AND T9_CODBEM  BETWEEN '"+MV_PAR01+"' AND '"+MV_PAR02+"' AND  T9_SITBEM='A' AND T9_TIPOSE IN ('G','U','M','P') -- FROTA DE ATE" + CRLF
		CQUERY += " AND FPO_STATUS BETWEEN '"+MV_PAR05+"' AND '"+MV_PAR06+"' AND FPO_FROTA IN " + CRESFIL + " " + CRLF
	ENDIF
	
ENDIF

// --> TRECHO IMPLEMENTADO PARA TRAZER AS CORRETIVAS
IF !EMPTY(MV_PAR07)
	CRESFIL := ""
	CQRYFIL := "SELECT DISTINCT FPO_FROTA" + CRLF
	CQRYFIL += "FROM "+ RETSQLNAME("FPO") + " ZLG " + CRLF
	CQRYFIL += "JOIN "+ RETSQLNAME("ST9") + " T9 ON T9_CODBEM = ZLG.FPO_FROTA AND T9.D_E_L_E_T_ = '' " + CRLF
	CQRYFIL += "LEFT JOIN "+ RETSQLNAME("SX5") + " STAT ON X5_TABELA = 'ZL' AND FPO_STATUS = X5_CHAVE AND STAT.D_E_L_E_T_ = '' " + CRLF
	CQRYFIL += "LEFT JOIN "+ RETSQLNAME("FP1") + " ZA1 ON FP1_PROJET = FPO_PROJET  AND FP1_OBRA = FPO_OBRA AND ZA1.D_E_L_E_T_ = '' " + CRLF
	CQRYFIL += "WHERE "
	IF MV_PAR05 <> "1"	
		CQRYFIL += "((ZLG.FPO_DTINI <= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= "  + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM >= " + DTOS(MV_PAR04) + ") OR "	// PERÕODO TOTALMENTE DENTRO DO LAN«AMENTO
		CQRYFIL += "(ZLG.FPO_DTINI >= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= "  + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM <= " + DTOS(MV_PAR04) + ") OR "	// PERÕODO TOTALMENTE FORA DO LAN«AMENTO
		CQRYFIL += "(ZLG.FPO_DTINI <= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= "  + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM <= " + DTOS(MV_PAR04) + ") OR "	// LAN«AMENTO TERMINA NO PERÕODO
		CQRYFIL += "(ZLG.FPO_DTINI >= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= "  + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM >= " + DTOS(MV_PAR04) + "))  AND "	// LAN«AMENTO INICIA NO PERÕODO
	ENDIF
	CQRYFIL += " ZLG.FPO_NRAS BETWEEN   '"+MV_PAR07+"' AND '"+MV_PAR08+"'-- ASG DE/ATE" + CRLF
	CQRYFIL += "AND ZLG.FPO_OBRA BETWEEN   '"+MV_PAR13+"' AND '"+MV_PAR14+"'--OBRA DE/ATE" + CRLF	
	CQRYFIL += "ZLG.FPO_NRAS BETWEEN   '"+MV_PAR07+"' AND '"+MV_PAR08+"' " + CRLF
	CQRYFIL += "AND ((ZLG.FPO_CODCLI BETWEEN '"+MV_PAR09+"' AND '"+MV_PAR10+"' --CLIENTE DE/ATE" + CRLF
	CQRYFIL += "AND ZLG.FPO_LOJA BETWEEN   '"+MV_PAR11+"' AND '"+MV_PAR12+"') OR (FPO_CODCLI = '' AND FPO_LOJA = '' AND FPO_STATUS IN ('C','9')) )--LOJA DE/ATE" + CRLF	   
	CQRYFIL := CHANGEQUERY(CQRYFIL)
	DBUSEAREA(.T., "TOPCONN", TCGENQRY(,,CQRYFIL), "TRBFIL", .F., .T.)
	IF !TRBFIL->(EOF())
		CRESFIL += "("
		WHILE !TRBFIL->(EOF())
			CRESFIL += "'"+ALLTRIM(TRBFIL->FPO_FROTA)+"',"
			TRBFIL->(DBSKIP())
		ENDDO
	ENDIF
	TRBFIL->(DBCLOSEAREA())
	CQUERY += "UNION ALL" + CRLF
	CQUERY += "SELECT FPO_FROTA, T9_CODFA,SUBSTRING(T9_NOME,1,30) T9_NOME, FPO_LOCAL, FPO_DTINI, FPO_DTFIM, " + CRLF
	CQUERY += "       UPPER(SUBSTRING(X5_DESCRI,1,11)) STAT_FR,"+ CRLF
	CQUERY += "       RTRIM(SUBSTRING(FPO_NOMCLI,1,30))+'/'+ISNULL(RTRIM(SUBSTRING(FP1_NOMORI,1,30)),'')  CLI_OBRA, " + CRLF
	CQUERY += "       ISNULL(RTRIM(SUBSTRING(FP1_MUNORI,1,20))+ '/'+ FP1_ESTORI,'') MUN_OBRA, FPO_STATUS, FPO_FILNF, 'B' ORIGEM, FPO_STATUS, FPO_CODCLI, FPO_LOJA " + CRLF
	CQUERY += "FROM "+ RETSQLNAME("FPO") + " ZLG " + CRLF
	CQUERY += "JOIN "+ RETSQLNAME("ST9") + " T9 ON T9_CODBEM = ZLG.FPO_FROTA AND T9.D_E_L_E_T_ = ''" + CRLF                  
	CQUERY += "LEFT JOIN "+ RETSQLNAME("SX5") + " STAT ON X5_TABELA = 'ZL' AND FPO_STATUS = X5_CHAVE AND STAT.D_E_L_E_T_ = '' " + CRLF
	CQUERY += "LEFT JOIN "+ RETSQLNAME("FP1") + " ZA1 ON FP1_PROJET = FPO_PROJET  AND FP1_OBRA = FPO_OBRA AND ZA1.D_E_L_E_T_ = '' "+CRLF
	CQUERY += "WHERE "
	IF MV_PAR05 <> "1"	
		CQUERY += "((ZLG.FPO_DTINI <= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= "  + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM >= " + DTOS(MV_PAR04) + ") OR "	// PERÕODO TOTALMENTE DENTRO DO LAN«AMENTO
		CQUERY += "(ZLG.FPO_DTINI >= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= "  + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM <= " + DTOS(MV_PAR04) + ") OR "	// PERÕODO TOTALMENTE FORA DO LAN«AMENTO
		CQUERY += "(ZLG.FPO_DTINI <= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= "  + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM <= " + DTOS(MV_PAR04) + ") OR "	// LAN«AMENTO TERMINA NO PERÕODO
		CQUERY += "(ZLG.FPO_DTINI >= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= "  + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM >= " + DTOS(MV_PAR04) + "))  "	// LAN«AMENTO INICIA NO PERÕODO
	ENDIF
//	CQUERY += " AND  ZLG.FPO_STATUS = 'C' "
	CQUERY += " AND FPO_NRAS = '' "
	CQUERY += " AND ZLG.FPO_OBRA BETWEEN   '"+MV_PAR13+"' AND '"+MV_PAR14+"'--OBRA DE/ATE" + CRLF
	CQUERY += " AND ZLG.D_E_L_E_T_ = '' " + CRLF                                                                              
	CQUERY += " AND ((ZLG.FPO_CODCLI BETWEEN '"+MV_PAR09+"' AND '"+MV_PAR10+"' --CLIENTE DE/ATE" + CRLF
	CQUERY += " AND ZLG.FPO_LOJA BETWEEN   '"+MV_PAR11+"' AND '"+MV_PAR12+"') OR (FPO_CODCLI = '' AND FPO_LOJA = '' AND FPO_STATUS IN ('C','9')) )--LOJA DE/ATE" + CRLF	   
	CQUERY += " AND  T9_SITBEM='A' AND T9_TIPOSE IN ('G','U','M','P') " + CRLF
	IF !EMPTY(CRESFIL)
		CRESFIL := SUBSTR(CRESFIL,1,LEN(CRESFIL)-1)+")" 	
	   	CQUERY += "AND T9_CODBEM  IN " + CRESFIL + " " + CRLF
	ENDIF
ENDIF


IF MV_PAR05 <= '1' .AND. MV_PAR06 >= '1' 
	//-->> CONSIDERA DISPONIVEL EM TODO O PERIODO TODOS OS BENS QUE NAO FOREM ENCONTRADOS NO ZLG       
	//-->> SO VAI EXISTIR ESSE UNION CASO OS PARAMETROS   DO ZLG FOREM <BRANCO> A <ZZZZ> 
	IF EMPTY(MV_PAR05+MV_PAR07+MV_PAR09+MV_PAR11+MV_PAR13)
		CQUERY += "UNION ALL" + CRLF
		CQUERY += "SELECT T9_CODBEM, T9_CODFA,SUBSTRING(T9_NOME,1,30) T9_NOME,'', '"+DTOS(MV_PAR03)+"', '"+DTOS(MV_PAR04)+"','DISPONIVEL','', '','1','', 'GN' ORRAS, FPO_STATUS, FPO_CODCLI, FPO_LOJA " + CRLF
		CQUERY += "FROM "+ RETSQLNAME("ST9") + " T9 " + CRLF
		CQUERY += "LEFT JOIN "+ RETSQLNAME("FPO") + " ZLG ON T9_CODBEM = ZLG.FPO_FROTA AND ZLG.D_E_L_E_T_ = '' AND " + CRLF      
   		CQUERY += CQRYWHER+CQRYCLI + CRLF 
		CQUERY += "LEFT JOIN "+CARQDIAS + " DIAS ON DIAS.FPO_FROTA = T9_CODBEM " + CRLF
		CQUERY += "WHERE FPO_OBRA IS NULL  AND DIAS.FPO_FROTA IS NULL AND T9.D_E_L_E_T_ = ''" + CRLF
    	CQUERY +=  CQRYWHT9
	ENDIF 
ENDIF

IF !EMPTY(MV_PAR09) .AND. !EMPTY(MV_PAR11) 
	CQUERY += "UNION ALL " + CRLF
	CQUERY += "SELECT FPO_FROTA, T9_CODFA,SUBSTRING(T9_NOME,1,30) T9_NOME, FPO_LOCAL, FPO_DTINI, FPO_DTFIM, " + CRLF
	CQUERY += "       UPPER(SUBSTRING(X5_DESCRI,1,11)) STAT_FR,"+ CRLF
	CQUERY += "       RTRIM(SUBSTRING(FPO_NOMCLI,1,30))+'/'+ISNULL(RTRIM(SUBSTRING(FP1_NOMORI,1,30)),'')  CLI_OBRA, " + CRLF
	CQUERY += "       ISNULL(RTRIM(SUBSTRING(FP1_MUNORI,1,20))+ '/'+ FP1_ESTORI,'') MUN_OBRA, FPO_STATUS, FPO_FILNF, 'B' ORIGEM, FPO_STATUS, FPO_CODCLI, FPO_LOJA " + CRLF
	CQUERY += "FROM "+ RETSQLNAME("FPO") + " ZLG " + CRLF
	CQUERY += "JOIN "+ RETSQLNAME("ST9") + " T9 ON T9_CODBEM = ZLG.FPO_FROTA AND T9.D_E_L_E_T_ = ''" + CRLF
	CQUERY += "LEFT JOIN "+ RETSQLNAME("SX5") + " STAT ON X5_TABELA = 'ZL' AND FPO_STATUS = X5_CHAVE AND STAT.D_E_L_E_T_ = '' " + CRLF
	CQUERY += "LEFT JOIN "+ RETSQLNAME("FP1") + " ZA1 ON FP1_PROJET = FPO_PROJET  AND FP1_OBRA = FPO_OBRA AND ZA1.D_E_L_E_T_ = '' "+CRLF
	CQUERY += "WHERE  ((ZLG.FPO_DTINI <= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= "  + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM >= " + DTOS(MV_PAR04) + ") OR "	// PERÕODO TOTALMENTE DENTRO DO LAN«AMENTO
	CQUERY += " (ZLG.FPO_DTINI >= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= "  + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM <= " + DTOS(MV_PAR04) + ") OR "	// PERÕODO TOTALMENTE FORA DO LAN«AMENTO
	CQUERY += " (ZLG.FPO_DTINI <= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= "  + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM <= " + DTOS(MV_PAR04) + ") OR "	// LAN«AMENTO TERMINA NO PERÕODO
	CQUERY += " (ZLG.FPO_DTINI >= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= "  + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM >= " + DTOS(MV_PAR04) + ")) "	// LAN«AMENTO INICIA NO PERÕODO
	CQUERY += "AND ZLG.FPO_NRAS BETWEEN   '"+MV_PAR07+"' AND '"+MV_PAR08+"'-- ASG DE/ATE" + CRLF	
	CQUERY += "AND ZLG.FPO_OBRA BETWEEN   '"+MV_PAR13+"' AND '"+MV_PAR14+"'--OBRA DE/ATE" + CRLF
	CQUERY += "AND ZLG.D_E_L_E_T_ = ''  AND FPO_CODBEM = '' " + CRLF                                                                              
	CQUERY += "AND ((ZLG.FPO_CODCLI BETWEEN '"+MV_PAR09+"' AND '"+MV_PAR10+"' --CLIENTE DE/ATE" + CRLF
	CQUERY += "AND ZLG.FPO_LOJA <> '"+MV_PAR11+"' AND FPO_CODCLI <> '' )) "
	CQUERY += "AND T9_CODBEM  BETWEEN '"+MV_PAR01+"' AND '"+MV_PAR02+"' AND  T9_SITBEM='A' AND T9_TIPOSE IN ('G','U','M','P') -- FROTA DE ATE" + CRLF	
ENDIF

CQUERY += "ORDER BY 1, 5,6 " + CRLF 

//MEMOWRITE("C:\TEMP\LOCDISFR.SQL", CQUERY) //GRAVA RESULTADO DA QUERY NO TEMP DO USUARIO PARA FACILITAR O SUPORTE

IF SELECT("TRBFR") > 0
   TRBFR->(DBCLOSEAREA())
ENDIF 

DBUSEAREA(.T., "TOPCONN", TCGENQRY(,,CQUERY), "TRBFR", .F., .T.)
TCSETFIELD("TRBFR","FPO_DTINI","D",8,0)
TCSETFIELD("TRBFR","FPO_DTFIM","D",8,0)

// --> MONTA CABECALHO COM TAMANHO DINAMICO PELO RESULTADO DA QUERY 
CABEC1 := PADR("FROTA"       , LEN(TRBFR->FPO_FROTA)+1)
//CABEC1 += PADR("FANTASIA"  , LEN(TRBFR->T9_CODFA)+1)
CABEC1 += PADR("DESCRICAO"   , LEN(TRBFR->T9_NOME)+1)
CABEC1 += PADR("STATUS"      , LEN(TRBFR->STAT_FR)+1)
CABEC1 += PADR("LOCALIDADE"  , LEN(TRBFR->FPO_LOCAL)+1)
CABEC1 += PADR("CLIENTE/OBRA", LEN(TRBFR->CLI_OBRA)+1)
CABEC1 += PADR("MUNICIPIO/UF", LEN(TRBFR->MUN_OBRA)+1)
CABEC1 += PADR("DT INICIO"   , LEN(DTOC(TRBFR->FPO_DTINI))+2)
CABEC1 += PADR("DT FIM"      , LEN(DTOC(TRBFR->FPO_DTFIM)))
  
// --> SETREGUA -> INDICA QUANTOS REGISTROS SERAO PROCESSADOS PARA A REGUA
SETREGUA(RECCOUNT())
CLOFRO  := ""
CLODTI  := ""
CLODTF  := ""     
CLO_MUN := ""          
CLO_CLI := ""            
CLOSTAT := ""
LSALTA  := .F.
NXXX    := ""
LCONTR  := .T.
LOK     := .T.

IF MV_PAR15 == 1							// SE FOR EXPORTAR PARA O EXCEL - CRISTIANE CAMPOS EM 11/11/2011
	// desativado por questoes dos debitos tecnicos - frank 06/04/2022
	/*
	CARQUIVO  := CRIATRAB(,.F.)+".HTM"		// ARQUIVO PADR√O HTML NA PASTA SERVER\SYSTEM
	NARQ      := FCREATE(CARQUIVO,0)		// ABERTURA DO ARQUIVO BIN¡RIO

	CHTML := "<HTML><HEAD><TITLE>DISPONIBILIDADE DE FROTAS</TITLE></HEAD>" + CRLF
	CHTML += "<BODY><TABLE BORDER='1'><TR>"
	CHTML += "<TD COLSPAN='09'><CENTER><H2>DISPONIBILIDADE DE FROTAS</H2></CENTER>"
	CHTML += "PAR¬METROS: FROTA" + IF( EMPTY(MV_PAR01), "", " DE :"+MV_PAR01) + " AT…: " + MV_PAR02
	CHTML += " - PERIODO" + IF( EMPTY(MV_PAR03), "", " DE :"+DTOC(MV_PAR03))+ " AT…: " + DTOC(MV_PAR04)
	CHTML += " - STATUS: " + IF( EMPTY(MV_PAR05), "", " DE :"+MV_PAR05) + " AT…: " + MV_PAR06
	CHTML += " - ASG:" + IF( EMPTY(MV_PAR07), "", " DE :"+(MV_PAR07)) + " AT…: " + (MV_PAR08)
	CHTML += " - CLIENTE:" + IF( EMPTY(MV_PAR09), "", " DE :"+(MV_PAR09)) + " AT…: " + (MV_PAR10)
	CHTML += " - LOJA:" + IF( EMPTY(MV_PAR11), "", " DE :"+(MV_PAR11)) + " AT…: " + (MV_PAR12)
	CHTML += " - OBRA:" + IF( EMPTY(MV_PAR13), "", " DE :"+(MV_PAR13)) + " AT…: " + (MV_PAR14)
	CHTML += "</TD></TR><TR>"
	CHTML += "<TH>FROTA</TH>"
 //	CHTML += "<TH>FANTASIA</TH>"
	CHTML += "<TH>DESCRICAO</TH>"
	CHTML += "<TH>STATUS</TH>"
	CHTML += "<TH>LOCALIDADE</TH>" // 2011-11-17 - TOTVS GRU - DENIS - CORRECAO DA DESCRICAO NA EXPORTACAO
	CHTML += "<TH>CLIENTE/OBRA</TH>"
	CHTML += "<TH>MUNICIPIO/UF</TH>" // 2011-11-17 - TOTVS GRU - DENIS - CORRECAO DO POSICIONAMENTO DOS TITULOS DT INICIO E DT FIM
	CHTML += "<TH>DT INICIO</TH>"
	CHTML += "<TH>DT FIM</TH>"
	CHTML += "</TR>" + CRLF
	FWRITE(NARQ,CHTML,LEN(CHTML))
	*/
ENDIF

IF TRBFR->(!EOF())
	EXISTF := .T.
ENDIF

IF !EXISTF
	TRBFR->(DBCLOSEAREA())
	//-->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
	//-->> CASO NAO TENHA NENHUMA INFORMA«√O NO ARRAY, CRIARA UM REGISTRO DE DISPONIBILIDADE 
	//-->> DE FROTA CONSIDERANDO O PERIODO DE DATA DO PARAMETRO
	//-->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
	CQRY := " SELECT T9_CODBEM FPO_FROTA, T9_CODFA,SUBSTRING(T9_NOME,1,30) T9_NOME, FPO_LOCAL, '"+DTOS(MV_PAR03)+"' FPO_DTINI, '"+DTOS(MV_PAR04)+"' FPO_DTFIM, " + CRLF
	CQRY += "        UPPER(SUBSTRING(X5_DESCRI,1,11)) STAT_FR, " + CRLF
	CQRY += "        RTRIM(SUBSTRING(FPO_NOMCLI,1,30))+'/'+ISNULL(RTRIM(SUBSTRING(FP1_NOMORI,1,30)),'')  CLI_OBRA, " + CRLF
	CQRY += "	     ISNULL(RTRIM(SUBSTRING(FP1_MUNORI,1,20))+ '/'+ FP1_ESTORI,'') MUN_OBRA, FPO_STATUS, FPO_FILNF, 'B' ORIGEM, '1', FPO_CODCLI, FPO_LOJA " + CRLF
	CQRY += " FROM " + RETSQLNAME("ST9") + "  T9 " + CRLF
	CQRY += "        LEFT JOIN " + RETSQLNAME("FPO") + " ZLG ON T9_CODBEM = ZLG.FPO_FROTA AND T9.D_E_L_E_T_ = '' " + CRLF
	CQRY += "        LEFT JOIN " + RETSQLNAME("SX5") + " STAT ON X5_TABELA = 'ZL' AND FPO_STATUS = X5_CHAVE AND STAT.D_E_L_E_T_ = '' " + CRLF
	CQRY += "        LEFT JOIN " + RETSQLNAME("FP1") + " ZA1 ON FP1_PROJET = FPO_PROJET  AND FP1_OBRA = FPO_OBRA AND ZA1.D_E_L_E_T_ = '' " + CRLF
	CQRY += " WHERE  T9.D_E_L_E_T_ = '' " + CRLF
	CQRY += "   AND  T9_CODBEM BETWEEN '"+MV_PAR01+"' AND '"+MV_PAR02+"' AND T9_SITBEM='A' " + CRLF
	CQRY += "   AND  FPO_CODBEM = '' " + CRLF
	CQRY += " ORDER BY T9_CODBEM" + CRLF
	DBUSEAREA(.T., "TOPCONN", TCGENQRY(,,CHANGEQUERY(CQRY)), "TRBFR", .F., .T.)

	TCSETFIELD("TRBFR","FPO_DTINI","D",8,0)
	TCSETFIELD("TRBFR","FPO_DTFIM","D",8,0)
ENDIF

IF TRBFR->(!EOF())
	EXISTF := .T.
	DDTFIM := TRBFR->FPO_DTFIM
	CFANT  := TRBFR->T9_CODFA
	CNOME  := TRBFR->T9_NOME
	NCONT  := 0
ENDIF

WHILE TRBFR->(!EOF())
	
    // --> VERIFICA O CANCELAMENTO PELO USUARIO...
    IF LABORTPRINT
		@NLIN,00 PSAY "*** CANCELADO PELO OPERADOR ***"
		EXIT
	ENDIF

   // --> IMPRESSAO DO CABECALHO DO RELATORIO... 
   IF NLIN > 55 // SALTO DE P¡GINA. NESTE CASO O FORMULARIO TEM 55 LINHAS...
      CABEC(TITULO,CABEC1,CABEC2,NOMEPROG,TAMANHO,NTIPO)
      NLIN := 8
   ENDIF     

    IF TRBFR->FPO_STATUS >= MV_PAR05 .AND. TRBFR->FPO_STATUS<= MV_PAR06      

	  IF !(CLOFRO == TRBFR->FPO_FROTA.AND. TRBFR->FPO_DTINI < CLODTF .AND.TRBFR->ORIGEM <> 'B')
      		
      		IF !EMPTY(TRBFR->FPO_CODCLI)
				IF	(TRBFR->FPO_CODCLI < MV_PAR09 .OR. TRBFR->FPO_CODCLI > MV_PAR10)
					TRBFR->(DBSKIP())
					LOOP
				ENDIF
			ENDIF

			IF TRBFR->FPO_DTINI>MV_PAR04 .OR. TRBFR->FPO_DTFIM < MV_PAR03
				TRBFR->(DBSKIP())
				LOOP				   					
			ENDIF

			IF !EMPTY(MV_PAR05)
				CQRYLOC := "SELECT * FROM "+RETSQLNAME("FPO")+ " ZLG "
				CQRYLOC +=  "WHERE FPO_FROTA = '"+TRBFR->FPO_FROTA+"' "
				CQRYLOC +=  "AND FPO_STATUS BETWEEN '"+MV_PAR05+"' AND '"+MV_PAR06+"' "
				CQRYLOC +=  "AND D_E_L_E_T_ = '' AND FPO_CODBEM = '' "
				CQRYLOC += "AND ((ZLG.FPO_DTINI <= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= "  + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM >= " + DTOS(MV_PAR04) + ") OR "	// PERÕODO TOTALMENTE DENTRO DO LAN«AMENTO
				CQRYLOC += "    (ZLG.FPO_DTINI >= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= "  + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM <= " + DTOS(MV_PAR04) + ") OR "	// PERÕODO TOTALMENTE FORA DO LAN«AMENTO
				CQRYLOC += "    (ZLG.FPO_DTINI <= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= "  + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM <= " + DTOS(MV_PAR04) + ") OR "	// LAN«AMENTO TERMINA NO PERÕODO
				CQRYLOC += "    (ZLG.FPO_DTINI >= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= "  + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM >= " + DTOS(MV_PAR04) + ")) "	// LAN«AMENTO INICIA NO PERÕODO							
				DBUSEAREA(.T., "TOPCONN", TCGENQRY(,,CQRYLOC), "TRBLOC", .F., .T.)
				TCSETFIELD("TRBLOC","FPO_DTINI","D",8,0)
				TCSETFIELD("TRBLOC","FPO_DTFIM","D",8,0)							
				IF !TRBLOC->(EOF())
					IF TRBLOC->FPO_DTINI>MV_PAR04 .OR. TRBLOC->FPO_DTFIM < MV_PAR03
						TRBFR->(DBSKIP())
						TRBLOC->(DBCLOSEAREA())
						LOOP				   					
					ENDIF
				ENDIF
				TRBLOC->(DBCLOSEAREA())				
			ENDIF
			
			IF !EMPTY(MV_PAR09)
				IF EMPTY(TRBFR->FPO_CODCLI) .AND. TRBFR->FPO_STATUS == "1"
					TRBFR->(DBSKIP())
					LOOP
				ENDIF
			ENDIF
			
			IF EMPTY(TRBFR->FPO_CODCLI) .AND. TRBFR->FPO_STATUS <> "1" 
				CQRYLOC := "SELECT * FROM "+RETSQLNAME("FPO")+ " "
				CQRYLOC +=  "WHERE FPO_FROTA = '"+TRBFR->FPO_FROTA+"' "
				CQRYLOC +=  "AND FPO_CODCLI BETWEEN '"+MV_PAR09+"' AND '"+MV_PAR10+"' "
				CQRYLOC +=  "AND FPO_LOJA BETWEEN '"+MV_PAR11+"' AND '"+MV_PAR12+"' AND D_E_L_E_T_ = ''"
				DBUSEAREA(.T., "TOPCONN", TCGENQRY(,,CQRYLOC), "TRBLOC", .F., .T.)
				IF TRBLOC->(EOF())
					TRBFR->(DBSKIP())
					TRBLOC->(DBCLOSEAREA())
					LOOP				   					
				ENDIF
				TRBLOC->(DBCLOSEAREA())
			ENDIF

			IF TRBFR->FPO_DTINI > MV_PAR04
				TRBFR->(DBSKIP())
				LOOP				
			ENDIF
			
			IF !EMPTY(MV_PAR09) .AND. EMPTY(MV_PAR05) .AND. TRBFR->FPO_STATUS <> "1"
				IF SELECT("TRBCLI") > 0
				   TRBCLI->(DBCLOSEAREA())
				ENDIF
				CQRYCLI := " SELECT * FROM "+RETSQLNAME("FPO")+ " ZLG "
				CQRYCLI += "  WHERE FPO_CODCLI BETWEEN '"+MV_PAR09+"' AND '"+MV_PAR09+"' " 				
				IF !EMPTY(MV_PAR11) 
					CQRYCLI += "    AND FPO_LOJA = '"+MV_PAR11+"' "
				ELSE
					CQRYCLI += "    AND FPO_LOJA = '"+TRBFR->FPO_LOJA+"' "
				ENDIF
				CQRYCLI += "    AND FPO_FROTA = '"+TRBFR->FPO_FROTA+"' AND D_E_L_E_T_ = '' AND "				
				CQRYCLI += " ((ZLG.FPO_DTINI <= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= "  + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM >= " + DTOS(MV_PAR04) + ") OR "
				CQRYCLI += "  (ZLG.FPO_DTINI >= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= "  + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM <= " + DTOS(MV_PAR04) + ") OR "
				CQRYCLI += "  (ZLG.FPO_DTINI <= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= "  + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM <= " + DTOS(MV_PAR04) + ") OR "
				CQRYCLI += "  (ZLG.FPO_DTINI >= "  + DTOS(MV_PAR03) + " AND ZLG.FPO_DTINI <= " + DTOS(MV_PAR04)  + " AND ZLG.FPO_DTFIM >= "  + DTOS(MV_PAR03) + "  AND ZLG.FPO_DTFIM >= " + DTOS(MV_PAR04) + ")) "						
				DBUSEAREA(.T., "TOPCONN", TCGENQRY(,,CQRYCLI), "TRBCLI", .F., .T.)
				IF TRBCLI->(EOF())
					IF CLOFRO <> TRBFR->FPO_FROTA
						IF DDTFIM < TRBFR->FPO_DTFIM
							DDTFIM := TRBFR->FPO_DTFIM+1
						ENDIF
						TRBFR->(DBSKIP())
						LOOP						
					ENDIF
					LCONTR := .T.
				ENDIF
				
				TRBCLI->(DBCLOSEAREA())
			ENDIF
            /*
			IF !EMPTY(CLOFRO)
				IF CLOFRO == TRBFR->FPO_FROTA .AND. EMPTY(MV_PAR05)
					IF TRBFR->FPO_DTINI-CLODTF>1
			     		@ NLIN, 000     	 PSAY CLOFROX
					    @ NLIN, PCOL()+1	 PSAY CFANTX
					    @ NLIN, PCOL()+1	 PSAY CNOMEX
					    @ NLIN, PCOL()+1	 PSAY "DISPONIVEL"
					    @ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->FPO_LOCAL))
					    @ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->CLI_OBRA))
					    @ NLIN, PCOL()+2	 PSAY SPACE(LEN(TRBFR->MUN_OBRA))
					    @ NLIN, PCOL()+1	 PSAY CLODTF+1
					    @ NLIN, PCOL()+1	 PSAY TRBFR->FPO_DTINI-1
					    NLIN++
					 // NLIN++
						IF MV_PAR15 == 1
							CHTML := '<TR>'
							CHTML += '<TD>&NBSP;' + CLOFROX + '</TD>'
							CHTML += '<TD>'       + CFANTX + '</TD>'
							CHTML += '<TD>&NBSP;' + CNOMEX + '</TD>'
							CHTML += '<TD>'       + "DISPONIVEL" + '</TD>'
							CHTML += '<TD>'       + "&NBSP;" + '</TD>'
							CHTML += '<TD>'       + "&NBSP;" + '</TD>'
							CHTML += '<TD>'       + "&NBSP;" + '</TD>'
							CHTML += '<TD>'       + DTOC(CLODTF+1) + '</TD>'
							CHTML += '<TD>'       + DTOC(TRBFR->FPO_DTINI-1) + '</TD>'+ CRLF
								CHTML += '<TD>STR0007</TD>' //'       + "DISPONIVEL" + '
						ENDIF	
					ENDIF
				ENDIF
			ENDIF
			*/
			IF !EMPTY(CLODTI)
				IF !EMPTY(CLOFRO) .AND. EMPTY(MV_PAR05)
					IF CLOFRO <> TRBFR->FPO_FROTA .AND. CLODTF < MV_PAR04
						IF CLODTF < MV_PAR04
				     		@ NLIN, 000     	 PSAY CLOFROX
						    @ NLIN, PCOL()+1	 PSAY CFANTX
						    @ NLIN, PCOL()+1	 PSAY CNOMEX
						    @ NLIN, PCOL()+1	 PSAY "DISPONIVEL"
						    @ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->FPO_LOCAL))
						    @ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->CLI_OBRA))
						    @ NLIN, PCOL()+2	 PSAY SPACE(LEN(TRBFR->MUN_OBRA))
						    @ NLIN, PCOL()+1	 PSAY CLODTF+1
						    @ NLIN, PCOL()+1	 PSAY MV_PAR04
						    NLIN++
							IF MV_PAR15 == 1
								/*
								CHTML := '<TR>'
								CHTML += '<TD>&NBSP;' + CLOFROX + '</TD>'
								CHTML += '<TD>'       + CFANTX + '</TD>'
								CHTML += '<TD>&NBSP;' + CNOMEX + '</TD>'
								CHTML += '<TD>'       + "DISPONIVEL" + '</TD>'
								CHTML += '<TD>'       + "&NBSP;" + '</TD>'
								CHTML += '<TD>'       + "&NBSP;" + '</TD>'
								CHTML += '<TD>'       + "&NBSP;" + '</TD>'
								CHTML += '<TD>'       + DTOC(CLODTF+1) + '</TD>'
								CHTML += '<TD>'       + DTOC(MV_PAR04) + '</TD>'+ CRLF
								CHTML += '<TD>STR0008</TD>' //'       + "DISPONIVEL" + '
								*/
							ENDIF
						ENDIF							
					ENDIF
				ENDIF
			ENDIF
			
			//-->> ADICIONADO 14/03/2012
			//IF TRBFR->FPO_DTINI-DDTFIM>1 .AND. !EMPTY(MV_PAR05) .
			IF TRBFR->FPO_DTINI-DDTFIM>1 .AND. (!EMPTY(MV_PAR05) .OR. FPO_STATUS == '1') .AND. LOK
	     		@ NLIN, 000     	 PSAY TRBFR->FPO_FROTA                                        
			    @ NLIN, PCOL()+1	 PSAY TRBFR->T9_CODFA    
			    @ NLIN, PCOL()+1	 PSAY TRBFR->T9_NOME                     
			    @ NLIN, PCOL()+1	 PSAY "DISPONIVEL"
			    @ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->FPO_LOCAL))
			    @ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->CLI_OBRA))
			    @ NLIN, PCOL()+2	 PSAY SPACE(LEN(TRBFR->MUN_OBRA))
			    @ NLIN, PCOL()+1	 PSAY DDTFIM+1
			    @ NLIN, PCOL()+1	 PSAY TRBFR->FPO_DTINI-1
			    NLIN++
				IF MV_PAR15 == 1		// SE FOR EXPORTAR PARA O EXCEL
					/*
					CHTML := '<TR>'
					CHTML += '<TD>&NBSP;' + TRBFR->FPO_FROTA + '</TD>'
					CHTML += '<TD>'       + TRBFR->T9_CODFA  + '</TD>'
					CHTML += '<TD>&NBSP;' + TRBFR->T9_NOME + '</TD>'
					CHTML += '<TD>'       + "DISPONIVEL" + '</TD>'
					CHTML += '<TD>'       + "&NBSP;" + '</TD>'
					CHTML += '<TD>'       + "&NBSP;" + '</TD>'
					CHTML += '<TD>'       + "&NBSP;" + '</TD>'
					CHTML += '<TD>'       + DTOC(DDTFIM+1) + '</TD>'
					CHTML += '<TD>'       + DTOC(TRBFR->FPO_DTINI-1) + '</TD>'
					CHTML += '<TD>STR0008</TD>' //'       + "DISPONIVEL" + '
					*/
				ENDIF
				LOK := .F.
			ENDIF
			
			IF EMPTY(CLODTF)
				CLODTF := CTOD(" / / ")	
			ENDIF
			
			IF TRBFR->FPO_STATUS == "1" .AND. CLOFRO <> TRBFR->FPO_FROTA .AND. CLODTF < MV_PAR04
	     		@ NLIN, 000     	 PSAY CLOFROX
			    @ NLIN, PCOL()+1	 PSAY CFANTX
			    @ NLIN, PCOL()+1	 PSAY CNOMEX
			    @ NLIN, PCOL()+1	 PSAY "DISPONIVEL"
			    @ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->FPO_LOCAL))
			    @ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->CLI_OBRA))
			    @ NLIN, PCOL()+2	 PSAY SPACE(LEN(TRBFR->MUN_OBRA))
			    @ NLIN, PCOL()+1	 PSAY CLODTF+1
			    @ NLIN, PCOL()+1	 PSAY MV_PAR04
			    NLIN++
				IF MV_PAR15 == 1
					/*
					CHTML := '<TR>'
					CHTML += '<TD>&NBSP;' + CLOFROX + '</TD>'
					CHTML += '<TD>'       + CFANTX + '</TD>'
					CHTML += '<TD>&NBSP;' + CNOMEX + '</TD>'
					CHTML += '<TD>'       + "DISPONIVEL" + '</TD>'
					CHTML += '<TD>'       + "&NBSP;" + '</TD>'
					CHTML += '<TD>'       + "&NBSP;" + '</TD>'
					CHTML += '<TD>'       + "&NBSP;" + '</TD>'
					CHTML += '<TD>'       + DTOC(CLODTF+1) + '</TD>'
					CHTML += '<TD>'       + DTOC(MV_PAR04) + '</TD>'+ CRLF
					CHTML += '<TD>STR0008</TD>' //'       + "DISPONIVEL" + '
					FWRITE(NARQ,CHTML,LEN(CHTML))					
					*/
				EndIf
			ENDIF
			
			NXXX := "OK"
			CLODTI := IF(TRBFR->FPO_DTINI < MV_PAR03, MV_PAR03, TRBFR->FPO_DTINI)
			CLODTF := IF(TRBFR->FPO_DTFIM  > MV_PAR04, MV_PAR04, TRBFR->FPO_DTFIM)
	  		
	  		//-->> PRIMEIRO DISPONÕVEL
	  		IF EMPTY(CLOFRO) .AND. (EMPTY(MV_PAR05) .OR. TRBFR->FPO_STATUS == "1") .AND. LOK
	  			IF CLODTI>MV_PAR03
		     		@ NLIN, 000     	 PSAY TRBFR->FPO_FROTA                                        
				    @ NLIN, PCOL()+1	 PSAY TRBFR->T9_CODFA    
				    @ NLIN, PCOL()+1	 PSAY TRBFR->T9_NOME                     
				    @ NLIN, PCOL()+1	 PSAY "DISPONIVEL"
				    @ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->FPO_LOCAL))
				    @ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->CLI_OBRA))
				    @ NLIN, PCOL()+2	 PSAY SPACE(LEN(TRBFR->MUN_OBRA))
				    @ NLIN, PCOL()+1	 PSAY MV_PAR03    
				    @ NLIN, PCOL()+1	 PSAY CLODTI-1
				    NLIN++
					IF MV_PAR15 == 1		// SE FOR EXPORTAR PARA O EXCEL
						/*
						CHTML := '<TR>'
						CHTML += '<TD>&NBSP;' + TRBFR->FPO_FROTA + '</TD>'
						CHTML += '<TD>'       + TRBFR->T9_CODFA  + '</TD>'
						CHTML += '<TD>&NBSP;' + TRBFR->T9_NOME + '</TD>'
						CHTML += '<TD>'       + "DISPONIVEL" + '</TD>'
						CHTML += '<TD>'       + "&NBSP;" + '</TD>'
						CHTML += '<TD>'       + "&NBSP;" + '</TD>'
						CHTML += '<TD>'       + "&NBSP;" + '</TD>'
						CHTML += '<TD>'       + DTOC(MV_PAR03) + '</TD>'
						CHTML += '<TD>'       + DTOC(CLODTI-1) + '</TD>'+ CRLF
						FWRITE(NARQ,CHTML,LEN(CHTML))   
						*/
					ENDIF						    
					LOK := .F.
	  			ENDIF
	  		ENDIF
	  		
	  		IF TRBFR->FPO_DTINI-DDTFIM>1 .AND. CLOFRO==TRBFR->FPO_FROTA .AND. (EMPTY(MV_PAR05) .OR. TRBFR->FPO_STATUS == "1")
		  		IF TRBFR->FPO_DTINI>=MV_PAR03 .AND. TRBFR->FPO_DTFIM<=MV_PAR04
		  			IF DDTFIM+1 > MV_PAR03 .AND. EMPTY(MV_PAR09) .AND. LOK
			     		@ NLIN, 000     	 PSAY TRBFR->FPO_FROTA                                        
					    @ NLIN, PCOL()+1	 PSAY TRBFR->T9_CODFA    
					    @ NLIN, PCOL()+1	 PSAY TRBFR->T9_NOME                     
					    @ NLIN, PCOL()+1	 PSAY "DISPONIVEL"
					    @ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->FPO_LOCAL))
					    @ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->CLI_OBRA))
					    @ NLIN, PCOL()+2	 PSAY SPACE(LEN(TRBFR->MUN_OBRA))
					    @ NLIN, PCOL()+1	 PSAY DDTFIM+1
					    @ NLIN, PCOL()+1	 PSAY TRBFR->FPO_DTINI-1
					    NLIN++
						IF MV_PAR15 == 1		// SE FOR EXPORTAR PARA O EXCEL
							/*
							CHTML := '<TR>'
							CHTML += '<TD>&NBSP;' + TRBFR->FPO_FROTA + '</TD>'
							CHTML += '<TD>'       + TRBFR->T9_CODFA  + '</TD>'
							CHTML += '<TD>&NBSP;' + TRBFR->T9_NOME + '</TD>'
							CHTML += '<TD>'       + "DISPONIVEL" + '</TD>'
							CHTML += '<TD>'       + "&NBSP;" + '</TD>'
							CHTML += '<TD>'       + "&NBSP;" + '</TD>'
							CHTML += '<TD>'       + "&NBSP;" + '</TD>'
							CHTML += '<TD>'       + DTOC(DDTFIM+1) + '</TD>'
							CHTML += '<TD>'       + DTOC(TRBFR->FPO_DTINI-1) + '</TD>'
							FWRITE(NARQ,CHTML,LEN(CHTML))   
							*/
						ENDIF						    
					ENDIF
					LOK := .T.
				ENDIF
	  		ENDIF
	  		

	  		IF !EMPTY(CLOFRO) .AND. CLOFRO<>TRBFR->FPO_FROTA .AND. (EMPTY(MV_PAR05) .OR. TRBFR->FPO_STATUS == "1")
	  			//-->> FINALIZA O REGISTRO DA FROTA ANTERIOR
	  			//IF MV_PAR04>TRBFR->FPO_DTFIM   
	  			/*
	  			IF MV_PAR04>DDTFIM
					IF MV_PAR03<DDTFIM .AND. MV_PAR04>DDTFIM+1
						DDTFIM := DDTFIM+1
					ELSE
						DDTFIM := MV_PAR03
					ENDIF  			
		     		@ NLIN, 000     	 PSAY CLOFROX
				    @ NLIN, PCOL()+1	 PSAY CFANTX
				    @ NLIN, PCOL()+1	 PSAY CNOMEX
				    @ NLIN, PCOL()+1	 PSAY "DISPONIVEL"
				    @ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->FPO_LOCAL))
				    @ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->CLI_OBRA))
				    @ NLIN, PCOL()+2	 PSAY SPACE(LEN(TRBFR->MUN_OBRA))
				    @ NLIN, PCOL()+1	 PSAY DDTFIM
				    @ NLIN, PCOL()+1	 PSAY MV_PAR04
				    NLIN++
				    //NLIN++
					IF MV_PAR15 == 1
						CHTML := '<TR>'
						CHTML += '<TD>&NBSP;' + CLOFROX + '</TD>'
						CHTML += '<TD>'       + CFANTX + '</TD>'
						CHTML += '<TD>&NBSP;' + CNOMEX + '</TD>'
						CHTML += '<TD>'       + "DISPONIVEL" + '</TD>'
						CHTML += '<TD>'       + "&NBSP;" + '</TD>'
						CHTML += '<TD>'       + "&NBSP;" + '</TD>'
						CHTML += '<TD>'       + "&NBSP;" + '</TD>'
						CHTML += '<TD>'       + DTOC(DDTFIM) + '</TD>'
						CHTML += '<TD>'       + DTOC(MV_PAR04) + '</TD>'+ CRLF
						FWRITE(NARQ,CHTML,LEN(CHTML))					
					ENDIF
				ENDIF
                */
				//-->> INICIA O REGISTRO DA NOVA FROTA
				IF MV_PAR03<TRBFR->FPO_DTINI .OR. TRBFR->FPO_STATUS = "1" .AND. LOK
					DDT := TRBFR->FPO_DTINI-1
					IF LSALTA
						DDTFIM := MV_PAR03
					ELSE
						IF DDTFIM<MV_PAR03
							DDTFIM := MV_PAR03
						CHTML += '<TD>STR0008</TD>' //'       + "DISPONIVEL" + '
							DDTFIM := DDTFIM+1    
						ENDIF
					ENDIF
					IF DDT < MV_PAR03
						DDT := TRBFR->FPO_DTFIM
					ENDIF
					IF DDT > MV_PAR04
						DDT := MV_PAR04
					ENDIF
		     		@ NLIN, 000     	 PSAY TRBFR->FPO_FROTA                                        
				    @ NLIN, PCOL()+1	 PSAY TRBFR->T9_CODFA    
				    @ NLIN, PCOL()+1	 PSAY TRBFR->T9_NOME                     
				    @ NLIN, PCOL()+1	 PSAY "DISPONIVEL"
				    @ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->FPO_LOCAL))
				    @ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->CLI_OBRA))
				    @ NLIN, PCOL()+2	 PSAY SPACE(LEN(TRBFR->MUN_OBRA))
				    @ NLIN, PCOL()+1	 PSAY MV_PAR03
				    @ NLIN, PCOL()+1	 PSAY DDT
				    NLIN++
					IF MV_PAR15 == 1		// SE FOR EXPORTAR PARA O EXCEL
						/*
						CHTML := '<TR>'
						CHTML += '<TD>&NBSP;' + TRBFR->FPO_FROTA + '</TD>'
						CHTML += '<TD>'       + TRBFR->T9_CODFA  + '</TD>'
						CHTML += '<TD>&NBSP;' + TRBFR->T9_NOME + '</TD>'
						CHTML += '<TD>'       + "DISPONIVEL" + '</TD>'
						CHTML += '<TD>'       + "&NBSP;" + '</TD>'
						CHTML += '<TD>'       + "&NBSP;" + '</TD>'
						CHTML += '<TD>'       + "&NBSP;" + '</TD>'
						CHTML += '<TD>'       + DTOC(MV_PAR03) + '</TD>'
						CHTML += '<TD>'       + DTOC(DDT) + '</TD>'+ CRLF
						FWRITE(NARQ,CHTML,LEN(CHTML))   
						*/
					ENDIF						   			
					LOK := .F.
				ENDIF
				
				DDTFIM := TRBFR->FPO_DTFIM
				
	  		ENDIF
			
			IF CLODTI>=MV_PAR03 .AND. CLODTF<=MV_PAR04
				IF TRBFR->FPO_LOJA>=MV_PAR11 .AND.TRBFR->FPO_LOJA<=MV_PAR12
		     		@ NLIN, 000      PSAY TRBFR->FPO_FROTA                                        
				    @ NLIN, PCOL()+1 PSAY TRBFR->T9_CODFA    
				    @ NLIN, PCOL()+1 PSAY TRBFR->T9_NOME                     
				    @ NLIN, PCOL()+1 PSAY TRBFR->STAT_FR    
				    @ NLIN, PCOL()+1 PSAY TRBFR->FPO_LOCAL    
		
				    IF TRBFR->FPO_STATUS == 'E'
				       CMUNOBRA := ALLTRIM(POSICIONE("SM0", 1, CEMPANT+TRBFR->FPO_FILNF, "M0_CIDCOB"))+"/"+POSICIONE("SM0", 1, CEMPANT+TRBFR->FPO_FILNF, "M0_ESTCOB")
			           CCLIOBRA := ALLTRIM(POSICIONE("SM0", 1, CEMPANT+TRBFR->FPO_FILNF, "M0_NOMECOM"))
					ELSE
					   CMUNOBRA := TRBFR->MUN_OBRA  
			           CCLIOBRA := TRBFR->CLI_OBRA
					ENDIF
				    
				    IF ALLTRIM(CCLIOBRA)=="/"
				    	CCLIOBRA := ""
					ENDIF
				    
				    @ NLIN, PCOL()+1 PSAY PADR(CCLIOBRA, LEN(TRBFR->CLI_OBRA))           
				    @ NLIN, PCOL()+1 PSAY PADR(CMUNOBRA, LEN(TRBFR->MUN_OBRA))    
				    @ NLIN, PCOL()+1 PSAY CLODTI    
				    @ NLIN, PCOL()+1 PSAY CLODTF 
				
					IF MV_PAR15 == 1		// SE FOR EXPORTAR PARA O EXCEL
						/*
						CHTML := '<TR>'
						CHTML += '<TD>&NBSP;' + TRBFR->FPO_FROTA + '</TD>'
						CHTML += '<TD>'       + TRBFR->T9_CODFA  + '</TD>'
						CHTML += '<TD>&NBSP;' + TRBFR->T9_NOME + '</TD>'
						CHTML += '<TD>'       + TRBFR->STAT_FR   + '</TD>'
						CHTML += '<TD>'       + TRBFR->FPO_LOCAL + '</TD>'
						CHTML += '<TD>'       + CCLIOBRA + '</TD>'
						CHTML += '<TD>'       + CMUNOBRA+ '</TD>'
						CHTML += '<TD>'       + DTOC(CLODTI) + '</TD>'
						CHTML += '<TD>'       + DTOC(CLODTF) + '</TD>'+ CRLF
						FWRITE(NARQ,CHTML,LEN(CHTML))   
						*/
					ENDIF
			  		CLO_CLI	:= CCLIOBRA
			        CLO_MUN	:= CMUNOBRA
			
				    NLIN := NLIN + 1 // AVANCA A LINHA DE IMPRESSAO
				    
				ENDIF
				LOK := .T.
			ENDIF
		    
			CLOFRO	:= TRBFR->FPO_FROTA
			CFANT	:= TRBFR->T9_CODFA
			CNOME	:= TRBFR->T9_NOME
	        CLOSTAT	:= TRBFR->FPO_STATUS		
			CLOFROX	:= TRBFR->FPO_FROTA
			CFANTX	:= TRBFR->T9_CODFA
			CNOMEX	:= TRBFR->T9_NOME
	
		ENDIF
	
	ELSE
	
			IF MV_PAR05 == "1"
		
			IF NCONT == 0
				NXXX := "OK"
				IF MV_PAR03<=TRBFR->FPO_DTINI
					IF TRBFR->FPO_DTINI>=MV_PAR03 //.AND. TRBFR->FPO_DTFIM<=MV_PAR04
						IF MV_PAR03 <= TRBFR->FPO_DTINI
							DDT := TRBFR->FPO_DTINI-1
							IF DDT > MV_PAR04
								DDT := MV_PAR04
							ENDIF
							IF EMPTY(TRBFR->FPO_LOCAL) .AND. EMPTY(TRBFR->STAT_FR) 
								DDT := TRBFR->FPO_DTFIM
							ENDIF
				     		@ NLIN, 000     	 PSAY TRBFR->FPO_FROTA                                        
						    @ NLIN, PCOL()+1	 PSAY TRBFR->T9_CODFA    
						    @ NLIN, PCOL()+1	 PSAY TRBFR->T9_NOME                     
						    @ NLIN, PCOL()+1	 PSAY "DISPONIVEL"
						    @ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->FPO_LOCAL))
						    @ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->CLI_OBRA))
						    @ NLIN, PCOL()+2	 PSAY SPACE(LEN(TRBFR->MUN_OBRA))
						    @ NLIN, PCOL()+1	 PSAY MV_PAR03    
						    @ NLIN, PCOL()+1	 PSAY DDT
						    NLIN++
							IF MV_PAR15 == 1		// SE FOR EXPORTAR PARA O EXCEL
								/*
								CHTML := '<TR>'
								CHTML += '<TD>&NBSP;' + TRBFR->FPO_FROTA + '</TD>'
								CHTML += '<TD>'       + TRBFR->T9_CODFA  + '</TD>'
								CHTML += '<TD>&NBSP;' + TRBFR->T9_NOME + '</TD>'
								CHTML += '<TD>'       + "DISPONIVEL" + '</TD>'
								CHTML += '<TD>'       + "&NBSP;" + '</TD>'
								CHTML += '<TD>'       + "&NBSP;" + '</TD>'
								CHTML += '<TD>'       + "&NBSP;" + '</TD>'
								CHTML += '<TD>'       + DTOC(MV_PAR03) + '</TD>'
								CHTML += '<TD>'       + DTOC(DDT) + '</TD>'+ CRLF
								FWRITE(NARQ,CHTML,LEN(CHTML))   
								*/
							ENDIF
						ENDIF							
					ENDIF
				ENDIF
				LSALTA := .F.
				CLOFRO	:= TRBFR->FPO_FROTA			
			ELSE			
				IF TRBFR->FPO_DTINI-DDTFIM>1
					IF TRBFR->FPO_DTINI>=MV_PAR03 //.AND. TRBFR->FPO_DTFIM<=MV_PAR04						
						IF DDTFIM <= MV_PAR04
							DDT := TRBFR->FPO_DTINI-1
							IF LSALTA
								DDTFIM := MV_PAR03
							ELSE
								IF DDTFIM<MV_PAR03
									DDTFIM := MV_PAR03
								ELSE
									DDTFIM := DDTFIM+1    
									CHTML += '<TD>STR0008</TD>' //'       + "DISPONIVEL" + '
							ENDIF
							IF DDT > MV_PAR04
								DDT := MV_PAR04
							ENDIF
							IF EMPTY(TRBFR->FPO_LOCAL) .AND. EMPTY(TRBFR->STAT_FR) 
								DDT := TRBFR->FPO_DTFIM
							ENDIF							
							//-->> ALTERADO 14/03 23:59HS
							IF DDTFIM <= MV_PAR04
					     		@ NLIN, 000     	 PSAY TRBFR->FPO_FROTA                                        
							    @ NLIN, PCOL()+1	 PSAY TRBFR->T9_CODFA    
							    @ NLIN, PCOL()+1	 PSAY TRBFR->T9_NOME                     
							    @ NLIN, PCOL()+1	 PSAY "DISPONIVEL"
							    @ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->FPO_LOCAL))
							    @ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->CLI_OBRA))
							    @ NLIN, PCOL()+2	 PSAY SPACE(LEN(TRBFR->MUN_OBRA))
							    @ NLIN, PCOL()+1	 PSAY DDTFIM    
							    @ NLIN, PCOL()+1	 PSAY DDT
							    NLIN++
								IF MV_PAR15 == 1		// SE FOR EXPORTAR PARA O EXCEL
									/*
									CHTML := '<TR>'
									CHTML += '<TD>&NBSP;' + TRBFR->FPO_FROTA + '</TD>'
									CHTML += '<TD>'       + TRBFR->T9_CODFA  + '</TD>'
									CHTML += '<TD>&NBSP;' + TRBFR->T9_NOME + '</TD>'
									CHTML += '<TD>'       + "DISPONIVEL" + '</TD>'
									CHTML += '<TD>'       + "&NBSP;" + '</TD>'
									CHTML += '<TD>'       + "&NBSP;" + '</TD>'
									CHTML += '<TD>'       + "&NBSP;" + '</TD>'
									CHTML += '<TD>'       + DTOC(DDTFIM) + '</TD>'
									CHTML += '<TD>'       + DTOC(DDT) + '</TD>'+ CRLF
									FWRITE(NARQ,CHTML,LEN(CHTML))   
									*/
								ENDIF
							ENDIF
							LSALTA := .F.
						ENDIF
					ENDIF
				ENDIF
				IF !EMPTY(CLOFROX) .AND. CLOFROX <> TRBFR->FPO_FROTA
					IF NCONT > 1

						IF (TRBFR->FPO_DTINI>=MV_PAR03 /*.AND. TRBFR->FPO_DTFIM<=MV_PAR04*/) .OR. (MV_PAR04 > DDTFIM)
							IF DDTFIM<=MV_PAR04
									CHTML += '<TD>STR0008</TD>' //'       + "DISPONIVEL" + '
									//IF LSALTA										
									//	DDTFIM := MV_PAR03
									//ELSE
										DDTFIM := DDTFIM+1
									//ENDIF
								ELSE
									DDTFIM := MV_PAR03
								ENDIF
					     		@ NLIN, 000     	 PSAY CLOFROX
							    @ NLIN, PCOL()+1	 PSAY CFANTX
							    @ NLIN, PCOL()+1	 PSAY CNOMEX
							    @ NLIN, PCOL()+1	 PSAY "DISPONIVEL"
							    @ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->FPO_LOCAL))
							    @ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->CLI_OBRA))
							    @ NLIN, PCOL()+2	 PSAY SPACE(LEN(TRBFR->MUN_OBRA))
							    @ NLIN, PCOL()+1	 PSAY DDTFIM
							    @ NLIN, PCOL()+1	 PSAY MV_PAR04
							    NLIN++
							    //NLIN++
								IF MV_PAR15 == 1		// SE FOR EXPORTAR PARA O EXCEL
									/*
									CHTML := '<TR>'
									CHTML += '<TD>&NBSP;' + CLOFROX + '</TD>'
									CHTML += '<TD>'       + CFANTX  + '</TD>'
									CHTML += '<TD>&NBSP;' + CNOMEX + '</TD>'
									CHTML += '<TD>'       + "DISPONIVEL" + '</TD>'
									CHTML += '<TD>'       + "&NBSP;" + '</TD>'
									CHTML += '<TD>'       + "&NBSP;" + '</TD>'
									CHTML += '<TD>'       + "&NBSP;" + '</TD>'
									CHTML += '<TD>'       + DTOC(DDTFIM) + '</TD>'
									CHTML += '<TD>'       + DTOC(MV_PAR04) + '</TD>'+ CRLF
									FWRITE(NARQ,CHTML,LEN(CHTML))   
									LSALTA := .T.
									//FWRITE(NARQ,CHTML,LEN(CHTML))
									CHTML += '<TD>STR0008</TD>' //'       + "DISPONIVEL" + '
									*/
								EndIf
							ENDIF
							IF MV_PAR03< TRBFR->FPO_DTINI-1
								DDT := TRBFR->FPO_DTINI-1
								IF DDT > MV_PAR04
									DDT := MV_PAR04
								ENDIF
								IF EMPTY(TRBFR->FPO_LOCAL) .AND. EMPTY(TRBFR->STAT_FR) 
									DDT := TRBFR->FPO_DTFIM
								ENDIF																			
					     		@ NLIN, 000     	 PSAY TRBFR->FPO_FROTA
							    @ NLIN, PCOL()+1	 PSAY TRBFR->T9_CODFA
							    @ NLIN, PCOL()+1	 PSAY TRBFR->T9_NOME
							    @ NLIN, PCOL()+1	 PSAY "DISPONIVEL"
							    @ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->FPO_LOCAL))
							    @ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->CLI_OBRA))
							    @ NLIN, PCOL()+2	 PSAY SPACE(LEN(TRBFR->MUN_OBRA))
							    @ NLIN, PCOL()+1	 PSAY MV_PAR03
							    @ NLIN, PCOL()+1	 PSAY DDT
							    NLIN++
								IF MV_PAR15 == 1		// SE FOR EXPORTAR PARA O EXCEL
									/*
									CHTML := '<TR>'
									CHTML += '<TD>&NBSP;' + TRBFR->FPO_FROTA + '</TD>'
									CHTML += '<TD>'       + TRBFR->T9_CODFA  + '</TD>'
									CHTML += '<TD>&NBSP;' + TRBFR->T9_NOME + '</TD>'
									CHTML += '<TD>'       + "DISPONIVEL" + '</TD>'
									CHTML += '<TD>'       + "&NBSP;" + '</TD>'
									CHTML += '<TD>'       + "&NBSP;" + '</TD>'
									CHTML += '<TD>'       + "&NBSP;" + '</TD>'
									CHTML += '<TD>'       + DTOC(MV_PAR03) + '</TD>'
									CHTML += '<TD>'       + DTOC(DDT) + '</TD>'+ CRLF
									FWRITE(NARQ,CHTML,LEN(CHTML))   
									*/
								ENDIF
								LSALTA := .F.
							ENDIF
						ENDIF
						DDTFIM := TRBFR->FPO_DTFIM
					ENDIF
	            ENDIF
				CLOFRO	:= TRBFR->FPO_FROTA			
				
			ENDIF
			
			CLOFROX	:= TRBFR->FPO_FROTA
			CFANTX	:= TRBFR->T9_CODFA
			CNOMEX	:= TRBFR->T9_NOME
			CLOSTAT	:= TRBFR->FPO_STATUS		
			CLODTF := IF(TRBFR->FPO_DTFIM  > MV_PAR04, MV_PAR04, TRBFR->FPO_DTFIM)
			
		ENDIF			
		
	ENDIF

	IF DDTFIM < TRBFR->FPO_DTFIM
		DDTFIM := TRBFR->FPO_DTFIM
	ENDIF
	
	NCONT++
	
	TRBFR->(DBSKIP()) // AVANCA O PONTEIRO DO REGISTRO NO ARQUIVO
		   
ENDDO

IF EXISTF .AND. !EMPTY(NXXX)
				CHTML += '<TD>STR0008</TD>' //'       + "DISPONIVEL" + '
	TRBFR->(DBSKIP(-1)) 
	
	IF EMPTY(MV_PAR05) .OR. CLOSTAT == "1"
		IF DDTFIM<MV_PAR04
			//DDTFIM := DDTFIM+1
			DDTFIM := CLODTF+1
			IF EMPTY(CLOSTAT) 
				DDTFIM := MV_PAR03
			ENDIF
			@ NLIN, 000     	 PSAY CLOFROX
		    @ NLIN, PCOL()+1	 PSAY CFANTX
		    @ NLIN, PCOL()+1	 PSAY CNOMEX
		    @ NLIN, PCOL()+1	 PSAY "DISPONIVEL"
		    @ NLIN, PCOL()+1	 PSAY SPACE(40)
		    @ NLIN, PCOL()+1	 PSAY SPACE(60)
		    @ NLIN, PCOL()+2	 PSAY SPACE(23)
		    @ NLIN, PCOL()+1	 PSAY DDTFIM
		    @ NLIN, PCOL()+1	 PSAY MV_PAR04
		    NLIN++
			IF MV_PAR15 == 1
				/*
				CHTML := '<TR>'
				CHTML += '<TD>&NBSP;' + CLOFROX + '</TD>'
				CHTML += '<TD>'       + CFANTX  + '</TD>'
				CHTML += '<TD>&NBSP;' + CNOMEX + '</TD>'
				CHTML += '<TD>'       + "DISPONIVEL" + '</TD>'
				CHTML += '<TD>'       + "&NBSP;" + '</TD>'
				CHTML += '<TD>'       + "&NBSP;" + '</TD>'
				CHTML += '<TD>'       + "&NBSP;" + '</TD>'
				CHTML += '<TD>'       + DTOC(DDTFIM) + '</TD>'
				CHTML += '<TD>'       + DTOC(MV_PAR04) + '</TD>'
					CHTML += '<TD>STR0008</TD>' //'       + "DISPONIVEL" + '
				*/
			ENDIF
		ENDIF
	ELSE
		IF MV_PAR05 == "1"
			IF MV_PAR04>=DDTFIM
				DDTFIM := DDTFIM+1
				IF EMPTY(CLOSTAT) 
					DDTFIM := MV_PAR03
				ENDIF
				@ NLIN, 000     	 PSAY CLOFROX
			    @ NLIN, PCOL()+1	 PSAY CFANTX
			    @ NLIN, PCOL()+1	 PSAY CNOMEX
			    @ NLIN, PCOL()+1	 PSAY "DISPONIVEL"
			    @ NLIN, PCOL()+1	 PSAY SPACE(40)
			    @ NLIN, PCOL()+1	 PSAY SPACE(60)
			    @ NLIN, PCOL()+2	 PSAY SPACE(23)
			    @ NLIN, PCOL()+1	 PSAY DDTFIM
			    @ NLIN, PCOL()+1	 PSAY MV_PAR04
			    NLIN++
				IF MV_PAR15 == 1
					/*
					CHTML := '<TR>'
					CHTML += '<TD>&NBSP;' + CLOFROX + '</TD>'
					CHTML += '<TD>'       + CFANTX  + '</TD>'
					CHTML += '<TD>&NBSP;' + CNOMEX + '</TD>'
					CHTML += '<TD>'       + "DISPONIVEL" + '</TD>'
					CHTML += '<TD>'       + "&NBSP;" + '</TD>'
					CHTML += '<TD>'       + "&NBSP;" + '</TD>'
					CHTML += '<TD>'       + "&NBSP;" + '</TD>'
					CHTML += '<TD>'       + DTOC(DDTFIM) + '</TD>'
					CHTML += '<TD>'       + DTOC(MV_PAR04) + '</TD>'
					FWRITE(NARQ,CHTML,LEN(CHTML))
					*/
				ENDIF
			ENDIF
		ENDIF
	ENDIF

ENDIF
	
TRBFR->(DBCLOSEAREA())                                          	

IF MV_PAR15 == 1		// SE FOR EXPORTAR PARA O EXCEL
	/*
	CHTML := ' </TABLE></BODY></HTML>'+CRLF
	FWRITE(NARQ,CHTML,LEN(CHTML))
	FCLOSE(NARQ)								// FECHAMOS O ARQUIVO PADR√O HTML
	CPYS2T(GETSRVPROFSTRING("STARTPATH","")+CARQUIVO, ALLTRIM(GETTEMPPATH()), .T.)	// COPIA ARQUIVO HTML DO SERVER\SYSTEM P/ TEMPOR¡RIO DO CLIENTE
	FERASE(CARQUIVO)							// REMOVE ARQUIVO DO SERVER\SYSTEM

	IF APOLECLIENT("MSEXCEL") 	// SE TEM EXCEL NO CLIENTE. ABRIMOS O EXCEL COM O ARQUIVO HTML
		OEXCELAPP := MSEXCEL():NEW()
		OEXCELAPP:WORKBOOKS:OPEN(ALLTRIM(GETTEMPPATH()) + CARQUIVO)
		OEXCELAPP:SETVISIBLE(.T.)
		OEXCELAPP:DESTROY()
	ELSE						//SE N√O ENCONTROU O EXCEL, O S.O. DECIDE COMO ABRIR
		SHELLEXECUTE("OPEN",ALLTRIM(GETTEMPPATH()) + CARQUIVO,"","",1)
	ENDIF
	*/
ENDIF

SET DEVICE TO SCREEN

IF ARETURN[5]==1
   DBCOMMITALL()
   SET PRINTER TO
   OURSPOOL(WNREL)
ENDIF

MS_FLUSH()

RETURN



/*
‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±⁄ƒƒƒƒƒƒƒƒƒƒ¬ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒø±±
±±≥DESCRIáÖO ≥ PROCESSAMENTO E EXECUCAO DO RELATORIO                        ≥±±
±±√ƒƒƒƒƒƒƒƒƒƒ≈ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒ¥±±
±±≥ USO      ≥ ESPECIFICO GPO                                               ≥±±
±±¿ƒƒƒƒƒƒƒƒƒƒ¡ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒŸ±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ
*/
STATIC FUNCTION VALIDPERG(CPERG)
/*
CPERG := PADR(CPERG,10)

PUTSX1(CPERG,"01","FROTA DE?   ","","","MV_CH1","C",16,00,00,"G","","ST9 ","","","MV_PAR01","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"02","FROTA ATE?  ","","","MV_CH2","C",16,00,00,"G","","ST9 ","","","MV_PAR02","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"03","PERIODO DE? ","","","MV_CH3","D",08,00,00,"G","NAOVAZIO()","    ","","","MV_PAR03","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"04","PERIODO ATE?","","","MV_CH4","D",08,00,00,"G","NAOVAZIO()","    ","","","MV_PAR04","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"05","STATUS DE?  ","","","MV_CH5","C",01,00,00,"G","","ZL  ","","","MV_PAR05","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"06","STATUS ATE? ","","","MV_CH6","C",01,00,00,"G","","ZL  ","","","MV_PAR06","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"07","ASG DE?     ","","","MV_CH7","C",27,00,00,"G","","DTQA","","","MV_PAR07","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"08","ASG ATE?    ","","","MV_CH8","C",27,00,00,"G","","DTQA","","","MV_PAR08","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"09","CLIENTE DE? ","","","MV_CH9","C",06,00,00,"G","","CLI ","","","MV_PAR09","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"10","CLIENTE ATE?","","","MV_CHA","C",06,00,00,"G","","CLI ","","","MV_PAR10","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"11","LOJA DE?    ","","","MV_CHB","C",02,00,00,"G","","    ","","","MV_PAR11","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"12","LOJA ATE?   ","","","MV_CHC","C",02,00,00,"G","","    ","","","MV_PAR12","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"13","OBRA DE?    ","","","MV_CHD","C",03,00,00,"G","","    ","","","MV_PAR13","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"14","OBRA ATE?   ","","","MV_CHE","C",03,00,00,"G","","    ","","","MV_PAR14","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"15","EXPORTA EXCEL?","","","MV_CHF","N",01,0,0,"C","","      ","","","MV_PAR15","SIM","","","","N√O","","" ,"","","","","","","","","")
*/
RETURN
