/*
CARREGAMENTO
*/

   SELECT Z0Y.Z0Y_FILIAL
        , CONVERT(DATE,Z0Y.Z0Y_DATA,103) Z0Y_DATA
		, Z0Y.Z0Y_ROTA
		, Z0Y.Z0Y_ORDEM
		, Z0Y.Z0Y_TRATO
		, Z0Y.Z0Y_RECEIT
		, B1R.B1_DESC DESC_REC
		, CASE WHEN Z0Y.Z0Y_ORIGEM = 'B' THEN 'BALANCA' 
		       WHEN Z0Y.Z0Y_ORIGEM = 'P' THEN 'PHIBRO'
			   WHEN Z0Y.Z0Y_ORIGEM = 'V' THEN 'CHUVEIRO'
			   ELSE ' ' 
			 END AS Z0Y_ORIGEM
		, Z0Y.Z0Y_COMP
		, B1C.B1_DESC DESC_COMP
        , CASE WHEN Z0Y.Z0Y_KGRECA > 0 THEN Z0Y.Z0Y_KGRECA 
		       ELSE Z0Y.Z0Y_QTDPRE 
			 END AS Z0Y_QTDPRE
		, CASE WHEN Z0Y.Z0Y_PESDIG > 0 THEN Z0Y.Z0Y_PESDIG
		       ELSE Z0Y.Z0Y_QTDREA
			 END AS Z0Y_QTDREA
		
		, ROUND((CASE WHEN Z0Y.Z0Y_PESDIG > 0 THEN Z0Y.Z0Y_PESDIG
		       ELSE Z0Y.Z0Y_QTDREA
			 END 
			 -
			 CASE WHEN Z0Y.Z0Y_KGRECA > 0 THEN Z0Y.Z0Y_KGRECA 
		       ELSE Z0Y.Z0Y_QTDPRE 
			 END ),2) KG_DIF

		, ROUND((CASE WHEN Z0Y.Z0Y_PESDIG > 0 THEN Z0Y.Z0Y_PESDIG
		       ELSE Z0Y.Z0Y_QTDREA
			 END 
			 /
			 CASE WHEN Z0Y.Z0Y_KGRECA > 0 THEN Z0Y.Z0Y_KGRECA 
		       ELSE Z0Y.Z0Y_QTDPRE 
			 END )-1,2)*100 PERC_DIF
		, ISNULL(ZRF_TOLPER ,0) ZRF_TOLPER
		, Z0Y_HORINI
		, Z0Y_HORFIN
     FROM Z0Y010 Z0Y
	 JOIN Z0X010 Z0X ON 
	      Z0X.Z0X_FILIAL = Z0Y.Z0Y_FILIAL
	  AND Z0X.Z0X_CODIGO = Z0Y.Z0Y_CODEI
	  AND Z0X_OPERAC = '1'
	 JOIN SB1010 B1R ON
	      B1R.B1_FILIAL = ' ' 
	  AND B1R.B1_COD = Z0Y_RECEIT
	  AND B1R.B1_X_TRATO = '1'
	  AND B1R.D_E_L_E_T_ = ' ' 
	  
	 JOIN SB1010 B1C ON 
	      B1C.B1_FILIAL = ' ' 
	  AND B1C.B1_COD = Z0Y_COMP
	  AND B1C.D_E_L_E_T_  = ' ' 
	 LEFT JOIN ZRF010 ZRF ON ZRF_DTINI <= '20211014' AND ZRF_DTFIM >= '20211014' AND ZRF_OPERAC = '1' AND RTRIM(ZRF_PRODUT) = RTRIM(Z0Y_COMP) AND ZRF.D_E_L_E_T_ = ' ' 
    WHERE Z0Y_FILIAL = '01' 
      AND Z0Y_DATA BETWEEN '20211014' AND '20211014'
	  AND Z0Y.D_E_L_E_T_ = ' ' 
	  AND Z0Y.Z0Y_ORIGEM IN ('P','B','V')
	  --AND ZRF_TOLPER IS NOT NULL
	  ORDER BY 1, 2, 3, 4, 5, 8,15
	  
	  
	  
/*
FORNECIMENTO
*/


   SELECT Z0W.Z0W_FILIAL
        , Z0W.Z0W_DATA
		, Z0W.Z0W_ROTA
		, Z0W.Z0W_ORDEM
		, Z0W.Z0W_TRATO
		, Z0W.Z0W_RECEIT
		, B1R.B1_DESC
		, Z0W.Z0W_CURRAL
		, Z0W.Z0W_LOTE
        , CASE WHEN Z0W.Z0W_KGRECA > 0 THEN Z0W.Z0W_KGRECA 
		       ELSE Z0W.Z0W_QTDPRE 
			 END AS Z0W_QTDPRE
		, CASE WHEN Z0W.Z0W_PESDIG > 0 THEN Z0W.Z0W_PESDIG
		       ELSE Z0W.Z0W_QTDREA
			 END AS Z0W_QTDREA
		
		, ROUND((CASE WHEN Z0W.Z0W_PESDIG > 0 THEN Z0W.Z0W_PESDIG
		       ELSE Z0W.Z0W_QTDREA
			 END 
			 -
			 CASE WHEN Z0W.Z0W_KGRECA > 0 THEN Z0W.Z0W_KGRECA 
		       ELSE Z0W.Z0W_QTDPRE 
			 END ),2) KG_DIF

		, ROUND((CASE WHEN Z0W.Z0W_PESDIG > 0 THEN Z0W.Z0W_PESDIG
		       ELSE Z0W.Z0W_QTDREA
			 END 
			 /
			 CASE WHEN Z0W.Z0W_KGRECA > 0 THEN Z0W.Z0W_KGRECA 
		       ELSE Z0W.Z0W_QTDPRE 
			 END )-1,2)*100 PERC_DIF
		, ISNULL(ZRF_TOLPER ,0) ZRF_TOLPER
			 
		, Z0W_HORINI
		, Z0W_HORFIN
		, Z0X_OPERAD
		, Z0U_NOME
     FROM Z0W010 Z0W
	 JOIN Z0X010 Z0X ON 
	      Z0X.Z0X_FILIAL = Z0W.Z0W_FILIAL
	  AND Z0X.Z0X_CODIGO = Z0W.Z0W_CODEI
	  AND Z0X_OPERAC = '1'
	 JOIN SB1010 B1R ON
	      B1R.B1_FILIAL = ' ' 
	  AND B1R.B1_COD = Z0W_RECEIT
	  AND B1R.B1_X_TRATO = '1'
	  AND B1R.D_E_L_E_T_ = ' ' 
LEFT JOIN Z0U010 Z0U ON 
          Z0U.Z0U_FILIAL = '01' 
      AND Z0U.Z0U_CODIGO = Z0X_OPERAD
	  AND Z0U.D_E_L_E_T_ = ' ' 
 LEFT JOIN ZRF010 ZRF ON ZRF_DTINI <= '20211014' AND ZRF_DTFIM >= '20211014'  AND ZRF_OPERAC = 2 AND ZRF.D_E_L_E_T_ = ' ' 

    WHERE Z0W_FILIAL = '01' 
      AND Z0W_DATA BETWEEN '20211004' AND '20211004'
	  AND Z0W.D_E_L_E_T_ = ' ' 
	  AND Z0W.Z0W_QTDPRE > 0 
	  --AND Z0W.Z0W_ORIGEM IN ('P','B','V')
	  ORDER BY 1, 3, 5, 8


