
WITH PRINCIPAL AS (
   SELECT  ZBC.ZBC_FILIAL FILIAL
        , ZBC.ZBC_CODIGO CODIGO
		, ZBC.ZBC_CODFOR COD_FORN
		, ZBC.ZBC_LOJFOR LOJ_FORN
		, ZCC.ZCC_NOMFOR FORNECEDOR 
		, SA2.A2_MUN MUNICIPIO
		, SA2.A2_EST ESTADO
		, ZBC.ZBC_PRODUT PRODUTO
		, ZBC_PRDDES DESCRICAO
		, CASE WHEN ZBC.ZBC_TPNEG	= 'P' THEN 'PESO'
 			   WHEN ZBC.ZBC_TPNEG	= 'K' THEN 'KG'
 			   WHEN ZBC.ZBC_TPNEG	= 'Q' THEN 'CABECA'
 			 							  ELSE 'VERIFICAR' END NEGOCIACAO
		, ZBC.ZBC_QUANT QTDE
		, ZBC.ZBC_PESO PESO_COMPRA
		, ZBC.ZBC_PESO / ZBC.ZBC_QUANT PESO_MEDIO
		, ZBC_REND RENDIMENTO
		, ZBC.ZBC_ARROV VALOR
		, CONVERT(DATE, MIN(SD1.D1_EMISSAO), 103) DATANF
		, SUM(SD1.D1_X_PESCH) PESO_CHEGADA
		, SUM(SD1.D1_X_PESCH) / ZBC.ZBC_QUANT PESOMEDIO
		, SUM(SD1.D1_TOTAL) GADO_TOTAL
		, SUM(SD1.D1_CUSTO) GADO_SEM_ICMS
		, SUM(SD1.D1_VALICM) GADO_ICMS_TOTAL
		, ZBC_VLFRPG VALOR_FRETE
		, ZBC_ICFRVL ICMS_FRETE
		, ZBC_VLRCOM COMISSAO
     FROM ZBC010 ZBC 
     JOIN ZCC010 ZCC ON 
	                    ZCC.ZCC_FILIAL = ZBC.ZBC_FILIAL 
					AND ZCC.ZCC_CODIGO = ZBC.ZBC_CODIGO 
					AND ZCC.ZCC_VERSAO = ZBC.ZBC_VERSAO 
					AND ZCC.ZCC_CODFOR = ZBC.ZBC_CODFOR
					AND ZCC.D_E_L_E_T_ = ' '
	 JOIN SA2010 SA2 ON 
	                   ZCC.ZCC_CODFOR+ZCC.ZCC_LOJFOR = SA2.A2_COD+SA2.A2_LOJA 
				   AND SA2.D_E_L_E_T_ = ' '
LEFT JOIN SD1010 SD1 ON 
				        SD1.D1_FILIAL = ZBC.ZBC_FILIAL 
					AND SD1.D1_FORNECE+SD1.D1_LOJA = ZBC.ZBC_CODFOR + ZBC.ZBC_LOJFOR 
					AND SD1.D1_PEDIDO =ZBC.ZBC_PEDIDO 
					AND SD1.D1_TIPO IN ('N') AND ZCC_CODFOR <> ' '
					AND SD1.D1_COD = ZBC.ZBC_PRODUT  
					AND SD1.D_E_L_E_T_ = ' ' JOIN SF4010 SF4 ON 
				        SF4.F4_FILIAL = ' ' 
					AND SF4.F4_CODIGO = SD1.D1_TES 
					AND SF4.F4_TRANFIL <> '1' 
					AND SF4.D_E_L_E_T_ = ' '   
    WHERE ZCC.ZCC_DTCONT >= '20210101' 
	 AND  ZBC.ZBC_PEDIDO <> ' ' 
	 AND ZBC.D_E_L_E_T_ = ' ' 
	 AND ZCC.ZCC_CODIGO >= '002568'
	 --AND ZBC.ZBC_CODIGO = '002199'
	 AND ZBC_PRODUT LIKE 'BOV%'
	 --AND ZBC_PRODUT NOT IN (SELECT D3_COD FROM SD3010 WHERE D3_COD
 GROUP BY ZBC.ZBC_FILIAL
        , ZBC.ZBC_CODIGO
		, ZBC.ZBC_CODFOR
		, ZBC.ZBC_LOJFOR
        , ZCC.ZCC_NOMFOR
		, SA2.A2_MUN
		, SA2.A2_EST
		, ZBC.ZBC_PRODUT
		, ZBC.ZBC_PRDDES
		, ZBC.ZBC_TPNEG
		, ZBC.ZBC_QUANT
		, ZBC.ZBC_PESO
		, ZBC_REND
		, ZBC.ZBC_ARROV
		, ZBC_VLFRPG
		, ZBC_ICFRVL
		, ZBC_VLRCOM
		--, SD1.D1_COD		

		
		)
		SELECT P.*, SUM(ISNULL(SD1C.D1_TOTAL,0)) GADO_COMPLEMENTO
		  FROM PRINCIPAL P 
		  LEFT JOIN SD1010 SD1C ON 
						SD1C.D1_FILIAL = FILIAL
					AND SD1C.D1_FORNECE+SD1C.D1_LOJA = P.COD_FORN+P.LOJ_FORN 
					AND SD1C.D1_COD = P.PRODUTO
					AND SD1C.D1_TIPO IN ('C') 
					AND P.COD_FORN <> ' '
					AND SD1C.D_E_L_E_T_ = ' ' 
		GROUP BY 
		  P.FILIAL
		, P.CODIGO
        , P.COD_FORN
		, P.LOJ_FORN
		, P.FORNECEDOR
		, P.MUNICIPIO
		, P.ESTADO
		, P.PRODUTO
		, P.DESCRICAO
		, P.NEGOCIACAO		
		, P.QTDE
		, P.PESO_COMPRA
		, P.PESO_MEDIO
		, P.RENDIMENTO
		, P.VALOR
		, P.PESO_CHEGADA
		, P.PESOMEDIO
		, P.DATANF
		, P.GADO_TOTAL
		, P.GADO_ICMS_TOTAL
		, P.GADO_SEM_ICMS
		, P.GADO_TOTAL
		, P.VALOR_FRETE
		, P.ICMS_FRETE
		, P.COMISSAO
		
	ORDER BY DATANF

	