with DADOS as (
     SELECT DISTINCT B8_FILIAL, B8_LOTECTL, SUM(B8_SALDO) B8_SALDO, B8_X_CURRA, B1_X_SEXO, B1_XRACA, B8_XPESOCO
	   FROM SB8010 (NOLOCK) SB8 
	   JOIN SB1010 (NOLOCK) SB1 ON 
	        B1_COD = B8_PRODUTO 
		AND SB1.D_E_L_E_T_ = ' ' 
	  WHERE B8_LOTECTL NOT IN (SELECT Z0O_LOTE FROM Z0O010 WHERE Z0O_FILIAL = B8_FILIAL AND Z0O_LOTE = B8_LOTECTL AND D_E_L_E_T_ =' ' )
	    AND B8_LOTECTL IN (SELECT DISTINCT Z0F_LOTE FROM Z0F010 WHERE Z0F_FILIAL = B8_FILIAL AND Z0F_LOTE = B8_LOTECTL AND D_E_L_E_T_ =' ' )
		AND B8_SALDO > 0 
		AND SB8.D_E_L_E_T_ =' ' 
	   GROUP BY B8_FILIAL, B8_LOTECTL, B8_X_CURRA, B8_LOTECTL, B1_X_SEXO, B1_XRACA, B8_XPESOCO
)
SELECT B8_FILIAL, B8_LOTECTL, SUM(B8_SALDO) SALDO, B8_X_CURRA, B8_XPESOCO
     , ISNULL((SELECT TOP(1) B1_X_SEXO 
	             FROM DADOS DA 
				WHERE DA.B8_FILIAL = D.B8_FILIAL 
				  AND DA.B8_LOTECTL = D.B8_LOTECTL 
				  ORDER BY DA.B8_SALDO DESC),'') SEXO
	, ISNULL((SELECT TOP(1) B1_XRACA
	             FROM DADOS DA 
				WHERE DA.B8_FILIAL = D.B8_FILIAL 
				  AND DA.B8_LOTECTL = D.B8_LOTECTL 
				  ORDER BY DA.B8_SALDO DESC),'') RACA
  FROM DADOS D
GROUP BY B8_FILIAL, B8_LOTECTL, B8_X_CURRA, B8_XPESOCO

select * from Z0O010 ORDER BY R_E_C_N_O_ DESC

select * from SRA010 where RA_MAT = '000293'

